## 1. run the next two cells as-is

In [1]:
#import libraries and set some variables

import requests
import pandas as pd
import xml.etree.ElementTree as ET
from pprint import pprint
from urllib.parse import quote
import numpy as np
import urllib.parse
import os
import warnings

pd.set_option('display.max_columns', None)


#Setting a few Alma Analytics API variables and whatnot
base_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&path=')  

token_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&token=')

loc1 = 'shared'
loc2 = 'University of Tennessee, Knoxville'
loc3 = 'Reports'
loc4 = 'Collections'
loc5 = 'Textbook ISBNs for Overlap Report_TM'
if loc5 != '':
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/' + loc5 
else:
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/'

get_path = location 
url_encoded_path = quote(get_path)
report_path = base_path + url_encoded_path

xml_snippet = '''
<sawx:expr xsi:type="sawx:list" op="in"
  xmlns:saw="com.siebel.analytics.web/report/v1.1"
  xmlns:sawx="com.siebel.analytics.web/expression/v1.1" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<sawx:expr xsi:type="sawx:sqlExpression">"Bibliographic Details"."MMS Id"</sawx:expr>
{}
</sawx:expr>
'''

In [2]:
report_path

'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?limit=1000&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5&path=/shared/University%20of%20Tennessee%2C%20Knoxville/Reports/Collections/Textbook%20ISBNs%20for%20Overlap%20Report_TM'

In [3]:
#define some functions

#function to extract data from the analytics report
def extract_data(row_elements, columns):
    data = []
    for row in row_elements:
        row_data = {}
        for col in row.findall('{urn:schemas-microsoft-com:xml-analysis:rowset}*'):
            column_name = col.tag.split('}')[1]
            column_value = col.text
            if column_name in columns:  # Check if the column is in the columns dictionary
                row_data[columns[column_name]] = column_value if column_value is not None else np.nan  # Insert NaN if value is missing
        data.append(row_data)
    return data

#pulling the analytics report and extracting data
def get_report(response):
    # Parse the XML response
    root = ET.fromstring(response.content)
    # Extract the ResumptionToken and IsFinished elements from the response XML
    resumption_token_element = root.find('.//ResumptionToken')
    resumption_token = resumption_token_element.text if resumption_token_element is not None else None
    is_finished_element = root.find('.//IsFinished')
    if is_finished_element is not None:
        is_finished = is_finished_element.text
    else:
        is_finished = None

    namespaces = {
        'xmlns': 'urn:schemas-microsoft-com:xml-analysis:rowset',
        'xsd': 'http://www.w3.org/2001/XMLSchema',
        'saw-sql': 'urn:saw-sql'
    }
    columns = {}

    for i, col in enumerate(root.findall('.//xsd:element[@saw-sql:columnHeading]', namespaces)):
        columns[f'Column{i}'] = col.get('{urn:saw-sql}columnHeading', col.get('name'))
    
    # Extract the data from the XML and store it in a list of dictionaries
    all_data = []
    data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
    all_data.extend(data)
    
    # Iterate through subsequent GET requests until IsFinished is True
    while is_finished == 'false':
        # Make the next GET request with the ResumptionToken
        response = requests.get(token_path + resumption_token)

        # Extract the ResumptionToken and IsFinished elements from the response XML
        root = ET.fromstring(response.content)
        is_finished = root.find('.//IsFinished').text

        # Process the response data
        data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
        all_data.extend(data)

    report_df = pd.DataFrame(all_data)

    # Drop the first column of the dataframe
    if not report_df.empty:
        report_df = report_df.drop(report_df.columns[0], axis=1)

    # Reset the index of the dataframe
    report_df = report_df.reset_index(drop=True)

    return report_df


def get_and_concat_report(report_path, report_data_df):
    response = requests.get(report_path)
    report_df = get_report(response)
    print(len(report_df))
    return pd.concat([report_data_df, report_df], ignore_index=True)

# Define a custom function to concatenate non-NaN values and deduplicate the notes fields which contain information about 
# online access type for each ebook
def concatenate_and_deduplicate_notes(row):
    notes = [str(row['Portfolio Public Note']), str(row['Portfolio Authentication Note']),
             str(row['Service Authentication Note']), str(row['Electronic location and access'])]
    non_nan_notes = set(note for note in notes if note != 'nan')
    return '; '.join(non_nan_notes)

## 2. Set the date

In [4]:
#set the date string for the rest of this notebook
date_str = '2026-04-20'

## 3. Read in the searchresults file from the bookstore
## make sure to point read_excel to the correct file location!

In [5]:
#load most recent file from bookstore
# you will need to have saved the automated bookstore file using format "searchresults_YYYY-MM-DD.xlsx" to your computer
df = pd.read_excel(r'searchresults_'+date_str+'.xlsx')

# Preview the sorted DataFrame
df

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity
0,Summer Mini 2026,ADVERTISING,202625-ADVT.480.001-70234,"Najera, Christina",9781483315430,CONTROVERSIES IN CONTEMPORARY ADVERTISING,"SHEEHAN, KIM BARTEL AND SHEEHAN, KIM B.","SAGE PUBLICATIONS, INCORPORATED",25
1,Summer Mini 2026,BIOCHEMISTRY CELLULAR MOLECULAR BIOLOGY,202625-BCMB.419.001-70259,"Korotych, Olena",9780470471319,FUNDAMENTAL LABORATORY APPROACHES FOR BIOCHEMI...,"NINFA, ALEXANDER J., BENORE, MARILEE, AND BALL...","WILEY & SONS, INCORPORATED, JOHN",12
2,Summer Mini 2026,BUSINESS ADMINISTRATION,202625-BUAD.200.001-70204,"Grant, Melissa",9781737565307,CAREER AI PLATFORM-QUINNCIA 2 YEAR ACCESS,QUINNCIA,QUINNCIA,50
3,Summer Mini 2026,COMMUNICATION STUDIES,202625-CMST.210.002-70420,"Lively, Traci",9781533943767,CUSTOM COURSE MATERIAL F/CMST 210 W/ACHIEVE,HAAS,MCMILLAN,20
4,Summer Mini 2026,COMMUNICATION STUDIES,202625-CMST.352.001-70126,"Smith, William",9781264978397,A FIRST LOOK AT COMMUNICATION THEORY,"EM GRIFFIN, ANDREW LEDBETTE, GLENN SPARKS",MCGRAW-HILL HIGHER EDUCATION (US),25
...,...,...,...,...,...,...,...,...,...
827,Summer 2026,THEATRE,202630-THEA.100.392-82104,"Russell, Neno",9798214354422,THE ART OF THEATRE: THEN AND NOW,DOWNS,CENGAGE,30
828,Summer 2026,THEATRE,202630-THEA.100.501-83315,"Russell, Neno",9798214354422,THE ART OF THEATRE: THEN AND NOW,DOWNS,CENGAGE,32
829,Summer 2026,"WOMEN, GENDER AND SEXUALITY",202630-WGS.200.301-87025,"Kendrick, Samantha",9781101992678,THE PORTABLE FEMINIST READER,NaN,PENGUIN PUBLISHING GROUP,20
830,Summer 2026,"WOMEN, GENDER AND SEXUALITY",202630-WGS.200.302-87026,"Kendrick, Samantha",9781101992678,THE PORTABLE FEMINIST READER,NaN,PENGUIN PUBLISHING GROUP,5
831,Summer 2026,"WOMEN, GENDER AND SEXUALITY",202630-WGS.375.301-87054,"Cooper, Sarah",9781324044048,"GENDER : IDEAS, INTERACTIONS, INSTITUTIONS (TH...","FERREE, MYRA MARX AND WADE, LISA","NORTON & COMPANY, INCORPORATED, W. W.",35

## 4. do some work on the bookstore-provided file to generate a list of ISBNs that 
## we will use in a later step

In [6]:
#create list of ISBNs for use in Alma Set creation
#do some pre-processing on the data for cleanup purposes
isbns = df[['ISBN']]
isbns = isbns.dropna()
isbns = isbns.drop_duplicates()
isbns['ISBN'] = isbns['ISBN'].apply(lambda x: x.replace('-',''))
isbns = isbns.astype(str)
isbns = isbns[(isbns['ISBN'].str.len() == 13) & (isbns['ISBN'].str.isdigit())]
isbns = isbns.reset_index()
isbns = isbns.drop('index', axis = 1)
isbns = isbns.iloc[isbns['ISBN'].str.len().sort_values(ascending = False).index]
isbns

              ISBN
0    9781483315430
244  9780062297266
253  9781610027359
252  9781975121549
251  9780323936798
..             ...
121  9798214342917
120  9780134010465
119  9780134423142
118  9781319258795
370  9781101992678

[371 rows x 1 columns]

In [7]:
isbns.dtypes

ISBN    object
dtype: object

In [8]:
#Fix known mismatching ISBNs

for i in range(isbns.shape[0]):
    if isbns.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found 1')
        print(i)
        isbns.at[i, 'ISBN'] = '9780191037610'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found 2')
        print(i)
        isbns.at[i, 'ISBN'] = '9781041036487'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found 3')
        print(i)
        isbns.at[i, 'ISBN'] = '9798400648236'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found 4')
        print(i)
        isbns.at[i, 'ISBN'] = '9780367725204' 
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found 5')
        print(i)
        isbns.at[i, 'ISBN'] = '9781119682141' 
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found 6')
        print(i)
        isbns.at[i, 'ISBN'] = '9781351133159'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found 7')
        print(i)
        isbns.at[i, 'ISBN'] = '9781501506024'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found 8')
        print(i)
        isbns.at[i, 'ISBN'] = '9781506352886'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781317346005': #On the History of Political Philosophy
        print('Found 9')
        print(i)
        isbns.at[i, 'ISBN'] = '9781317346012'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781000690835': #Child-Centered Play Therapy
        print('Found 10')
        print(i)
        isbns.at[i, 'ISBN'] = '9781003260431'
        print(isbns.at[i, 'ISBN'])

Found 10
94
9781003260431
Found 9
274
9781317346012
Found 7
327
9781501506024

## 5. Save the isbns to an Excel file

In [9]:
#create new itemized set in Alma using this isbn file:
isbns.to_excel(date_str+'_isbns.xlsx', index = False)

# after the set is created, export the results (All Fields) and save the file using format "YYYY-MM-DD_set_output.xlsx"

## 5. Use the isbn file to create an itemized set in alma
## After the set is created, export the results (All Fields) and save using the file name format "YYYY-MM-DD_set_output.xlsx" to the same location that all your other files for this process live in

## 6. The following cell will use the set_output you just made to call on the alma analytics API, looking for any matching ISBNs

In [13]:
#use the alma API and the set results to get all ISBNs for any MMS IDs found in set
#analytics report: Collections folder > "Textbook ISBNs for Overlap Report_TM"

#create list of mms_ids from set output
mms_ids = pd.read_excel(date_str+"_set_output.xlsx")
#mms_ids = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
mms_ids = mms_ids[['MMS ID']]

# Get the list of MMS IDs from the DataFrame
mms_list = mms_ids['MMS ID'].tolist()

# Define the batch size for API call(s)
batch_size = 50

# Create a list to store the batches
batches = []

# Iterate through the MMS ID list and create batches
for i in range(0, len(mms_list), batch_size):
    batch = mms_list[i : i + batch_size]
    batches.append(batch)

#create an empty list into which we will put api call results
df_list = []

#for each batch of mms ids, call analytics api
for batch in batches:
    values_xml = '\n'.join(f'<sawx:expr xsi:type="xsd:string">{value}</sawx:expr>' for value in batch)
    formatted_xml_snippet = xml_snippet.format(values_xml)

    url_encoded_filter_query = urllib.parse.quote(formatted_xml_snippet)

    full_path = base_path + url_encoded_path + r'&filter=' + url_encoded_filter_query

    report_data_df = get_and_concat_report(full_path, pd.DataFrame())
    df_list.append(report_data_df)
    
# concatenate together all the api call results into one big dataframe
combined_df = pd.concat(df_list, ignore_index=True)
combined_df

42
8

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Id,No. of Available Portfolio,Portfolio Public Note,Service Authentication Note,Portfolio Authentication Note
0,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks (EBA),Available,53390423470002311,0,NaN,NaN,NaN
1,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407973790002311,0,Online Access- Unlimited users (DRM-Free),NaN,NaN
2,https://www.taylorfrancis.com/books/9781003524090,1003524095; 9781003524090; 1040524826; 9781040...,1003524095; 9781003524090; 1040524826; 9781040...,9926907593802311,An evidence-based guide to assistive technolog...,Taylor & Francis Ebooks (EBA),Available,53452318750002311,1,NaN,NaN,NaN
3,https://link.springer.com/978-3-031-05740-3 Un...,9783031057403; 3031057406; 9783031057397; 3031...,9783031057403; 3031057406; 9783031057397; 3031...,9926837078602311,Applied Artificial Intelligence in Business : ...,Springer Ebooks Individually Purchased,Available,53446362200002311,1,Unlimited Access,NaN,NaN
4,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407996680002311,1,Online Access- Unlimited users (DRM-Free),NaN,NaN
5,https://www.taylorfrancis.com/books/9780203107...,0415887518; 9780415887519; 0415643465; 9780415...,0415887518; 9780415887519; 0415643465; 9780415...,9926414501702311,Core Competencies in Cognitive-Behavioral Ther...,Taylor & Francis Ebooks EBA Purchased,Available,53407972830002311,1,Online Access- Unlimited users (DRM-Free),NaN,NaN
6,https://www.taylorfrancis.com/books/9781003278290,1000566269; 9781000566260; 1003278299; 9781003...,1000566269; 9781000566260; 1003278299; 9781003...,9926211119402311,Ethics of data and analytics : concepts and ca...,Taylor & Francis Ebooks (EBA),Available,53384931230002311,1,NaN,NaN,NaN
7,https://search.ebscohost.com/login.aspx?direct...,0826182143; 9780826182142; 9780826182135; 0826...,0826182143; 9780826182142; 9780826182135; 0826...,9926521386802311,Evidence-based practice improvement : merging ...,Ebooks moved from ProQuest to EBSCO,Available,53450840880002311,1,NaN,NaN,NaN
8,https://www.taylorfrancis.com/books/9781315774251,1315774259; 9781315774251; 1317683862; 9781317...,1315774259; 9781315774251; 1317683862; 9781317...,9926081510102311,Global writing for public relations : connecti...,Taylor & Francis Ebooks EBA Purchased,Available,53362652360002311,1,NaN,NaN,NaN
9,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,ProQuest Ebook Central: Academic Complete,Available,53377612100002311,1,NaN,Online Access - Unlimited users,NaN
10,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,ProQuest Ebook Central Rialto,Available,53389361250002311,1,Single User,NaN,NaN
11,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,JSTOR Ebooks Individually Purchased,Available,53436529840002311,1,Online Access - Unlimited Users,NaN,NaN
12,NaN,1119819741; 9781119819745; 1119819733; 9781119...,1119819741; 9781119819745; 1119819733; 9781119...,9926910091102311,"Hey whipple, squeeze this : the classic guide ...",O'Reilly Online Learning: Academic/Public Libr...,Available,53452773190002311,1,NaN,NaN,NaN
13,NaN,111828223X; 9781118282236,111828223X; 9781118282236,9926914664702311,How great leaders think : the art of reframing,O'Reilly Online Learning: Academic/Public Libr...,Available,53454187110002311,1,NaN,NaN,NaN
14,https://search.ebscohost.com/login.aspx?direct...,9780080920856; 0080920853; 9780123741349; 0123...,9780080920856; 0080920853; 9780123741349; 0123...,9926677862202311,Human osteology /,EBSCO Ebooks Individually Purchased,Available,53432565050002311,1,Unlimited Access,NaN,NaN
15,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926852848702311,INTRODUCTION TO AMERICAN DEAF CULTURE,EBSCO Ebooks Individually Purchased,Available,53448439790002311,1,Unlimited Access,NaN,NaN
16,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926876681102311,INTRODUCTION TO AMERICAN DEAF CULTURE,Ebooks moved from ProQuest to EBSCO,Available,53451023240002311,1,NaN,NaN,NaN
17,https://onlinelibrary.wiley.com/book/10.1002/9...,9781119685135; 1119685133; 9781394347216; 1394...,9781119685135; 1119685133; 9781394347216; 1394...,9926721490202311,Introduction to Crisis and Trauma Counseling.,Wiley Ebooks Individually Purchased,Available,53436129820002311,1,Unlimited Access,NaN,NaN
18,https://muse.jhu.edu/book/77997/ Unlimited Acc...,9781944838881; 1944838880; 1563685078; 9781563...,9781944838881; 1944838880; 1563685078; 9781563...,9926721690202311,"Linguistics of American Sign Language, 5th Ed....",Project Muse Ebooks Individually Purchased,Available,53436149810002311,1,Unlimited Access,NaN,NaN
19,http://link.overdrive.com/?websiteID=120589&ti...,9780062691217; 006269121X; 9780062691194; 0062...,9780062691217; 006269121X; 9780062691194; 0062...,9926858905602311,New kid,OverDrive - Advantage,Available,53449394640002311,1,Click to access digital title.,NaN,NaN
20,https://www.taylorfrancis.com/books/9781315663...,1317346017; 9781317346012; 0205119743; 9780205...,1317346017; 9781317346012; 0205119743; 9780205...,9926414514502311,On the history of political philosophy : great...,Taylor & Francis Ebooks EBA Purchased,Available,53407950100002311,1,Online Access- Unlimited users (DRM-Free),NaN,NaN
21,https://ebookcentral.proquest.com/lib/utk/deta...,9781903544877; 1903544874; 9781780460154; 1780...,9781903544877; 1903544874; 9781780460154; 1780...,9926306865402311,Planetary Geology : An Introduction.,ProQuest Ebook Central: Academic Complete,Available,53393796650002311,1,Click to View,Online Access - Unlimited users,NaN
22,https://search.ebscohost.com/login.aspx?direct...,1626255989; 9781626255982; 9781626255975; 1626...,1626255989; 9781626255982; 9781626255975; 1626...,9926357087402311,Process-based CBT : the science and core clini...,EBSCO Ebooks Individually Purchased,Available,53400302360002311,1,Unlimited Access,NaN,NaN
23,https://www.taylorfrancis.com/books/9781315386744,1315386747; 9781315386744; 1315386720; 9781315...,1315386747; 9781315386744; 1315386720; 9781315...,9926068438502311,Professional development : what works /,Taylor & Francis Ebooks EBA Purchased,Available,53358266480002311,1,NaN,NaN,NaN
24,https://search.ebscohost.com/login.aspx?direct...,9781524771492; 152477149X,9781524771492; 152477149X,9926255787602311,Property of the Rebel Librarian,EBSCO Ebooks Individually Purchased,Available,53389170510002311,1,Single User,NaN,NaN
25,https://ebookcentral.proquest.com/lib/utk/deta...,1319056326; 9781319056322; 9781319258795; 1319...,1319056326; 9781319056322; 9781319258795; 1319...,9926630187902311,Pursuing happiness a Bedford spotlight reader /,ProQuest Ebook Central Rialto,Available,53427846840002311,1,Online Access - 3 Users,NaN,NaN
26,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,1,NaN,NaN,Online Access - Unlimited users
27,https://search.ebscohost.com/login.aspx?direct...,1590174887; 9781590174883; 9781590175033; 1590...,1590174887; 9781590174883; 9781590175033; 1590...,9926781641702311,"Religio Medici and Hydriotaphia, or Urne-Buria...",EBSCO Ebooks Individually Purchased,Available,53441638660002311,1,Single User,NaN,NaN
28,NaN,1071878875; 9781071878873; 150634531X; 9781506...,1071878875; 9781071878873; 150634531X; 9781506...,9926174911902311,Research methods for social work : a problem-b...,SAGE Research Methods Core,Available,53379272510002311,1,NaN,NaN,NaN
29,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,1,NaN,NaN,NaN
30,https://search.ebscohost.com/login.aspx?direct...,9780826163967; 0826163963; 9780826163950; 0826...,9780826163967; 0826163963; 9780826163950; 0826...,9926311284602311,School social work : a skills-based competency...,Ebooks moved from ProQuest to EBSCO,Available,53450018210002311,1,NaN,NaN,NaN
31,https://search.ebscohost.com/login.aspx?direct...,1975126920; 9781975126926; 9781975126919; 1975...,1975126920; 9781975126926; 9781975126919; 1975...,9926738030202311,Stoelting's pharmacology & physiology in anest...,EBSCO Ebooks Individually Purchased,Available,53437481400002311,1,Unlimited Access,NaN,NaN
32,https://dx.doi.org/10.1093/oso/9780190081478.0...,0197521843; 9780197521847; 9780190081508; 0190...,0197521843; 9780197521847; 9780190081508; 0190...,9926600557802311,"Strategy in 3D : essential tools to diagnose, ...",Oxford Academic Ebooks Individually Purchased,Available,53424712610002311,1,NaN,NaN,Online Access - Unlimited users
33,https://search.ebscohost.com/login.aspx?direct...,9780826148049; 0826148042; 9780826148032; 0826...,9780826148049; 0826148042; 9780826148032; 0826...,9926224985502311,Successful grant writing : strategies for heal...,Ebooks moved from ProQuest to EBSCO,Available,53450032740002311,1,NaN,NaN,NaN
34,NaN,1283634740; 9781283634748; 0071798315; 9780071...,1283634740; 9781283634748; 0071798315; 9780071...,9926913176702311,Supply chain transformation : building and exe...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453702880002311,1,NaN,NaN,NaN
35,https://link.springer.com/978-3-031-10330-8 Un...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926829231602311,The Comprehensive Guide to Interdisciplinary V...,Springer Ebooks Individually Purchased,Available,53433284910002311,1,Unlimited Access,NaN,NaN
36,https://search.ebscohost.com/login.aspx?direct...,0593655044; 9780593655047; 1802063285; 9781802...,0593655044; 9780593655047; 1802063285; 9781802...,9926536272302311,The anxious generation : how the great rewirin...,Ebooks moved from ProQuest to EBSCO,Available,53450796290002311,1,NaN,NaN,NaN
37,http://link.overdrive.com/?websiteID=120589&ti...,9780593655047; 0593655044; 9780593655030; 0593...,9780593655047; 0593655044; 9780593655030; 0593...,9926907601302311,The anxious generation How the great rewiring ...,OverDrive - Consortium,Available,53452246900002311,1,Click to access digital title.,NaN,NaN
38,https://search.ebscohost.com/login.aspx?direct...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926301284902311,The comprehensive guide to interdisciplinary v...,Ebooks moved from ProQuest to EBSCO,Available,53450658140002311,1,NaN,NaN,NaN
39,https://search.ebscohost.com/login.aspx?direct...,1101992670; 9781101992678; 9780143110392; 0143...,1101992670; 9781101992678; 9780143110392; 0143...,9926747489202311,The portable feminist reader /,EBSCO Ebooks Individually Purchased,Available,53438150710002311,1,NaN,NaN,Online Access - 1 user
40,https://ebookcentral.proquest.com/lib/utk/deta...,9781422131022; 1422131025; 9781422105764; 1422...,9781422131022; 1422131025; 9781422105764; 1422...,9926689981202311,The practice of adaptive leadership : tools an...,ProQuest Ebook Central Rialto,Available,53433399500002311,1,Three User,NaN,NaN
41,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,1,Single User,NaN,NaN
42,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central DDA Discovery,Available,53342336300002311,0,Click to View,NaN,NaN
43,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53380851750002311,0,Click to View,NaN,NaN
44,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,Ebooks moved from ProQuest to EBSCO,Available,53450960430002311,1,NaN,NaN,NaN
45,https://ebookcentral.proquest.com/lib/utk/deta...,9781501506024; 1501506021; 9781501515156; 1501...,9781501506024; 1501506021; 9781501515156; 1501...,9925796118702311,Demand and Supply Integration : The Key to Wor...,ProQuest Ebook Central: Academic Complete,Available,53307862990002311,1,NaN,Online Access - Unlimited users,NaN
46,https://search.ebscohost.com/login.aspx?direct...,0553447459; 9780553447453; 9780553447446; 0553...,0553447459; 9780553447453; 9780553447446; 0553...,9925735170102311,Evicted poverty and profit in the American city,EBSCO Ebooks Individually Purchased,Available,53294165900002311,1,Single User,NaN,Online Access : 1 simultaneous user
47,https://search.ebscohost.com/login.aspx?direct...,9780323755825; 0323755828; 9780323673327; 0323...,9780323755825; 0323755828; 9780323673327; 0323...,9926034431502311,Pediatric acute care : a guide for interprofes...,Ebooks moved from ProQuest to EBSCO,Available,53450032360002311,1,NaN,NaN,NaN
48,https://ebookcentral.proquest.com/lib/utk/deta...,9781606492468; 1606492462; 9781606492451; 1606...,9781606492468; 1606492462; 9781606492451; 1606...,9925725944102311,Supply Chain Planning and Analytics : The Righ...,ProQuest Ebook Central: Academic Complete,Available,53292994490002311,1,NaN,Online Access - Unlimited users,NaN
49,https://search.ebscohost.com/login.aspx?direct...,1606492462; 9781606492468; 9781606492451; 1606...,1606492462; 9781606492468; 9781606492451; 1606...,9924042300102311,Supply chain planning and analytics : the righ...,Ebooks moved from ProQuest to EBSCO,Available,53449627790002311,1,NaN,NaN,NaN

In [14]:
combined_df.sort_values(by = 'Title')['Title'].unique()

array(['An evidence-based guide to assistive technology : meeting the needs of all students with disabilities /',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Child-centered play therapy : a practical guide to therapeutic relationships with children /',
       'Core Competencies in Cognitive-Behavioral Therapy : Becoming a Highly Effective and Competent Cognitive-Behavioral Therapist /',
       'Deaf culture : exploring deaf communities in the United States /',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Ethics of data and analytics : concepts and cases /',
       'Evicted poverty and profit in the American city',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement /',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide /',
       'Guide to the vascular plants of Tennessee /',
       'Hey whipple, squeeze this : the classic guide to creating great advertising /',
       'How great leaders think : the art of reframing',
       'Human osteology /', 'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'Introduction to Crisis and Trauma Counseling.',
       'Linguistics of American Sign Language, 5th Ed. : An Introduction /',
       'New kid',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke /',
       'Pediatric acute care : a guide for interprofessional practice /',
       'Planetary Geology : An Introduction.',
       'Process-based CBT : the science and core clinical competencies of cognitive behavioral therapy /',
       'Professional development : what works /',
       'Property of the Rebel Librarian',
       'Pursuing happiness a Bedford spotlight reader /',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases /',
       'Religio Medici and Hydriotaphia, or Urne-Buriall /',
       'Research methods for social work : a problem-based approach /',
       'Sales force management : leadership, innovation, technology /',
       'School social work : a skills-based competency approach /',
       "Stoelting's pharmacology & physiology in anesthetic practice",
       'Strategy in 3D : essential tools to diagnose, decide, & deliver /',
       'Successful grant writing : strategies for health and human service professionals /',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time /',
       'Supply chain transformation : building and executing an integrated supply chain strategy /',
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The anxious generation : how the great rewiring of childhood is causing an epidemic of mental illness /',
       'The anxious generation How the great rewiring of childhood is causing an epidemic of mental illness.',
       'The comprehensive guide to interdisciplinary veterinary social work /',
       'The portable feminist reader /',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world /',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster /'],
      dtype=object)

In [15]:
combined_df['Service Authentication Note']

0                                 NaN
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9     Online Access - Unlimited users
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN
18                                NaN
19                                NaN
20                                NaN
21    Online Access - Unlimited users
22                                NaN
23                                NaN
24                                NaN
25                                NaN
26                                NaN
27                                NaN
28                                NaN
29                                NaN
30                                NaN
31                                NaN
32                                NaN
33                                NaN
34                                NaN
35                                NaN
36                                NaN
37                                NaN
38                                NaN
39                                NaN
40                                NaN
41                                NaN
42                                NaN
43                                NaN
44                                NaN
45    Online Access - Unlimited users
46                                NaN
47                                NaN
48    Online Access - Unlimited users
49                                NaN
Name: Service Authentication Note, dtype: object

In [16]:
combined_df['Electronic location split'] = combined_df['Electronic location and access'].apply(lambda x: x.split() if isinstance(x, str) else x)

combined_df['Electronic location'] = combined_df['Electronic location split'].apply(lambda x: ''.join(map(str, x[:1])) if isinstance(x, list) else x)

# Extract items excluding the first item from each list
combined_df['Electronic access'] = combined_df['Electronic location split'].apply(lambda x: ' '.join(x[1:]) if isinstance(x, list) else x)

In [17]:
combined_df['Electronic access']

0     Online Access- Unlimited users (DRM-Free)
1     Online Access- Unlimited users (DRM-Free)
2
3             Unlimited Access Unlimited Access
4     Online Access- Unlimited users (DRM-Free)
5     Online Access- Unlimited users (DRM-Free)
6
7
8
9                       Single User Single User
10                      Single User Single User
11                      Single User Single User
12                                          NaN
13                                          NaN
14            Unlimited Access Unlimited Access
15            Unlimited Access Unlimited Access
16
17            Unlimited Access Unlimited Access
18            Unlimited Access Unlimited Access
19               Click to access digital title.
20    Online Access- Unlimited users (DRM-Free)
21                                Click to View
22            Unlimited Access Unlimited Access
23
24                      Single User Single User
25                      Single User Single User
26              Online Access - Unlimited users
27                      Single User Single User
28                                          NaN
29                                          NaN
30
31            Unlimited Access Unlimited Access
32              Online Access - Unlimited users
33
34                                          NaN
35            Unlimited Access Unlimited Access
36
37               Click to access digital title.
38
39                       Online Access - 1 user
40                        Three User Three User
41                      Single User Single User
42
43
44
45                                Click to View
46                      Single User Single User
47
48                                Click to View
49
Name: Electronic access, dtype: object

## 7. save the alma analytics api output as an excel file

In [18]:
#save the big, concatenated dataframe to disk
combined_df.to_excel(date_str+'_analytics_output.xlsx', index = False)

## do some work on the dataframe

In [19]:
# Create a new column 'Concatenated Notes' with deduplication
combined_df['Concatenated Notes'] = combined_df.apply(concatenate_and_deduplicate_notes, axis=1)

#filter to only show rows where the No. of Available Portfolios is not zero
combined_df = combined_df.loc[combined_df['No. of Available Portfolio'] != 0]


# Display the updated DataFrame
combined_df

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Id,No. of Available Portfolio,Portfolio Public Note,Service Authentication Note,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks (EBA),Available,53390423470002311,0,NaN,NaN,NaN,[https://www.taylorfrancis.com/books/978100326...,https://www.taylorfrancis.com/books/9781003260431,Online Access- Unlimited users (DRM-Free),https://www.taylorfrancis.com/books/9781003260...
1,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407973790002311,0,Online Access- Unlimited users (DRM-Free),NaN,NaN,[https://www.taylorfrancis.com/books/978100326...,https://www.taylorfrancis.com/books/9781003260431,Online Access- Unlimited users (DRM-Free),https://www.taylorfrancis.com/books/9781003260...
2,https://www.taylorfrancis.com/books/9781003524090,1003524095; 9781003524090; 1040524826; 9781040...,1003524095; 9781003524090; 1040524826; 9781040...,9926907593802311,An evidence-based guide to assistive technolog...,Taylor & Francis Ebooks (EBA),Available,53452318750002311,1,NaN,NaN,NaN,[https://www.taylorfrancis.com/books/978100352...,https://www.taylorfrancis.com/books/9781003524090,,https://www.taylorfrancis.com/books/9781003524090
3,https://link.springer.com/978-3-031-05740-3 Un...,9783031057403; 3031057406; 9783031057397; 3031...,9783031057403; 3031057406; 9783031057397; 3031...,9926837078602311,Applied Artificial Intelligence in Business : ...,Springer Ebooks Individually Purchased,Available,53446362200002311,1,Unlimited Access,NaN,NaN,"[https://link.springer.com/978-3-031-05740-3, ...",https://link.springer.com/978-3-031-05740-3,Unlimited Access Unlimited Access,Unlimited Access; https://link.springer.com/97...
4,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407996680002311,1,Online Access- Unlimited users (DRM-Free),NaN,NaN,[https://www.taylorfrancis.com/books/978100326...,https://www.taylorfrancis.com/books/9781003260431,Online Access- Unlimited users (DRM-Free),https://www.taylorfrancis.com/books/9781003260...
5,https://www.taylorfrancis.com/books/9780203107...,0415887518; 9780415887519; 0415643465; 9780415...,0415887518; 9780415887519; 0415643465; 9780415...,9926414501702311,Core Competencies in Cognitive-Behavioral Ther...,Taylor & Francis Ebooks EBA Purchased,Available,53407972830002311,1,Online Access- Unlimited users (DRM-Free),NaN,NaN,[https://www.taylorfrancis.com/books/978020310...,https://www.taylorfrancis.com/books/9780203107447,Online Access- Unlimited users (DRM-Free),https://www.taylorfrancis.com/books/9780203107...
6,https://www.taylorfrancis.com/books/9781003278290,1000566269; 9781000566260; 1003278299; 9781003...,1000566269; 9781000566260; 1003278299; 9781003...,9926211119402311,Ethics of data and analytics : concepts and ca...,Taylor & Francis Ebooks (EBA),Available,53384931230002311,1,NaN,NaN,NaN,[https://www.taylorfrancis.com/books/978100327...,https://www.taylorfrancis.com/books/9781003278290,,https://www.taylorfrancis.com/books/9781003278290
7,https://search.ebscohost.com/login.aspx?direct...,0826182143; 9780826182142; 9780826182135; 0826...,0826182143; 9780826182142; 9780826182135; 0826...,9926521386802311,Evidence-based practice improvement : merging ...,Ebooks moved from ProQuest to EBSCO,Available,53450840880002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
8,https://www.taylorfrancis.com/books/9781315774251,1315774259; 9781315774251; 1317683862; 9781317...,1315774259; 9781315774251; 1317683862; 9781317...,9926081510102311,Global writing for public relations : connecti...,Taylor & Francis Ebooks EBA Purchased,Available,53362652360002311,1,NaN,NaN,NaN,[https://www.taylorfrancis.com/books/978131577...,https://www.taylorfrancis.com/books/9781315774251,,https://www.taylorfrancis.com/books/9781315774251
9,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,ProQuest Ebook Central: Academic Complete,Available,53377612100002311,1,NaN,Online Access - Unlimited users,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Single User Single User,https://ebookcentral.proquest.com/lib/utk/deta...
10,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,ProQuest Ebook Central Rialto,Available,53389361250002311,1,Single User,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Single User Single User,https://ebookcentral.proquest.com/lib/utk/deta...
11,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,JSTOR Ebooks Individually Purchased,Available,53436529840002311,1,Online Access - Unlimited Users,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Single User Single User,https://ebookcentral.proquest.com/lib/utk/deta...
12,NaN,1119819741; 9781119819745; 1119819733; 9781119...,1119819741; 9781119819745; 1119819733; 9781119...,9926910091102311,"Hey whipple, squeeze this : the classic guide ...",O'Reilly Online Learning: Academic/Public Libr...,Available,53452773190002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
13,NaN,111828223X; 9781118282236,111828223X; 9781118282236,9926914664702311,How great leaders think : the art of reframing,O'Reilly Online Learning: Academic/Public Libr...,Available,53454187110002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
14,https://search.ebscohost.com/login.aspx?direct...,9780080920856; 0080920853; 9780123741349; 0123...,9780080920856; 0080920853; 9780123741349; 0123...,9926677862202311,Human osteology /,EBSCO Ebooks Individually Purchased,Available,53432565050002311,1,Unlimited Access,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
15,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926852848702311,INTRODUCTION TO AMERICAN DEAF CULTURE,EBSCO Ebooks Individually Purchased,Available,53448439790002311,1,Unlimited Access,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
16,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926876681102311,INTRODUCTION TO AMERICAN DEAF CULTURE,Ebooks moved from ProQuest to EBSCO,Available,53451023240002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
17,https://onlinelibrary.wiley.com/book/10.1002/9...,9781119685135; 1119685133; 9781394347216; 1394...,9781119685135; 1119685133; 9781394347216; 1394...,9926721490202311,Introduction to Crisis and Trauma Counseling.,Wiley Ebooks Individually Purchased,Available,53436129820002311,1,Unlimited Access,NaN,NaN,[https://onlinelibrary.wiley.com/book/10.1002/...,https://onlinelibrary.wiley.com/book/10.1002/9...,Unlimited Access Unlimited Access,Unlimited Access; https://onlinelibrary.wiley....
18,https://muse.jhu.edu/book/77997/ Unlimited Acc...,9781944838881; 1944838880; 1563685078; 9781563...,9781944838881; 1944838880; 1563685078; 9781563...,9926721690202311,"Linguistics of American Sign Language, 5th Ed....",Project Muse Ebooks Individually Purchased,Available,53436149810002311,1,Unlimited Access,NaN,NaN,"[https://muse.jhu.edu/book/77997/, Unlimited, ...",https://muse.jhu.edu/book/77997/,Unlimited Access Unlimited Access,Unlimited Access; https://muse.jhu.edu/book/77...
19,http://link.overdrive.com/?websiteID=120589&ti...,9780062691217; 006269121X; 9780062691194; 0062...,9780062691217; 006269121X; 9780062691194; 0062...,9926858905602311,New kid,OverDrive - Advantage,Available,53449394640002311,1,Click to access digital title.,NaN,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,http://link.overdrive.com/?websiteID=120589&ti...
20,https://www.taylorfrancis.com/books/9781315663...,1317346017; 9781317346012; 0205119743; 9780205...,1317346017; 9781317346012; 0205119743; 9780205...,9926414514502311,On the history of political philosophy : great...,Taylor & Francis Ebooks EBA Purchased,Available,53407950100002311,1,Online Access- Unlimited users (DRM-Free),NaN,NaN,[https://www.taylorfrancis.com/books/978131566...,https://www.taylorfrancis.com/books/9781315663401,Online Access- Unlimited users (DRM-Free),https://www.taylorfrancis.com/books/9781315663...
21,https://ebookcentral.proquest.com/lib/utk/deta...,9781903544877; 1903544874; 9781780460154; 1780...,9781903544877; 1903544874; 9781780460154; 1780...,9926306865402311,Planetary Geology : An Introduction.,ProQuest Ebook Central: Academic Complete,Available,53393796650002311,1,Click to View,Online Access - Unlimited users,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Click to View; https://ebookcentral.proquest.c...
22,https://search.ebscohost.com/login.aspx?direct...,1626255989; 9781626255982; 9781626255975; 1626...,1626255989; 9781626255982; 9781626255975; 1626...,9926357087402311,Process-based CBT : the science and core clini...,EBSCO Ebooks Individually Purchased,Available,53400302360002311,1,Unlimited Access,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
23,https://www.taylorfrancis.com/books/9781315386744,1315386747; 9781315386744; 1315386720; 9781315...,1315386747; 9781315386744; 1315386720; 9781315...,9926068438502311,Professional development : what works /,Taylor & Francis Ebooks EBA Purchased,Available,53358266480002311,1,NaN,NaN,NaN,[https://www.taylorfrancis.com/books/978131538...,https://www.taylorfrancis.com/books/9781315386744,,https://www.taylorfrancis.com/books/9781315386744
24,https://search.ebscohost.com/login.aspx?direct...,9781524771492; 152477149X,9781524771492; 152477149X,9926255787602311,Property of the Rebel Librarian,EBSCO Ebooks Individually Purchased,Available,53389170510002311,1,Single User,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Single User; https://search.ebscohost.com/logi...
25,https://ebookcentral.proquest.com/lib/utk/deta...,1319056326; 9781319056322; 9781319258795; 1319...,1319056326; 9781319056322; 9781319258795; 1319...,9926630187902311,Pursuing happiness a Bedford spotlight reader /,ProQuest Ebook Central Rialto,Available,53427846840002311,1,Online Access - 3 Users,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Single User Single User,Online Access - 3 Users; https://ebookcentral....
26,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,1,NaN,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,https://search.ebscohost.com/login.aspx?direct...
27,https://search.ebscohost.com/login.aspx?direct...,1590174887; 9781590174883; 9781590175033; 1590...,1590174887; 9781590174883; 9781590175033; 1590...,9926781641702311,"Religio Medici and Hydriotaphia, or Urne-Buria...",EBSCO Ebooks Individually Purchased,Available,53441638660002311,1,Single User,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Single User; https://search.ebscohost.com/logi...
28,NaN,1071878875; 9781071878873; 150634531X; 9781506...,1071878875; 9781071878873; 150634531X; 9781506...,9926174911902311,Research methods for social work : a problem-b...,SAGE Research Methods Core,Available,53379272510002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
29,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
30,https://search.ebscohost.com/login.aspx?direct...,9780826163967; 0826163963; 9780826163950; 0826...,9780826163967; 0826163963; 9780826163950; 0826...,9926311284602311,School social work : a skills-based competency...,Ebooks moved from ProQuest to EBSCO,Available,53450018210002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
31,https://search.ebscohost.com/login.aspx?direct...,1975126920; 9781975126926; 9781975126919; 1975...,1975126920; 9781975126926; 9781975126919; 1975...,9926738030202311,Stoelting's pharmacology & physiology in anest...,EBSCO Ebooks Individually Purchased,Available,53437481400002311,1,Unlimited Access,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
32,https://dx.doi.org/10.1093/oso/9780190081478.0...,0197521843; 9780197521847; 9780190081508; 0190...,0197521843; 9780197521847; 9780190081508; 0190...,9926600557802311,"Strategy in 3D : essential tools to diagnose, ...",Oxford Academic Ebooks Individually Purchased,Available,53424712610002311,1,NaN,NaN,Online Access - Unlimited users,[https://dx.doi.org/10.1093/oso/9780190081478....,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,https://dx.doi.org/10.1093/oso/9780190081478.0...
33,https://search.ebscohost.com/login.aspx?direct...,9780826148049; 0826148042; 9780826148032; 0826...,9780826148049; 0826148042; 9780826148032; 0826...,9926224985502311,Successful grant writing : strategies for heal...,Ebooks moved from ProQuest to EBSCO,Available,53450032740002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
34,NaN,1283634740; 9781283634748; 0071798315; 9780071...,1283634740; 9781283634748; 0071798315; 9780071...,9926913176702311,Supply chain transformation : building and exe...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453702880002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
35,https://link.springer.com/978-3-031-10330-8 Un...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926829231602311,The Comprehensive Guide to Interdisciplinary V...,Springer Ebooks Individually Purchased,Available,53433284910002311,1,Unlimited Access,NaN,NaN,"[https://link.springer.com/978-3-031-10330-8, ...",https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,Unlimited Access; https://link.springer.com/97...
36,https://search.ebscohost.com/login.aspx?direct...,0593655044; 9780593655047; 1802063285; 9781802...,0593655044; 9780593655047; 1802063285; 9781802...,9926536272302311,The anxious generation : how the great rewirin...,Ebooks moved from ProQuest to EBSCO,Available,53450796290002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
37,http://link.overdrive.com/?websiteID=120589&ti...,9780593655047; 0593655044; 9780593655030; 0593...,9780593655047; 0593655044; 9780593655030; 0593...,9926907601302311,The anxious generation How the great rewiring ...,OverDrive - Consortium,Available,53452246900002311,1,Click to access digital title.,NaN,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,http://link.overdrive.com/?websiteID=120589&ti...
38,https://search.ebscohost.com/login.aspx?direct...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926301284902311,The comprehensive guide to interdisciplinary v...,Ebooks moved from ProQuest to EBSCO,Available,53450658140002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
39,https://search.ebscohost.com/login.aspx?direct...,1101992670; 9781101992678; 9780143110392; 0143...,1101992670; 9781101992678; 9780143110392; 0143...,9926747489202311,The portable feminist reader /,EBSCO Ebooks Individually Purchased,Available,53438150710002311,1,NaN,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - 1 user,Online Access - 1 user; https://search.ebscoho...
40,https://ebookcentral.proquest.com/lib/utk/deta...,9781422131022; 1422131025; 9781422105764; 1422...,9781422131022; 1422131025; 9781422105764; 1422...,9926689981202311,The practice of adaptive leadership : tools an...,ProQuest Ebook Central Rialto,Available,53433399500002311,1,Three User,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Three User Three User,Three User; https://ebookcentral.proquest.com/...
41,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,1,Single User,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Single User; https://search.ebscohost.com/logi...
42,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central DDA Discovery,Available,53342336300002311,0,Click to View,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,Click to View; https://search.ebscohost.com/lo...

## 8. save the analytics_output file as csv

In [20]:
#save the dataframe to disk once again, only this time as a csv
combined_df.to_csv(date_str+'_analytics_output.csv', index = False)

## 9. Combine Data Files for Exporting and the LibGuide

In [21]:
results = pd.read_excel(date_str+'_set_output.xlsx') #From Alma Directly
#results = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
bookstoreList = pd.read_excel('searchresults_'+date_str+'.xlsx') #From VolBooks Directly
textbookISBNs = combined_df #Alma Cleaned-Up Version

In [22]:
#Fix known mismatching ISBNs in bookstoreList

for i in range(bookstoreList.shape[0]):
    if bookstoreList.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found 1')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9780191037610'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found 2')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781041036487'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found 3')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9798400648236'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found 4')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9780367725204' 
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found 5')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781119682141' 
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found 6')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781351133159'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found 7')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781501506024'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found 8')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781506352886'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781317346005': #On the History of Political Philosophy
        print('Found 9')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781317346012'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781000690835': #Child-Centered Play Therapy
        print('Found 10')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781003260431'
        print(bookstoreList.at[i, 'ISBN'])

Found 10
162
9781003260431
Found 9
568
9781317346012
Found 9
569
9781317346012
Found 7
688
9781501506024

In [23]:
pd.set_option('display.max_rows', None)
results.sort_values(by = 'Title')['Title'].unique()

array(['An evidence-based guide to assistive technology : meeting the needs of all students with disabilities / edited by Alice L. Rhodes and Victoria Slocum.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Child-centered play therapy : a practical guide to therapeutic relationships with children / Nancy H. Cochran, William J. Nordling and Jeff L. Cochran.',
       'Child-centered play therapy : a practical guide to therapeutic relationships with children / Nancy H. Cochran, William J. Nordling, Jeff L. Cochran.',
       'Core Competencies in Cognitive-Behavioral Therapy : Becoming a Highly Effective and Competent Cognitive-Behavioral Therapist / Cory F. Newman.',
       'Deaf culture : exploring deaf communities in the United States / Irene W. Leigh, PhD, Jean F. Andrews, PhD, Raychelle L. Harris, PhD, Topher González Ávila, MA.',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Diagnostic and statistical manual of mental disorders : DSM-5-TR / American Psychiatric Association.',
       'Ethical issues in professional life / Joan C. Callahan, [editor].',
       'Ethics of data and analytics : concepts and cases / Kirsten Martin.',
       'Evicted : poverty and profit in the American city / Matthew Desmond.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement / Rona F. Levin, Bonnie Lauder, editors.',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Gordis epidemiology / David D. Celentano, Moyses Szklo.',
       'Guide to the vascular plants of Tennessee / compiled and edited by members of the Tennessee Flora Committee.',
       'Hey whipple, squeeze this : the classic guide to creating great advertising / Luke Sullivan.',
       'How great leaders think : the art of reframing',
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'INTRODUCTION TO AMERICAN DEAF CULTURE [electronic resource].',
       'Introduction to Crisis and Trauma Counseling.',
       'Introduction to kinesiology : studying physical activity / Duane V. Knudson, Timothy A. Brusseau, editors.',
       'Introductory textbook of psychiatry / Donald W. Black, Nancy C. Andreasen.',
       'Linguistics of American Sign Language, 5th Ed. :  An Introduction /  Clayton Valli [and others].',
       "Miller's basics of anesthesia / Manuel C. Pardo, Jr., MD.",
       'Multicultural psychology : understanding our diverse communities / Jeffery Scott Mio, Lori A. Barker, Melanie M. Domenech Rodríguez, John Gonzalez.',
       'New kid / Jerry Craft ; with color by Jim Callahan.',
       'New kid [electronic resource]. Jerry Craft.',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke / W. Julian Korab-Karpowicz.',
       'Pediatric acute care : a guide for interprofessional practice / edited by Beth Nachtsheim Bolick, Karin Reuter-Rice, Maureen A. Madden, Paul N. Severin.',
       'Physical activity epidemiology / Rod K. Dishman, Gregory W. Heath, Michael D. Schmidt,  I-Min Lee.',
       'Planetary Geology : An Introduction.',
       'Process-based CBT : the science and core clinical competencies of cognitive behavioral therapy / edited by Steven C. Hayes, and Stefan G. Hofmann.',
       'Professional development : what works / Sally J. Zepeda.',
       'Property of the Rebel Librarian [electronic resource] / Allison Varnes.',
       'Property of the rebel librarian / Allison Varnes.',
       'Pursuing happiness [electronic resource] : a Bedford spotlight reader / [compiled and edited by] Matthew Parfitt, Boston University, Dawn Skorczewski, Brandeis University.',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases / author: Committee on Infectious Diseases, American Academy of Pediatrics; David W. Kimberlin, MD, FAAP, editor; Ritu Banerjee, MD, PhD, FAAP, Elizabeth D. Barnett, MD, FAAP, Ruth Lynfield, MD, FAAP, Mark H. Sawyer, MD, FAAP, associate editor.',
       'Religio Medici and Hydriotaphia, or Urne-Buriall / Sir Thomas Browne ; edited and with an introduction by Stephen Greenblatt and Ramie Targoff.',
       'Research methods for social work : a problem-based approach / Antoinette Y. Farmer, G. Lawrence Farmer.',
       'Sales force management : leadership, innovation, technology / Mark W. Johnston, Greg W. Marshall, and Jessica L. Ogilvie.',
       'School social work : a skills-based competency approach / JoDee Keller, PhD, LICSW Department of Social Work, Professor of Social Work Pacific Lutheran University.',
       "Stoelting's pharmacology & physiology in anesthetic practice / [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman.",
       "Stoelting's pharmacology & physiology in anesthetic practice [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman",
       'Strategy in 3D : essential tools to diagnose, decide, & deliver / Greg Fisher, John E. Wisneski, Rene M. Bakker.',
       'Successful grant writing : strategies for health and human service professionals / Laura N. Gitlin, Ann Kolanowski, Kevin J. Lyons.',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time / Gerald Feigin.',
       'Supply chain transformation : building and executing an integrated supply chain strategy / J. Paul Dittmann.',
       "Thanks for the feedback : the science and art of receiving feedback well (even when it is off base, unfair, poorly delivered, and frankly, you're not in the mood) / Douglas Stone & Sheila Heen.",
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The anxious generation : how the great rewiring of childhood is causing an epidemic of mental illness / Jonathan Haidt.',
       'The anxious generation [electronic resource] : How the great rewiring of childhood is causing an epidemic of mental illness. Jonathan Haidt.',
       'The comprehensive guide to interdisciplinary veterinary social work / Sana Loue, Pamela Linden, editors.',
       'The goal : a process of ongoing improvement / by Eliyahu M. Goldratt and Jeff Cox.',
       'The holocene : an environmental history / Professor Neil Roberts, School of Geography, Earth and Environmental Sciences, Plymouth University, UK.',
       'The portable feminist reader / edited with an introduction by Roxane Gay.',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world / Ronald Heifetz, Alexander Grashow, Marty Linsky.',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster / [edited by] Lisa López Levers, PhD, LPCC-S, LPC, CRC, NCC.'],
      dtype=object)

In [24]:
textbookISBNs = textbookISBNs.astype({'MMS Id': 'int64'})



resultsPlusList = pd.merge(results, textbookISBNs, left_on = 'MMS ID', right_on = 'MMS Id', how = 'inner')

In [25]:
resultsPlusList

,Title_x,Alternate Graphic Representation,Type,Creator / Imprint,Subject,Series,Relation,Modification Date,Edition,Uniform Title,Medium Type,Language,Creation Date,Language of Cataloging,ISBN_x,ISBN (13),ISSN,Cluster ISSN,Record Number,MMS ID,Bibliographic Rank,Local Call Number,Other Classification Number,NLM Call Number,Dewey Decimal Classification Number,LC Call Number,Classification Part,UDC Classification Number,NAL Call Number,Handle Identifier,Peer Reviewed,Open Access,Physical Availability,Digital Availability,Electronic Availability,Collection Name,Collection ID,Orders,Requests,Physical Description Extent,Local Labels,Related Records,Courses,Licenses,Reminders,Notes,Electronic location and access,ISBN (Normalized),ISBN_y,MMS Id,Title_y,Electronic Collection Public Name,Availability,Portfolio Id,No. of Available Portfolio,Portfolio Public Note,Service Authentication Note,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,Red book : 2024-2027 report of the Committee o...,NaN,Book {Book - Electronic} text; computer; onlin...,American Academy of Pediatrics. Committee on I...,Communicable diseases in children--Periodicals...,STAT!Ref electronic medical library. Red Book:...,NaN,2026-04-03 04:22:00,33rd edition.,NaN,NaN,English,2026-04-02 10:08:00,NaN,9781610027359; 1610027353; 9781610027342,9781610027359; 9781610027359; 9781610027342,NaN,NaN,90103981814; (NhCcYBP)ybp306401256,9926931276402311,111,NaN,NaN,WC 100,618.929,RJ240 .A44 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (L, 1261 pages) :",NaN,1,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,1,NaN,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,https://search.ebscohost.com/login.aspx?direct...
1,"Sales force management : leadership, innovatio...",NaN,Book {Book - Electronic} text; computer; onlin...,"Johnston, Mark W., (New York, NY : Routledge, ...",Sales management.,NaN,NaN,2026-03-27 13:24:00,Fourteenth edition.,NaN,NaN,English,2025-06-10 08:16:00,English,1-04-030131-2,9781040301319,NaN,NaN,(CKB)39206405800041; (CaSebORM)9781040301319; ...,9926916167202311,90,NaN,NaN,NaN,658.8/1,HF5438.4 .C48 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,"1 online resource (xxx, 470 pages) :",NaN,0,0,0,0,0,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
2,How great leaders think : the art of reframing,NaN,Book {Book - Electronic} text; computer; onlin...,"Bolman, Lee G (San Francisco CA Jossey Bass A ...",Leadership.;Organizational change.;Management;...,NaN,NaN,2026-03-27 13:22:00,1st edition,NaN,NaN,English,2015-03-15 08:35:00,NaN,9781118282236; 111828223X,9781118282236; 9781118282236,NaN,NaN,(CKB)3710000000372697; (SSID)ssj0001261991; (P...,9926914664702311,92,NaN,NaN,NaN,658.4/092,HD57.7.B6393 2014 and others,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (240 pages),NaN,0,0,0,0,0,NaN,111828223X; 9781118282236,111828223X; 9781118282236,9926914664702311,How great leaders think : the art of reframing,O'Reilly Online Learning: Academic/Public Libr...,Available,53454187110002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
3,Supply chain transformation : building and exe...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dittmann, J. Paul, (New York : McGraw-Hill, 20...",Business logistics.;Strategic planning.,NaN,NaN,2026-03-27 13:18:00,1st edition,NaN,NaN,English,2013-01-20 01:44:00,English,9781283634748; 1283634740; 9780071798310; 0071...,9781283634748; 9781283634748; 9780071798310; 9...,NaN,NaN,(CKB)2550000000707210; (SSID)ssj0000760008; (P...,9926913176702311,100,NaN,NaN,NaN,658.7,HD38.5 .D588 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (1 v.) :,NaN,1,0,0,0,0,NaN,1283634740; 9781283634748; 0071798315; 9780071...,1283634740; 9781283634748; 0071798315; 9780071...,9926913176702311,Supply chain transformation : building and exe...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453702880002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
4,"Hey whipple, squeeze this : the classic guide ...",NaN,Book {Book - Electronic} text; computer; onlin...,"Sullivan, Luke, (Hoboken, New Jersey : John Wi...",Advertising copy.,NaN,NaN,2026-03-27 13:12:00,Sixth edition,NaN,NaN,English,2022-03-02 03:11:00,English,9781119819745; 1119819741; 9781119819738; 1119...,9781119819745; 9781119819745; 9781119819738; 9...,NaN,NaN,(MiAaPQ)EBC6896741; (Au-PeEL)EBL6896741; (CKB)...,9926910091102311,95,NaN,674 and others,NaN,659.132,HF5825 .S855 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (413 pages),NaN,0,0,0,0,0,NaN,1119819741; 9781119819745; 1119819733; 9781119...,1119819741; 9781119819745; 1119819733; 9781119...,9926910091102311,"Hey whipple, squeeze this : the classic guide ...",O'Reilly Online Learning: Academic/Public Libr...,Available,53452773190002311,1,NaN,NaN,NaN,NaN,NaN,NaN,
5,The anxious generation [electronic resource] :...,NaN,Book {Book - Electronic} text; computer; onlin...,"Haidt, Jonathan. (2024.)",Nonfiction.;Family & Relationships.;Psychology...,NaN,NaN,2026-03-20 04:08:00,NaN,NaN,NaN,English,2026-03-19 12:45:00,NaN,9780593655047 (electronic bk); 9780593655030,9780593655047 (electronic bk); 9780593655030,NaN,NaN,NaN,9926907601302311,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at OverDrive (OverDrive - C...,NaN,NaN,0,0,1 online resource,NaN,1,0,1,0,0,http://link.overdrive.com/?websiteID=120589&ti...,9780593655047; 0593655044; 9780593655030; 0593...,9780593655047; 0593655044; 9780593655030; 0593...,9926907601302311,The anxious generation How the great rewiring ...,OverDrive - Consortium,Available,53452246900002311,1,Click to access digital title.,NaN,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,http://link.overdrive.com/?websiteID=120589&ti...
6,An evidence-based guide to assistive technolog...,NaN,Book {Book - Electronic} text; computer; onlin...,"Rhodes, Alice L., (New York, NY : Routledge, 2...",Students with disabilities--Services for.;Stud...,Evidence-based instruction in special education,NaN,2026-03-24 04:13:00,NaN,NaN,NaN,English,2026-03-23 16:04:00,English,9781003524090; 1003524095; 9781040524824; 1040...,9781003524090; 9781003524090; 9781040524824; 9...,NaN,NaN,(NhCcYBP)880e3b0db083431896f223e324a7708697810...,9926907593802311,98,NaN,NaN,NaN,371.9045,LC4015 .E87 2026eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,0,0,1 online resource (200 pages) :,NaN,0,0,0,0,0,https://www.taylorfrancis.com/books/9781003524090,1003524095; 9781003524090; 1040524826; 9781040...,1003524095; 9781003524090; 1040524826; 9781040...,9926907593802311,An evidence-based guide to assistive technolog...,Taylor & Francis Ebooks (EBA),Available,53452318750002311,1,NaN,NaN,NaN,[https://www.taylorfrancis.com/books/978100352...,https://www.taylorfrancis.com/books/9781003524090,,https://www.taylorfrancis.com/books/9781003524090
7,INTRODUCTION TO AMERICAN DEAF CULTURE [electro...,NaN,Book {Book - Electronic},THOMAS K. HOLCOMB. (OXFORD : OXFORD UNIV PRESS...,Deaf culture--United States.;Electronic books.,NaN,NaN,2026-02-17 04:03:00,NaN,NaN,NaN,English,2026-02-16 15:58:00,English,0190240857; 9780190240851,9780190240851; 9780190240851,NaN,NaN,(OCoLC)on1500519961; (OCoLC)1500519961,9926876681102311,78,NaN,NaN,NaN,NaN,HV2380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,0,0,1 online resource,NaN,0,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926876681102311,INTRODUCTION TO AMERICAN DEAF CULTURE,Ebooks moved from ProQuest to EBSCO,Available,53451023240002311,1,NaN,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
8,Trauma counseling : theories and interventions...,NaN,Book {Book - Electronic} text; computer; onlin...,"López Levers, Lisa (New York, NY : Springer Pu...",Psychic trauma--Treatment.;Wounds and injuries...,NaN,NaN,2026-04-15 08:28:00,Second edition.,NaN,NaN,English,2026-02-02 11:07:00,English,9780826150851; 0826150853; 9780826150851 (EBSC...,9780826150851; 9780826150851; 9780826150851 (E...,NaN,NaN,(OCoLC)1298514014; (OCoLC)cis063794753,9926868740402311,101,NaN,NaN,NaN,362.1/04256,RC552.P67 L475 2023eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xxvi, 550 pages) :",NaN,0,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,1,Single User,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Single User; https://search.ebscohost.com/logi...
9,New kid [electronic resource]. Jerry Craft.,NaN,Book {Book - Electronic} text; computer; onlin...,"Craft, Jerry. (2019.)",Juvenile Fiction.;African American Fiction.;Co...,NaN,NaN,2026-01-27 04:11:00,NaN,NaN,NaN,English,2026-01-26 15:25:00,NaN,9780062691217 (electronic bk); 9780062691194,9780062691217 (electronic bk); 9780062691194,NaN,NaN,NaN,9926858905602311,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at OverDrive (OverDrive - A...,NaN,NaN,0,0,1 online resource,NaN,1,0,1,0,0,http://link.overdrive.com/?websiteID=120589&ti...,9780062691217; 006269121X; 9780062691194; 0062...,9780062691217; 006269121X; 9780062691194; 0062...,9926858905602311,New kid,OverDrive - Advantage,Available,53449394640002311,1,Click to access digital title.,NaN,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,http://link.overdrive.com/?websiteID=120589&ti...
10,INTRODUCTION TO AMERICAN DEAF CULTURE [electro...,NaN,Book {Book - Electronic} text; unmediated; volume,THOMAS K. HOLCOMB. (OXFORD : OXFORD UNIV PRESS...,Deaf culture--United States.;Culture sourde--É...,NaN,NaN,2026-04-15 08:28:00,NaN,NaN,NaN,English,2026-01-05 16:35:00,English,0190240857; 9780190240851; 9780190240851 (EBSCO),9780190240851; 9780190240851; 9780190240851 (E...,NaN,NaN,(OCoLC)1500519961; (OCoLC)cis070811966,9926852848702311,84,NaN,NaN,NaN,305.9/0820973,HV2380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,0,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926852848702311,INTRODUCTION TO AMERICAN DEAF CULTURE,EBSCO Ebooks Individually Purchased,Available,53448439790002311,1,Unlimited Access,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
11,Applied Artificial Intelligence in Business : ...,NaN,Book {Book - Electronic} text; computer; onlin...,"Chan, Leong. (Cham : Springer International Pu...",Artificial intelligence-Industrial application...,Applied Innovation and Technology Management S...,NaN,2026-04-15 08:28:00,NaN,NaN,NaN,English,2025-12-03 09:32:00,NaN,9783031057397; 9783031057403 (Springer e-books...,9783031057397; 9783031057403 (Springer e-books...,NaN,NaN,(CaONFJC)cis064550969,9926837078602311,87,NaN,NaN,NaN,658.0563,HD30.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Springer Nature; Springe...,NaN,NaN,1,0,1 online resource (370 pages),NaN,0,0,0,0,0,https://link.springer.com/978-3-031-05740-3 Un...,9783031057403; 3031057406; 9783031057397; 3031...,9783031057403; 3031057406; 9783031057397; 3031...,9926837078602311,Applied Artificial Intelligence in Business : ...,Springer Ebooks Individually Purchased,Available,53446362200002311,1,Unlimited Access,NaN,NaN,"[https://link.springer.com/978-3-031-05740-3, ...",https://link.springer.com/978-3-031-05740-3,Unlimited Access Unlimited Access,Unlimited Access; https://link.springer.com/97...
12,The Comprehensive Guide to Interdisciplinary V...,NaN,Book {Book - Electronic} text; computer; onlin...,"Loue, Sana. (Cham : Springer International Pub...",Animal welfare.,NaN,NaN,2025-12-30 10:17:00,1st ed.,NaN,NaN,English,2025-12-06 14:56:00,NaN,9783031103292; 9783031103308 (Springer e-books...,9783031103292; 9783031103308 (Springer e-books...,NaN,NaN,(CaONFJC)cis064862564,9926829231602311,86,NaN,NaN,NaN,NaN,RC455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Springer Nature; Springe...,NaN,NaN,0,0,1 online resource (370 pages),NaN,2,0,0,0,0,https://link.springer.com/978-3-031-10330-8 Un...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926829231602311,The Comprehensive Guide to Interdisciplinary V...,Springer Ebooks Individually Purchased,Available,53433284910002311,1,Unlimited Access,NaN,NaN,"[https://link.springer.com/978-3-031-10330-8, ...",https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,Unlimited Access; https://link.springer.com/97...
13,"Religio Medici and Hydriotaphia, or Urne-Buria...",NaN,Book {Book - Electronic} text; computer; onlin...,"Browne, Thomas, (New York, NY : The New York R...",1500-1700;English prose literature--Early mode...,New York Review Books classics,NaN,2026-04-15 08:28:00,NaN,NaN,NaN,English,2025-08-15 13:02:00,English,9781590175033; 1590175034; 9781590175033 (EBSC...,9781590175033; 9781590175033; 9781590175033 (E...,NaN,NaN,(OCoLC)869384333; (OCoLC)cis023169076,9926781641702311,114,NaN,NaN,2015 J-990 and others,828/.409,PR3327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,0,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,1590174887; 9781590174883; 9781590175033; 1590...,1590174887; 9781590174883; 9781590175033; 1590...,9926781641702311,"Religio Medici and Hydriotaphia, or Urne-Buria...",EBSCO Ebooks Individually Purchased,Available,53441638660002311,1,Single User,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Single User; https://search.ebscohost.com/logi...
14,The portable feminist reader / edited with an ...,NaN,Book {Book - Electronic} text; computer; onlin...,"Gay, Roxane, (New York : Penguin Books, [2025])",Feminism.;Electronic books.,Penguin classics,NaN,2025-12-30 10:17:00,NaN,NaN,NaN,English,2025-06-10 15:02:00,NaN,9781101992678; 1101992670; 9780143110392,9781101992678; 9781101992678; 9780143110392,NaN,NaN,90101993167; (DLC)ybp308895455,9926747489202311,88,NaN,NaN,NaN,305.42,HQ1150 .P67 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,0,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,1101992670; 9781101992678; 9780143110392; 0143...,1101992670; 9781101992678; 9780143110392; 0143...,9926747489202311,The portable feminist reader /,EBSCO Ebooks Individually Purchased,Available,53438150710002311,1,NaN,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - 1 user,Online Access - 1 user; https://search.ebscoho...
15,Stoelting's pharmacology & physiology in anest...,NaN,Book {Book - Electronic} text; computer; onlin...,"Flood, Pamela; Rathmell, James P.; Urman, Rich...","Anesthesiology--Handbooks, manuals, etc.;Anest...",NaN,NaN,2026-04-15 08:28:00,Sixth edition,Stoelting's pharmacology and physiology in ane...,NaN,English,2025-05-30 09:32:00,English,9781975126926; 1975126920; 9781975126919; 1975...,9781975126926; 9781975126926; 9781975126919; 9...,NaN,NaN,(OCoLC)1249630319; (OCoLC)cis062117750,9926738030202311,106,NaN,NaN,QV 81,615.7/81,RD82.2 .S76 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,1,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,1975126920; 9781975126926; 9781975126919; 1975...,1975126920; 9781975126926; 9781975126919; 1975...,9926738030202311,Stoelting's pharmacology & physiology in anest...,EBSCO Ebooks Individually Purchased,Available,53437481400002311,1,Unlimited Access,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
16,"Linguistics of American Sign Language, 5th Ed....",NaN,Book {Book - Electronic} text; computer; onlin...,"Valli, Clayton, (Washington, D.C. : Gallaudet ...","American Sign Language--Guides, manuels, etc.;...",Book collections on Project MUSE.,NaN,2026-04-15 08:28:00,5th ed.,NaN,NaN,English,2025-04-08 08:55:00,NaN,9781563685071; 9781944838881 (PMUSE); 97815636...,9781563685071; 9781944838881 (PMUSE); 97815636...,NaN,NaN,(CaONFJC)cis059843963,9926721690202311,91,NaN,NaN,NaN,419/.7,HV2474 .V35 2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Project Muse; Project Mu...,NaN,NaN,1,0,1 online resource (595 pages):,NaN,1,0,0,0,0,https://muse.jhu.edu/book/77997/ Unlimited Acc...,9781944838881; 1944838880; 1563685078; 9781563...,9781944838881; 1944838880; 1563685078; 9781563...,9926721690202311,"Linguistics of American Sign Language, 5th Ed....",Project Muse Ebooks Individually Purchased,Available,53436149810002311,1,Unlimited Access,NaN,NaN,"[https://muse.jhu.edu/book/77997/, Unlimited, ...",https://muse.jhu.edu/book/77997/,Unlimited Access Unlimited Access,Unlimited Access; https://muse.jhu.edu/book/77...
17,Introduction to Crisis and Trauma Counseling.,NaN,Book {Book - Electronic} text; computer; onlin...,"Duffey, Thelma. (Newark : American Counseling ...",Crisis intervention (Mental health services),NaN,NaN,2026-04-15 08:28:00,1st ed.,NaN,NaN,English,2025-04-08 08:39:00,NaN,9781119685135; 9781119685111; 9781394347216 (J...,9781119685135; 9781119685111; 9781394347216 (J...,NaN,NaN,(CaONFJC)cis070858783,9926721490202311,88,NaN,NaN,NaN,616.89025000000004,RC480.6 .I587 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Wiley Online Library; Wi...,NaN,NaN,1,0,1 online resource (372 pages),NaN,0,0,0,0,0,https://onlinelibrary.wiley.com/book/10.1002/9...,9781119685135; 1119685133; 9781394347216; 1394...,9781119685135; 1119685133; 9781394347216; 1394...,9926721490202311,Introduction to Crisis and Trauma Counseling.,Wiley Ebooks Individually Purchased,Available,53436129820002311,1,Unlimited Access,NaN,NaN,[https://onlinelibrary.wiley.com/book/10.1002/...,https://onlinelibrary.wiley.com/book/10.1002/9...,Unlimited Access Unlimited Access,Unlimited Access; https://onlinelibrary.wiley....

In [26]:
#resultsPlusList.to_excel('Results Plus List Example.xlsx')

resultsPlusList.sort_values(by = 'Title_x')['Title_x'].unique()

array(['An evidence-based guide to assistive technology : meeting the needs of all students with disabilities / edited by Alice L. Rhodes and Victoria Slocum.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Child-centered play therapy : a practical guide to therapeutic relationships with children / Nancy H. Cochran, William J. Nordling, Jeff L. Cochran.',
       'Core Competencies in Cognitive-Behavioral Therapy : Becoming a Highly Effective and Competent Cognitive-Behavioral Therapist / Cory F. Newman.',
       'Deaf culture : exploring deaf communities in the United States / Irene W. Leigh, PhD, Jean F. Andrews, PhD, Raychelle L. Harris, PhD, Topher González Ávila, MA.',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Ethics of data and analytics : concepts and cases / Kirsten Martin.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement / Rona F. Levin, Bonnie Lauder, editors.',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Guide to the vascular plants of Tennessee / compiled and edited by members of the Tennessee Flora Committee.',
       'Hey whipple, squeeze this : the classic guide to creating great advertising / Luke Sullivan.',
       'How great leaders think : the art of reframing',
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'INTRODUCTION TO AMERICAN DEAF CULTURE [electronic resource].',
       'Introduction to Crisis and Trauma Counseling.',
       'Linguistics of American Sign Language, 5th Ed. :  An Introduction /  Clayton Valli [and others].',
       'New kid [electronic resource]. Jerry Craft.',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke / W. Julian Korab-Karpowicz.',
       'Pediatric acute care : a guide for interprofessional practice / edited by Beth Nachtsheim Bolick, Karin Reuter-Rice, Maureen A. Madden, Paul N. Severin.',
       'Planetary Geology : An Introduction.',
       'Process-based CBT : the science and core clinical competencies of cognitive behavioral therapy / edited by Steven C. Hayes, and Stefan G. Hofmann.',
       'Professional development : what works / Sally J. Zepeda.',
       'Property of the Rebel Librarian [electronic resource] / Allison Varnes.',
       'Pursuing happiness [electronic resource] : a Bedford spotlight reader / [compiled and edited by] Matthew Parfitt, Boston University, Dawn Skorczewski, Brandeis University.',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases / author: Committee on Infectious Diseases, American Academy of Pediatrics; David W. Kimberlin, MD, FAAP, editor; Ritu Banerjee, MD, PhD, FAAP, Elizabeth D. Barnett, MD, FAAP, Ruth Lynfield, MD, FAAP, Mark H. Sawyer, MD, FAAP, associate editor.',
       'Religio Medici and Hydriotaphia, or Urne-Buriall / Sir Thomas Browne ; edited and with an introduction by Stephen Greenblatt and Ramie Targoff.',
       'Research methods for social work : a problem-based approach / Antoinette Y. Farmer, G. Lawrence Farmer.',
       'Sales force management : leadership, innovation, technology / Mark W. Johnston, Greg W. Marshall, and Jessica L. Ogilvie.',
       'School social work : a skills-based competency approach / JoDee Keller, PhD, LICSW Department of Social Work, Professor of Social Work Pacific Lutheran University.',
       "Stoelting's pharmacology & physiology in anesthetic practice [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman",
       'Strategy in 3D : essential tools to diagnose, decide, & deliver / Greg Fisher, John E. Wisneski, Rene M. Bakker.',
       'Successful grant writing : strategies for health and human service professionals / Laura N. Gitlin, Ann Kolanowski, Kevin J. Lyons.',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time / Gerald Feigin.',
       'Supply chain transformation : building and executing an integrated supply chain strategy / J. Paul Dittmann.',
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The anxious generation : how the great rewiring of childhood is causing an epidemic of mental illness / Jonathan Haidt.',
       'The anxious generation [electronic resource] : How the great rewiring of childhood is causing an epidemic of mental illness. Jonathan Haidt.',
       'The comprehensive guide to interdisciplinary veterinary social work / Sana Loue, Pamela Linden, editors.',
       'The portable feminist reader / edited with an introduction by Roxane Gay.',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world / Ronald Heifetz, Alexander Grashow, Marty Linsky.',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster / [edited by] Lisa López Levers, PhD, LPCC-S, LPC, CRC, NCC.'],
      dtype=object)

### Expand the ISBN Normalized Column

In [27]:
resultsPlusList['ISBN (Normalized) List'] = resultsPlusList['ISBN (Normalized)'].apply(lambda x: x.split(";"))

In [28]:
expandedList = resultsPlusList.explode('ISBN (Normalized) List')

expandedList['ISBN (Normalized) List'] = expandedList['ISBN (Normalized) List'].str.strip()

#expandedList.to_excel('Expanded List Example.xlsx')

In [29]:
finalJoin = pd.merge(expandedList, bookstoreList, left_on = 'ISBN (Normalized) List', right_on = 'ISBN', how = 'inner')

#finalJoin

In [30]:
selectiveCols = finalJoin[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN (Normalized) List', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Electronic location', 'Electronic access', 'Electronic Availability']]

selectiveCols = selectiveCols.drop_duplicates()

selectiveCols = selectiveCols.rename(columns = {'Section Code': 'Course Code'})

len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

40

In [31]:
selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique()

array(['AN EVIDENCE-BASED GUIDE TO ASSISTIVE TECHNOLOGY : MEETING THE NEEDS OF ALL STUDENTS WITH DISABILITIES',
       'APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : CONCEPTS AND CASES',
       'CHILD-CENTERED PLAY THERAPY',
       'CORE COMPETENCIES IN COGNITIVE-BEHAVIORAL THERAPY',
       'DEAF CULTURE : EXPLORING DEAF COMMUNITIES IN THE UNITED STATES',
       'DEMAND AND SUPPLY INTEGRATION : THE KEY TO WORLD-CLASS DEMAND FORECASTING, SECOND EDITION',
       'ETHICS OF DATA AND ANALYTICS', 'EVICTED',
       'EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING EVIDENCE-BASED PRACTICE AND QUALITY IMPROVEMENT',
       'GLOBAL WRITING FOR PUBLIC RELATIONS : CONNECTING IN ENGLISH WITH STAKEHOLDERS AND PUBLICS WORLDWIDE',
       'GUIDE TO THE VASCULAR PLANTS OF TENNESSEE',
       'HEY WHIPPLE, SQUEEZE THIS : THE CLASSIC GUIDE TO CREATING GREAT ADVERTISING',
       'HOW GREAT LEADERS THINK : THE ART OF REFRAMING',
       'HUMAN OSTEOLOGY', 'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'INTRODUCTION TO CRISIS AND TRAUMA COUNSELING',
       'LINGUISTICS OF ASL: INTRO (W/DVD)', 'NEW KID',
       'ON THE HISTORY OF POLITICAL PHILOSOPHY : GREAT POLITICAL THINKERS FROM THUCYDIDES TO LOCKE',
       'PEDIATRIC ACUTE CARE : A GUIDE TO INTERPROFESSIONAL PRACTICE',
       'PLANETARY GEOLOGY : AN INTRODUCTION', 'PROCESSED BASED CBT',
       'PROFESSIONAL DEVELOPMENT : WHAT WORKS',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'RED BOOK 2024 : REPORT OF THE COMMITTEE ON INFECTIOUS DISEASES',
       'RELIGIO MEDICI AND URNE-BURIALL',
       'RESEARCH METHODS FOR SOCIAL WORK : A PROBLEM-BASED APPROACH',
       'SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATION, TECHNOLOGY',
       'SCHOOL SOCIAL WORK',
       "STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANESTHETIC PRACTICE",
       'STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, DECIDE, AND DELIVER',
       'SUCCESSFUL GRANT WRITING : STRATEGIES FOR HEALTH AND HUMAN SERVICE PROFESSIONALS',
       'SUPPLY CHAIN TRANSFORMATION: BUILDING AND EXECUTING AN INTEGRATED SUPPLY CHAIN STRATEGY',
       'THE ANXIOUS GENERATION : HOW THE GREAT REWIRING OF CHILDHOOD IS CAUSING AN EPIDEMIC OF MENTAL ILLNESS',
       'THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY VETERINARY SOCIAL WORK',
       'THE PORTABLE FEMINIST READER',
       'THE PRACTICE OF ADAPTIVE LEADERSHIP : TOOLS AND TACTICS FOR CHANGING YOUR ORGANIZATION AND THE WORLD',
       'THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION: SUPPLY CHAIN PLANNING AND ANALYTICS : THE RIGHT PRODUCT IN THE RIGHT PLACE AT THE RIGHT TIME',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER'],
      dtype=object)

In [32]:
# Filter out the titles whose access is not Unlimited

selectiveCols = selectiveCols[(selectiveCols['Electronic access'] != 'Online Access - 1 user') & (selectiveCols['Electronic access'] != 'Single User Single User') & (selectiveCols['Electronic access'] != 'Three User Three User') & (selectiveCols['Electronic access'] != 'Online Access - 3 users') & (selectiveCols['Electronic access'] != 'Online access : 2 simultaneous users; http://www.ebrary.com/corp/legal.jsp Click here for terms of use') & (selectiveCols['Electronic access'] != 'Online access - 1 simultaneous user') & (selectiveCols['Electronic access'] != 'Online Access - 3 simultaneous users.')]

selectiveCols = selectiveCols[(selectiveCols['Short Title'] != 'CEREMONY') & (selectiveCols['Short Title'] != 'CRAFTING THE PERSONAL ESSAY : A GUIDE FOR WRITING AND PUBLISHING CREATIVE NON-FICTION') & (selectiveCols['Short Title'] != 'EVERYTHING IS OBVIOUS : HOW COMMON SENSE FAILS US') & (selectiveCols['Short Title'] != 'FUN HOME : A FAMILY TRAGICOMIC') & (selectiveCols['Short Title'] != 'INFORMATION ARCHITECTURE F/WORLD WI') & (selectiveCols['Short Title'] != 'ME AND MY DADDY LISTEN TO BOB MARLEY : NOVELLAS AND STORIES') & (selectiveCols['Short Title'] != 'PUBLIC LIBRARIES AND THEIR COMMUNITIES') & (selectiveCols['Short Title'] != 'STRATEGIC PLANNING FOR PUBLIC RELATIONS') & (selectiveCols['Short Title'] != 'SUN ALSO RISES') & (selectiveCols['Short Title'] != 'THE PROFESSOR IS IN : THE ESSENTIAL GUIDE TO TURNING YOUR PH. D. INTO A JOB') & (selectiveCols['Short Title'] != "ALL THAT SHE CARRIED : THE JOURNEY OF ASHLEY'S SACK, A BLACK FAMILY KEEPSAKE") & (selectiveCols['Short Title'] != 'INTERPERSONAL COMMUNICATION') & (selectiveCols['Short Title'] != 'LET NOBODY TURN US AROUND') & (selectiveCols['Short Title'] != 'LINEAR SYSTEMS THEORY') & (selectiveCols['Short Title'] != 'MERCY') & (selectiveCols['Short Title'] != 'NATURES BEST HOPE') & (selectiveCols['Short Title'] != 'FACILITATING BREAKTHROUGH : HOW TO REMOVE OBSTACLES, BRIDGE DIFFERENCES, AND MOVE FORWARD TOGETHER&NBSP;')]

selectiveCols = selectiveCols[selectiveCols['MMS ID'] != 9926793973502311]

selectiveCols

,Academic Term,Academic Department Name,Course Code,Instructor Name,ISBN (Normalized) List,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Electronic location,Electronic access,Electronic Availability
0,Summer 2026,NURSING,202630-NURS.670.001-85245,"Malone, Marian",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,9,9926931276402311,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...
1,Summer 2026,NURSING,202630-NURS.670.002-87778,"Neal, Allyson",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,5,9926931276402311,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...
2,Summer 2026,MARKETING,202630-MARK.471.301-88179,"Presley Bone, Blair",9781040301319,"SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATIO...","JOHNSTON, MARK W., MARSHALL, GREG W., AND OGIL...","ROUTLEDGE, CHAPMAN & HALL, INCORPORATED",35,9926916167202311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...
3,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.580.001-85258,"Bolumole, Yemisi",9781118282236,HOW GREAT LEADERS THINK : THE ART OF REFRAMING,"BOLMAN, LEE G. AND DEAL, TERRENCE E.","WILEY & SONS, INCORPORATED, JOHN",50,9926914664702311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...
4,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.580.001-85258,"Bolumole, Yemisi",9780071798310,SUPPLY CHAIN TRANSFORMATION: BUILDING AND EXEC...,"DITTMANN, J. PAUL",MCGRAW-HILL EDUCATION,50,9926913176702311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...
5,Summer 2026,ADVERTISING,202630-ADVT.350.001-88124,"Short Piercy, Megan",9781119819745,"HEY WHIPPLE, SQUEEZE THIS : THE CLASSIC GUIDE ...","SULLIVAN, LUKE AND BOCHES, EDWARD","WILEY & SONS, INCORPORATED, JOHN",30,9926910091102311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...
6,Summer 2026,CINEMA STUDIES,202630-CNST.312.001-82846,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926907601302311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...
7,Summer 2026,CINEMA STUDIES,202630-CNST.312.002-88115,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,5,9926907601302311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...
8,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.001-82757,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926907601302311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...
9,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.004-85995,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926907601302311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...
10,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.601-86498,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926907601302311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...
11,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.602-86532,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926907601302311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...
12,Summer 2026,SPECIAL EDUCATION,202630-SPED.590.301-87244,"Malone, Elisabeth",9781040656297,AN EVIDENCE-BASED GUIDE TO ASSISTIVE TECHNOLOG...,NaN,TAYLOR & FRANCIS GROUP,20,9926907593802311,https://www.taylorfrancis.com/books/9781003524090,,Electronic version at Taylor & Francis; Taylor...
13,Summer 2026,SPECIAL EDUCATION,202630-SPED.590.302-85926,"Malone, Elisabeth",9781040656297,AN EVIDENCE-BASED GUIDE TO ASSISTIVE TECHNOLOG...,NaN,TAYLOR & FRANCIS GROUP,20,9926907593802311,https://www.taylorfrancis.com/books/9781003524090,,Electronic version at Taylor & Francis; Taylor...
14,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.301-83576,"Swafford, Ethan",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926876681102311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at EBSCOhost; EBSCO Ebooks ...
15,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.302-85682,"Shahan, Cheryl",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.","OXFORD UNIVERSITY PRESS, INCORPORATED",15,9926876681102311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at EBSCOhost; EBSCO Ebooks ...
16,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.501-83577,"Haggard, April",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926876681102311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at EBSCOhost; EBSCO Ebooks ...
17,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.502-85684,"Stricklen, William",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926876681102311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at EBSCOhost; EBSCO Ebooks ...
21,Summer 2026,READING EDUCATION,202630-REED.230.300-87093,"Varnes, Allison",9780062691194,NEW KID,CRAFT,HARPERCOLLINS,25,9926858905602311,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Electronic version at OverDrive (OverDrive - A...
22,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.301-83576,"Swafford, Ethan",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926852848702311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
23,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.302-85682,"Shahan, Cheryl",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.","OXFORD UNIVERSITY PRESS, INCORPORATED",15,9926852848702311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
24,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.501-83577,"Haggard, April",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926852848702311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
25,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.502-85684,"Stricklen, William",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926852848702311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
26,Summer 2026,ARTIFICIAL INTELLEGIENCE,202630-AI.101.001-87621,"Sedighi, Art",9783031057403,APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : ...,"CHAN, LEONG, HOGABOAM, LILIYA, AND CAO, RENZHI",SPRINGER INTERNATIONAL PUBLISHING AG,100,9926837078602311,https://link.springer.com/978-3-031-05740-3,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...
27,Summer 2026,ARTIFICIAL INTELLEGIENCE,202630-AI.101.002-88157,"Sedighi, Art",9783031057403,APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : ...,"CHAN, LEONG, HOGABOAM, LILIYA, AND CAO, RENZHI",SPRINGER INTERNATIONAL PUBLISHING AG,100,9926837078602311,https://link.springer.com/978-3-031-05740-3,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...
28,Summer 2026,SOCIAL WORK,202630-SOWK.567.001-86095,"Poe, Bethanie",9783031103308,THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY V...,SPRINGER,SPRINGER NATURE,6,9926829231602311,https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...
29,Summer 2026,SOCIAL WORK,202630-SOWK.567.002-86096,"Poe, Bethanie",9783031103308,THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY V...,SPRINGER,SPRINGER NATURE,6,9926829231602311,https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...
30,Summer 2026,SOCIAL WORK,202630-SOWK.567.003-86097,"Poe, Bethanie",9783031103308,THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY V...,SPRINGER,SPRINGER NATURE,6,9926829231602311,https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...
35,Summer Mini 2026,NURSING,202625-NURS.637.001-70302,"Gheen, Melissa",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,8,9926738030202311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
36,Summer Mini 2026,NURSING,202625-NURS.637.002-70303,"Emion, Adryan",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,9,9926738030202311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
37,Summer 2026,NURSING,202630-NURS.629.001-85211,"Alberding, James",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,10,9926738030202311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
38,Summer 2026,NURSING,202630-NURS.629.002-85212,"Gheen, Melissa",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,9,9926738030202311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
39,Summer 2026,NURSING,202630-NURS.640.001-87568,"Gheen, Melissa",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,20,9926738030202311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
40,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.435.501-84629,"Holder, Shawn",9781944838881,LINGUISTICS OF ASL: INTRO (W/DVD),"VALLI, CLAYTON, LUCAS, CEIL, MULROONEY, KRISTI...",GALLAUDET UNIVERSITY PRESS,15,9926721690202311,https://muse.jhu.edu/book/77997/,Unlimited Access Unlimited Access,Electronic version at Project Muse; Project Mu...
41,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.435.502-86293,"Holder, Shawn",9781944838881,LINGUISTICS OF ASL: INTRO (W/DVD),"VALLI, CLAYTON, LUCAS, CEIL, MULROONEY, KRISTI...",GALLAUDET UNIVERSITY PRESS,5,9926721690202311,https://muse.jhu.edu/book/77997/,Unlimited Access Unlimited Access,Electronic version at Project Muse; Project Mu...
42,Summer 2026,COUNSELOR EDUCATION,202630-COUN.563.001-83836,"Moralejo, Jennifer",9781119685135,INTRODUCTION TO CRISIS AND TRAUMA COUNSELING,"DUFFEY, T. & HABERSTROH, S. (2020).",AMERICAN COUNSELING ASSOCIATION,30,9926721490202311,https://onlinelibrary.wiley.com/book/10.1002/9...,Unlimited Access Unlimited Access,Electronic version at Wiley Online Library; Wi...
45,Summer 2026,ANTHROLOPOGY,202630-ANTH.480.002-85299,"Platt, Rebecca",9780080920856,HUMAN OSTEOLOGY,"WHITE, TIM D., FOLKENS, PIETER A., BLACK, MICH...",ELSEVIER SCIENCE & TECHNOLOGY,15,9926677862202311,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...
47,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.002-84819,"Kinson, Victor",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",5,9926600557802311,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...
48,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.501-86437,"Ekern, Christina",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",40,9926600557802311,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...
49,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.502-83893,"Whitworth, Allison",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",40,9926600557802311,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...
50,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.901-83892,"Kinson, Victor",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",15,9926600557802311,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...
51,Summer 2026,MANAGEMENT,202630-MGT.503.001-87215,"Williams, David",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",45,9926600557802311,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...
52,Summer 2026,CINEMA STUDIES,202630-CNST.312.001-82846,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926536272302311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
53,Summer 2026,CINEMA STUDIES,202630-CNST.312.002-88115,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,5,9926536272302311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
54,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.001-82757,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926536272302311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
55,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.004-85995,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926536272302311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
56,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.601-86498,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926536272302311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
57,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.602-86532,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926536272302311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
58,Summer 2026,NURSING,202630-NURS.630.001-84831,"Brewer, Tracy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
59,Summer 2026,NURSING,202630-NURS.630.002-85214,"Alberding, James",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",11,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
60,Summer 2026,NURSING,202630-NURS.630.003-85216,"Apalodimas, Leah",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
61,Summer 2026,NURSING,202630-NURS.630.004-85220,"Bauer, Samantha",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",6,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
62,Summer 2026,NURSING,202630-NURS.630.006-85222,"Gheen, Melissa",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
63,Summer 2026,NURSING,202630-NURS.630.007-85223,"Hessock, Melissa",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
64,Summer 2026,NURSING,202630-NURS.630.008-85224,"Mills, Jeremy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
65,Summer 2026,NURSING,202630-NURS.630.009-85225,"Patrick, Jennifer",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
66,Summer 2026,NURSING,202630-NURS.630.010-85226,"Philpott, Cathy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",6,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
67,Summer 2026,NURSING,202630-NURS.630.011-85227,"Sowell, Elizabeth",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
68,Summer 2026,NURSING,202630-NURS.630.012-86040,"Talley, Thomas",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",5,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
69,Summer 2026,NURSING,202630-NURS.631.001-87540,"Apalodimas, Leah",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",10,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
70,Summer 2026,NURSING,202630-NURS.631.002-87541,"Philpott, Cathy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",16,9926521386802311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...

In [33]:
len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

32

In [34]:
nonUnlimited = finalJoin[~finalJoin['Short Title'].isin(selectiveCols['Short Title'])].dropna(how = 'all')

nonUnlimited.sort_values(by = 'Short Title')['Short Title'].unique()

array(['EVICTED', 'GUIDE TO THE VASCULAR PLANTS OF TENNESSEE',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'RELIGIO MEDICI AND URNE-BURIALL', 'THE PORTABLE FEMINIST READER',
       'THE PRACTICE OF ADAPTIVE LEADERSHIP : TOOLS AND TACTICS FOR CHANGING YOUR ORGANIZATION AND THE WORLD',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER'],
      dtype=object)

## Export the Overlap Report

### This is the dataset that gets transferred to the Transforming Bookstore List Python code.

In [35]:
selectiveCols.to_excel(date_str+'_overlap_report.xlsx', index = False)

## Export the Bookstore Results to Send to the Bookstore

In [36]:
warnings.filterwarnings("ignore")

bookstoreExport = selectiveCols

# Fill in the Primo Link based on the MMS ID

for i in range(len(bookstoreExport['MMS ID'])):
    bookstoreExport['Electronic location'].iloc[i] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma' + str(bookstoreExport['MMS ID'].iloc[i])

bookstoreExport = bookstoreExport.rename(columns = {'ISBN (Normalized) List': 'ISBN', 'Electronic access': 'Access_Type', 'Electronic location': 'Permalink', 'Course Code': 'Section Code'})

bookstoreExport = bookstoreExport[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Access_Type', 'Electronic Availability', 'Permalink']]

bookstoreExport

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Electronic Availability,Permalink
0,Summer 2026,NURSING,202630-NURS.670.001-85245,"Malone, Marian",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,9,9926931276402311,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
1,Summer 2026,NURSING,202630-NURS.670.002-87778,"Neal, Allyson",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,5,9926931276402311,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
2,Summer 2026,MARKETING,202630-MARK.471.301-88179,"Presley Bone, Blair",9781040301319,"SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATIO...","JOHNSTON, MARK W., MARSHALL, GREG W., AND OGIL...","ROUTLEDGE, CHAPMAN & HALL, INCORPORATED",35,9926916167202311,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...
3,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.580.001-85258,"Bolumole, Yemisi",9781118282236,HOW GREAT LEADERS THINK : THE ART OF REFRAMING,"BOLMAN, LEE G. AND DEAL, TERRENCE E.","WILEY & SONS, INCORPORATED, JOHN",50,9926914664702311,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...
4,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.580.001-85258,"Bolumole, Yemisi",9780071798310,SUPPLY CHAIN TRANSFORMATION: BUILDING AND EXEC...,"DITTMANN, J. PAUL",MCGRAW-HILL EDUCATION,50,9926913176702311,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...
5,Summer 2026,ADVERTISING,202630-ADVT.350.001-88124,"Short Piercy, Megan",9781119819745,"HEY WHIPPLE, SQUEEZE THIS : THE CLASSIC GUIDE ...","SULLIVAN, LUKE AND BOCHES, EDWARD","WILEY & SONS, INCORPORATED, JOHN",30,9926910091102311,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...
6,Summer 2026,CINEMA STUDIES,202630-CNST.312.001-82846,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926907601302311,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...,https://utk.primo.exlibrisgroup.com/permalink/...
7,Summer 2026,CINEMA STUDIES,202630-CNST.312.002-88115,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,5,9926907601302311,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...,https://utk.primo.exlibrisgroup.com/permalink/...
8,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.001-82757,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926907601302311,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...,https://utk.primo.exlibrisgroup.com/permalink/...
9,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.004-85995,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926907601302311,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...,https://utk.primo.exlibrisgroup.com/permalink/...
10,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.601-86498,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926907601302311,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...,https://utk.primo.exlibrisgroup.com/permalink/...
11,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.602-86532,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926907601302311,Click to access digital title.,Electronic version at OverDrive (OverDrive - C...,https://utk.primo.exlibrisgroup.com/permalink/...
12,Summer 2026,SPECIAL EDUCATION,202630-SPED.590.301-87244,"Malone, Elisabeth",9781040656297,AN EVIDENCE-BASED GUIDE TO ASSISTIVE TECHNOLOG...,NaN,TAYLOR & FRANCIS GROUP,20,9926907593802311,,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...
13,Summer 2026,SPECIAL EDUCATION,202630-SPED.590.302-85926,"Malone, Elisabeth",9781040656297,AN EVIDENCE-BASED GUIDE TO ASSISTIVE TECHNOLOG...,NaN,TAYLOR & FRANCIS GROUP,20,9926907593802311,,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...
14,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.301-83576,"Swafford, Ethan",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926876681102311,,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
15,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.302-85682,"Shahan, Cheryl",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.","OXFORD UNIVERSITY PRESS, INCORPORATED",15,9926876681102311,,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
16,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.501-83577,"Haggard, April",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926876681102311,,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
17,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.502-85684,"Stricklen, William",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926876681102311,,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
21,Summer 2026,READING EDUCATION,202630-REED.230.300-87093,"Varnes, Allison",9780062691194,NEW KID,CRAFT,HARPERCOLLINS,25,9926858905602311,Click to access digital title.,Electronic version at OverDrive (OverDrive - A...,https://utk.primo.exlibrisgroup.com/permalink/...
22,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.301-83576,"Swafford, Ethan",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926852848702311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
23,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.211.302-85682,"Shahan, Cheryl",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.","OXFORD UNIVERSITY PRESS, INCORPORATED",15,9926852848702311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
24,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.501-83577,"Haggard, April",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926852848702311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
25,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.212.502-85684,"Stricklen, William",9780190240851,INTRODUCTION TO AMERICAN DEAF CULTURE,"HOLCOMB, THOMAS K.",OXFORD UNIVERSITY PRESS ACADEMIC US,15,9926852848702311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
26,Summer 2026,ARTIFICIAL INTELLEGIENCE,202630-AI.101.001-87621,"Sedighi, Art",9783031057403,APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : ...,"CHAN, LEONG, HOGABOAM, LILIYA, AND CAO, RENZHI",SPRINGER INTERNATIONAL PUBLISHING AG,100,9926837078602311,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...,https://utk.primo.exlibrisgroup.com/permalink/...
27,Summer 2026,ARTIFICIAL INTELLEGIENCE,202630-AI.101.002-88157,"Sedighi, Art",9783031057403,APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : ...,"CHAN, LEONG, HOGABOAM, LILIYA, AND CAO, RENZHI",SPRINGER INTERNATIONAL PUBLISHING AG,100,9926837078602311,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...,https://utk.primo.exlibrisgroup.com/permalink/...
28,Summer 2026,SOCIAL WORK,202630-SOWK.567.001-86095,"Poe, Bethanie",9783031103308,THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY V...,SPRINGER,SPRINGER NATURE,6,9926829231602311,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...,https://utk.primo.exlibrisgroup.com/permalink/...
29,Summer 2026,SOCIAL WORK,202630-SOWK.567.002-86096,"Poe, Bethanie",9783031103308,THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY V...,SPRINGER,SPRINGER NATURE,6,9926829231602311,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...,https://utk.primo.exlibrisgroup.com/permalink/...
30,Summer 2026,SOCIAL WORK,202630-SOWK.567.003-86097,"Poe, Bethanie",9783031103308,THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY V...,SPRINGER,SPRINGER NATURE,6,9926829231602311,Unlimited Access Unlimited Access,Electronic version at Springer Nature; Springe...,https://utk.primo.exlibrisgroup.com/permalink/...
35,Summer Mini 2026,NURSING,202625-NURS.637.001-70302,"Gheen, Melissa",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,8,9926738030202311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
36,Summer Mini 2026,NURSING,202625-NURS.637.002-70303,"Emion, Adryan",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,9,9926738030202311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
37,Summer 2026,NURSING,202630-NURS.629.001-85211,"Alberding, James",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,10,9926738030202311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
38,Summer 2026,NURSING,202630-NURS.629.002-85212,"Gheen, Melissa",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,9,9926738030202311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
39,Summer 2026,NURSING,202630-NURS.640.001-87568,"Gheen, Melissa",9781975126926,STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANE...,RATHMELL,LIPPINCOTT WILLIAMS & WILKINS,20,9926738030202311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
40,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.435.501-84629,"Holder, Shawn",9781944838881,LINGUISTICS OF ASL: INTRO (W/DVD),"VALLI, CLAYTON, LUCAS, CEIL, MULROONEY, KRISTI...",GALLAUDET UNIVERSITY PRESS,15,9926721690202311,Unlimited Access Unlimited Access,Electronic version at Project Muse; Project Mu...,https://utk.primo.exlibrisgroup.com/permalink/...
41,Summer 2026,AMERICAN SIGN LANGUAGE,202630-ASL.435.502-86293,"Holder, Shawn",9781944838881,LINGUISTICS OF ASL: INTRO (W/DVD),"VALLI, CLAYTON, LUCAS, CEIL, MULROONEY, KRISTI...",GALLAUDET UNIVERSITY PRESS,5,9926721690202311,Unlimited Access Unlimited Access,Electronic version at Project Muse; Project Mu...,https://utk.primo.exlibrisgroup.com/permalink/...
42,Summer 2026,COUNSELOR EDUCATION,202630-COUN.563.001-83836,"Moralejo, Jennifer",9781119685135,INTRODUCTION TO CRISIS AND TRAUMA COUNSELING,"DUFFEY, T. & HABERSTROH, S. (2020).",AMERICAN COUNSELING ASSOCIATION,30,9926721490202311,Unlimited Access Unlimited Access,Electronic version at Wiley Online Library; Wi...,https://utk.primo.exlibrisgroup.com/permalink/...
45,Summer 2026,ANTHROLOPOGY,202630-ANTH.480.002-85299,"Platt, Rebecca",9780080920856,HUMAN OSTEOLOGY,"WHITE, TIM D., FOLKENS, PIETER A., BLACK, MICH...",ELSEVIER SCIENCE & TECHNOLOGY,15,9926677862202311,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
47,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.002-84819,"Kinson, Victor",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",5,9926600557802311,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...,https://utk.primo.exlibrisgroup.com/permalink/...
48,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.501-86437,"Ekern, Christina",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",40,9926600557802311,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...,https://utk.primo.exlibrisgroup.com/permalink/...
49,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.502-83893,"Whitworth, Allison",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",40,9926600557802311,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...,https://utk.primo.exlibrisgroup.com/permalink/...
50,Summer 2026,BUSINESS ADMINISTRATION,202630-BUAD.453.901-83892,"Kinson, Victor",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",15,9926600557802311,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...,https://utk.primo.exlibrisgroup.com/permalink/...
51,Summer 2026,MANAGEMENT,202630-MGT.503.001-87215,"Williams, David",9780190081508,"STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, ...","FISHER, GREG, WISNESKI, JOHN E., BAKKER, RENE ...","OXFORD UNIVERSITY PRESS, INCORPORATED",45,9926600557802311,Online Access - Unlimited users,Electronic version at Oxford Academic; Oxford ...,https://utk.primo.exlibrisgroup.com/permalink/...
52,Summer 2026,CINEMA STUDIES,202630-CNST.312.001-82846,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926536272302311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
53,Summer 2026,CINEMA STUDIES,202630-CNST.312.002-88115,STAFF,9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,5,9926536272302311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
54,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.001-82757,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926536272302311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
55,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.004-85995,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926536272302311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
56,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.601-86498,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,30,9926536272302311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
57,Summer 2026,POLITICAL SCIENCE,202630-POLS.312.602-86532,"Nownes, Anthony",9780593655047,THE ANXIOUS GENERATION : HOW THE GREAT REWIRIN...,"HAIDT, JONATHAN",PENGUIN PUBLISHING GROUP,10,9926536272302311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
58,Summer 2026,NURSING,202630-NURS.630.001-84831,"Brewer, Tracy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
59,Summer 2026,NURSING,202630-NURS.630.002-85214,"Alberding, James",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",11,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
60,Summer 2026,NURSING,202630-NURS.630.003-85216,"Apalodimas, Leah",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
61,Summer 2026,NURSING,202630-NURS.630.004-85220,"Bauer, Samantha",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",6,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
62,Summer 2026,NURSING,202630-NURS.630.006-85222,"Gheen, Melissa",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
63,Summer 2026,NURSING,202630-NURS.630.007-85223,"Hessock, Melissa",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
64,Summer 2026,NURSING,202630-NURS.630.008-85224,"Mills, Jeremy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
65,Summer 2026,NURSING,202630-NURS.630.009-85225,"Patrick, Jennifer",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
66,Summer 2026,NURSING,202630-NURS.630.010-85226,"Philpott, Cathy",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",6,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
67,Summer 2026,NURSING,202630-NURS.630.011-85227,"Sowell, Elizabeth",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",4,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
68,Summer 2026,NURSING,202630-NURS.630.012-86040,"Talley, Thomas",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",5,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
69,Summer 2026,NURSING,202630-NURS.631.001-87540,"Apalodimas, Leah",9780826182142,EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING ...,"LEVIN, RONA","SPRINGER PUBLISHING COMPANY, INCORPORATED",10,9926521386802311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...

In [37]:
bookstoreExport.to_excel(date_str+'BookStoreResults_TPQ.xlsx', index = False) #Send this to the Bookstore