## 1. run the next two cells as-is

In [1]:
#import libraries and set some variables

import requests
import pandas as pd
import xml.etree.ElementTree as ET
from pprint import pprint
from urllib.parse import quote
import numpy as np
import urllib.parse
import os
import warnings
from rapidfuzz import process, fuzz
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

#nltk.download('punkt_tab')
#nltk.download('stopwords')

pd.set_option('display.max_columns', None)


#Setting a few Alma Analytics API variables and whatnot
base_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&path=')  

token_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&token=')

loc1 = 'shared'
loc2 = 'University of Tennessee, Knoxville'
loc3 = 'Reports'
loc4 = 'Collections'
loc5 = 'Textbook ISBNs for Overlap Report_TM'
if loc5 != '':
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/' + loc5 
else:
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/'

get_path = location 
url_encoded_path = quote(get_path)
report_path = base_path + url_encoded_path

xml_snippet = '''
<sawx:expr xsi:type="sawx:list" op="in"
  xmlns:saw="com.siebel.analytics.web/report/v1.1"
  xmlns:sawx="com.siebel.analytics.web/expression/v1.1" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<sawx:expr xsi:type="sawx:sqlExpression">"Bibliographic Details"."MMS Id"</sawx:expr>
{}
</sawx:expr>
'''

In [2]:
report_path

'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?limit=1000&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5&path=/shared/University%20of%20Tennessee%2C%20Knoxville/Reports/Collections/Textbook%20ISBNs%20for%20Overlap%20Report_TM'

In [3]:
#define some functions

#function to extract data from the analytics report
def extract_data(row_elements, columns):
    data = []
    for row in row_elements:
        row_data = {}
        for col in row.findall('{urn:schemas-microsoft-com:xml-analysis:rowset}*'):
            column_name = col.tag.split('}')[1]
            column_value = col.text
            if column_name in columns:  # Check if the column is in the columns dictionary
                row_data[columns[column_name]] = column_value if column_value is not None else np.nan  # Insert NaN if value is missing
        data.append(row_data)
    return data

#pulling the analytics report and extracting data
def get_report(response):
    # Parse the XML response
    root = ET.fromstring(response.content)
    # Extract the ResumptionToken and IsFinished elements from the response XML
    resumption_token_element = root.find('.//ResumptionToken')
    resumption_token = resumption_token_element.text if resumption_token_element is not None else None
    is_finished_element = root.find('.//IsFinished')
    if is_finished_element is not None:
        is_finished = is_finished_element.text
    else:
        is_finished = None

    namespaces = {
        'xmlns': 'urn:schemas-microsoft-com:xml-analysis:rowset',
        'xsd': 'http://www.w3.org/2001/XMLSchema',
        'saw-sql': 'urn:saw-sql'
    }
    columns = {}

    for i, col in enumerate(root.findall('.//xsd:element[@saw-sql:columnHeading]', namespaces)):
        columns[f'Column{i}'] = col.get('{urn:saw-sql}columnHeading', col.get('name'))
    
    # Extract the data from the XML and store it in a list of dictionaries
    all_data = []
    data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
    all_data.extend(data)
    
    # Iterate through subsequent GET requests until IsFinished is True
    while is_finished == 'false':
        # Make the next GET request with the ResumptionToken
        response = requests.get(token_path + resumption_token)

        # Extract the ResumptionToken and IsFinished elements from the response XML
        root = ET.fromstring(response.content)
        is_finished = root.find('.//IsFinished').text

        # Process the response data
        data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
        all_data.extend(data)

    report_df = pd.DataFrame(all_data)

    # Drop the first column of the dataframe
    if not report_df.empty:
        report_df = report_df.drop(report_df.columns[0], axis=1)

    # Reset the index of the dataframe
    report_df = report_df.reset_index(drop=True)

    return report_df


def get_and_concat_report(report_path, report_data_df):
    response = requests.get(report_path)
    report_df = get_report(response)
    print(len(report_df))
    return pd.concat([report_data_df, report_df], ignore_index=True)

# Define a custom function to concatenate non-NaN values and deduplicate the notes fields which contain information about 
# online access type for each ebook
def concatenate_and_deduplicate_notes(row):
    notes = [str(row['Portfolio Public Note']), str(row['Portfolio Authentication Note']), str(row['Electronic location and access'])]
    non_nan_notes = set(note for note in notes if note != 'nan')
    return '; '.join(non_nan_notes)

## 2. Set the date and location of important Excel files

In [4]:
#set the date string for the rest of this notebook
date_str = '2026-08-10'

#Set the location where all bookstore data will be saved to and read from for the rest of this notebook

bookstoreFolder = r"C:\Users\aharrima\GitHub_UTK\Bookstore_Program_Data_Holding_Area"

directory = os.chdir(bookstoreFolder)

## 3. Read in the searchresults file from the bookstore
## make sure to point read_excel to the correct file location!

In [5]:
#load most recent file from bookstore
# you will need to have saved the automated bookstore file using format "searchresults_YYYY-MM-DD.xlsx" to your computer
df = pd.read_excel(r'searchresults_'+date_str+'.xlsx')

# Preview the sorted DataFrame
df

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity
0,Fall 2026,ACCOUNTING,202640-ACCT.200.001-43202,"Jordan, Latonya",9781264453948,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING...,EDMONDS,MCGRAW-HILL HIGHER EDUCATION (US),50
1,Fall 2026,ACCOUNTING,202640-ACCT.200.001-43202,"Jordan, Latonya",9781266677090,CONNECT FOR SURVEY OF ACCOUNTING AND SHARPEN ...,EDMONDS,MCGRAW-HILL HIGHER EDUCATION (US),50
2,Fall 2026,ACCOUNTING,202640-ACCT.200.002-43203,"Jordan, Latonya",9781266677090,CONNECT FOR SURVEY OF ACCOUNTING AND SHARPEN ...,EDMONDS,MCGRAW-HILL HIGHER EDUCATION (US),250
3,Fall 2026,ACCOUNTING,202640-ACCT.200.002-43203,"Jordan, Latonya",9781264453948,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING...,EDMONDS,MCGRAW-HILL HIGHER EDUCATION (US),250
4,Fall 2026,ACCOUNTING,202640-ACCT.200.005-43206,"Jordan, Latonya",9781266677090,CONNECT FOR SURVEY OF ACCOUNTING AND SHARPEN ...,EDMONDS,MCGRAW-HILL HIGHER EDUCATION (US),50
...,...,...,...,...,...,...,...,...,...
5703,Fall 2026,WORLD LANGUAGES AND CULTURES,202640-WLC.530.001-60590,"Brauer, Matthew",9780307793843,ALLAH IS NOT OBLIGED,"KOUROUMA, AHMADOU",KNOPF DOUBLEDAY PUBLISHING GROUP,20
5704,Fall 2026,WORLD LANGUAGES AND ESL EDUCATION,202640-WLEL.455.001-47664,"Coda, James",9781647930080,COMMON GROUND SECOND LANGUAGE ACQUISITION,HENSHAW,HACKETT,15
5705,Fall 2026,WORLD LANGUAGES AND ESL EDUCATION,202640-WLEL.455.002-53260,"Coda, James",9781647930080,COMMON GROUND SECOND LANGUAGE ACQUISITION,HENSHAW,HACKETT,10
5706,Fall 2026,WORLD LANGUAGES AND ESL EDUCATION,202640-WLEL.551.001-58210,"Coda, James",9781647930080,COMMON GROUND : SECOND LANGUAGE ACQUISITION TH...,"HENSHAW, FLORENCIA G. AND HAWKINS, MARIS D.","HACKETT PUBLISHING COMPANY, INCORPORATED",15
5707,Fall 2026,WORLD LANGUAGES AND ESL EDUCATION,202640-WLEL.551.002-58211,"Coda, James",9781647930080,COMMON GROUND : SECOND LANGUAGE ACQUISITION TH...,"HENSHAW, FLORENCIA G. AND HAWKINS, MARIS D.","HACKETT PUBLISHING COMPANY, INCORPORATED",10

## 4. do some work on the bookstore-provided file to generate a list of ISBNs that 
## we will use in a later step

In [6]:
#create list of ISBNs for use in Alma Set creation
#do some pre-processing on the data for cleanup purposes
isbns = df[['ISBN']]
isbns = isbns.dropna()
isbns = isbns.drop_duplicates()
isbns['ISBN'] = isbns['ISBN'].apply(lambda x: x.replace('-',''))
isbns = isbns.astype(str)
#isbns = isbns[(isbns['ISBN'].str.len() == 13) & (isbns['ISBN'].str.isdigit())]
isbns = isbns[(isbns['ISBN'].str.isdigit())]
isbns = isbns.reset_index()
isbns = isbns.drop('index', axis = 1)
isbns = isbns.iloc[isbns['ISBN'].str.len().sort_values(ascending = False).index]
isbns

               ISBN
0     9781264453948
1158  9781071902035
1036  9781420095234
1035  9780191502101
1034  9780081006108
...             ...
1223     1265632278
783      1265444927
859      1266904646
1396     0679601813
1397      812975049

[1547 rows x 1 columns]

In [7]:
isbns.dtypes

ISBN    object
dtype: object

## Fix Known Mismatched ISBNs in the cell below.

These titles can be possibly identified with the fuzzy title matching section (Section #7 later in this code), or by checking their Alma holding and VolBooks title information against each other manually.

In [8]:
#Fix known mismatching ISBNs

for i in range(isbns.shape[0]):
    if isbns.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found Silas Marner')
        isbns.at[i, 'ISBN'] = '9780191037610'    
    if isbns.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found Sick Enough')       
        isbns.at[i, 'ISBN'] = '9781041036487'   
    if isbns.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found Evaluation and Measurement of Library Services')     
        isbns.at[i, 'ISBN'] = '9781440855368'     
    if isbns.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found Information Science')     
        isbns.at[i, 'ISBN'] = '9780367725204'      
    if isbns.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found International Financial Statement Analysis')    
        isbns.at[i, 'ISBN'] = '9781119682141'     
    if isbns.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found Counseling Children and Adolescents')  
        isbns.at[i, 'ISBN'] = '9781351133159'   
    if isbns.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found Demand and Supply Integration')  
        isbns.at[i, 'ISBN'] = '9781501506024'  
    if isbns.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found Performance Appraisal and Management')  
        isbns.at[i, 'ISBN'] = '9781506352886'  
    if isbns.at[i, 'ISBN'] == '9781317346005': #On the History of Political Philosophy
        print('Found On the History of Political Philosophy')
        isbns.at[i, 'ISBN'] = '9781317346012'
    if isbns.at[i, 'ISBN'] == '9781000690835': #Child-Centered Play Therapy
        print('Found Child-Centered Play Therapy')
        isbns.at[i, 'ISBN'] = '9781003260431' 
    if isbns.at[i, 'ISBN'] == '9781483315430': #Controversies in Contemporary Advertising
        print('Found Controversies in Contemporary Advertising')
        isbns.at[i, 'ISBN'] = '9781452233130' 
    if isbns.at[i, 'ISBN'] == '9781538139332': #Cooperation and Conflict Between State and Local Government
        print('Found Cooperation and Conflict Between State and Local Government')
        isbns.at[i, 'ISBN'] = '9798216405665' 
    if isbns.at[i, 'ISBN'] == '9781315218489': #Advanced Linear Algebra for Engineers with MATLAB
        print('Found Advanced Linear Algebra for Engineers with MATLAB') 
        isbns.at[i, 'ISBN'] = '9781420095241' 
    if isbns.at[i, 'ISBN'] == '9781351834377': #Advanced Linear Algebra for Engineers with MATLAB, second ISBN
        print('Found Advanced Linear Algebra for Engineers with MATLAB')
        isbns.at[i, 'ISBN'] = '9781420095241'  
    if isbns.at[i, 'ISBN'] == '9780393069754': #Beowulf
        print('Found Beowulf') 
        isbns.at[i, 'ISBN'] = '9781350212718'
    if isbns.at[i, 'ISBN'] == '9781483322100': #Conflict, War, and Peace: An Introduction to Scientific Research
        print('Found Conflict, War, and Peace')
        isbns.at[i, 'ISBN'] = '9781071934111'
    if isbns.at[i, 'ISBN'] == '9780742575622': #Criminologiccal Theory: An Analysis of its Underlying Assumptions
        print('Found Criminological Theory')
        isbns.at[i, 'ISBN'] = '9798216404972'
    if isbns.at[i, 'ISBN'] == '9780191007774': #Global Environments Through the Quarternary: Exploring Environmental Change
        print('Found Global Environments Through the Quarternary')
        isbns.at[i, 'ISBN'] = '9780191810169'
    if isbns.at[i, 'ISBN'] == '9780191606373': #History: A Very Short Introduction
        print('Found History')
        isbns.at[i, 'ISBN'] = '9780191540189'
    if isbns.at[i, 'ISBN'] == '9780124079489': #Introduction to Probability Models
        print('Found Introduction to Probability Models')
        isbns.at[i, 'ISBN'] = '9780125984560'
    if isbns.at[i, 'ISBN'] == '9781948057882': #John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
        print("Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition")
        print('Make sure this is the Unlimited version from ProQuest, not the 1 user from R2 Digital!')
        isbns.at[i, 'ISBN'] = '9781948057899'
    if isbns.at[i, 'ISBN'] == '9780838937952': #Metadata
        print('Found Metadata')
        isbns.at[i, 'ISBN'] = '9780838948637'
    if isbns.at[i, 'ISBN'] == '9780307757890': #Paradise Lost
        print('Found Paradise Lost')
        isbns.at[i, 'ISBN'] = '9781317865735'
    if isbns.at[i, 'ISBN'] == '9781466887787': #14-18: Understanding the Great War
        print('Found 14-18 Understanding the Great War')
        isbns.at[i, 'ISBN'] = '9780809046430'
    if isbns.at[i, 'ISBN'] == '9781400030156': #The Big Sleep
        print('Found The Big Sleep')
        isbns.at[i, 'ISBN'] = '9781479403776'
    if isbns.at[i, 'ISBN'] == '9780191629112': #The Book of Marvels and Travels
        print('Found The Book of Marvels and Travels')
        isbns.at[i, 'ISBN'] = '9780191629105'
    if isbns.at[i, 'ISBN'] == '9780140449617': #The Death of Ivan Ilyich and Other Stories
        print('Found The Death of Ivan Ilyich')
        isbns.at[i, 'ISBN'] = '9780191649042'
    if isbns.at[i, 'ISBN'] == '9781479823550': #Forced Out: Migrant Mothers in Search of Refuge and Hope
        print('Found Forced Out')
        isbns.at[i, 'ISBN'] = '9781479823529'
    if isbns.at[i, 'ISBN'] == '9780198745686': #Imperial Apocalypse: The Great War and the Destruction of the Russian Empire
        print('Found Imperial Apocalypse')
        isbns.at[i, 'ISBN'] = '9781644699522'
    if isbns.at[i, 'ISBN'] == '9780262367509': #Introduction to Algorithms, Fourth Edition
        print('Found Introduction to Algorithms')
        isbns.at[i, 'ISBN'] = '9780262046305'
    if isbns.at[i, 'ISBN'] == '9780813178288': #John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights]
        print('Found John Hervey Wheeler')
        isbns.at[i, 'ISBN'] = '9780813178271'
    if isbns.at[i, 'ISBN'] == '9781452289236': #Mental Health Case Management: A Practical Guide
        print('Found Mental Health Case Management')
        isbns.at[i, 'ISBN'] = '9781452256078'
    if isbns.at[i, 'ISBN'] == '9781101576984': #Merchants of Culture The Publishing Business in the Twenty-First Century
        print('Found Merchants of Culture')
        isbns.at[i, 'ISBN'] = '9780745661421'
    if isbns.at[i, 'ISBN'] == '9781319049966': #Narrative of the Life of Frederick Douglass: An American Slave, Written by Himself
        print('Found Frederick Douglass')
        isbns.at[i, 'ISBN'] = '9780760355466'
    if isbns.at[i, 'ISBN'] == '9780199720149': #The Oxford Handbook of Engineering and Technology in the Classical World
        print('Found Handbook of Engineering and Technology')
        isbns.at[i, 'ISBN'] = '9780195187311'
    if isbns.at[i, 'ISBN'] == '9781350113008': #Performance Drawing
        print('Found Performance Drawing')
        isbns.at[i, 'ISBN'] = '9781350113015'
    if isbns.at[i, 'ISBN'] == '9780191624711': #Persuasion
        print('Found Persuasion')
        isbns.at[i, 'ISBN'] = '9781316848630'
    if isbns.at[i, 'ISBN'] == '9781009314848': #The Gas Mask in Interwar Germany: Visions of Chemical Modernity
        print('Found Gas Mask')
        isbns.at[i, 'ISBN'] = '9781009314862'
    if isbns.at[i, 'ISBN'] == '9780385093309': #Good-Bye to All That
        print('Found Good-Bye to All That')
        isbns.at[i, 'ISBN'] = '9781774649367'
    if isbns.at[i, 'ISBN'] == '9781119837909': #Research Ethics for Scientists
        print('Found Research Ethics for Scientists')
        isbns.at[i, 'ISBN'] = '9781119978862'
    if isbns.at[i, 'ISBN'] == '9780307432568': #The Return of the Soldier
        print('Found The Return of the Soldier')
        isbns.at[i, 'ISBN'] = '9780486846545'
    if isbns.at[i, 'ISBN'] == '9781496203168': #Siberian Exile
        print('Found Siberian Exile')
        isbns.at[i, 'ISBN'] = '9780803299597'
    if isbns.at[i, 'ISBN'] == '9780190879976': #Teaching Music Theory
        print('Found Teaching Music Theory')
        isbns.at[i, 'ISBN'] = '9780197510575'
    if isbns.at[i, 'ISBN'] == '9780197644058': #An Uneasy Peace
        print('Found An Uneasy Peace')
        isbns.at[i, 'ISBN'] = '9780197619407'
    if isbns.at[i, 'ISBN'] == '9781975121549': #Fleisher & Ludwig's Textbook of Pediatric Emergency Medicine
        print('Found Fleisher & Ludwig Textbook')
        isbns.at[i, 'ISBN'] = '9781975121532'
    if isbns.at[i, 'ISBN'] == '9781482542222': #Treating Complex Traumatic Stress Disorders in Adults: Scientific Foundations and Therapeutic Models
        print('Found Treating Complex Traumatic Stress Disorders in Adults')
        isbns.at[i, 'ISBN'] = '9781462542239'
    if isbns.at[i, 'ISBN'] == '9781316044582': #Elements of Mathematical Ecology
        print('Found Elements of Mathematical Ecology')
        isbns.at[i, 'ISBN'] = '9780511608520'
    if isbns.at[i, 'ISBN'] == '9780307758071': #Herland
        print('Found Herland')
        isbns.at[i, 'ISBN'] = '9781667601038'
    if isbns.at[i, 'ISBN'] == '9780393270372': #Narrative of the Life of Frederick Douglass
        print('Found Frederick Douglass')
        isbns.at[i, 'ISBN'] = '9780760355466'
    if isbns.at[i, 'ISBN'] == '9780199748037': #Population Health: Concepts and Methods
        print('Found Population Health')
        isbns.at[i, 'ISBN'] = '9780199864379'
    if isbns.at[i, 'ISBN'] == '9780300048124': #Preschool in Three Cultures: Japan, China and the United States
        print('Found Preschool in Three Cultures')
        isbns.at[i, 'ISBN'] = '9780585358543'
    if isbns.at[i, 'ISBN'] == '9781101078143': #The Souls of BLack Folk
        print('Found The Souls of Black Folk')
        isbns.at[i, 'ISBN'] = '9781315631998'
    if isbns.at[i, 'ISBN'] == '0679601813': #The Brothers Karamazov
        print('Found The Brothers Karamazov')
        isbns.at[i, 'ISBN'] = '9781786565556'
    if isbns.at[i, 'ISBN'] == '9781612495736': #Manufacturing Facilities Design and Material Handling: Sixth Edition
        print('Found Manufacturing Facilities Design')
        isbns.at[i, 'ISBN'] = '9781612495729'
    if isbns.at[i, 'ISBN'] == '9780191605475': #Bleak House
        print('Found Bleak House')
        isbns.at[i, 'ISBN'] = '9780486822556'
    if isbns.at[i, 'ISBN'] == '9781119348450': #Modern Nuclear Chemistry
        print('Found Modern Nuclear Chemistry')
        isbns.at[i, 'ISBN'] = '9780471768623'
    if isbns.at[i, 'ISBN'] == '9781903544877': #Planetary Geology: An Introduction
        print('Found Planetary Geology')
        isbns.at[i, 'ISBN'] = '9781780461045'
    if isbns.at[i, 'ISBN'] == '9783031758539': #R for Political Science Research: An Introduction for Absolute Beginners
        print('Found R for Political Science Research')
        isbns.at[i, 'ISBN'] = '9783031758522'
    if isbns.at[i, 'ISBN'] == '9780674040793': #Clinging to Mammy: The Faithful Slave in Twentieth-Century America
        print('Found Clinging to Mammy')
        isbns.at[i, 'ISBN'] = '9780674024335'
    if isbns.at[i, 'ISBN'] == '9781460404027': #The Return of the Soldier
        print('Found Return of the Soldier')
        isbns.at[i, 'ISBN'] = '9780486846545'

Found Controversies in Contemporary Advertising
Found Frederick Douglass
Found The Souls of Black Folk
Found Clinging to Mammy
Found Research Ethics for Scientists
Found Advanced Linear Algebra for Engineers with MATLAB
Found Introduction to Algorithms
Found Planetary Geology
Found Persuasion
Found Return of the Soldier
Found Herland
Found Bleak House
Found Manufacturing Facilities Design
Found Preschool in Three Cultures
Found Information Science
Found Metadata
Found Evaluation and Measurement of Library Services
Found Elements of Mathematical Ecology
Found Modern Nuclear Chemistry
Found Fleisher & Ludwig Textbook
Found On the History of Political Philosophy
Found R for Political Science Research
Found Population Health
Found The Brothers Karamazov
Found Criminological Theory
Found Mental Health Case Management

## 5. Save the isbns to an Excel file

In [9]:
#create new itemized set in Alma using this isbn file:
isbns.to_excel(date_str+'_isbns.xlsx', index = False)

# after the set is created, export the results (All Fields) and save the file using format "YYYY-MM-DD_set_output.xlsx"

## Use the isbn file to create an itemized set in alma
## After the set is created, export the results (All Fields) and save using the file name format "YYYY-MM-DD_set_output.xlsx" to the same location that all your other files for this process live in

## 6. The following cell will use the set_output you just made to call on the alma analytics API, looking for any matching ISBNs

In [10]:
#use the alma API and the set results to get all ISBNs for any MMS IDs found in set
#analytics report: Collections folder > "Textbook ISBNs for Overlap Report_TM"

#create list of mms_ids from set output
mms_ids = pd.read_excel(date_str+"_set_output.xlsx")
#mms_ids = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
mms_ids = mms_ids[['MMS ID']]

# Get the list of MMS IDs from the DataFrame
mms_list = mms_ids['MMS ID'].tolist()

# Define the batch size for API call(s)
batch_size = 50

# Create a list to store the batches
batches = []

# Iterate through the MMS ID list and create batches
for i in range(0, len(mms_list), batch_size):
    batch = mms_list[i : i + batch_size]
    batches.append(batch)

#create an empty list into which we will put api call results
df_list = []

#for each batch of mms ids, call analytics api
for batch in batches:
    values_xml = '\n'.join(f'<sawx:expr xsi:type="xsd:string">{value}</sawx:expr>' for value in batch)
    formatted_xml_snippet = xml_snippet.format(values_xml)

    url_encoded_filter_query = urllib.parse.quote(formatted_xml_snippet)

    full_path = base_path + url_encoded_path + r'&filter=' + url_encoded_filter_query

    report_data_df = get_and_concat_report(full_path, pd.DataFrame())
    df_list.append(report_data_df)
    
# concatenate together all the api call results into one big dataframe
combined_df = pd.concat(df_list, ignore_index=True)
combined_df

33
20
49
39
37
41
40
23

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Id,Portfolio Public Note,No. of Available Portfolio,Portfolio Authentication Note
0,https://search.ebscohost.com/login.aspx?direct...,144434594X; 9781444345940; 1444345915; 9781444...,144434594X; 9781444345940; 1444345915; 9781444...,9922520450102311,A companion to paleopathology /,ProQuest Ebook Central DDA Discovery,Available,53366614400002311,Click to View,0,NaN
1,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN
2,https://search.ebscohost.com/login.aspx?direct...,144434594X; 9781444345940; 1444345915; 9781444...,144434594X; 9781444345940; 1444345915; 9781444...,9922520450102311,A companion to paleopathology /,Ebooks moved from ProQuest to EBSCO,Available,53449629450002311,NaN,1,NaN
3,http://search.ebscohost.com/login.aspx?direct=...,080703312X; 9780807033128; 0807033111; 9780807...,080703312X; 9780807033128; 0807033111; 9780807...,9925891178202311,A history of religion in 5 1/2 objects : bring...,EBSCO Ebooks Individually Purchased,Available,53326427370002311,NaN,1,Online Access - 1 user
4,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,Taylor & Francis Ebooks Individually Purchased,Available,53259519420002311,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
277,https://www.jstor.org/stable/10.2307/j.ctvc77b...,9780691022956; 069102295X; 9781400888368; 1400...,9780691022956; 069102295X; 9781400888368; 1400...,9927021969102311,The rhetorical presidency /,JSTOR Rialto Implementation,Available,53466976110002311,Unlimited Access,1,NaN
278,NaN,1098155408; 9781098155407; 9781098155414; 1098...,1098155408; 9781098155407; 9781098155414; 1098...,9927022061902311,Think Python : how to think like a computer sc...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453654960002311,NaN,1,NaN
279,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,Online Access - 1 user
280,NaN,1119886112; 9781119886112; 1119886120; 9781119...,1119886112; 9781119886112; 1119886120; 9781119...,9926909582702311,True north : leading authentically in today's ...,O'Reilly Online Learning: Academic/Public Libr...,Available,53452603080002311,NaN,1,NaN
281,NaN,0429000332; 9780429000331; 0429000324; 9780429...,0429000332; 9780429000331; 0429000324; 9780429...,9926910284202311,Video field production and editing /,O'Reilly Online Learning: Academic/Public Libr...,Available,53452820550002311,NaN,1,NaN

In [11]:
#combined_df.to_excel('Alma Textbook List Check Summer 2026.xlsx')

In [12]:
combined_df.sort_values(by = 'Title')['Title'].unique()

array(['58-in-mind : multilingual teaching strategies for diverse deaf students /',
       'A History of Modern Linguistics : From the Beginnings to World War II',
       'A case study in visual agnosia revisited : to see but not to see /',
       'A companion to paleopathology /',
       'A history of religion in 5 1/2 objects : bringing the spiritual to its senses /',
       'A history of the American musical theatre : no business like it /',
       'ACT Made Simple : An Easy-To-Read Primer on Acceptance and Commitment Therapy.',
       'Achilles in Vietnam : combat trauma and the undoing of character /',
       'Advanced linear algebra for engineers with MATLAB',
       'Affirming disability : strengths-based portraits of culturally diverse families /',
       'After Appomattox : military occupation and the ends of war /',
       'Algebra', 'An Introduction to Mathematical Epidemiology',
       'An introduction to applied behavioral neuroscience : biological psychology in everyday life /',
       'An introduction to system modeling and control /',
       'Ancient Greek religion /',
       'Apophatic elements in the theory and practice of psychoanalysis : pseudo-dionysius and C.G. Jung /',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Art education for a sustainable planet : embracing ecopedagogy in K-12 classrooms /',
       'Artificial intelligence for cybersecurity : develop AI approaches to solve cybersecurity problems in your organization /',
       'Banking on freedom : black women in U.S. finance before the New Deal /',
       "Because of sex one law, ten cases, and fifty years that changed American women's lives at work /",
       'Becoming a data head : how to think, speak, and understand data science, statistics, and machine learning /',
       'Beloved /',
       'Bestiary being an English version of the Bodleian Library, Oxford M.S. Bodley 764 : with all the original miniatures reproduced in facsimile /',
       'Biomaterials Science : An Introduction to Materials in Medicine.',
       'Biomaterials science : an introduction to materials in medicine /',
       'Black Beauty/', 'Bleak house /',
       'Business ethics : a contemporary introduction /',
       'Buy Black : How Black Women Transformed US Pop Culture.',
       'COURSE IN MATHEMATICAL MODELING', 'Call of the Wild, The/',
       'Carceral con : the deceptive terrain of criminal justice reform /',
       'Case studies in deaf education : inquiry, application, and resources /',
       'Ceremony /',
       'Chief sustainability officers at work : how CSOs build successful sustainability and ESG strategies /',
       'Chief sustainability officers at work how CSOs build successful sustainability and ESG strategies /',
       'Climate change and managed ecosystems /',
       'Clinging to mammy the faithful slave in twentieth-century America /',
       'Cognitive behavior therapy : basics and beyond /',
       'Comparative education : the dialectic of the global and the local /',
       'Controversies in contemporary advertising',
       'Conversations with families of children with disabilities : insights for teacher understanding /',
       'Crack rock cocaine, street capitalism, and the decade of greed /',
       'Cracked, not broken surviving and thriving after a suicide attempt /',
       'Creating outstanding classrooms : a whole-school approach /',
       'Criminological Theory: An Analysis of Its Underlying Assumptions',
       'Customer experience 3.0 : high-profit strategies in the age of techno service /',
       'Dancing with the devil : why bad feelings make life good /',
       'Deaf culture : exploring deaf communities in the United States /',
       'Deaf people and society : psychological, sociological and educational perspectives /',
       'Debating reform conflicting perspectives on how to fix the American political system /',
       'Democracy for realists : why elections do not produce responsive government /',
       'Design : history, theory and practice of product design /',
       'Design Education : Creating Thinkers to Improve the World.',
       'Differential Equations, Dynamical Systems, and an Introduction to Chaos.',
       'Differential equations, dynamical systems, and an introduction to chaos (Third Edition) /',
       'Disaster prevention /',
       "Disciplinary and content literacy for today's adolescents : honoring diversity and building competence /",
       'Early music : a very short introduction /',
       'Econometric analysis of cross section and panel data /',
       'Educational and psychological measurement /',
       'Elements of mathematical ecology',
       'Engaged anthropology : politics beyond the text /',
       'Engineering design : a project-based introduction /',
       'Enviromedics : the impact of climate change on human health /',
       'Ethics of data and analytics : concepts and cases /',
       'Evicted poverty and profit in the American city',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement /',
       'Exactly How to Sell : The Sales Guide for Non-Sales Professionals.',
       'Exactly how to sell : the sales guide for non-sales professionals /',
       "Experiencing design : the innovator's journey /",
       'Facilitating Breakthrough : How to Remove Obstacles, Bridge Differences, and Move Forward Together',
       'Fields and streams stream restoration, neoliberalism, and the future of environmental science /',
       'Fighting Against the Injustice of the State and Globalization Comparing the African American and Oromo Movements /',
       'Financial and business management for the doctor of nursing practice /',
       'Finding the mother tree : discovering the wisdom of the forest /',
       "Fishing through the apocalypse : an angler's adventures in the 21st century /",
       "Fleisher & Ludwig's textbook of pediatric emergency medicine /",
       'Focus on Developmentally Appropriate Practice : Equitable and Joyful Learning in Kindergarten.',
       'Forensic Anthropology : An Introductory Lab Manual.',
       'Forms : whole, rhythm, hierarchy, network /',
       'Fun home A family tragicomic.', 'Fundamentals of gas dynamics /',
       'Fundamentals of physics.',
       'GENKI : an integrated course in elementary Japanese.',
       "Geminos's Introduction to the phenomena : a translation and study of a Hellenistic survey of astronomy /",
       'Getting real about inequality : intersectionality in real life (IRL) /',
       "Giovanni's room /",
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide /',
       'Globalization of education : an introduction /',
       "Good to great Why some companies make the leap...and others don't.",
       'Government and Politics in Tennessee',
       'Guide to the vascular plants of Tennessee /',
       'Hands-on large language models language understanding and generation /',
       'Head off & split poems /', 'Herland /',
       'Hey Whipple, Squeeze This : The Classic Guide to Creating Great Advertising.',
       'Hey Whipple, squeeze this : the classic guide to creating great advertising /',
       'High fidelity', 'How great leaders think : the art of reframing',
       'How to Do Critical Discourse Analysis : A Multimodal Introduction.',
       'Human osteology /',
       'Information Architecture for the World Wide Web : Designing Large-Scale Web Sites.',
       'Information architecture for the World Wide Web : designing large-scale web sites /',
       'Information science : the basics /',
       'Integrating Program Management and Systems Engineering : Methods, Tools and Organizational Systems for Improving Performance.',
       'Integrating program management and systems engineering : methods, tools, and organizational systems for improving performance /',
       'International trade and agriculture',
       'Interpersonal communication : putting theory into practice /',
       'Introduction to Algorithms /', 'Introduction to deaf culture /',
       'Introduction to industrial organization. /',
       'Invisible child : poverty, survival & hope in an American city /',
       'John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights /',
       'Johns Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals: Model & Guidelines',
       'Just practice : a social justice approach to social work /',
       "Karl Marx's theory of history : a defence /",
       "King of the North : Martin Luther King's life of struggle outside the South /",
       'Language vs. reality : why language is good for lawyers and bad for scientists /',
       "Leaders eat last : why some teams pull together and others don't /",
       'Lean Production for Competitive Advantage : A Comprehensive Guide to Lean Methodologies and Management Practices, Second Edition.',
       'Listening to war : sound, music, trauma and survival in wartime Iraq /',
       'Manufacturing Facilities Design & Material Handling : Sixth Edition.',
       'Materials and Sustainable Development /',
       'Measurement and detection of radiation /',
       'Mental health case management : a practical guide /',
       'Mere Christianity : a revised and amplified edition, with a new introduction, of the three books, Broadcast talks, Christian behaviour, and Beyond personality /',
       'Metadata /', 'Metadata.',
       'Metaracism : how systemic racism devastates Black lives--and how we break free /',
       'Milk and filth', 'Mindset : the new psychology of success /',
       'Modern nuclear chemistry',
       "Morgan & Mikhail's Clinical Anesthesiology",
       'Movements in organizational communication research : current issues and future directions /',
       'Multilevel modeling : applications in STATA®, IBM® SPSS®, SAS®, R, & HLM™ /',
       'Multimedia environmental models : the fugacity approach /',
       'Narrative of the life of Frederick Douglass, an American slave /',
       'Native nations : a millennium in North America /', 'New kid',
       'Next steps : decision cases for social work practice /',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke /',
       "Ortner's identification of pathological conditions in human skeletal remains /",
       'Passing.', 'Persuasion',
       'Phenomenology : a contemporary introduction /',
       'Pitch, tweet, or engage on the street : how to practice global public relations and strategic communication.',
       'Planetary geology an introduction.',
       'Planning for play, observation, and learning in preschool and kindergarten /',
       'Population health concepts and methods /',
       'Practical Implementation in Social Work Practice : A Guide to Engaging in Evidence-Based Practice.',
       'Preschool in three cultures : Japan, China, and the United States /',
       'Principles and methods of social research /',
       'Probability: A Graduate Course',
       'Property of the Rebel Librarian',
       'Public libraries and their communities : an introduction /',
       'Public speaking for engineers : communicating effectively with clients, the public, and local government /',
       'Pursuing happiness a Bedford spotlight reader /',
       'R for political science research : an introduction for absolute beginners /',
       'Racial theories in social science : a systemic racism critique /',
       'Radiation biophysics /',
       'Red Book : 2024-2027 Report of the Committee on Infectious Diseases.',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases /',
       'Research ethics for scientists a companion for students.',
       'Sales force management : leadership, innovation, technology /',
       'Sanford Meisner on acting /',
       'School social work : a skills-based competency approach /',
       'Sexuality in Medieval Europe : doing unto others /',
       'Shaping a science of social work : professional knowledge and identity /',
       'Shokyū Nihongo genki.',
       'Skill acquisition in sport : research, theory and practice /',
       'Social welfare policy for a sustainable future : the U.S. in global context /',
       'Social work values and ethics /',
       'Song walking : women, music, and environmental justice in an African borderland /',
       'Statistical mechanics /',
       "Stoelting's pharmacology & physiology in anesthetic practice",
       'Strategic Healthcare Management : Planning and Execution.',
       'Strategic Planning for Public Relations.',
       'Strategy in 3D : essential tools to diagnose, decide, & deliver /',
       'SuperCollider for the creative musician : a practical guide /',
       'Supply chain transformation : building and executing an integrated supply chain strategy /',
       'System engineering management /',
       'Teaching Adult Learners : A Guide for Public Librarians.',
       'Teaching and assessing social justice art education : power, politics, and possibilities /',
       'Teeth : the story of beauty, inequality, and the struggle for oral health in America /',
       'Tell It Slant, Third Edition, 3rd Edition /',
       'Tell it slant : creating, refining, and publishing creative nonfiction /',
       'The BRICs and emerging economies in comparative perspective : political economy, liberalisation and institutional change /',
       "The Black fives : the epic story of basketball's forgotten era /",
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The Craft of Research.', 'The Future of an Illusion.',
       'The Grapes of wrath /',
       'The Great Debate : Edmund Burke, Thomas Paine, and the Birth of Right and Left.',
       'The Island of Doctor Moreau/',
       'The Licit Life of Capitalism : US Oil in Equatorial Guinea.',
       'The New Jim Crow : Mass Incarceration in the Age of Colorblindness.',
       'The Oxford Solid State Basics.',
       'The Sun Also Rises : The Hemingway Library Edition.',
       'The art of the pitch persuasion and presentation skills that win business /',
       'The beast within : animals in the Middle Ages /',
       'The bluest eye : a novel /', 'The brothers Karamazov /',
       'The comprehensive guide to interdisciplinary veterinary social work /',
       'The constitution of liberty : the definitive edition /',
       'The crucible : a play in four acts /',
       'The evaluation and measurement of library services',
       'The five dysfunctions of a team : a leadership fable /',
       "The forest unseen : a year's watch in nature /",
       'The haunting of Hill House /',
       "The historian's toolbox : a student's guide to the theory and craft of history /",
       'The language instinct : how the mind creates language /',
       'The licit life of capitalism : U.S. Oil in Equatorial Guinea /',
       'The museum of unnatural histories /',
       'The portable feminist reader /',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world /',
       'The return of the soldier  /', 'The rhetorical presidency /',
       'The souls of Black folk /',
       'The theory and practice of group psychotherapy /',
       'The woman warrior : memoirs of a girlhood among ghosts /',
       'Think Python : how to think like a computer scientist /',
       'Thinking in systems : a primer /',
       'Transport Modeling for Environmental Engineers and Scientists.',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster /',
       "True north : leading authentically in today's workplace /",
       'University Physics, Volume 3',
       'Until we reckon : violence, mass incarceration, and a road to repair /',
       'Using statistical methods in social science research : with a complete SPSS guide /',
       'Versification a short introduction /',
       'Video field production and editing /', 'Water Chemistry',
       'What really works with exceptional learners. /',
       'Where rivers and mountains sing : sound, music, and nomadism in tuva and beyond /',
       'Why We Lost the ERA /', 'Why people die by suicide /',
       'Wolf and Stanley on environmental law.',
       'Writing Literature Reviews : A Guide for Students of the Social and Behavioral Sciences.',
       'Writing science : how to write papers that get cited and proposals that get funded /'],
      dtype=object)

## 7. Check for mismatched ISBNs using Fuzzy Matching

Since titles often have several different ISBNs, and we only receive one ISBN from VolBooks, we need to make sure as many of those ISBNs match up as possible. The cell below checks for any of these potential mismatches.
|
### If a title's ISBN does not align between VolBooks and Alma, go to the ISBN fixing cell in Section #4 and edit the VolBooks holdings to match the Alma holdings.

**NOTE:** This code finds the closest matching title within the VolBooks and Alma lists, and thus it may not always be a direct match. Double-check the code before changing any ISBNs.

In [43]:
## Load the Alma Data

volBooksTitleList = df['Short Title'].unique()
almaUnlimited = pd.read_excel('Textbook ISBN Checking File July 14.xlsx')

In [44]:
## Alma ISBN Splitting Code
combinedCopy = almaUnlimited

combinedCopy['ISBN (Normalized) List'] = combinedCopy['ISBN (Normalized)'].apply(lambda x: str(x).split(";"))

expandedCopy = combinedCopy.explode('ISBN (Normalized) List')

expandedCopy['ISBN (Normalized) List'] = expandedCopy['ISBN (Normalized) List'].str.strip()

In [45]:
## Clean and Tokenize the Titles

def TextPreProcess(title):
    title = str(title)
    title = title.lower()
    title = title.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(title)

    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    return tokens

## Load Title Lists
df['Tokenized Title'] = df['Short Title'].apply(TextPreProcess)
expandedCopy['Tokenized Title'] = expandedCopy['Title'].apply(TextPreProcess)

In [46]:
## Create Stems and Rejoin Titles

stemmer = SnowballStemmer(language = 'english')

def StemTokens(tokens):
    stems = [stemmer.stem(token) for token in tokens]
    return ' '.join(stems)

df['Stemmed Title'] = df['Tokenized Title'].apply(StemTokens)
expandedCopy['Stemmed Title'] = expandedCopy['Tokenized Title'].apply(StemTokens)

In [47]:
## Initialize Information

volBooksTitleList = df['Stemmed Title'].unique()
almaTitleList = expandedCopy['Stemmed Title'].unique()

almaTitle = pd.Series([])
volBooksTitle = pd.Series([])
almaISBN = pd.Series([])
volBooksISBN = pd.Series([])
almaStem = pd.Series([])
volBooksStem = pd.Series([])

In [48]:
expandedCopy.columns

Index(['No. of Available Portfolio', 'Electronic location and access', 'Title',
       'MMS Id', 'Portfolio Id', 'Electronic Collection Public Name',
       'Portfolio Public Note', 'Portfolio Authentication Note',
       'Service Authentication Note', 'ISBN', 'ISBN (Normalized)',
       'Availability', 'Portfolio Activation Date', 'ISBN (Normalized) List',
       'Tokenized Title', 'Stemmed Title'],
      dtype='object')

In [87]:
## Find the Potential Titles with Mismatched ISBNs

## Note: this code chunk can take many minutes to run to completion

for i in range(len(volBooksTitleList)):
    titleName = volBooksTitleList[i]
    bestResult = process.extractOne(titleName, almaTitleList, scorer = fuzz.token_sort_ratio)
    
    selectVolBooksRows = df[df['Stemmed Title'] == titleName]
    volBooksStem = pd.concat([volBooksStem, pd.Series([selectVolBooksRows['Stemmed Title'].iloc[0]])], ignore_index = True)
    volBooksISBN = pd.concat([volBooksISBN, pd.Series([selectVolBooksRows['ISBN'].iloc[0]])], ignore_index = True)
    volBooksTitle = pd.concat([volBooksTitle, pd.Series([selectVolBooksRows['Short Title'].iloc[0]])], ignore_index = True)
    
    selectAlmaRows = expandedCopy[expandedCopy['Stemmed Title'] == bestResult[0]]
    almaStem = pd.concat([almaStem, pd.Series([selectAlmaRows['Stemmed Title'].iloc[0]])], ignore_index = True)
    almaISBN = pd.concat([almaISBN, pd.Series([selectAlmaRows['ISBN (Normalized) List'].iloc[0]])], ignore_index = True)
    almaTitle = pd.concat([almaTitle, pd.Series([selectAlmaRows['Title'].iloc[0]])], ignore_index = True)
    
    for j in range(expandedCopy.shape[0]):
        if expandedCopy['Title'].iloc[j] == bestResult:
            almaISBN = pd.concat(volBooksISBN, pd.Series([expandedCopy.at[j, 'ISBN (Normalized) List']]), ignore_index = True)
            almaTitle = pd.concat(volBooksTitle, pd.Series([bestResult]), ignore_index = True)
    for k in range(df.shape[0]):
        if expandedCopy['Title'].iloc[k] == titleName:
            volBooksISBN = pd.concat(almaISBN, pd.Series([df.at[k, 'ISBN']]), ignore_index = True)
            volBooksTitle = pd.concat(almaTitle, pd.Series([titleName]), ignore_index = True)

titleComparisonTable = pd.concat([volBooksStem, almaStem, volBooksISBN, almaISBN, volBooksTitle, almaTitle], axis = 1)
    
titleComparisonTable.columns = ['VolBooks Stemmed Title', 'Alma Stemmed Title', 'VolBooks ISBN', 'Alma ISBN', 'VolBooks Raw Title', 'Alma Raw Title']

titleComparisonTable

,VolBooks Stemmed Title,Alma Stemmed Title,VolBooks ISBN,Alma ISBN,VolBooks Raw Title,Alma Raw Title
0,connect onlin access survey account sharpen co...,macroeconom age pension save survey,9781264453948,nan,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING...,"The Macroeconomics of Ageing, Pensions and Sav..."
1,connect survey account sharpen companion,act context canon paper steven c hay,9781266677090,1317594274,CONNECT FOR SURVEY OF ACCOUNTING AND SHARPEN ...,The act in context : the canonical papers of S...
2,cnowv2 richjonesmy financi account 1 term inst...,financi system industri countri evid financi a...,9780357984963,9783642231117,CNOWV2 FOR RICH/JONES/MYERS' FINANCIAL ACCOUNT...,The Financial Systems of Industrial Countries ...
3,cnowv2 richjonesmy financi account,financi account,9780357984963,nan,CNOWV2 FOR RICH/JONES/MYERS' FINANCIAL ACCOUNTING,Financial Accounts
4,intermedi account,nerv conduct intermedi,9781394254439,nan,INTERMEDIATE ACCOUNTING,Nerve Conduction Intermediate /
...,...,...,...,...,...,...
1520,write literatur review guid student social beh...,success academ write complet guid social behav...,9781351858922,1462529429,WRITING LITERATURE REVIEWS : A GUIDE FOR STUDE...,Successful academic writing : a complete guide...
1521,rise fall dinosaur,dinosaur horizon guid,9780062490452,nan,THE RISE AND FALL OF THE DINOSAURS,Dinosaurs A Horizon Guide /
1522,portabl feminist reader,race public administr,9781101992678,1003017630,THE PORTABLE FEMINIST READER,Race and public administration /
1523,ill gone dark one woman obsess search golden s...,merz tate global odyssey black woman scholar,9780062916310,0300274815,I'LL BE GONE IN THE DARK : ONE WOMAN'S OBSESSI...,Merze Tate : the global Odyssey of a black wom...
1524,communic languag teach action,psycholog languag communic,830901A,1315187191,COMMUNICATIVE LANGUAGE TEACHING IN ACTION,The psychology of language and communication /

In [88]:
titleComparisonTable.to_excel(date_str+'ISBN Matching Table.xlsx', index = False)

## 8. Continue cleaning up the VolBooks report

Return here once all ISBNs have been fixed above.

In [13]:
combined_df['Portfolio Authentication Note']

0                         NaN
1                         NaN
2                         NaN
3      Online Access - 1 user
4                         NaN
                ...
277                       NaN
278                       NaN
279    Online Access - 1 user
280                       NaN
281                       NaN
Name: Portfolio Authentication Note, Length: 282, dtype: object

In [14]:
combined_df['Electronic location split'] = combined_df['Electronic location and access'].apply(lambda x: x.split() if isinstance(x, str) else x)

combined_df['Electronic location'] = combined_df['Electronic location split'].apply(lambda x: ''.join(map(str, x[:1])) if isinstance(x, list) else x)

# Extract items excluding the first item from each list
combined_df['Electronic access'] = combined_df['Electronic location split'].apply(lambda x: ' '.join(x[1:]) if isinstance(x, list) else x)

In [15]:
combined_df['Electronic access']

0
1       Online Access - Unlimited users.
2
3                 Online Access - 1 user
4       Online Access - Unlimited users.
                     ...
277    Unlimited Access Unlimited Access
278                                  NaN
279              Single User Single User
280                                  NaN
281                                  NaN
Name: Electronic access, Length: 282, dtype: object

## 9. save the alma analytics api output as an excel file

In [16]:
#save the big, concatenated dataframe to disk
combined_df.to_excel(date_str+'_analytics_output.xlsx', index = False)

## do some work on the dataframe

In [17]:
# Create a new column 'Concatenated Notes' with deduplication
combined_df['Concatenated Notes'] = combined_df.apply(concatenate_and_deduplicate_notes, axis=1)

#filter to only show rows where the No. of Available Portfolios is not zero
combined_df = combined_df.loc[combined_df['No. of Available Portfolio'] != 0]


# Display the updated DataFrame
combined_df

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Id,Portfolio Public Note,No. of Available Portfolio,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,https://search.ebscohost.com/login.aspx?direct...,144434594X; 9781444345940; 1444345915; 9781444...,144434594X; 9781444345940; 1444345915; 9781444...,9922520450102311,A companion to paleopathology /,ProQuest Ebook Central DDA Discovery,Available,53366614400002311,Click to View,0,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
1,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...
2,https://search.ebscohost.com/login.aspx?direct...,144434594X; 9781444345940; 1444345915; 9781444...,144434594X; 9781444345940; 1444345915; 9781444...,9922520450102311,A companion to paleopathology /,Ebooks moved from ProQuest to EBSCO,Available,53449629450002311,NaN,1,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
3,http://search.ebscohost.com/login.aspx?direct=...,080703312X; 9780807033128; 0807033111; 9780807...,080703312X; 9780807033128; 0807033111; 9780807...,9925891178202311,A history of religion in 5 1/2 objects : bring...,EBSCO Ebooks Individually Purchased,Available,53326427370002311,NaN,1,Online Access - 1 user,[http://search.ebscohost.com/login.aspx?direct...,http://search.ebscohost.com/login.aspx?direct=...,Online Access - 1 user,http://search.ebscohost.com/login.aspx?direct=...
4,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,Taylor & Francis Ebooks Individually Purchased,Available,53259519420002311,NaN,1,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,https://www.jstor.org/stable/10.2307/j.ctvc77b...,9780691022956; 069102295X; 9781400888368; 1400...,9780691022956; 069102295X; 9781400888368; 1400...,9927021969102311,The rhetorical presidency /,JSTOR Rialto Implementation,Available,53466976110002311,Unlimited Access,1,NaN,[https://www.jstor.org/stable/10.2307/j.ctvc77...,https://www.jstor.org/stable/10.2307/j.ctvc77bq6,Unlimited Access Unlimited Access,https://www.jstor.org/stable/10.2307/j.ctvc77b...
278,NaN,1098155408; 9781098155407; 9781098155414; 1098...,1098155408; 9781098155407; 9781098155414; 1098...,9927022061902311,Think Python : how to think like a computer sc...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453654960002311,NaN,1,NaN,NaN,NaN,NaN,
279,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
280,NaN,1119886112; 9781119886112; 1119886120; 9781119...,1119886112; 9781119886112; 1119886120; 9781119...,9926909582702311,True north : leading authentically in today's ...,O'Reilly Online Learning: Academic/Public Libr...,Available,53452603080002311,NaN,1,NaN,NaN,NaN,NaN,
281,NaN,0429000332; 9780429000331; 0429000324; 9780429...,0429000332; 9780429000331; 0429000324; 9780429...,9926910284202311,Video field production and editing /,O'Reilly Online Learning: Academic/Public Libr...,Available,53452820550002311,NaN,1,NaN,NaN,NaN,NaN,

## 10. save the analytics_output file as csv

In [18]:
#save the dataframe to disk once again, only this time as a csv
combined_df.to_csv(date_str+'_analytics_output.csv', index = False)

## 11. Combine Data Files for Exporting

In [19]:
results = pd.read_excel(date_str+'_set_output.xlsx') #From Alma Directly
#results = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
bookstoreList = pd.read_excel('searchresults_'+date_str+'.xlsx') #From VolBooks Directly
textbookISBNs = combined_df #Alma Cleaned-Up Version

## Make sure that any ISBNs that were fixed before loading into Alma are also fixed here!

In [20]:
#Fix known mismatching ISBNs in bookstoreList

for i in range(bookstoreList.shape[0]):
    if bookstoreList.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found Silas Marner')
        bookstoreList.at[i, 'ISBN'] = '9780191037610'    
    if bookstoreList.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found Sick Enough')       
        bookstoreList.at[i, 'ISBN'] = '9781041036487'   
    if bookstoreList.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found Evaluation and Measurement of Library Services')     
        bookstoreList.at[i, 'ISBN'] = '9781440855368'     
    if bookstoreList.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found Information Science')     
        bookstoreList.at[i, 'ISBN'] = '9780367725204'      
    if bookstoreList.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found International Financial Statement Analysis')    
        bookstoreList.at[i, 'ISBN'] = '9781119682141'     
    if bookstoreList.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found Counseling Children and Adolescents')  
        bookstoreList.at[i, 'ISBN'] = '9781351133159'   
    if bookstoreList.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found Demand and Supply Integration')  
        bookstoreList.at[i, 'ISBN'] = '9781501506024'  
    if bookstoreList.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found Performance Appraisal and Management')  
        bookstoreList.at[i, 'ISBN'] = '9781506352886'  
    if bookstoreList.at[i, 'ISBN'] == '9781317346005': #On the History of Political Philosophy
        print('Found On the History of Political Philosophy')
        bookstoreList.at[i, 'ISBN'] = '9781317346012'
    if bookstoreList.at[i, 'ISBN'] == '9781000690835': #Child-Centered Play Therapy
        print('Found Child-Centered Play Therapy')
        bookstoreList.at[i, 'ISBN'] = '9781003260431' 
    if bookstoreList.at[i, 'ISBN'] == '9781483315430': #Controversies in Contemporary Advertising
        print('Found Controversies in Contemporary Advertising')
        bookstoreList.at[i, 'ISBN'] = '9781452233130' 
    if bookstoreList.at[i, 'ISBN'] == '9781538139332': #Cooperation and Conflict Between State and Local Government
        print('Found Cooperation and Conflict Between State and Local Government')
        bookstoreList.at[i, 'ISBN'] = '9798216405665' 
    if bookstoreList.at[i, 'ISBN'] == '9781315218489': #Advanced Linear Algebra for Engineers with MATLAB
        print('Found Advanced Linear Algebra for Engineers with MATLAB') 
        bookstoreList.at[i, 'ISBN'] = '9781420095241' 
    if bookstoreList.at[i, 'ISBN'] == '9781351834377': #Advanced Linear Algebra for Engineers with MATLAB, second ISBN
        print('Found Advanced Linear Algebra for Engineers with MATLAB')
        bookstoreList.at[i, 'ISBN'] = '9781420095241'  
    if bookstoreList.at[i, 'ISBN'] == '9780393069754': #Beowulf
        print('Found Beowulf') 
        bookstoreList.at[i, 'ISBN'] = '9781350212718'
    if bookstoreList.at[i, 'ISBN'] == '9781483322100': #Conflict, War, and Peace: An Introduction to Scientific Research
        print('Found Conflict, War, and Peace')
        bookstoreList.at[i, 'ISBN'] = '9781071934111'
    if bookstoreList.at[i, 'ISBN'] == '9780742575622': #Criminologiccal Theory: An Analysis of its Underlying Assumptions
        print('Found Criminological Theory')
        bookstoreList.at[i, 'ISBN'] = '9798216404972'
    if bookstoreList.at[i, 'ISBN'] == '9780191007774': #Global Environments Through the Quarternary: Exploring Environmental Change
        print('Found Global Environments Through the Quarternary')
        bookstoreList.at[i, 'ISBN'] = '9780191810169'
    if bookstoreList.at[i, 'ISBN'] == '9780191606373': #History: A Very Short Introduction
        print('Found History')
        bookstoreList.at[i, 'ISBN'] = '9780191540189'
    if bookstoreList.at[i, 'ISBN'] == '9780124079489': #Introduction to Probability Models
        print('Found Introduction to Probability Models')
        bookstoreList.at[i, 'ISBN'] = '9780125984560'
    if bookstoreList.at[i, 'ISBN'] == '9781948057882': #John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
        print("Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition")
        bookstoreList.at[i, 'ISBN'] = '9781948057899'
    if bookstoreList.at[i, 'ISBN'] == '9780838937952': #Metadata
        print('Found Metadata')
        bookstoreList.at[i, 'ISBN'] = '9780838948637'
    if bookstoreList.at[i, 'ISBN'] == '9780307757890': #Paradise Lost
        print('Found Paradise Lost')
        bookstoreList.at[i, 'ISBN'] = '9781317865735'
    if bookstoreList.at[i, 'ISBN'] == '9781466887787': #14-18: Understanding the Great War
        print('Found 14-18 Understanding the Great War')
        bookstoreList.at[i, 'ISBN'] = '9780809046430'
    if bookstoreList.at[i, 'ISBN'] == '9781400030156': #The Big Sleep
        print('Found The Big Sleep')
        bookstoreList.at[i, 'ISBN'] = '9781479403776'
    if bookstoreList.at[i, 'ISBN'] == '9780191629112': #The Book of Marvels and Travels
        print('Found The Book of Marvels and Travels')
        bookstoreList.at[i, 'ISBN'] = '9780191629105'
    if bookstoreList.at[i, 'ISBN'] == '9780140449617': #The Death of Ivan Ilyich and Other Stories
        print('Found The Death of Ivan Ilyich')
        bookstoreList.at[i, 'ISBN'] = '9780191649042'
    if bookstoreList.at[i, 'ISBN'] == '9781479823550': #Forced Out: Migrant Mothers in Search of Refuge and Hope
        print('Found Forced Out')
        bookstoreList.at[i, 'ISBN'] = '9781479823529'
    if bookstoreList.at[i, 'ISBN'] == '9780198745686': #Imperial Apocalypse: The Great War and the Destruction of the Russian Empire
        print('Found Imperial Apocalypse')
        bookstoreList.at[i, 'ISBN'] = '9781644699522'
    if bookstoreList.at[i, 'ISBN'] == '9780262367509': #Introduction to Algorithms, Fourth Edition
        print('Found Introduction to Algorithms')
        bookstoreList.at[i, 'ISBN'] = '9780262046305'
    if bookstoreList.at[i, 'ISBN'] == '9780813178288': #John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights]
        print('Found John Hervey Wheeler')
        bookstoreList.at[i, 'ISBN'] = '9780813178271'
    if bookstoreList.at[i, 'ISBN'] == '9781452289236': #Mental Health Case Management: A Practical Guide
        print('Found Mental Health Case Management')
        bookstoreList.at[i, 'ISBN'] = '9781452256078'
    if bookstoreList.at[i, 'ISBN'] == '9781101576984': #Merchants of Culture The Publishing Business in the Twenty-First Century
        print('Found Merchants of Culture')
        bookstoreList.at[i, 'ISBN'] = '9780745661421'
    if bookstoreList.at[i, 'ISBN'] == '9781319049966': #Narrative of the Life of Frederick Douglass: An American Slave, Written by Himself
        print('Found Frederick Douglass')
        bookstoreList.at[i, 'ISBN'] = '9780760355466'
    if bookstoreList.at[i, 'ISBN'] == '9780199720149': #The Oxford Handbook of Engineering and Technology in the Classical World
        print('Found Handbook of Engineering and Technology')
        bookstoreList.at[i, 'ISBN'] = '9780195187311'
    if bookstoreList.at[i, 'ISBN'] == '9781350113008': #Performance Drawing
        print('Found Performance Drawing')
        bookstoreList.at[i, 'ISBN'] = '9781350113015'
    if bookstoreList.at[i, 'ISBN'] == '9780191624711': #Persuasion
        print('Found Persuasion')
        bookstoreList.at[i, 'ISBN'] = '9781316848630'
    if bookstoreList.at[i, 'ISBN'] == '9781009314848': #The Gas Mask in Interwar Germany: Visions of Chemical Modernity
        print('Found Gas Mask')
        bookstoreList.at[i, 'ISBN'] = '9781009314862'
    if bookstoreList.at[i, 'ISBN'] == '9780385093309': #Good-Bye to All That
        print('Found Good-Bye to All That')
        bookstoreList.at[i, 'ISBN'] = '9781774649367'
    if bookstoreList.at[i, 'ISBN'] == '9781119837909': #Research Ethics for Scientists
        print('Found Research Ethics for Scientists')
        bookstoreList.at[i, 'ISBN'] = '9781119978862'
    if bookstoreList.at[i, 'ISBN'] == '9780307432568': #The Return of the Soldier
        print('Found The Return of the Soldier')
        bookstoreList.at[i, 'ISBN'] = '9780486846545'
    if bookstoreList.at[i, 'ISBN'] == '9781496203168': #Siberian Exile
        print('Found Siberian Exile')
        bookstoreList.at[i, 'ISBN'] = '9780803299597'
    if bookstoreList.at[i, 'ISBN'] == '9780190879976': #Teaching Music Theory
        print('Found Teaching Music Theory')
        bookstoreList.at[i, 'ISBN'] = '9780197510575'
    if bookstoreList.at[i, 'ISBN'] == '9780197644058': #An Uneasy Peace
        print('Found An Uneasy Peace')
        bookstoreList.at[i, 'ISBN'] = '9780197619407'
    if bookstoreList.at[i, 'ISBN'] == '9781975121549': #Fleisher & Ludwig's Textbook of Pediatric Emergency Medicine
        print('Found Fleisher & Ludwig Textbook')
        bookstoreList.at[i, 'ISBN'] = '9781975121532'
    if bookstoreList.at[i, 'ISBN'] == '9781482542222': #Treating Complex Traumatic Stress Disorders in Adults: Scientific Foundations and Therapeutic Models
        print('Found Treating Complex Traumatic Stress Disorders in Adults')
        bookstoreList.at[i, 'ISBN'] = '9781462542239'
    if bookstoreList.at[i, 'ISBN'] == '9781316044582': #Elements of Mathematical Ecology
        print('Found Elements of Mathematical Ecology')
        bookstoreList.at[i, 'ISBN'] = '9780511608520'
    if bookstoreList.at[i, 'ISBN'] == '9780307758071': #Herland
        print('Found Herland')
        bookstoreList.at[i, 'ISBN'] = '9781667601038'
    if bookstoreList.at[i, 'ISBN'] == '9780393270372': #Narrative of the Life of Frederick Douglass
        print('Found Frederick Douglass')
        bookstoreList.at[i, 'ISBN'] = '9780760355466'
    if bookstoreList.at[i, 'ISBN'] == '9780199748037': #Population Health: Concepts and Methods
        print('Found Population Health')
        bookstoreList.at[i, 'ISBN'] = '9780199864379'
    if bookstoreList.at[i, 'ISBN'] == '9780300048124': #Preschool in Three Cultures: Japan, China and the United States
        print('Found Preschool in Three Cultures')
        bookstoreList.at[i, 'ISBN'] = '9780585358543'
    if bookstoreList.at[i, 'ISBN'] == '9781101078143': #The Souls of BLack Folk
        print('Found The Souls of Black Folk')
        bookstoreList.at[i, 'ISBN'] = '9781315631998'
    if bookstoreList.at[i, 'ISBN'] == '0679601813': #The Brothers Karamazov
        print('Found The Brothers Karamazov')
        bookstoreList.at[i, 'ISBN'] = '9781786565556'
    if bookstoreList.at[i, 'ISBN'] == '9781612495736': #Manufacturing Facilities Design and Material Handling: Sixth Edition
        print('Found Manufacturing Facilities Design')
        bookstoreList.at[i, 'ISBN'] = '9781612495729'
    if bookstoreList.at[i, 'ISBN'] == '9780191605475': #Bleak House
        print('Found Bleak House')
        bookstoreList.at[i, 'ISBN'] = '9780486822556'
    if bookstoreList.at[i, 'ISBN'] == '9781119348450': #Modern Nuclear Chemistry
        print('Found Modern Nuclear Chemistry')
        bookstoreList.at[i, 'ISBN'] = '9780471768623'
    if bookstoreList.at[i, 'ISBN'] == '9781903544877': #Planetary Geology: An Introduction
        print('Found Planetary Geology')
        bookstoreList.at[i, 'ISBN'] = '9781780461045'
    if bookstoreList.at[i, 'ISBN'] == '9783031758539': #R for Political Science Research: An Introduction for Absolute Beginners
        print('Found R for Political Science Research')
        bookstoreList.at[i, 'ISBN'] = '9783031758522'
    if bookstoreList.at[i, 'ISBN'] == '9780674040793': #Clinging to Mammy: The Faithful Slave in Twentieth-Century America
        print('Found Clinging to Mammy')
        bookstoreList.at[i, 'ISBN'] = '9780674024335'
    if bookstoreList.at[i, 'ISBN'] == '9781460404027': #The Return of the Soldier
        print('Found Return of the Soldier')
        bookstoreList.at[i, 'ISBN'] = '9780486846545'

Found Controversies in Contemporary Advertising
Found Controversies in Contemporary Advertising
Found Frederick Douglass
Found The Souls of Black Folk
Found Clinging to Mammy
Found Clinging to Mammy
Found Research Ethics for Scientists
Found Advanced Linear Algebra for Engineers with MATLAB
Found Advanced Linear Algebra for Engineers with MATLAB
Found Introduction to Algorithms
Found Advanced Linear Algebra for Engineers with MATLAB
Found Planetary Geology
Found Planetary Geology
Found Planetary Geology
Found Planetary Geology
Found Planetary Geology
Found Planetary Geology
Found Persuasion
Found Persuasion
Found Frederick Douglass
Found The Souls of Black Folk
Found Return of the Soldier
Found Herland
Found Herland
Found Bleak House
Found Advanced Linear Algebra for Engineers with MATLAB
Found Manufacturing Facilities Design
Found Manufacturing Facilities Design
Found Advanced Linear Algebra for Engineers with MATLAB
Found Preschool in Three Cultures
Found Preschool in Three Cultures
Found Information Science
Found Metadata
Found Metadata
Found Evaluation and Measurement of Library Services
Found Evaluation and Measurement of Library Services
Found Elements of Mathematical Ecology
Found Modern Nuclear Chemistry
Found Advanced Linear Algebra for Engineers with MATLAB
Found Fleisher & Ludwig Textbook
Found Fleisher & Ludwig Textbook
Found Research Ethics for Scientists
Found Research Ethics for Scientists
Found On the History of Political Philosophy
Found On the History of Political Philosophy
Found On the History of Political Philosophy
Found On the History of Political Philosophy
Found On the History of Political Philosophy
Found R for Political Science Research
Found Population Health
Found The Brothers Karamazov
Found Criminological Theory
Found Criminological Theory
Found Mental Health Case Management
Found Mental Health Case Management
Found Mental Health Case Management
Found Clinging to Mammy
Found Clinging to Mammy
Found Herland

In [21]:
#pd.set_option('display.max_rows', None)
results.sort_values(by = 'Title')['Title'].unique()

array(['4-ginō de hirogaru chūkyū Nihongo karutetto / kanshū Sakamoto Tadashi ; cho Yasui Akemi, Ide Yuriko, Doi Miyuki, Hamada Hideki = Quartet : intermediate Japanese across the four language skills / supervisor Tadashi Sakamoto ; authors Akemi Yasui, Yuriko Ide, Miyuki Doi, Hideki Hamada.',
       '58-in-mind : multilingual teaching strategies for diverse deaf students / edited by Debbie Golos, Marlon Kuntze, Kimberly Wolbers, Chris Kurz.',
       'A History of Modern Linguistics : From the Beginnings to World War II',
       'A brief introduction to astronomy in the Middle East / John M. Steele.',
       'A case study in visual agnosia revisited : to see but not to see / Glyn Humphreys and Jane Riddoch.',
       'A companion to paleopathology / edited by Anne L. Grauer.',
       'A first course in continuum mechanics / Oscar Gonzalez and Andrew M. Stuart.',
       'A first time for everything : a true story / by Dan Santat',
       'A history of Roman art / Steven L. Tuck.',
       'A history of religion in 5 1/2 objects : bringing the spiritual to its senses / S. Brent Plate.',
       'A history of the American musical theatre : no business like it / Nathan Hurwitz.',
       'A lexicon of the Homeric dialect / Richard John Cunliffe ; with a new preface by James H. Dee.',
       'A manual for writers of research papers, theses, and dissertations : Chicago Style for students and researchers / Kate L. Turabian ; revised by Wayne C. Booth, Gregory G. Colomb, Joseph M. Williams, and the University of Chicago Press editorial staff.',
       'A walk in the night : and other stories / Alex La Guma.',
       'ACT Made Simple : An Easy-To-Read Primer on Acceptance and Commitment Therapy.',
       'Abstract algebra / David S. Dummit, Richard M. Foote.',
       'Achilles in Vietnam : combat trauma and the undoing of character / Jonathan Shay.',
       'Administrative law and policy / by John M. Scheb, II, Hemant K. Sharma.',
       'Advanced linear algebra for engineers with MATLAB / Sohail A. Dianat, Eli S. Saber.',
       'Advanced linear algebra for engineers with MATLAB [electronic resource] / Sohail A. Dianat, Eli S. Saber.',
       'Affirming disability : strengths-based portraits of culturally diverse families / Janet Story Sauer, Zachary Rossetti ; foreword by Maria de Lourdes B. Serpa.',
       'After Appomattox : military occupation and the ends of war / Gregory P. Downs.',
       'Algebra [electronic resource] / by Thomas W. Hungerford.',
       'All my rage / Sabaa Tahir.',
       'America divided : the civil war of the 1960s / Maurice Isserman, Michael Kazin.',
       'American sonnets for my past and future assassin / Terrance Hayes.',
       'An Introduction to Mathematical Epidemiology [electronic resource] / by Maia Martcheva.',
       'An introduction to applied behavioral neuroscience : biological psychology in everyday life / Laura A. Freberg.',
       'An introduction to system modeling and control / John Chiasson.',
       'Ancient Greek religion / Jon D. Mikalson.',
       'Animal behavior / Dustin R. Rubenstein, Columbia University.',
       'Apophatic elements in the theory and practice of psychoanalysis : pseudo-dionysius and C.G. Jung / David Henderson.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Art education for a sustainable planet : embracing ecopedagogy in K-12 classrooms / Joy G. Bertling ; foreword by Olivia Gude.',
       'Artificial intelligence for cybersecurity : develop AI approaches to solve cybersecurity problems in your organization / Bojan Kolosnjaji [and three others].',
       'Aya de Yopougon / Marguerite Abouet, Clément Oubrerie.',
       'Banking on freedom : black women in U.S. finance before the New Deal / Shennette Garrett-Scott.',
       "Because of sex : one law, ten cases, and fifty years that changed American women's lives at work / Gillian Thomas.",
       "Because of sex [electronic resource] : one law, ten cases, and fifty years that changed American women's lives at work / Gillian Thomas.",
       'Becoming a data head :  how to think, speak, and understand data science, statistics, and machine learning /  Alex J. Gutman, Jordan Goldmeier.',
       'Beloved / a novel by Toni Morrison.',
       'Bestiary [electronic resource] : being an English version of the Bodleian Library, Oxford M.S. Bodley 764 : with all the original miniatures reproduced in facsimile / translated and introduced by Richard Barber.',
       'Binti / Nnedi Okorafor.',
       'Biomaterials Science : An Introduction to Materials in Medicine.',
       'Biomaterials science : an introduction to materials in medicine / edited by William Wagner, Shelly Sakiyama-Elbert, Guigen Zhang, Michael Yaszemski.',
       'Black Beauty/  Anna Sewell.',
       'Bleak house / Charles Dickens ; editor, Gregory Koutrouby.',
       "Burning at Europe's borders : an ethnography on the African migrant experience in Morocco / Isabella Alexander-Nathani.",
       'Business ethics : a contemporary introduction / Jeffrey Moriarty.',
       'Buy Black : How Black Women Transformed US Pop Culture.',
       'Buy Black : how Black women transformed US pop culture / Aria S. Halliday.',
       'COURSE IN MATHEMATICAL MODELING [electronic resource].',
       'Call of the Wild, The/  Jack London, Nicholas Ruddick (editor).',
       'Carceral con : the deceptive terrain of criminal justice reform / Kay Whitlock and Nancy A. Heitzeg.',
       'Case studies in deaf education : inquiry, application, and resources / Caroline Guardino [and four others].',
       'Case studies in deaf education : inquiry, application, and resources / Caroline Guardino, Jennifer S. Beal, Joanna E. Cannon, Jenna Voss, and Jessica P. Bergeron.',
       'Ceremony / Leslie Marmon Silko ; introduction by Larry McMurtry ; with a new preface by the author.',
       'Chief sustainability officers at work : how CSOs build successful sustainability and ESG strategies / Chrissa Pagitsas.',
       'Chief sustainability officers at work [electronic resource] : how CSOs build successful sustainability and ESG strategies / Chrissa Pagitsas.',
       "Children's mathematics : cognitively guided instruction / Thomas P. Carpenter, Elizabeth Fennema, Megan Loef Franke, Linda Levi, Susan B. Empson.",
       'Clashing views in sustainability / selected, edited, and with introductions by Robert W. Taylor.',
       'Climate change and managed ecosystems / edited by J.S. Bhatti [and others].',
       'Clinging to mammy : the faithful slave in twentieth-century America / Micki McElya.',
       'Clinging to mammy [electronic resource] : the faithful slave in twentieth-century America / Micki McElya.',
       'Clinical interviewing / John Sommers-Flanagan, Rita Sommers-Flanagan.',
       'Cognitive behavior therapy : basics and beyond / Judith S. Beck ; foreword by Aaron T. Beck.',
       'Comparative education : the dialectic of the global and the local / Carlos Alberto Torres, Robert F. Arnove, Lauren Ila Misiaszek.',
       'Controversies in contemporary advertising [electronic resource] / Kim Bartel Sheehan.',
       'Conversations with families of children with disabilities : insights for teacher understanding / Victoria I. Puig and Susan L. Recchia.',
       'Counseling psychology / Charles J. Gelso and Elizabeth Nutt Williams.',
       'Crack [electronic resource] : rock cocaine, street capitalism, and the decade of greed / David Farber.',
       'Cracked, not broken [electronic resource] : surviving and thriving after a suicide attempt / Kevin Hines.',
       'Creating outstanding classrooms : a whole-school approach / Oliver Knight and David Benson.',
       'Creativity, Inc. : overcoming the unseen forces that stand in the way of true inspiration / Ed Catmull ; with Amy Wallace.',
       'Criminological Theory: An Analysis of Its Underlying Assumptions [electronic resource].',
       'Customer Experience 3. 0 : High-Profit Strategies in the Age of Techno Service.',
       'Customer experience 3.0 : high-profit strategies in the age of techno service / John A. Goodman.',
       'Dancing with the devil : why bad feelings make life good / Krista K. Thomason.',
       'Deaf culture : exploring deaf communities in the United States / Irene W. Leigh, PhD, Jean F. Andrews, PhD, Raychelle L. Harris, PhD, Topher González Ávila, MA.',
       'Deaf people and society : psychological, sociological and educational perspectives / Irene W. Leigh, Jean F. Andrews, Cara A. Miller, and Ju-Lee A. Wolsey.',
       'Debating reform [electronic resource] : conflicting perspectives on how to fix the American political system / Richard J. Ellis (Willamette University), Michael C. Nelson (Rhodes College), editors.',
       'Democracy for realists : why elections do not produce responsive government / Christopher H. Achen, Larry M. Bartels.',
       'Design : history, theory and practice of product design / Bernhard E. Bürdek.',
       'Design Education : Creating Thinkers to Improve the World.',
       'Diagnostic and statistical manual of mental disorders : DSM-5-TR / American Psychiatric Association.',
       'Differential Equations, Dynamical Systems, and an Introduction to Chaos.',
       'Differential equations, dynamical systems, and an introduction to chaos (Third Edition) / Morris W. Hirsch, Stephen Smale, Robert L. Devaney.',
       'Dimensions of human behavior : the changing life course / [edited by] Elizabeth D. Hutchison, Emeritus, Virginia Commonwealth University, Leanne Wood Charlesworth, Nazareth University and contributing authors.',
       'Disaster prevention / edited by Ilan Kelman.',
       "Disciplinary and content literacy for today's adolescents : honoring diversity and building competence / William G. Brozo.",
       'Early music : a very short introduction / Thomas Forrest Kelly.',
       'Econometric analysis of cross section and panel data / Jeffrey M. Wooldridge.',
       'Educational and psychological measurement / W. Holmes Finch and Brian F. French.',
       'Elements of mathematical ecology [electronic resource] / Mark Kot.',
       'Engaged anthropology : politics beyond the text / Stuart Kirsch.',
       'Engineering design :  a project-based introduction /  Clive L. Dym, Patrick Little, and Elizabeth J. Orwin.',
       'Enviromedics : the impact of climate change on human health / Jay Lemery and Paul Auerbach.',
       'Essentials of nonprofit management and leadership : a skills-based approach / Richard Hoefer & Larry D. Watson.',
       'Ethics of data and analytics : concepts and cases / Kirsten Martin.',
       'Evicted : poverty and profit in the American city / Matthew Desmond.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement / Rona F. Levin, Bonnie Lauder, editors.',
       'Exactly How to Sell : The Sales Guide for Non-Sales Professionals.',
       'Exactly how to sell : the sales guide for non-sales professionals / Phil M. Jones.',
       "Experiencing design : the innovator's journey / Jeanne Liedtka, Karen Hold, Jessica Eldridge.",
       'Facilitating Breakthrough : How to Remove Obstacles, Bridge Differences, and Move Forward Together',
       'Fields and streams [electronic resource] : stream restoration, neoliberalism, and the future of environmental science / Rebecca Lave.',
       'Fighting Against the Injustice of the State and Globalization [electronic resource] : Comparing the African American and Oromo Movements / by A. Jalata.',
       'Financial and business management for the doctor of nursing practice / KT Waxman.',
       'Finding the mother tree : discovering the wisdom of the forest / Suzanne Simard.',
       "Fishing through the apocalypse : an angler's adventures in the 21st century / Matthew L. Miller.",
       "Fleisher & Ludwig's textbook of pediatric emergency medicine / senior editors, Kathy N. Shaw, Richard G. Bachur ; associate editors, James M. Chamberlain, Jane Lavelle, Joshua Nagler, Joan E. Shook.",
       'Focus on Developmentally Appropriate Practice : Equitable and Joyful Learning in Kindergarten.',
       'Forensic Anthropology : An Introductory Lab Manual.',
       'Forms : whole, rhythm, hierarchy, network / Caroline Levine.',
       'Frauds, myths, and mysteries : science and pseudoscience in archaeology / Kenneth L. Feder, Central Connecticut State University.',
       "Frieren : beyond journey's end / story by Kanehito Yamada ; art by Tsukasa Abe.",
       'Fun home [electronic resource] : A family tragicomic. Alison Bechdel.',
       'Fundamentals of gas dynamics /  Robert D. Zucker, Oscar Biblarz.',
       'Fundamentals of physics. II, Electromagnetism, optics, and quantum mechanics / R. Shankar.',
       'GENKI : an integrated course in elementary Japanese. I / Eri Banno, Yoko Ikeda, Yutaka Ohno, Chikako Shinagawa, Kyoko Tokashiki.',
       "Geminos's Introduction to the phenomena : a translation and study of a Hellenistic survey of astronomy / James Evans and J. Lennart Berggren.",
       'Getting real about inequality : intersectionality in real life (IRL) / editors,  Cherise A. Harris, Stephanie M. McClure.',
       "Giovanni's room / James Baldwin.",
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Globalization of education : an introduction / Joel Spring.',
       "Good to great [electronic resource] : Why some companies make the leap...and others don't. Jim Collins.",
       'Gordis epidemiology / David D. Celentano, Moyses Szklo.',
       'Government and Politics in Tennessee [electronic resource].',
       'Great short works of Fyodor Dostoevsky / with an introduction by Ronald Hingley.',
       'Green nature/human nature : the meaning of plants in our lives / Charles A. Lewis.',
       'Guide to the vascular plants of Tennessee / compiled and edited by members of the Tennessee Flora Committee.',
       'Hands-on large language models [electronic resource] : language understanding and generation / Jay Alammar and Maarten Grootendorst.',
       'Head off & split : poems / Nikky Finney.',
       'Head off & split [electronic resource] : poems / Nikky Finney.',
       'Herland / Charlotte Perkins Gilman.',
       'Hey Whipple, Squeeze This : The Classic Guide to Creating Great Advertising.',
       'Hey Whipple, squeeze this :  the classic guide to creating great advertising /  by Luke Sullivan ; foreword by Anselmo Ramos.',
       'High fidelity [electronic resource] / Nick Hornby.',
       'History and philosophy of sport and physical activity / R. Scott Kretchmar, Mark Dyreson, Matthew P. Llewellyn, John Gleaves.',
       'How great leaders think : the art of reframing',
       'How to Do Critical Discourse Analysis : A Multimodal Introduction.',
       "How to lead : wisdom from the world's greatest CEOs, founders, and game changers / David M. Rubenstein.",
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'Improving your storytelling : beyond the basics for all who tell stories in work or play / Doug Lipman.',
       'Inequality : a contemporary approach to race, class, and gender / Lisa A. Keister, Duke University, Darby E. Southgate, Los Angeles Valley College.',
       'Information Architecture for the World Wide Web : Designing Large-Scale Web Sites.',
       'Information architecture for the World Wide Web : designing large-scale web sites / Peter Morville, Louis Rosenfeld.',
       'Information science : the basics / Judith Pintar and David Hopping.',
       'Integrating Program Management and Systems Engineering : Methods, Tools and Organizational Systems for Improving Performance.',
       'Integrating program management and systems engineering : methods, tools, and organizational systems for improving performance / Eric S. Rebentisch, editor ; with foreword by Larry Prusak.',
       'International trade and agriculture [electronic resource] / Won W. Koo and P. Lynn Kennedy.',
       'Interpersonal communication : putting theory into practice / Denise Solomon, Jennifer Theiss.',
       'Introduction to Algorithms / Thomas H. Cormen [and three others].',
       'Introduction to automata theory, languages, and computation / John E. Hopcroft, Jeffrey D. Ullman.',
       'Introduction to deaf culture / Thomas K. Holcomb.',
       'Introduction to industrial organization. / Luis M.B. Cabral.',
       'Introduction to kinesiology : studying physical activity / Duane V. Knudson, Timothy A. Brusseau, editors.',
       'Introduction to leadership : concepts and practice / Peter G. Northouse, Western Michigan University.',
       'Invisible child : poverty, survival & hope in an American city / Andrea Elliott.',
       'Invitation to law & society : an introduction to the study of real law / Kitty Calavita.',
       'Invitation to world religions / Jeffrey Brodd, California State University, Sacramento; Layne Little, University of California, Davis; Bradley Nystrom, California State University, Sacramento; Robert Platzner, California State University, Sacramento; Richard Shek, California State University, Sacramento; Erin Stiles, University of Nevada, Reno.',
       'John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights / Brandon K. Winford.',
       'Johns Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals: Model & Guidelines [electronic resource].',
       'Just practice : a social justice approach to social work / Janet L. Finn, Jen K. Molloy, Ashley R. Trautman.',
       'Just practice : a social justice approach to social work / Janet L. Finn.',
       "Karl Marx's theory of history : a defence / G. A. Cohen.",
       'King Richard II / William Shakespeare.',
       "King of the North : Martin Luther King's life of struggle outside the South / Jeanne Theoharis.",
       'Language deprivation and deaf mental health / edited by Neil S. Glickman and Wyatte C. Hall.',
       'Language vs. reality : why language is good for lawyers and bad for scientists / N.J. Enfield.',
       'Language, society and power : an introduction / Annabelle Mooney, Betsy Evans.',
       "Leaders eat last : why some teams pull together and others don't / Simon Sinek.",
       'Lean Production for Competitive Advantage : A Comprehensive Guide to Lean Methodologies and Management Practices, Second Edition.',
       'Learning things : material culture in art education / Doug Blandy, Paul E. Bolin.',
       'Legends & lattes : a novel of high fantasy and low stakes / Travis Baldree.',
       'Listening to war : sound, music, trauma and survival in wartime Iraq / J. Martin Daughtry.',
       'Listening to war : sound, music, trauma, and survival in wartime Iraq / J. Martin Daughtry.',
       'Literary theory and criticism : an introduction / Anne H. Stevens.',
       'Long way down / Jason Reynolds.',
       'MLA handbook / [Modern Language Association Of America].',
       'Macbeth : texts and contexts / William Shakespeare ; edited by William C. Carroll.',
       'Managing to learn : using the A3 management process to solve problems, gain agreement, mentor and lead / by John Shook ; foreword by Jim Womack.',
       'Manual of woody landscape plants : their identification, ornamental characteristics, culture, propagation and uses / Michael A. Dirr ; illustrations by Bonnie Dirr ... [et al.].',
       'Manufacturing Facilities Design & Material Handling : Sixth Edition.',
       'Materials and Sustainable Development / M. F. Ashby.',
       'Materials science and engineering : an introduction / William D. Callister, Jr., David G. Rethwisch.',
       "Maus : a survivor's tale : my father bleeds history : and here my troubles began / Art Spiegelman.",
       'Measurement and detection of radiation / Nicholas Tsoulfanidis, Sheldon Landsberger.',

In [22]:
textbookISBNs = textbookISBNs.astype({'MMS Id': 'int64'})



resultsPlusList = pd.merge(results, textbookISBNs, left_on = 'MMS ID', right_on = 'MMS Id', how = 'inner')

In [23]:
resultsPlusList

,Title_x,Alternate Graphic Representation,Type,Creator / Imprint,Subject,Series,Relation,Modification Date,Edition,Uniform Title,Medium Type,Language,Creation Date,Language of Cataloging,ISBN_x,ISBN (13),ISSN,Cluster ISSN,Record Number,MMS ID,Bibliographic Rank,Local Call Number,Other Classification Number,NLM Call Number,Dewey Decimal Classification Number,LC Call Number,Classification Part,UDC Classification Number,NAL Call Number,Handle Identifier,Peer Reviewed,Open Access,Physical Availability,Digital Availability,Electronic Availability,Collection Name,Collection ID,Orders,Requests,Physical Description Extent,Local Labels,Related Records,Courses,Licenses,Reminders,Notes,Short Title,Electronic location and access,ISBN (Normalized),ISBN_y,MMS Id,Title_y,Electronic Collection Public Name,Availability,Portfolio Id,Portfolio Public Note,No. of Available Portfolio,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...
1,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,Taylor & Francis Ebooks Individually Purchased,Available,53259519420002311,NaN,1,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...
2,Affirming disability : strengths-based portrai...,NaN,Book {Book - Electronic} text; computer; onlin...,"Sauer, Janet Story (New York, NY : Teachers Co...",Children with disabilities--Education--United ...,"Disability, culture, and equity series",NaN,2020-02-26 04:11:00,NaN,NaN,NaN,English,2020-02-25 22:02:00,NaN,9780807778203; 0807778206; 9780807763292,9780807778203; 9780807778203; 9780807763292,NaN,NaN,(DLC)ybp301050360,9925885567802311,92,NaN,NaN,NaN,371.9,LC4015 .S24 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xiii, 161 pages)",NaN,0,0,0,0,0,Affirming disability :,http://search.ebscohost.com/login.aspx?direct=...,0807778206; 9780807778203; 9780807763308; 0807...,0807778206; 9780807778203; 9780807763308; 0807...,9925885567802311,Affirming disability : strengths-based portrai...,EBSCO Ebooks Individually Purchased,Available,53325024970002311,NaN,1,Online Access - 1 user,[http://search.ebscohost.com/login.aspx?direct...,http://search.ebscohost.com/login.aspx?direct=...,Online Access - 1 user,http://search.ebscohost.com/login.aspx?direct=...
3,Algebra [electronic resource] / by Thomas W. H...,NaN,Book {Book - Electronic} text; computer; onlin...,"Hungerford, Thomas W. (New York, NY : Springer...",Mathematics.;Algebra.,Graduate texts in mathematics ; 73,NaN,2021-07-30 19:49:00,NaN,NaN,NaN,English,2016-05-05 14:40:00,NaN,9781461261018; 9781461261032,9781461261018; 9781461261032,NaN,NaN,(DE-He213)978-1-4612-6101-8,9925413371102311,95,NaN,NaN,NaN,512,QA150-272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Springer Nature; Springe...,NaN,NaN,0,0,"XXIV, 504 p.",NaN,0,0,0,0,0,Algebra,http://dx.doi.org/10.1007/978-1-4612-6101-8,9781461261018; 1461261015; 9781461261032; 1461...,9781461261018; 1461261015; 9781461261032; 1461...,9925413371102311,Algebra,Springer English/International Ebook Collection,Available,53262394480002311,NaN,1,NaN,[http://dx.doi.org/10.1007/978-1-4612-6101-8],http://dx.doi.org/10.1007/978-1-4612-6101-8,,http://dx.doi.org/10.1007/978-1-4612-6101-8
4,Banking on freedom : black women in U.S. finan...,NaN,Book {Book - Electronic} text; computer; onlin...,"Garrett-Scott, Shennette (New York : Columbia ...",Women in finance--United States--History.;Afri...,Columbia studies in the history of U.S. capita...,NaN,2021-07-30 23:31:00,NaN,NaN,NaN,English,2020-03-24 12:04:00,NaN,9780231545211 (electronic bk.); 0231545215 (el...,9780231545211 (electronic bk.); 9780231545211 ...,NaN,NaN,99984029118; (NhCcYBP)ybp16030689,9925893939902311,93,NaN,NaN,NaN,332.1092/520973,HG181 .G357 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at JSTOR; JSTOR Ebooks (JST...,NaN,NaN,1,0,"1 online resource (xi, 273 pages) :",NaN,0,0,0,0,0,Banking on freedom :,https://www.jstor.org/stable/10.7312/garr18390...,0231545215; 9780231545211; 0231183909; 9780231...,0231545215; 9780231545211; 0231183909; 9780231...,9925893939902311,Banking on freedom : black women in U.S. finan...,JSTOR Ebooks Individually Purchased,Available,53327072440002311,NaN,1,Online Access - Unlimited users (DRM-free),[https://www.jstor.org/stable/10.7312/garr1839...,https://www.jstor.org/stable/10.7312/garr18390,Online Access - Unlimited users (DRM-free),https://www.jstor.org/stable/10.7312/garr18390...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,The five dysfunctions of a team : a leadershi...,NaN,Book {Book - Electronic} text; computer; onlin...,"(San Francisco: Jossey-Bass, c2002.)",Teams in the workplace,NaN,NaN,2026-08-02 03:24:00,First edition.,NaN,NaN,English,2012-02-25 16:40:00,English,0-470-89386-9; 1-62198-483-4; 1-280-85623-8; 9...,9780470893869; 9781621984832; 9781280856235; 9...,NaN,NaN,(MiAaPQ)EBC292516; (OCoLC)402454236; (OCoLC)oc...,9926909576802311,92,NaN,336.3,NaN,658.402 658.4036,HD66 .L456 2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,"1 online resource (ix, 229 pages) :",NaN,1,0,0,0,0,The five dysfunctions of a team :,NaN,0470893869; 9780470893869; 1621984834; 9781621...,0470893869; 9780470893869; 1621984834; 9781621...,9926909576802311,The five dysfunctions of a team : a leadership...,O'Reilly Online Learning: Academic/Public Libr...,Available,53452601260002311,NaN,1,NaN,NaN,NaN,NaN,
278,Think Python : how to think like a computer sc...,NaN,Book {Book - Electronic} text; computer; onlin...,"Downey, Allen, (Sebastopol, CA : O'Reilly Medi...","Python (Computer program language)--Handbooks,...",NaN,NaN,2026-08-06 00:28:00,Third edition,NaN,NaN,English,2024-05-28 05:01:00,English,9781098155438; 9781098155407; 1098155408; 9781...,9781098155438; 9781098155407; 9781098155407; 9...,NaN,NaN,(MiAaPQ)EBC31354103; (Au-PeEL)EBL31354103; (CK...,9927022061902311,100,NaN,NaN,NaN,005.133,QA76.73.P98 D69 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,"1 online resource (xvii, 306 pages) :",NaN,0,0,0,0,0,Think Python :,NaN,1098155408; 9781098155407; 9781098155414; 1098...,1098155408; 9781098155407; 9781098155414; 1098...,9927022061902311,Think Python : how to think like a computer sc...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453654960002311,NaN,1,NaN,NaN,NaN,NaN,
279,Trauma counseling : theories and interventions...,NaN,Book {Book - Electronic} text; computer; onlin...,"López Levers, Lisa (New York, NY : Springer Pu...",Psychic trauma--Treatment.;Wounds and injuries...,NaN,NaN,2026-04-15 08:28:00,Second edition.,NaN,NaN,English,2026-02-02 11:07:00,English,9780826150851; 0826150853; 9780826150851 (EBSC...,9780826150851; 9780826150851; 9780826150851 (E...,NaN,NaN,(OCoLC)1298514014; (OCoLC)cis063794753,9926868740402311,101,NaN,NaN,NaN,362.1/04256,RC552.P67 L475 2023eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xxvi, 550 pages) :",NaN,0,0,0,0,0,Trauma counseling :,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
280,True north : leading authentically in today's ...,NaN,Book {Book - Electronic} text; computer; onlin...,"George, Bill (Hoboken, New Jersey : Wiley, [20...",Leadership.;Organizational effectiveness.,NaN,NaN,2026-03-27 13:11:00,Emerging leader edition.,NaN,NaN,English,2022-08-28 05:20:00,English,9781119886112; 1119886112; 9781119886129; 1119...,9781119886112; 9781119886112; 9781119886129; 9...,NaN,NaN,(MiAaPQ)EBC7077658; (Au-PeEL)EBL7077658; (CKB)...,9926909582702311,95,NaN,NaN,NaN,658.4092,HD57.7 .G467 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (323 pages),NaN,0,0,0,0,0,True north :,NaN,1119886112; 9781119886112; 1119886120; 9781119...,1119886112; 9781119886112; 1119886120; 9781119...,9926909582702311,True north : leading authentically in today's ...,O'Reilly Online Learning: Academic/Public Libr...,Available,53452603080002311,NaN,1,NaN,NaN,NaN,NaN,
281,Video field production and editing / Ronald J....,NaN,Book {Book - Electronic} text; computer; onlin...,"Compesi, Ronald J., (New York ; London : Routl...",Television--Production and direction.;Video re...,NaN,NaN,2026-07-21 03:42:00,Eighth edition.,NaN,NaN,English,2019-03-10 11:04:00,English,0-429-50593-0; 0-429-00033-2; 0-429-00032-4; 9...,9780429505935; 9780429000331; 9780429000324; 9...,NaN,NaN,(CKB)4100000007741523; (MiAaPQ)EBC5716876; (Ca...,9926910284202311,95,NaN,NaN,NaN,791.4502/32,PN1992.75 .C667 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (303 pages),NaN,0,0,0,0,0,Video field production and editing /,NaN,0429000332; 9780429000331; 0429000324; 9780429...,0429000332; 9780429000331; 0429000324; 9780429...,9926910284202311,Video field production and editing /,O'Reilly Online Learning: Academic/Public Libr...,Available,53452820550002311,NaN,1,NaN,NaN,NaN,NaN,

In [24]:
#resultsPlusList.to_excel('Results Plus List Example.xlsx')

resultsPlusList.sort_values(by = 'Title_x')['Title_x'].unique()

array(['58-in-mind : multilingual teaching strategies for diverse deaf students / edited by Debbie Golos, Marlon Kuntze, Kimberly Wolbers, Chris Kurz.',
       'A History of Modern Linguistics : From the Beginnings to World War II',
       'A case study in visual agnosia revisited : to see but not to see / Glyn Humphreys and Jane Riddoch.',
       'A companion to paleopathology / edited by Anne L. Grauer.',
       'A history of religion in 5 1/2 objects : bringing the spiritual to its senses / S. Brent Plate.',
       'A history of the American musical theatre : no business like it / Nathan Hurwitz.',
       'ACT Made Simple : An Easy-To-Read Primer on Acceptance and Commitment Therapy.',
       'Achilles in Vietnam : combat trauma and the undoing of character / Jonathan Shay.',
       'Advanced linear algebra for engineers with MATLAB [electronic resource] / Sohail A. Dianat, Eli S. Saber.',
       'Affirming disability : strengths-based portraits of culturally diverse families / Janet Story Sauer, Zachary Rossetti ; foreword by Maria de Lourdes B. Serpa.',
       'After Appomattox : military occupation and the ends of war / Gregory P. Downs.',
       'Algebra [electronic resource] / by Thomas W. Hungerford.',
       'An Introduction to Mathematical Epidemiology [electronic resource] / by Maia Martcheva.',
       'An introduction to applied behavioral neuroscience : biological psychology in everyday life / Laura A. Freberg.',
       'An introduction to system modeling and control / John Chiasson.',
       'Ancient Greek religion / Jon D. Mikalson.',
       'Apophatic elements in the theory and practice of psychoanalysis : pseudo-dionysius and C.G. Jung / David Henderson.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Art education for a sustainable planet : embracing ecopedagogy in K-12 classrooms / Joy G. Bertling ; foreword by Olivia Gude.',
       'Artificial intelligence for cybersecurity : develop AI approaches to solve cybersecurity problems in your organization / Bojan Kolosnjaji [and three others].',
       'Banking on freedom : black women in U.S. finance before the New Deal / Shennette Garrett-Scott.',
       "Because of sex [electronic resource] : one law, ten cases, and fifty years that changed American women's lives at work / Gillian Thomas.",
       'Becoming a data head :  how to think, speak, and understand data science, statistics, and machine learning /  Alex J. Gutman, Jordan Goldmeier.',
       'Beloved / a novel by Toni Morrison.',
       'Bestiary [electronic resource] : being an English version of the Bodleian Library, Oxford M.S. Bodley 764 : with all the original miniatures reproduced in facsimile / translated and introduced by Richard Barber.',
       'Biomaterials Science : An Introduction to Materials in Medicine.',
       'Biomaterials science : an introduction to materials in medicine / edited by William Wagner, Shelly Sakiyama-Elbert, Guigen Zhang, Michael Yaszemski.',
       'Black Beauty/  Anna Sewell.',
       'Bleak house / Charles Dickens ; editor, Gregory Koutrouby.',
       'Business ethics : a contemporary introduction / Jeffrey Moriarty.',
       'Buy Black : How Black Women Transformed US Pop Culture.',
       'COURSE IN MATHEMATICAL MODELING [electronic resource].',
       'Call of the Wild, The/  Jack London, Nicholas Ruddick (editor).',
       'Carceral con : the deceptive terrain of criminal justice reform / Kay Whitlock and Nancy A. Heitzeg.',
       'Case studies in deaf education : inquiry, application, and resources / Caroline Guardino, Jennifer S. Beal, Joanna E. Cannon, Jenna Voss, and Jessica P. Bergeron.',
       'Ceremony / Leslie Marmon Silko ; introduction by Larry McMurtry ; with a new preface by the author.',
       'Chief sustainability officers at work : how CSOs build successful sustainability and ESG strategies / Chrissa Pagitsas.',
       'Chief sustainability officers at work [electronic resource] : how CSOs build successful sustainability and ESG strategies / Chrissa Pagitsas.',
       'Climate change and managed ecosystems / edited by J.S. Bhatti [and others].',
       'Clinging to mammy [electronic resource] : the faithful slave in twentieth-century America / Micki McElya.',
       'Cognitive behavior therapy : basics and beyond / Judith S. Beck ; foreword by Aaron T. Beck.',
       'Comparative education : the dialectic of the global and the local / Carlos Alberto Torres, Robert F. Arnove, Lauren Ila Misiaszek.',
       'Controversies in contemporary advertising [electronic resource] / Kim Bartel Sheehan.',
       'Conversations with families of children with disabilities : insights for teacher understanding / Victoria I. Puig and Susan L. Recchia.',
       'Crack [electronic resource] : rock cocaine, street capitalism, and the decade of greed / David Farber.',
       'Cracked, not broken [electronic resource] : surviving and thriving after a suicide attempt / Kevin Hines.',
       'Creating outstanding classrooms : a whole-school approach / Oliver Knight and David Benson.',
       'Criminological Theory: An Analysis of Its Underlying Assumptions [electronic resource].',
       'Customer experience 3.0 : high-profit strategies in the age of techno service / John A. Goodman.',
       'Dancing with the devil : why bad feelings make life good / Krista K. Thomason.',
       'Deaf culture : exploring deaf communities in the United States / Irene W. Leigh, PhD, Jean F. Andrews, PhD, Raychelle L. Harris, PhD, Topher González Ávila, MA.',
       'Deaf people and society : psychological, sociological and educational perspectives / Irene W. Leigh, Jean F. Andrews, Cara A. Miller, and Ju-Lee A. Wolsey.',
       'Debating reform [electronic resource] : conflicting perspectives on how to fix the American political system / Richard J. Ellis (Willamette University), Michael C. Nelson (Rhodes College), editors.',
       'Democracy for realists : why elections do not produce responsive government / Christopher H. Achen, Larry M. Bartels.',
       'Design : history, theory and practice of product design / Bernhard E. Bürdek.',
       'Design Education : Creating Thinkers to Improve the World.',
       'Differential Equations, Dynamical Systems, and an Introduction to Chaos.',
       'Differential equations, dynamical systems, and an introduction to chaos (Third Edition) / Morris W. Hirsch, Stephen Smale, Robert L. Devaney.',
       'Disaster prevention / edited by Ilan Kelman.',
       "Disciplinary and content literacy for today's adolescents : honoring diversity and building competence / William G. Brozo.",
       'Early music : a very short introduction / Thomas Forrest Kelly.',
       'Econometric analysis of cross section and panel data / Jeffrey M. Wooldridge.',
       'Educational and psychological measurement / W. Holmes Finch and Brian F. French.',
       'Elements of mathematical ecology [electronic resource] / Mark Kot.',
       'Engaged anthropology : politics beyond the text / Stuart Kirsch.',
       'Engineering design :  a project-based introduction /  Clive L. Dym, Patrick Little, and Elizabeth J. Orwin.',
       'Enviromedics : the impact of climate change on human health / Jay Lemery and Paul Auerbach.',
       'Ethics of data and analytics : concepts and cases / Kirsten Martin.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement / Rona F. Levin, Bonnie Lauder, editors.',
       'Exactly How to Sell : The Sales Guide for Non-Sales Professionals.',
       'Exactly how to sell : the sales guide for non-sales professionals / Phil M. Jones.',
       "Experiencing design : the innovator's journey / Jeanne Liedtka, Karen Hold, Jessica Eldridge.",
       'Facilitating Breakthrough : How to Remove Obstacles, Bridge Differences, and Move Forward Together',
       'Fields and streams [electronic resource] : stream restoration, neoliberalism, and the future of environmental science / Rebecca Lave.',
       'Fighting Against the Injustice of the State and Globalization [electronic resource] : Comparing the African American and Oromo Movements / by A. Jalata.',
       'Financial and business management for the doctor of nursing practice / KT Waxman.',
       'Finding the mother tree : discovering the wisdom of the forest / Suzanne Simard.',
       "Fishing through the apocalypse : an angler's adventures in the 21st century / Matthew L. Miller.",
       "Fleisher & Ludwig's textbook of pediatric emergency medicine / senior editors, Kathy N. Shaw, Richard G. Bachur ; associate editors, James M. Chamberlain, Jane Lavelle, Joshua Nagler, Joan E. Shook.",
       'Focus on Developmentally Appropriate Practice : Equitable and Joyful Learning in Kindergarten.',
       'Forensic Anthropology : An Introductory Lab Manual.',
       'Forms : whole, rhythm, hierarchy, network / Caroline Levine.',
       'Fun home [electronic resource] : A family tragicomic. Alison Bechdel.',
       'Fundamentals of gas dynamics /  Robert D. Zucker, Oscar Biblarz.',
       'Fundamentals of physics. II, Electromagnetism, optics, and quantum mechanics / R. Shankar.',
       'GENKI : an integrated course in elementary Japanese. I / Eri Banno, Yoko Ikeda, Yutaka Ohno, Chikako Shinagawa, Kyoko Tokashiki.',
       "Geminos's Introduction to the phenomena : a translation and study of a Hellenistic survey of astronomy / James Evans and J. Lennart Berggren.",
       'Getting real about inequality : intersectionality in real life (IRL) / editors,  Cherise A. Harris, Stephanie M. McClure.',
       "Giovanni's room / James Baldwin.",
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Globalization of education : an introduction / Joel Spring.',
       "Good to great [electronic resource] : Why some companies make the leap...and others don't. Jim Collins.",
       'Government and Politics in Tennessee [electronic resource].',
       'Guide to the vascular plants of Tennessee / compiled and edited by members of the Tennessee Flora Committee.',
       'Hands-on large language models [electronic resource] : language understanding and generation / Jay Alammar and Maarten Grootendorst.',
       'Head off & split [electronic resource] : poems / Nikky Finney.',
       'Herland / Charlotte Perkins Gilman.',
       'Hey Whipple, Squeeze This : The Classic Guide to Creating Great Advertising.',
       'Hey Whipple, squeeze this :  the classic guide to creating great advertising /  by Luke Sullivan ; foreword by Anselmo Ramos.',
       'High fidelity [electronic resource] / Nick Hornby.',
       'How great leaders think : the art of reframing',
       'How to Do Critical Discourse Analysis : A Multimodal Introduction.',
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'Information Architecture for the World Wide Web : Designing Large-Scale Web Sites.',
       'Information architecture for the World Wide Web : designing large-scale web sites / Peter Morville, Louis Rosenfeld.',
       'Information science : the basics / Judith Pintar and David Hopping.',
       'Integrating Program Management and Systems Engineering : Methods, Tools and Organizational Systems for Improving Performance.',
       'Integrating program management and systems engineering : methods, tools, and organizational systems for improving performance / Eric S. Rebentisch, editor ; with foreword by Larry Prusak.',
       'International trade and agriculture [electronic resource] / Won W. Koo and P. Lynn Kennedy.',
       'Interpersonal communication : putting theory into practice / Denise Solomon, Jennifer Theiss.',
       'Introduction to Algorithms / Thomas H. Cormen [and three others].',
       'Introduction to deaf culture / Thomas K. Holcomb.',
       'Introduction to industrial organization. / Luis M.B. Cabral.',
       'Invisible child : poverty, survival & hope in an American city / Andrea Elliott.',
       'John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights / Brandon K. Winford.',
       'Johns Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals: Model & Guidelines [electronic resource].',
       'Just practice : a social justice approach to social work / Janet L. Finn.',
       "Karl Marx's theory of history : a defence / G. A. Cohen.",
       "King of the North : Martin Luther King's life of struggle outside the South / Jeanne Theoharis.",
       'Language vs. reality : why language is good for lawyers and bad for scientists / N.J. Enfield.',
       "Leaders eat last : why some teams pull together and others don't / Simon Sinek.",
       'Lean Production for Competitive Advantage : A Comprehensive Guide to Lean Methodologies and Management Practices, Second Edition.',
       'Listening to war : sound, music, trauma and survival in wartime Iraq / J. Martin Daughtry.',
       'Manufacturing Facilities Design & Material Handling : Sixth Edition.',
       'Materials and Sustainable Development / M. F. Ashby.',
       'Measurement and detection of radiation / Nicholas Tsoulfanidis, Sheldon Landsberger.',
       'Mental health case management : a practical guide / Shaun M. Eack, Carol M. Anderson, Catherine G. Greeno.',
       'Mere Christianity : a revised and amplified edition, with a new introduction, of the three books, Broadcast talks, Christian behaviour, and Beyond personality / C. S. Lewis.',
       'Metadata / Marcia Lei Zeng, Jian Qin.', 'Metadata.',
       'Metaracism : how systemic racism devastates Black lives--and how we break free / Tricia Rose.',
       'Milk and filth [electronic resource] / Carmen Gimenez Smith.',
       'Mindset : the new psychology of success / Carol S. Dweck.',
       'Modern nuclear chemistry [electronic resource] / Walter D. Loveland, David J. Morrissey, Glenn T. Seaborg.',
       "Morgan & Mikhail's Clinical Anesthesiology [electronic resource] / John F. Butterworth IV, David C. Mackey, John D. Wasnick.",
       'Movements in organizational communication research : current issues and future directions / edited by Jamie McDonald, Rahul Mitra.',
       'Multilevel modeling : applications in STATA®, IBM® SPSS®, SAS®, R, & HLM™ / G. David Garson.',
       'Multimedia environmental models : the fugacity approach / Donald Mackay, Mark Parnis.',
       'Narrative of the life of Frederick Douglass, an American slave / written by himself ; introduction by Robert B. Stepto.',
       'Native nations : a millennium in North America / Kathleen DuVal.',
       'New kid [electronic resource]. Jerry Craft.',
       'Next steps : decision cases for social work practice / Lori D. Franklin, Jonathan R. Kratz, and Karen A. Gray.',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke / W. Julian Korab-Karpowicz.',
       "Ortner's identification of pathological conditions in human skeletal remains / edited by Jane E. Buikstra.",
       'Passing.', 'Persuasion [electronic resource].',
       'Phenomenology : a contemporary introduction / Walter Hopp.',
       'Pitch, tweet, or engage on the street : how to practice global public relations and strategic communication.',
       'Planetary geology [electronic resource] : an introduction.',
       'Planning for play, observation, and learning in preschool and kindergarten / Gaye Gronlund.',
       'Population health [electronic resource] : concepts and methods / T. Kue Young.',
       'Practical Implementation in Social Work Practice : A Guide to Engaging in Evidence-Based Practice.',
       'Preschool in three cultures : Japan, China, and the United States / Joseph J. Tobin, David Y.H. Wu, Dana H. Davidson.',
       'Principles and methods of social research / William D. Crano, Marilynn B. Brewer, Andrew Lac.',
       'Probability: A Graduate Course [electronic resource] / by Allan Gut.',
       'Property of the Rebel Librarian [electronic resource] / Allison Varnes.',
       'Public libraries and their communities : an introduction / Kay Ann Cassell.',
       'Public speaking for engineers : communicating effectively with clients, the public, and local government / by Christopher A. "Shoots" Veis, P.E. ; foreword by Mark W. Woodson, P.E., L.S., D. WRE.',
       'Pursuing happiness [electronic resource] : a Bedford spotlight reader / [compiled and edited by] Matthew Parfitt, Boston University, Dawn Skorczewski, Brandeis University.',
       'R for political science research : an introduction for absolute beginners / Jane L. Sumner.',
       'Racial theories in social science : a systemic racism critique / Sean Elias and Joe R. Feagin.',
       'Radiation biophysics / Edward L. Alpen.',
       'Red Book : 2024-2027 Report of the Committee on Infectious Diseases.',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases / author: Committee on Infectious Diseases, American Academy of Pediatrics; David W. Kimberlin, MD, FAAP, editor; Ritu Banerjee, MD, PhD, FAAP, Elizabeth D. Barnett, MD, FAAP, Ruth Lynfield, MD, FAAP, Mark H. Sawyer, MD, FAAP, associate editor.',
       'Research ethics for scientists [electronic resource] : a companion for students.',
       'Sales force management : leadership, innovation, technology / Mark W. Johnston, Greg W. Marshall, and Jessica L. Ogilvie.',
       'Sanford Meisner on acting / Sanford Meisner and Dennis Longwell ; introduction by Sydney Pollack.',
       'School social work : a skills-based competency approach / JoDee Keller, PhD, LICSW Department of Social Work, Professor of Social Work Pacific Lutheran University.',
       'Sexuality in Medieval Europe : doing unto others / Ruth Mazo Karras and Katherine E. Pierpont.',
       'Shaping a science of social work : professional knowledge and identity / edited by John Brekke and Jeane Anastas.',
       'Shokyū Nihongo genki. I, Wākubukku = Genki : an integrated course in elementary Japanese. I, Workbook / Eri Banno [and 4 others].',
       'Skill acquisition in sport : research, theory and practice / edited by Nicola J. Hodges and A. Mark Williams.',
       'Social welfare policy for a sustainable future : the U.S. in global context / Katherine S. van Wormer, Rosemary J. Link.',
       'Social work values and ethics / Frederic G. Reamer.',
       'Song walking : women, music, and environmental justice in an African borderland / Angela Impey.',
       'Statistical mechanics / Donald A. McQuarrie.',
       "Stoelting's pharmacology & physiology in anesthetic practice [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman",
       'Strategic Healthcare Management : Planning and Execution.',
       'Strategic Planning for Public Relations.',
       'Strategy in 3D : essential tools to diagnose, decide, & deliver / Greg Fisher, John E. Wisneski, Rene M. Bakker.',
       'SuperCollider for the creative musician : a practical guide / Eli Fieldsteel.',
       'Supply chain transformation : building and executing an integrated supply chain strategy / J. Paul Dittmann.',
       'System engineering management / Benjamin S. Blanchard, John Blyler.',
       'Teaching Adult Learners : A Guide for Public Librarians.',
       'Teaching and assessing social justice art education : power, politics, and possibilities / Karen Keifer-Boyd [and more].',
       'Teeth : the story of beauty, inequality, and the struggle for oral health in America / Mary Otto.',
       'Tell It Slant, Third Edition, 3rd Edition / Miller, Brenda.',
       'Tell it slant : creating, refining, and publishing creative nonfiction / Brenda Miller and Suzanne Paola.',
       'The BRICs and emerging economies in comparative perspective : political economy, liberalisation and institutional change / edited by Uwe Becker.',
       "The Black fives : the epic story of basketball's forgotten era / Claude Johnson.",

### Expand the ISBN Normalized Column

In [25]:
resultsPlusList['ISBN (Normalized) List'] = resultsPlusList['ISBN (Normalized)'].apply(lambda x: x.split(";"))

In [26]:
expandedList = resultsPlusList.explode('ISBN (Normalized) List')

expandedList['ISBN (Normalized) List'] = expandedList['ISBN (Normalized) List'].str.strip()

#expandedList.to_excel('Expanded List Example.xlsx')

In [27]:
finalJoin = pd.merge(expandedList, bookstoreList, left_on = 'ISBN (Normalized) List', right_on = 'ISBN', how = 'inner')

finalJoin = finalJoin.rename(columns = {'Short Title_y': 'Short Title'})

finalJoin

,Title_x,Alternate Graphic Representation,Type,Creator / Imprint,Subject,Series,Relation,Modification Date,Edition,Uniform Title,Medium Type,Language,Creation Date,Language of Cataloging,ISBN_x,ISBN (13),ISSN,Cluster ISSN,Record Number,MMS ID,Bibliographic Rank,Local Call Number,Other Classification Number,NLM Call Number,Dewey Decimal Classification Number,LC Call Number,Classification Part,UDC Classification Number,NAL Call Number,Handle Identifier,Peer Reviewed,Open Access,Physical Availability,Digital Availability,Electronic Availability,Collection Name,Collection ID,Orders,Requests,Physical Description Extent,Local Labels,Related Records,Courses,Licenses,Reminders,Notes,Short Title_x,Electronic location and access,ISBN (Normalized),ISBN_y,MMS Id,Title_y,Electronic Collection Public Name,Availability,Portfolio Id,Portfolio Public Note,No. of Available Portfolio,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes,ISBN (Normalized) List,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity
0,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...,9781420095241,Fall 2026,BIOMEDICAL ENGINEERING,202640-BME.529.002-46165,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30
1,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...,9781420095241,Fall 2026,CHEMICAL AND BIOMOLECULAR ENGINEERING,202640-CBE.529.002-46170,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30
2,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...,9781420095241,Fall 2026,ELECTRICAL AND COMPUTER SCIENCE,202640-ECE.529.002-46166,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30
3,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...,9781420095241,Fall 2026,ENVIRONMENTAL ENGINEERING,202640-ENVE.529.002-48495,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30
4,Advanced linear algebra for engineers with MAT...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dianat, Sohail A. (Boca Raton, FL : CRC Press,...","MATLAB.;Mathematics.;Algebras, Linear.;Matrice...",NaN,NaN,2023-11-30 18:06:00,NaN,NaN,NaN,English,2016-02-23 12:00:00,NaN,9781420095241 (electronic bk.); 1420095242 (el...,9781420095241 (electronic bk.); 9781420095241 ...,NaN,NaN,99966244344; (NhCcYBP)ybp11138830,9925403550002311,89,NaN,*00A06 and others,NaN,620.001/51,QA184.2 .D53 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xviii, 345 pages) :",NaN,1,0,0,0,0,Advanced linear algebra for engineers with MATLAB,https://www.taylorfrancis.com/books/9781420095...,1420095242; 9781420095241; 1420095234; 9781420...,1420095242; 9781420095241; 1420095234; 9781420...,9925403550002311,Advanced linear algebra for engineers with MATLAB,CRCnetBASE Complete,Available,53265253610002311,NaN,0,NaN,[https://www.taylorfrancis.com/books/978142009...,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,https://www.taylorfrancis.com/books/9781420095...,9781420095241,Fall 2026,INDUSTRIAL ENGINEERING,202640-IE.529.002-46167,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,Trauma counseling : theories and interventions...,NaN,Book {Book - Electronic} text; computer; onlin...,"López Levers, Lisa (New York, NY : Springer Pu...",Psychic trauma--Treatment.;Wounds and injuries...,NaN,NaN,2026-04-15 08:28:00,Second edition.,NaN,NaN,English,2026-02-02 11:07:00,English,9780826150851; 0826150853; 9780826150851 (EBSC...,9780826150851; 9780826150851; 9780826150851 (E...,NaN,NaN,(OCoLC)1298514014; (OCoLC)cis063794753,9926868740402311,101,NaN,NaN,NaN,362.1/04256,RC552.P67 L475 2023eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xxvi, 550 pages) :",NaN,0,0,0,0,0,Trauma counseling :,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...,9780826150844,Fall 2026,SOCIAL WORK,202640-SOWK.531.001-46722,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",10
698,Trauma counseling : theories and interventions...,NaN,Book {Book - Electronic} text; computer; onlin...,"López Levers, Lisa (New York, NY : Springer Pu...",Psychic trauma--Treatment.;Wounds and injuries...,NaN,NaN,2026-04-15 08:28:00,Second edition.,NaN,NaN,English,2026-02-02 11:07:00,English,9780826150851; 0826150853; 9780826150851 (EBSC...,9780826150851; 9780826150851; 9780826150851 (E...,NaN,NaN,(OCoLC)1298514014; (OCoLC)cis063794753,9926868740402311,101,NaN,NaN,NaN,362.1/04256,RC552.P67 L475 2023eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xxvi, 550 pages) :",NaN,0,0,0,0,0,Trauma counseling :,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...,9780826150844,Fall 2026,SOCIAL WORK,202640-SOWK.531.002-56742,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",3
699,Trauma counseling : theories and interventions...,NaN,Book {Book - Electronic} text; computer; onlin...,"López Levers, Lisa (New York, NY : Springer Pu...",Psychic trauma--Treatment.;Wounds and injuries...,NaN,NaN,2026-04-15 08:28:00,Second edition.,NaN,NaN,English,2026-02-02 11:07:00,English,9780826150851; 0826150853; 9780826150851 (EBSC...,9780826150851; 9780826150851; 9780826150851 (E...,NaN,NaN,(OCoLC)1298514014; (OCoLC)cis063794753,9926868740402311,101,NaN,NaN,NaN,362.1/04256,RC552.P67 L475 2023eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xxvi, 550 pages) :",NaN,0,0,0,0,0,Trauma counseling :,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...,9780826150844,Fall 2026,SOCIAL WORK,202640-SOWK.531.101-52230,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",2
700,True north : leading authentically in today's ...,NaN,Book {Book - Electronic} text; computer; onlin...,"George, Bill (Hoboken, New Jersey : Wiley, [20...",Leadership.;Organizational effectiveness.,NaN,NaN,2026-03-27 13:11:00,Emerging leader edition.,NaN,NaN,English,2022-08-28 05:20:00,English,9781119886112; 1119886112; 9781119886129; 1119...,9781119886112; 9781119886112; 9781119886129; 9...,NaN,NaN,(MiAaPQ)EBC7077658; (Au-PeEL)EBL7077658; (CKB)...,9926909582702311,95,NaN,NaN,NaN,658.4092,HD57.7 .G467 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (323 pages),NaN,0,0,0,0,0,True north :,NaN,1119886112; 9781119886112; 1119886120; 9781119...,1119886112; 9781119886112; 1119886120; 9781119...,9926909582702311,True north : leading authentically in today's ...,O'Reilly Online Learning: Academic/Public Libr...,Available,53452603080002311,NaN,1,NaN,NaN,NaN,NaN,,9781119886112,Fall 2026,BUSINESS ADMINISTRATION,202640-BUAD.217.001-44744,"Rittenhouse, Jennifer",9781119886112,"TRUE NORTH, EMERGING LEADER EDITION : LEADING ...","GEORGE, BILL AND CLAYTON, ZACH","WILEY & SONS, INCORPORATED, JOHN",27
701,Video field production and editing / Ronald J....,NaN,Book {Book - Electronic} text; computer; onlin...,"Compesi, Ronald J., (New York ; London : Routl...",Television--Production and direction.;Video re...,NaN,NaN,2026-07-21 03:42:00,Eighth edition.,NaN,NaN,English,2019-03-10 11:04:00,English,0-429-50593-0; 0-429-00033-2; 0-429-00032-4; 9...,9780429505935; 9780429000331; 9780429000324; 9...,NaN,NaN,(CKB)4100000007741523; (MiAaPQ)EBC5716876; (Ca...,9926910284202311,95,NaN,NaN,NaN,791.4502/32,PN1992.75 .C667 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (303 pages),NaN,0,0,0,0,0,Video field production and editing /,NaN,0429000332; 9780429000331; 0429000324; 9780429...,0429000332; 9780429000331; 0429000324; 9780429...,9926910284202311,Video field production and editing /,O'Reilly Online Learning: Academic/Public Libr...,Available,53452820550002311,NaN,1,NaN,NaN,NaN,NaN,,9780429000324,Fall 2026,JOURNALISM AND MEDIA,202640-JMED.436.001-57630,"Santos, Timothy",9780429000324,VIDEO FIELD PRODUCTION AND EDITING,"COMPESI, RONALD J.",ROUTLEDGE,20

In [28]:
selectiveCols = finalJoin[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN (Normalized) List', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Electronic location', 'Electronic access', 'Electronic Availability']]

selectiveCols = selectiveCols.drop_duplicates().reset_index()

selectiveCols = selectiveCols.rename(columns = {'Section Code': 'Course Code'})

len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

228

In [29]:
selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique()

array(['58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES FOR DIVERSE DEAF STUDENTS',
       'A COMPANION TO PALEOPATHOLOGY',
       'A COURSE IN MATHEMATICAL MODELING',
       'A HISTORY OF MODERN LINGUISTICS : FROM THE BEGINNINGS TO WORLD WAR II',
       'A HISTORY OF RELIGION IN 5? OBJECTS : BRINGING THE SPIRITUAL TO ITS SENSES',
       'A HISTORY OF THE AMERICAN MUSICAL THEATRE',
       'ACHILLES IN VIETNAM : COMBAT TRAUMA AND THE UNDOING OF CHARACTER',
       'ACT MADE SIMPLE : AN EASY-TO-READ PRIMER ON ACCEPTANCE AND COMMITMENT THERAPY',
       'ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB',
       'AFFIRMING DISABILITY : STRENGTHS-BASED PORTRAITS OF CULTURALLY DIVERSE FAMILIES',
       'AFTER APPOMATTOX : MILITARY OCCUPATION AND THE ENDS OF WAR',
       'ALGEBRA', 'AN INTRODUCTION TO APPLIED BEHAVIORAL NEUROSCIENCE',
       'AN INTRODUCTION TO MATHEMATICAL EPIDEMIOLOGY',
       'AN INTRODUCTION TO SYSTEM MODELING AND CONTROL',
       'ANCIENT GREEK RELIGION',
       'APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS',
       'APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : CONCEPTS AND CASES',
       'ART EDUCATION FOR A SUSTAINABLE PLANET : EMBRACING ECOPEDAGOGY IN K-12 CLASSROOMS',
       'ARTIFICIAL INTELLIGENCE FOR CYBERSECURITY',
       'BANKING ON FREEDOM : BLACK WOMEN IN U. S. FINANCE BEFORE THE NEW DEAL',
       "BECAUSE OF SEX : ONE LAW, TEN CASES, AND FIFTY YEARS THAT CHANGED AMERICAN WOMEN'S LIVES AT WORK",
       'BECOMING A DATA HEAD : HOW TO THINK, SPEAK, AND UNDERSTAND DATA SCIENCE, STATISTICS, AND MACHINE LEARNING',
       'BELOVED', 'BESTIARY', 'BIOMATERIALS SCIENCE', 'BLACK BEAUTY',
       'BLEAK HOUSE', 'BLUEST EYE', 'BUSINESS ETHICS',
       'BUY BLACK : HOW BLACK WOMEN TRANSFORMED US POP CULTURE',
       'CARCERAL CON : THE DECEPTIVE TERRAIN OF CRIMINAL JUSTICE REFORM',
       'CASE STUDIES IN DEAF EDUCATION : INQUIRY, APPLICATION, AND RESOURCES',
       'CEREMONY', 'CHIEF SUSTAINABILITY OFFICERS AT WORK',
       'CLINGING TO MAMMY : THE FAITHFUL SLAVE IN TWENTIETH-CENTURY AMERICA',
       'COGNITIVE BEHAVIOR THERAPY : BASICS AND BEYOND',
       'COMPARATIVE EDUCATION : THE DIALECTIC OF THE GLOBAL AND THE LOCAL',
       'CONTROVERSIES IN CONTEMPORARY ADVERTISING',
       'CONVERSATIONS WITH FAMILIES OF CHILDREN WITH DISABILITIES',
       'CRACK : ROCK COCAINE, STREET CAPITALISM, AND THE DECADE OF GREED',
       'CRACKED NOT BROKEN',
       'CRIMINOLOGICAL THEORY : AN ANALYSIS OF ITS UNDERLYING ASSUMPTIONS',
       'CUSTOMER EXPERIENCE 3. 0 : HIGH-PROFIT STRATEGIES IN THE AGE OF TECHNO SERVICE',
       'DANCING WITH THE DEVIL : WHY BAD FEELINGS MAKE LIFE GOOD',
       'DEAF CULTURE : EXPLORING DEAF COMMUNITIES IN THE UNITED STATES',
       'DEAF PEOPLE AND SOCIETY : PSYCHOLOGICAL, SOCIOLOGICAL, AND EDUCATIONAL PERSPECTIVES',
       'DEBATING REFORM : CONFLICTING PERSPECTIVES',
       'DEMOCRACY FOR REALISTS : WHY ELECTIONS DO NOT PRODUCE RESPONSIVE GOVERNMENT',
       'DESIGN : HISTORY, THEORY AND PRACTICE OF PRODUCT DESIGN',
       'DESIGN EDUCATION : CREATING THINKERS TO IMPROVE THE WORLD',
       'DIFFERENTIAL EQUATIONS, DYNAMIC SYS & INTRO TO CHAOS',
       "DISCIPLINARY AND CONTENT LITERACY FOR TODAY'S ADOLESCENTS : HONORING DIVERSITY AND BUILDING COMPETENCE",
       'EARLY MUSIC : A VERY SHORT INTRODUCTION',
       'ECONOMETRIC ANALY OF CROSS SECT & P',
       'EDUCATIONAL AND PSYCHOLOGICAL MEASUREMENT',
       'ELEMENTS OF MATHEMATICAL ECOLOGY (FREE DIGITAL AVAILABLE FROM UTK LIBRARY)',
       'ENGAGED ANTHROPOLOGY : POLITICS BEYOND THE TEXT',
       'ENGINEERING DESIGN: A PROJECT-BASED INTRODUCTION',
       'ENVIROMEDICS : THE IMPACT OF CLIMATE CHANGE ON HUMAN HEALTH',
       'ETHICS OF DATA AND ANALYTICS',
       'EVALUATION AND MEASUREMENT OF LIBRARY SERVICES', 'EVICTED',
       'EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING EVIDENCE-BASED PRACTICE AND QUALITY IMPROVEMENT',
       'EXACTLY HOW TO SELL : THE SALES GUIDE FOR NON-SALES PROFESSIONALS',
       "EXPERIENCING DESIGN : THE INNOVATOR'S JOURNEY",
       'FACILITATING BREAKTHROUGH : HOW TO REMOVE OBSTACLES, BRIDGE DIFFERENCES, AND MOVE FORWARD TOGETHER&NBSP;',
       'FIELDS AND STREAMS : STREAM RESTORATION, NEOLIBERALISM, AND THE FUTURE OF ENVIRONMENTAL SCIENCE',
       'FIGHTING AGAINST INJUSTICE OF STATE',
       'FINANCIAL AND BUSINESS MANAGEMENT FOR THE DOCTOR OF NURSING PRACTICE',
       'FINDING THE MOTHER TREE : DISCOVERING THE WISDOM OF THE FOREST',
       'FISHING THROUGH THE APOCALYPSE',
       "FLEISHER AND LUDWIG'S TEXTBOOK OF PEDIATRIC EMERGENCY MEDICINE",
       'FOCUS ON DEVELOPMENTALLY APPROPRIATE PRACTICE',
       'FORENSIC ANTHROPOLOGY : AN INTRODUCTORY LAB MANUAL',
       'FORMS : WHOLE, RHYTHM, HIERARCHY, NETWORK',
       'FUN HOME : A FAMILY TRAGICOMIC', 'FUNDAMENTALS OF GAS DYNAMICS',
       'FUNDAMENTALS OF PHYSICS II : ELECTROMAGNETISM, OPTICS, AND QUANTUM MECHANICS',
       "GEMINOS'S INTRODUCTION TO THE PHENOMENA : A TRANSLATION AND STUDY OF A HELLENISTIC SURVEY OF ASTRONOMY",
       'GENKI: AN INTEGRATED COURSE IN ELEMENTARY JAPANESE I TEXTBOOK [THIRD EDITION]',
       'GETTING REAL ABOUT INEQUALITY : INTERSECTIONALITY IN REAL LIFE',
       "GIOVANNI'S ROOM",
       'GLOBAL WRITING FOR PUBLIC RELATIONS : CONNECTING IN ENGLISH WITH STAKEHOLDERS AND PUBLICS WORLDWIDE',
       'GLOBALIZATION OF EDUCATION', 'GOOD TO GREAT',
       'GOVERNMENT AND POLITICS IN TENNESSEE',
       'GUIDE TO THE VASCULAR PLANTS OF TENNESSEE',
       'HANDS-ON LARGE LANGUAGE MODELS : LANGUAGE UNDERSTANDING AND GENERATION',
       'HAUNTING OF HILL HOUSE', 'HEAD OFF & SPLIT', 'HERLAND',
       'HEY WHIPPLE, SQUEEZE THIS',
       'HEY WHIPPLE, SQUEEZE THIS : THE CLASSIC GUIDE TO CREATING GREAT ADVERTISING',
       'HIGH FIDELITY', 'HOW GREAT LEADERS THINK : THE ART OF REFRAMING',
       'HOW TO DO CRITICAL DISCOURSE ANALYSIS : A MULTIMODAL INTRODUCTION',
       'HUMAN OSTEOLOGY',
       'INFORMATION ARCHITECTURE FOR THE WORLD WIDE WEB',
       'INFORMATION SCIENCE : THE BASICS',
       'INTEGRATING PROGRAM MANAGEMENT AND SYSTEMS ENGINEERING',
       'INTERNATIONAL TRADE AND AGRICULTURE : THEORIES AND PRACTICES',
       'INTERPERSONAL COMMUNICATION',
       'INTRODUCTION TO ALGORITHMS, FOURTH EDITION',
       'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'INTRODUCTION TO INDUSTRIAL ORGANIZATION, SECOND EDITION',
       'INVISIBLE CHILD : POVERTY, SURVIVAL AND HOPE IN AN AMERICAN CITY (PULITZER PRIZE WINNER)',
       'JOHN HERVEY WHEELER BLACK BANKING AND THE ECONOMIC STRUGGLE FOR CIVIL RIGHTS',
       'JOHNS HOPKINS EVIDENCE-BASED PRACTICE MODEL',
       'JUST PRACTICE: A SOCIAL JUSTICE APPROACH TO SOCIAL WORK',
       "KARL MARX'S THEORY OF HISTORY",
       "KING OF THE NORTH : MARTIN LUTHER KING JR. 'S LIFE OF STRUGGLE OUTSIDE THE SOUTH",
       'LANGUAGE INSTINCT',
       'LANGUAGE VS. REALITY : WHY LANGUAGE IS GOOD FOR LAWYERS AND BAD FOR SCIENTISTS',
       "LEADERS EAT LAST : WHY SOME TEAMS PULL TOGETHER AND OTHERS DON'T",
       'LEAN PRODUCTION FOR COMPETITIVE ADVANTAGE : A COMPREHENSIVE GUIDE TO LEAN METHODOLOGIES AND MANAGEMENT PRACTICES, SECOND EDITION',
       'LISTENING TO WAR',
       'MANUFACTURING FACILITIES DESIGN AND MATERIAL HANDLING : SIXTH EDITION',
       'MATERIALS AND SUSTAINABLE DEVELOPMENT',
       'MEASUREMENT AND DETECTION OF RADIATION',
       'MENTAL HEALTH CASE MANAGEMENT', 'MERE CHRISTIANITY', 'METADATA',
       'METARACISM : HOW SYSTEMIC RACISM DEVASTATES BLACK LIVES--AND HOW WE BREAK FREE',
       'MILK AND FILTH', 'MINDSET : THE NEW PSYCHOLOGY OF SUCCESS',
       'MODERN NUCLEAR CHEMISTRY',
       "MORGAN AND MIKHAIL'S CLINICAL ANESTHESIOLOGY, SEVENTH EDITION",
       'MOVEMENTS IN ORGANIZATIONAL COMMUNICATION RESEARCH',
       'MOVEMENTS IN ORGANIZATIONAL COMMUNICATION RESEARCH : CURRENT ISSUES AND FUTURE DIRECTIONS',
       'MULTILEVEL MODELING : APPLICATIONS IN STATA?, IBM? SPSS?, SAS?, R, AND HLM(TM)',
       'MULTIMEDIA ENVIRONMENTAL MODELS : THE FUGACITY APPROACH',
       'NARRATIVE OF THE LIFE OF FREDERICK DOUGLASS',
       'NATIVE NATIONS : A MILLENNIUM IN NORTH AMERICA', 'NEW JIM CROW',
       'NEW KID', 'NEXT STEPS : DECISION CASES FOR SOCIAL WORK PRACTICE',
       'ON THE HISTORY OF POLITICAL PHILOSOPHY : GREAT POLITICAL THINKERS FROM THUCYDIDES TO LOCKE',
       "ORTNER'S IDENTIFICATION OF PATHOLOGICAL CONDITIONS (FREE DIGITAL ACCESS- UTK LIBRARY)",
       'OXFORD SOLID STATE BASICS', 'PASSING',
       'PERSUASION, A NORTON CRITICAL EDITION', 'PHENOMENOLOGY',
       'PITCH, TWEET, OR ENGAGE ON THE STREET',
       'PLANETARY GEOLOGY : AN INTRODUCTION',
       'PLANNING FOR PLAY, OBSERVATION, AND LEARNING IN PRESCHOOL AND KINDERGARTEN',
       'POPULATION HEALTH : CONCEPTS AND METHODS',
       'PRACTICAL IMPLEMENTATION IN SOCIAL WORK PRACTICE : A GUIDE TO ENGAGING IN EVIDENCE-BASED PRACTICE',
       'PRESCHOOL IN THREE CULTURES : JAPAN, CHINA AND THE UNITED STATES',
       'PRINCIPLES AND METHODS OF SOCIAL RESEARCH',
       'PROBABILITY, A GRADUATE COURSE (FREE DIGITAL ACCESS- UTK LIBRARY)',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PUBLIC LIBRARIES AND THEIR COMMUNITIES',
       'PUBLIC SPEAKING FOR ENGINEERS : COMMUNICATING EFFECTIVELY WITH CLIENTS, THE PUBLIC, AND LOCAL GOVERNMENT',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'R FOR POLITICAL SCIENCE RESEARCH : AN INTRODUCTION FOR ABSOLUTE BEGINNERS',
       'RACIAL THEORIES IN SOCIAL SCIENCE', 'RADIATION BIOPHYSICS',
       'RED BOOK 2024 : REPORT OF THE COMMITTEE ON INFECTIOUS DISEASES',
       'RESEARCH ETHICS FOR SCIENTISTS : A COMPANION FOR STUDENTS',
       'SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATION, TECHNOLOGY',
       'SANFORD MEISNER ON ACTING', 'SCHOOL SOCIAL WORK',
       'SEXUALITY IN MEDIEVAL EUROPE : DOING UNTO OTHERS',
       'SHAPING A SCIENCE OF SOCIAL WORK : PROFESSIONAL KNOWLEDGE AND IDENTITY',
       'SKILL ACQUISITION IN SPORT : THEORY AND PRACTICE',
       'SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE',
       'SOCIAL WORK VALUES AND ETHICS',
       'SONG WALKING : WOMEN, MUSIC, AND ENVIRONMENTAL JUSTICE IN AN AFRICAN BORDERLAND',
       'SOULS OF BLACK FOLKS', 'STATISTICAL MECHANICS',
       "STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANESTHETIC PRACTICE",
       'STRATEGIC HEALTHCARE MANAGEMENT: PLANNING AND EXECUTION, SECOND EDITION',
       'STRATEGIC PLANNING FOR PUBLIC RELATIONS', 'STRATEGY IN 3D',
       'STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, DECIDE, AND DELIVER',
       'SUN ALSO RISES', 'SUPERCOLLIDER FOR THE CREATIVE MUSICIAN',
       'SUPPLY CHAIN TRANSFORMATION: BUILDING AND EXECUTING AN INTEGRATED SUPPLY CHAIN STRATEGY',
       'SYSTEM ENGINEERING MANAGEMENT',
       'TEACHING ADULT LEARNERS : A GUIDE FOR PUBLIC LIBRARIANS',
       'TEACHING AND ASSESSING SOCIAL JUSTICE ART EDUCATION : POWER, POLITICS, AND POSSIBILITIES',
       'TEETH : THE STORY OF BEAUTY, INEQUALITY, AND THE STRUGGLE FOR ORAL HEALTH IN AMERICA',
       'TELL IT SLANT, THIRD EDITION',
       'THE ART OF THE PITCH : PERSUASION AND PRESENTATION SKILLS THAT WIN BUSINESS',
       'THE BEAST WITHIN : ANIMALS IN THE MIDDLE AGES',
       "THE BLACK FIVES : THE EPIC STORY OF BASKETBALL'S FORGOTTEN ERA",
       'THE BROTHERS KARAMAZOV', 'THE CALL OF THE WILD',
       'THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY VETERINARY SOCIAL WORK',
       'THE CONSTITUTION OF LIBERTY : THE DEFINITIVE EDITION',
       'THE CRAFT OF RESEARCH, FIFTH EDITION', 'THE CRUCIBLE',
       'THE FIVE DYSFUNCTIONS OF A TEAM : A LEADERSHIP FABLE, 20TH ANNIVERSARY EDITION',
       "THE FOREST UNSEEN : A YEAR'S WATCH IN NATURE",
       'THE FUTURE OF AN ILLUSION', 'THE GRAPES OF WRATH',
       'THE GREAT DEBATE',
       "THE HISTORIAN'S TOOLBOX : A STUDENT'S GUIDE TO THE THEORY AND CRAFT OF HISTORY",
       'THE ISLAND OF DOCTOR MOREAU',
       'THE LICIT LIFE OF CAPITALISM : US OIL IN EQUATORIAL GUINEA',
       'THE MUSEUM OF UNNATURAL HISTORIES',
       'THE NEW JIM CROW : MASS INCARCERATION IN THE AGE OF COLORBLINDNESS',
       'THE PORTABLE FEMINIST READER',
       'THE PRACTICE OF ADAPTIVE LEADERSHIP',
       'THE PRACTICE OF ADAPTIVE LEADERSHIP : TOOLS AND TACTICS FOR CHANGING YOUR ORGANIZATION AND THE WORLD',
       'THE RETURN OF THE SOLDIER',
       'THE RHETORICAL PRESIDENCY : NEW EDITION',
       'THE THEORY AND PRACTICE OF GROUP PSYCHOTHERAPY',
       'THINK PYTHON : HOW TO THINK LIKE A COMPUTER SCIENTIST',
       'THINKING IN SYSTEMS',
       'TRANSPORT MODELING FOR ENVIRONMENTAL ENGINEERS AND SCIENTISTS',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER',
       "TRUE NORTH, EMERGING LEADER EDITION : LEADING AUTHENTICALLY IN TODAY'S WORKPLACE",
       'UNIVERSITY PHYSICS VOLUME 3',
       'UNTIL WE RECKON : VIOLENCE, MASS INCARCERATION, AND A ROAD TO REPAIR',
       'USING STATISTICAL METHODS IN SOCIAL SCIENCE RESEARCH : WITH A COMPLETE SPSS GUIDE',
       'VERSIFICATION(OP)(FREE DIGITAL ACCESS-UTK LIBRARY)',
       'VIDEO FIELD PRODUCTION AND EDITING', 'WATER CHEMISTRY',
       'WHAT REALLY WORKS WITH EXCEPTIONAL LEARNERS',
       'WHERE RIVERS AND MOUNTAINS SING : SOUND, MUSIC, AND NOMADISM IN TUVA AND BEYOND',
       'WHY PEOPLE DIE BY SUICIDE', 'WHY WE LOST THE ERA',
       'WKBK T/A GENKI I', 'WOMAN WARRIOR',
       'WRITING LITERATURE REVIEWS : A GUIDE FOR STUDENTS OF THE SOCIAL AND BEHAVIORAL SCIENCES',
       'WRITING SCIENCE : HOW TO WRITE PAPERS THAT GET CITED AND PROPOSALS THAT GET FUNDED'],
      dtype=object)

## 12. Use the code block below to edit information in the VolBooks file as needed

This should be done when a title has multiple holdings in our collections, but only one fits the criteria for VolBooks submission. Coding it here will save manual editing time later.

In [30]:
selectiveCols.to_excel('Selective Cols Check.xlsx')

In [31]:
for i in range(selectiveCols.shape[0]):
    if selectiveCols.at[i, 'Short Title'] == '58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES FOR DIVERSE DEAF STUDENTS':
        selectiveCols.at[i, 'MMS ID'] = '9926829233602311'
        selectiveCols.at[i, 'Access_Type'] = 'Unlimited Access Unlimited Access'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at JSTOR; JSTOR Ebooks (JSTOR Rialto Implementation); Full Text; Available; 53441315590002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926829233602311'
  
    if selectiveCols.at[i, 'Short Title'] == 'SKILL ACQUISITION IN SPORT : THEORY AND PRACTICE':
        selectiveCols.at[i, 'MMS ID'] = '9925871824802311'
        selectiveCols.at[i, 'Access_Type'] = 'Online Access - Unlimited users (DRM-free)'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at Taylor & Francis; Taylor & Francis Ebooks (Taylor & Francis Ebooks Individually Purchased); Full Text; Available; 53323272990002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9925871824802311'
 
    if selectiveCols.at[i, 'Short Title'] == 'THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY VETERINARY SOCIAL WORK':
        selectiveCols.at[i, 'MMS ID'] = '9926829231602311'
        selectiveCols.at[i, 'Access_Type'] = 'Unlimited Access Unlimited Access'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at Springer Nature; Springer Ebooks (Springer Ebooks Individually Purchased); Full Text; Available; 53433284910002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926829231602311'

    if selectiveCols.at[i, 'Short Title'] == 'CHIEF SUSTAINABILITY OFFICERS AT WORK':
        selectiveCols.at[i, 'MMS ID'] = '9926909978602311'
        selectiveCols.at[i, 'Access_Type'] = ''
        selectiveCols.at[i, 'Electronic Availability'] = "Electronic version at ProQuest; O'Reilly for Higher Education (O'Reilly Online Learning: Academic/Public Library Edition); Full Text; Available; 53452720100002311"
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926909978602311'

    if selectiveCols.at[i, 'Short Title'] == 'THE MUSEUM OF UNNATURAL HISTORIES':
        selectiveCols.at[i, 'MMS ID'] = '9926839378502311'
        selectiveCols.at[i, 'Access_Type'] = 'Full text available:'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at Project Muse; Project Muse Ebooks (Project Muse Ebooks Individually Purchased); Full Text; Available; 53446391740002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926839378502311'

    if selectiveCols.at[i, 'Short Title'] == 'DIFFERENTIAL EQUATIONS, DYNAMIC SYS & INTRO TO CHAOS':
        selectiveCols.at[i, 'MMS ID'] = '9925873484102311'
        selectiveCols.at[i, 'Access_Type'] = 'Click to View'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at ProQuest; ProQuest Ebook Central: Academic Complete; Full Text; Available; 53323574290002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9925873484102311'

    if selectiveCols.at[i, 'Short Title'] == 'INFORMATION ARCHITECTURE FOR THE WORLD WIDE WEB':
        selectiveCols.at[i, 'MMS ID'] = '9926909740702311'
        selectiveCols.at[i, 'Access_Type'] = ''
        selectiveCols.at[i, 'Electronic Availability'] = "Electronic version at ProQuest; O'Reilly for Higher Education (O'Reilly Online Learning: Academic/Public Library Edition); Full Text; Available; 53452757920002311"
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926909740702311'

    if selectiveCols.at[i, 'Short Title'] == 'MOVEMENTS IN ORGANIZATIONAL COMMUNICATION RESEARCH':
        selectiveCols.at[i, 'MMS ID'] = '9926414519802311'
        selectiveCols.at[i, 'Access_Type'] = 'Online Access- Unlimited users (DRM-Free)'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at Taylor & Francis; Taylor & Francis Ebooks (Taylor & Francis Ebooks EBA Purchased); Full Text; Available; 53407938040002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926414519802311'

    if selectiveCols.at[i, 'Short Title'] == 'MOVEMENTS IN ORGANIZATIONAL COMMUNICATION RESEARCH : CURRENT ISSUES AND FUTURE DIRECTIONS':
        selectiveCols.at[i, 'MMS ID'] = '9926414519802311'
        selectiveCols.at[i, 'Access_Type'] = 'Online Access- Unlimited users (DRM-Free)'
        selectiveCols.at[i, 'Electronic Availability'] = 'Electronic version at Taylor & Francis; Taylor & Francis Ebooks (Taylor & Francis Ebooks EBA Purchased); Full Text; Available; 53407938040002311'
        selectiveCols.at[i, 'Permalink'] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma9926414519802311'
    
selectiveCols

C:\Users\aharrima\AppData\Local\Temp\ipykernel_31356\1045223992.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9925873484102311' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  selectiveCols.at[i, 'MMS ID'] = '9925873484102311'

,index,Academic Term,Academic Department Name,Course Code,Instructor Name,ISBN (Normalized) List,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Electronic location,Electronic access,Electronic Availability,Access_Type,Permalink
0,0,Fall 2026,BIOMEDICAL ENGINEERING,202640-BME.529.002-46165,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,Electronic version at Taylor & Francis; Taylor...,NaN,NaN
1,1,Fall 2026,CHEMICAL AND BIOMOLECULAR ENGINEERING,202640-CBE.529.002-46170,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,Electronic version at Taylor & Francis; Taylor...,NaN,NaN
2,2,Fall 2026,ELECTRICAL AND COMPUTER SCIENCE,202640-ECE.529.002-46166,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,Electronic version at Taylor & Francis; Taylor...,NaN,NaN
3,3,Fall 2026,ENVIRONMENTAL ENGINEERING,202640-ENVE.529.002-48495,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,Electronic version at Taylor & Francis; Taylor...,NaN,NaN
4,4,Fall 2026,INDUSTRIAL ENGINEERING,202640-IE.529.002-46167,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,https://www.taylorfrancis.com/books/9781420095241,Online Access - Unlimited users.,Electronic version at Taylor & Francis; Taylor...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,697,Fall 2026,SOCIAL WORK,202640-SOWK.531.001-46722,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",10,9926868740402311,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN
574,698,Fall 2026,SOCIAL WORK,202640-SOWK.531.002-56742,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",3,9926868740402311,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN
575,699,Fall 2026,SOCIAL WORK,202640-SOWK.531.101-52230,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",2,9926868740402311,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN
576,700,Fall 2026,BUSINESS ADMINISTRATION,202640-BUAD.217.001-44744,"Rittenhouse, Jennifer",9781119886112,"TRUE NORTH, EMERGING LEADER EDITION : LEADING ...","GEORGE, BILL AND CLAYTON, ZACH","WILEY & SONS, INCORPORATED, JOHN",27,9926909582702311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN
577,701,Fall 2026,JOURNALISM AND MEDIA,202640-JMED.436.001-57630,"Santos, Timothy",9780429000324,VIDEO FIELD PRODUCTION AND EDITING,"COMPESI, RONALD J.",ROUTLEDGE,20,9926910284202311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN

In [32]:
len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

228

In [33]:
nonUnlimited = finalJoin[~finalJoin['Short Title'].isin(selectiveCols['Short Title'])].dropna(how = 'all')

nonUnlimited.sort_values(by = 'Short Title')['Short Title'].unique()

array([], dtype=object)

## Export the Overlap Report

### This is the dataset that gets transferred to the Transforming Bookstore List Python code.

In [34]:
selectiveCols.to_excel(date_str+'_overlap_report.xlsx', index = False)

In [35]:
warnings.filterwarnings("ignore")

bookstoreExport = selectiveCols

# Fill in the Primo Link based on the MMS ID

for i in range(len(bookstoreExport['MMS ID'])):
    bookstoreExport['Electronic location'].iloc[i] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma' + str(bookstoreExport['MMS ID'].iloc[i])

bookstoreExport = bookstoreExport.rename(columns = {'ISBN (Normalized) List': 'ISBN', 'Electronic access': 'Access_Type', 'Electronic location': 'Permalink', 'Course Code': 'Section Code'})

bookstoreExport = bookstoreExport[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Access_Type', 'Electronic Availability', 'Permalink']]

bookstoreExport['Section Title Code'] = bookstoreExport['Section Code'] + bookstoreExport['Short Title']

bookstoreExport

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Access_Type,Electronic Availability,Permalink,Permalink,Section Title Code
0,Fall 2026,BIOMEDICAL ENGINEERING,202640-BME.529.002-46165,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,Online Access - Unlimited users.,NaN,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-BME.529.002-46165ADVANCED LINEAR ALGEBR...
1,Fall 2026,CHEMICAL AND BIOMOLECULAR ENGINEERING,202640-CBE.529.002-46170,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,Online Access - Unlimited users.,NaN,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-CBE.529.002-46170ADVANCED LINEAR ALGEBR...
2,Fall 2026,ELECTRICAL AND COMPUTER SCIENCE,202640-ECE.529.002-46166,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,Online Access - Unlimited users.,NaN,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-ECE.529.002-46166ADVANCED LINEAR ALGEBR...
3,Fall 2026,ENVIRONMENTAL ENGINEERING,202640-ENVE.529.002-48495,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,Online Access - Unlimited users.,NaN,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-ENVE.529.002-48495ADVANCED LINEAR ALGEB...
4,Fall 2026,INDUSTRIAL ENGINEERING,202640-IE.529.002-46167,"Smith, L Montgomery",9781420095241,ADVANCED LINEAR ALGEBRA FOR ENGINEERS WITH MATLAB,"DIANAT, SOHAIL A., SABER, ELI, AND DIANAT, SOHAIL",TAYLOR & FRANCIS GROUP,30,9925403550002311,Online Access - Unlimited users.,NaN,Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-IE.529.002-46167ADVANCED LINEAR ALGEBRA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,Fall 2026,SOCIAL WORK,202640-SOWK.531.001-46722,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",10,9926868740402311,Single User Single User,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-SOWK.531.001-46722TRAUMA COUNSELING : T...
574,Fall 2026,SOCIAL WORK,202640-SOWK.531.002-56742,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",3,9926868740402311,Single User Single User,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-SOWK.531.002-56742TRAUMA COUNSELING : T...
575,Fall 2026,SOCIAL WORK,202640-SOWK.531.101-52230,"Brooks, Hannah",9780826150844,TRAUMA COUNSELING : THEORIES AND INTERVENTIONS...,"LOPEZ LEVERS, LISA AND LEVERS, LISA LOPEZ","SPRINGER PUBLISHING COMPANY, INCORPORATED",2,9926868740402311,Single User Single User,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-SOWK.531.101-52230TRAUMA COUNSELING : T...
576,Fall 2026,BUSINESS ADMINISTRATION,202640-BUAD.217.001-44744,"Rittenhouse, Jennifer",9781119886112,"TRUE NORTH, EMERGING LEADER EDITION : LEADING ...","GEORGE, BILL AND CLAYTON, ZACH","WILEY & SONS, INCORPORATED, JOHN",27,9926909582702311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,"202640-BUAD.217.001-44744TRUE NORTH, EMERGING ..."
577,Fall 2026,JOURNALISM AND MEDIA,202640-JMED.436.001-57630,"Santos, Timothy",9780429000324,VIDEO FIELD PRODUCTION AND EDITING,"COMPESI, RONALD J.",ROUTLEDGE,20,9926910284202311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-JMED.436.001-57630VIDEO FIELD PRODUCTIO...

# 13. Check Bookstore Access

Use this table to make sure all of the access labels from Alma are correct.

In [36]:
# If this is the first list of the semester, do not run this cell
alreadyChecked1 = pd.read_excel(r'Bookstore Access Check 2026-07-14.xlsx')
alreadyChecked2 = pd.read_excel(r'Bookstore Access Check 2026-07-15.xlsx')
alreadyChecked3 = pd.read_excel(r'Bookstore Access Check 2026-07-15V2.xlsx')
alreadyChecked4 = pd.read_excel(r'Bookstore Access Check 2026-08-04V1.xlsx')
alreadyChecked5 = pd.read_excel(r'Bookstore Access Check 2026-08-04V2.xlsx')
alreadyChecked6 = pd.read_excel(r'Bookstore Access Check 2026-08-04V3.xlsx')

alreadyChecked = pd.concat([alreadyChecked1, alreadyChecked2, alreadyChecked3, alreadyChecked4, alreadyChecked5, alreadyChecked6])

alreadyChecked['Section Title Code'] = alreadyChecked['Section Code'] + alreadyChecked['Short Title']

alreadyChecked

,Access Check,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Electronic Availability,Permalink,Access_Type2,Permalink3,Section Title Code,Access_Type.1,Permalink.1
0,GOOD,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.415.002-54557,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,20,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-EDDE.415.002-5455758-IN-MIND : MULTILIN...,NaN,NaN
1,GOOD,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.426.001-57840,"Smith, David",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,20,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-EDDE.426.001-5784058-IN-MIND : MULTILIN...,NaN,NaN
2,GOOD,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.515.001-58070,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,10,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-EDDE.515.001-5807058-IN-MIND : MULTILIN...,NaN,NaN
3,GOOD,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.515.003-59796,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,5,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-EDDE.515.003-5979658-IN-MIND : MULTILIN...,NaN,NaN
4,GOOD,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.528.001-52251,"Smith, David",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,20,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-EDDE.528.001-5225158-IN-MIND : MULTILIN...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,NO GOOD - 3 USERS,Fall 2026,JAPANESE,202640-JAPA.151.005-52650,"Takeuchi, Kazuhide",9784789017312,WKBK T/A GENKI I,BANNO,CHENG & TSUI,18,9925935656802312,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-JAPA.151.005-52650WKBK T/A GENKI I,NaN,NaN
136,NO GOOD - 1 USER,Fall 2026,ENGLISH,202640-ENGL.332.001-41509,"Jennings, La Vinia",9780307759337,WOMAN WARRIOR,"KINGSTON, MAXINE AND KINGSTON, MAXINE HONG",KNOPF DOUBLEDAY PUBLISHING GROUP,28,9925908084602312,Online Access - 1 user,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-ENGL.332.001-41509WOMAN WARRIOR,NaN,NaN
137,NO GOOD - 1 USER,Fall 2026,"WOMEN, GENDER AND SEXUALITY",202640-WGS.332.001-49943,"Jennings, La Vinia",9780307759337,WOMAN WARRIOR,"KINGSTON, MAXINE AND KINGSTON, MAXINE HONG",KNOPF DOUBLEDAY PUBLISHING GROUP,28,9925908084602312,Online Access - 1 user,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-WGS.332.001-49943WOMAN WARRIOR,NaN,NaN
138,NO GOOD - 3 USERS,Fall 2026,THEORY AND PRACTICE IN TEACHER EDUCATION,202640-TPTE.574.014-49801,"Bertling, Joy",9781351858922,WRITING LITERATURE REVIEWS : A GUIDE FOR STUDE...,"GALVAN, JOSE L. AND GALVAN, MELISA C.",ROUTLEDGE,15,9925696667702312,Click to View,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-TPTE.574.014-49801WRITING LITERATURE RE...,NaN,NaN
139,GOOD,Fall 2026,SOCIAL WORK,202640-SOWK.626.001-47369,"Zottarelli, Lisa",9780199399123,WRITING SCIENCE : HOW TO WRITE PAPERS THAT GET...,"SCHIMEL, JOSHUA","OXFORD UNIVERSITY PRESS, INCORPORATED",10,9923913730102312,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,NaN,202640-SOWK.626.001-47369WRITING SCIENCE : HOW...,NaN,NaN

In [37]:
# Use this for the first list of the semester only
#newChecks = bookstoreExport

# Use this for every list except for the first of the semester
newChecks = bookstoreExport[~bookstoreExport['Section Title Code'].isin(alreadyChecked['Section Title Code'])]

newChecks

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Access_Type,Electronic Availability,Permalink,Permalink,Section Title Code
467,Fall 2026,HISTORY UNITED STATES,202640-HIUS.353.001-55736,"Harlow, Luke",9780674426146,AFTER APPOMATTOX : MILITARY OCCUPATION AND THE...,"DOWNS, GREGORY P.",HARVARD UNIVERSITY PRESS,35,9927021036302311,Unlimited Access Unlimited Access,NaN,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-HIUS.353.001-55736AFTER APPOMATTOX : MI...
495,Fall 2026,MUSICOLOGY,202640-MUCO.215.001-60644,"Golden, Rachel",9780199831890,EARLY MUSIC : A VERY SHORT INTRODUCTION,"KELLY, THOMAS FORREST","OXFORD UNIVERSITY PRESS, INCORPORATED",38,9927022868502311,Online Access - Unlimited users,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-MUCO.215.001-60644EARLY MUSIC : A VERY ...
496,Fall 2026,MUSICOLOGY,202640-MUCO.215.002-60645,"Golden, Rachel",9780199831890,EARLY MUSIC : A VERY SHORT INTRODUCTION,"KELLY, THOMAS FORREST","OXFORD UNIVERSITY PRESS, INCORPORATED",38,9927022868502311,Online Access - Unlimited users,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-MUCO.215.002-60645EARLY MUSIC : A VERY ...
517,Fall 2026,CLASSICS,202640-CLAS.389.001-57662,"Barnes, John",9780691187150,GEMINOS'S INTRODUCTION TO THE PHENOMENA : A TR...,"EVANS, JAMES AND BERGGREN, J. LENNART",PRINCETON UNIVERSITY PRESS,30,9927022569102311,Unlimited Access Unlimited Access,NaN,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-CLAS.389.001-57662GEMINOS'S INTRODUCTIO...
544,Fall 2026,NUCLEAR ENGINEERING,202640-NE.490.003-45681,"Bobba, Kondapa",9780080540207,RADIATION BIOPHYSICS,"ALPEN, EDWARD L.",ELSEVIER SCIENCE & TECHNOLOGY,20,9927022066502311,Unlimited Access Unlimited Access,NaN,Electronic version at Elsevier ScienceDirect; ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-NE.490.003-45681RADIATION BIOPHYSICS
545,Fall 2026,NUCLEAR ENGINEERING,202640-NE.590.001-60888,"Bobba, Kondapa",9780080540207,RADIATION BIOPHYSICS,"ALPEN, EDWARD L.",ELSEVIER SCIENCE & TECHNOLOGY,10,9927022066502311,Unlimited Access Unlimited Access,NaN,Electronic version at Elsevier ScienceDirect; ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-NE.590.001-60888RADIATION BIOPHYSICS
546,Fall 2026,NUCLEAR ENGINEERING,202640-NE.490.003-45681,"Bobba, Kondapa",9780080540207,RADIATION BIOPHYSICS,"ALPEN, EDWARD L.",ELSEVIER SCIENCE & TECHNOLOGY,20,9927022789002311,NaN,NaN,Electronic version at Elsevier ScienceDirect; ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-NE.490.003-45681RADIATION BIOPHYSICS
547,Fall 2026,NUCLEAR ENGINEERING,202640-NE.590.001-60888,"Bobba, Kondapa",9780080540207,RADIATION BIOPHYSICS,"ALPEN, EDWARD L.",ELSEVIER SCIENCE & TECHNOLOGY,10,9927022789002311,NaN,NaN,Electronic version at Elsevier ScienceDirect; ...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-NE.590.001-60888RADIATION BIOPHYSICS
552,Fall 2026,INSTITUTE FOR AMERICAN CIVICS,202640-IAC.301.001-58573,"Busch, Andrew",9781400888368,THE RHETORICAL PRESIDENCY : NEW EDITION,"TULIS, JEFFREY K.",PRINCETON UNIVERSITY PRESS,35,9927021969102311,Unlimited Access Unlimited Access,NaN,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-IAC.301.001-58573THE RHETORICAL PRESIDE...
553,Fall 2026,INSTITUTE FOR AMERICAN CIVICS,202640-IAC.301.002-58574,"Patterson, James",9781400888368,THE RHETORICAL PRESIDENCY : NEW EDITION,"TULIS, JEFFREY K.",PRINCETON UNIVERSITY PRESS,30,9927021969102311,Unlimited Access Unlimited Access,NaN,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-IAC.301.002-58574THE RHETORICAL PRESIDE...
569,Fall 2026,ARTIFICIAL INTELLEGIENCE,202640-AI.102.001-60344,"Kidane, Nahom",9781098155407,THINK PYTHON : HOW TO THINK LIKE A COMPUTER SC...,"DOWNEY, ALLEN AND DOWNEY, ALLEN B.","O'REILLY MEDIA, INCORPORATED",75,9927022061902311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...,NaN,202640-AI.102.001-60344THINK PYTHON : HOW TO T...

In [38]:
# If there is nothing in newChecks, skip this cell

newChecks.to_excel('Bookstore Access Check ' +date_str+'.xlsx')

### After checking all of the books, save the file as "Bookstore Access Check YYYY-MM-DD.xlsx" to be loaded into the cells below.

## 14. Export the Bookstore Results to Send to the Bookstore

In [39]:
# Use this for the first list of the semester only
#finalChecked = pd.read_excel(r'Bookstore Access Check '+date_str+'.xlsx')

# Use this for every list except for the first of the semester
previousChecked1 = pd.read_excel(r'Bookstore Access Check 2026-07-14.xlsx')
previousChecked2 = pd.read_excel(r'Bookstore Access Check 2026-07-15.xlsx')
previousChecked3 = pd.read_excel(r'Bookstore Access Check 2026-07-15V2.xlsx')
previousChecked4 = pd.read_excel(r'Bookstore Access Check 2026-08-04V1.xlsx')
previousChecked5 = pd.read_excel(r'Bookstore Access Check 2026-08-04V2.xlsx')
previousChecked6 = pd.read_excel(r'Bookstore Access Check 2026-08-04V3.xlsx')
previousChecked7 = pd.read_excel(r'Bookstore Access Check 2026-08-10.xlsx')
#newChecked = pd.read_excel(r'Bookstore Access Check '+date_str+'.xlsx')

finalChecked = pd.concat([previousChecked1, previousChecked2, previousChecked3, previousChecked4, previousChecked5, previousChecked6, previousChecked7])

In [40]:
# Use this for the first list of the semester only
#finalExport = bookstoreExport

# Use this for every list except for the first of the semester
finalExport = finalChecked[finalChecked['Access Check'] == 'GOOD']

finalExport = finalExport[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Access_Type', 'Electronic Availability', 'Permalink']]

finalExport = finalExport.sort_values(by = 'Short Title')

finalExport

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Electronic Availability,Permalink
0,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.415.002-54557,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,20,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
8,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.515.003-59796,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,5,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
7,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.515.001-58070,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,10,9926829233602310,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
6,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.426.001-57840,"Smith, David",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,20,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
5,Fall 2026,EDUCATION OF THE DEAF AND HARD OF HEARING,202640-EDDE.415.002-54557,"Shahan, Cheryl",9781954622210,58-IN-MIND : MULTILINGUAL TEACHING STRATEGIES ...,NaN,GALLAUDET UNIVERSITY PRESS,20,9926829233602312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,Fall 2026,MUSICOLOGY,202640-MUCO.454.001-60693,"Gay, Leslie",9780253045034,"WHERE RIVERS AND MOUNTAINS SING : SOUND, MUSIC...","LEVIN, THEODORE",INDIANA UNIVERSITY PRESS,6,9926283387202312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
128,Fall 2026,PUBLIC HEALTH,202640-PUBH.430.001-51542,"Ramage, Kaylee",9780674039209,WHY PEOPLE DIE BY SUICIDE,"JOINER, THOMAS",HARVARD UNIVERSITY PRESS,50,9926678262502312,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
129,Fall 2026,POLITICAL SCIENCE,202640-POLS.414.001-56028,"Widner, Kirsten",9780226186443,WHY WE LOST THE ERA,"MANSBRIDGE, JANE J.",UNIVERSITY OF CHICAGO PRESS,30,9926785135102312,Unlimited Access Unlimited Access,Electronic version at De Gruyter; De Gruyter E...,https://utk.primo.exlibrisgroup.com/permalink/...
130,Fall 2026,"WOMEN, GENDER AND SEXUALITY",202640-WGS.340.001-56390,"Widner, Kirsten",9780226186443,WHY WE LOST THE ERA,JANE J. MANSBRIDGE,UNIVERSITY OF CHICAGO PRESS,7,9926785135102312,Unlimited Access Unlimited Access,Electronic version at De Gruyter; De Gruyter E...,https://utk.primo.exlibrisgroup.com/permalink/...
139,Fall 2026,SOCIAL WORK,202640-SOWK.626.001-47369,"Zottarelli, Lisa",9780199399123,WRITING SCIENCE : HOW TO WRITE PAPERS THAT GET...,"SCHIMEL, JOSHUA","OXFORD UNIVERSITY PRESS, INCORPORATED",10,9923913730102312,Unlimited Access Unlimited Access,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...

In [41]:
finalExport.to_excel(date_str+'BookStoreResults_TPQ.xlsx', index = False) #Send this to the Bookstore