## 1. run the next two cells as-is

In [34]:
#import libraries and set some variables

import requests
import pandas as pd
import xml.etree.ElementTree as ET
from pprint import pprint
from urllib.parse import quote
import numpy as np
import urllib.parse
import os
import warnings

pd.set_option('display.max_columns', None)


#Setting a few Alma Analytics API variables and whatnot
base_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&path=')  

token_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&token=')

loc1 = 'shared'
loc2 = 'University of Tennessee, Knoxville'
loc3 = 'Reports'
loc4 = 'Collections'
loc5 = 'Textbook ISBNs for Overlap Report_TM'
if loc5 != '':
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/' + loc5 
else:
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/'

get_path = location 
url_encoded_path = quote(get_path)
report_path = base_path + url_encoded_path

xml_snippet = '''
<sawx:expr xsi:type="sawx:list" op="in"
  xmlns:saw="com.siebel.analytics.web/report/v1.1"
  xmlns:sawx="com.siebel.analytics.web/expression/v1.1" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<sawx:expr xsi:type="sawx:sqlExpression">"Bibliographic Details"."MMS Id"</sawx:expr>
{}
</sawx:expr>
'''

In [35]:
report_path

'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?limit=1000&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5&path=/shared/University%20of%20Tennessee%2C%20Knoxville/Reports/Collections/Textbook%20ISBNs%20for%20Overlap%20Report_TM'

In [36]:
#define some functions

#function to extract data from the analytics report
def extract_data(row_elements, columns):
    data = []
    for row in row_elements:
        row_data = {}
        for col in row.findall('{urn:schemas-microsoft-com:xml-analysis:rowset}*'):
            column_name = col.tag.split('}')[1]
            column_value = col.text
            if column_name in columns:  # Check if the column is in the columns dictionary
                row_data[columns[column_name]] = column_value if column_value is not None else np.nan  # Insert NaN if value is missing
        data.append(row_data)
    return data

#pulling the analytics report and extracting data
def get_report(response):
    # Parse the XML response
    root = ET.fromstring(response.content)
    # Extract the ResumptionToken and IsFinished elements from the response XML
    resumption_token_element = root.find('.//ResumptionToken')
    resumption_token = resumption_token_element.text if resumption_token_element is not None else None
    is_finished_element = root.find('.//IsFinished')
    if is_finished_element is not None:
        is_finished = is_finished_element.text
    else:
        is_finished = None

    namespaces = {
        'xmlns': 'urn:schemas-microsoft-com:xml-analysis:rowset',
        'xsd': 'http://www.w3.org/2001/XMLSchema',
        'saw-sql': 'urn:saw-sql'
    }
    columns = {}

    for i, col in enumerate(root.findall('.//xsd:element[@saw-sql:columnHeading]', namespaces)):
        columns[f'Column{i}'] = col.get('{urn:saw-sql}columnHeading', col.get('name'))
    
    # Extract the data from the XML and store it in a list of dictionaries
    all_data = []
    data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
    all_data.extend(data)
    
    # Iterate through subsequent GET requests until IsFinished is True
    while is_finished == 'false':
        # Make the next GET request with the ResumptionToken
        response = requests.get(token_path + resumption_token)

        # Extract the ResumptionToken and IsFinished elements from the response XML
        root = ET.fromstring(response.content)
        is_finished = root.find('.//IsFinished').text

        # Process the response data
        data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
        all_data.extend(data)

    report_df = pd.DataFrame(all_data)

    # Drop the first column of the dataframe
    if not report_df.empty:
        report_df = report_df.drop(report_df.columns[0], axis=1)

    # Reset the index of the dataframe
    report_df = report_df.reset_index(drop=True)

    return report_df


def get_and_concat_report(report_path, report_data_df):
    response = requests.get(report_path)
    report_df = get_report(response)
    print(len(report_df))
    return pd.concat([report_data_df, report_df], ignore_index=True)

# Define a custom function to concatenate non-NaN values and deduplicate the notes fields which contain information about 
# online access type for each ebook
def concatenate_and_deduplicate_notes(row):
    notes = [str(row['Portfolio Public Note']), str(row['Portfolio Authentication Note']),
             str(row['Service Authentication Note']), str(row['Electronic location and access'])]
    non_nan_notes = set(note for note in notes if note != 'nan')
    return '; '.join(non_nan_notes)

## 2. Set the date

In [4]:
#set the date string for the rest of this notebook
date_str = '2026-01-14'

## 3. Read in the searchresults file from the bookstore
## make sure to point read_excel to the correct file location!

In [5]:
#load most recent file from bookstore
# you will need to have saved the automated bookstore file using format "searchresults_YYYY-MM-DD.xlsx" to your computer
df = pd.read_excel(r'searchresults_'+date_str+'.xlsx')

# Preview the sorted DataFrame
df

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity
0,SPRING 2026,ACCOUNTING,202620-ACCT.200.001-20001,"Jordan, Latonya",9781266584633,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING,THOMAS EDMONDS; CHRISTOPHER EDMONDS; PHILIP OL...,MCGRAW-HILL HIGHER EDUCATION (US),50
1,SPRING 2026,ACCOUNTING,202620-ACCT.200.002-20002,"Jordan, Latonya",9781266584633,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING,THOMAS EDMONDS; CHRISTOPHER EDMONDS; PHILIP OL...,MCGRAW-HILL HIGHER EDUCATION (US),50
2,SPRING 2026,ACCOUNTING,202620-ACCT.200.003-20003,"Jordan, Latonya",9781266584633,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING,THOMAS EDMONDS; CHRISTOPHER EDMONDS; PHILIP OL...,MCGRAW-HILL HIGHER EDUCATION (US),300
3,SPRING 2026,ACCOUNTING,202620-ACCT.200.004-20004,"Jordan, Latonya",9781266584633,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING,THOMAS EDMONDS; CHRISTOPHER EDMONDS; PHILIP OL...,MCGRAW-HILL HIGHER EDUCATION (US),50
4,SPRING 2026,ACCOUNTING,202620-ACCT.200.005-20005,"Jordan, Latonya",9781266584633,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING,THOMAS EDMONDS; CHRISTOPHER EDMONDS; PHILIP OL...,MCGRAW-HILL HIGHER EDUCATION (US),300
...,...,...,...,...,...,...,...,...,...
5208,SPRING 2026,"WOMEN, GENDER AND SEXUALITY",202620-WGS.375.002-30965,"Petersen, Camille",9781324044055,"GENDER : IDEAS, INTERACTIONS, INSTITUTIONS (TH...","WADE, LISA AND FERREE, MYRA MARX","NORTON & COMPANY, INCORPORATED, W. W.",35
5209,SPRING 2026,"WOMEN, GENDER AND SEXUALITY",202620-WGS.460.001-40482,"Destine, Shaneda",9781442200142,STUDY GUIDE FOR LET NOBODY TURN US AROUND,KAREN WILLIAMS; ANDREA QUEELEY,BLOOMSBURY USA,30
5210,SPRING 2026,WORLD LANGUAGES AND ESL EDUCATION,202620-WLEL.489.001-28056,"Slisher, Inna",9781071902684,UNLOCKING MULTILINGUAL LEARNERS? POTENTIAL,DIANE STAEHR FENNER; SYDNEY SNYDER; MEGHAN GRE...,"SAGE PUBLICATIONS, INC. (US)",40
5211,SPRING 2026,WORLD LANGUAGES AND ESL EDUCATION,202620-WLEL.545.001-39142,"Coda, James",9780134045207,LANGUAGES AND LEARNERS : MAKING THE MATCH: WOR...,"CURTAIN, HELENA I., DAHLBERG, CAROL ANN, AND C...",PEARSON EDUCATION,10
5212,SPRING 2026,WORLD LANGUAGES AND ESL EDUCATION,202620-WLEL.545.002-39143,"Coda, James",9780134045207,LANGUAGES AND LEARNERS : MAKING THE MATCH: WOR...,"CURTAIN, HELENA I., DAHLBERG, CAROL ANN, AND C...",PEARSON EDUCATION,15

## 4. do some work on the bookstore-provided file to generate a list of ISBNs that 
## we will use in a later step

In [6]:
#create list of ISBNs for use in Alma Set creation
#do some pre-processing on the data for cleanup purposes
isbns = df[['ISBN']]
isbns = isbns.dropna()
isbns = isbns.drop_duplicates()
isbns['ISBN'] = isbns['ISBN'].apply(lambda x: x.replace('-',''))
isbns = isbns.astype(str)
isbns = isbns[(isbns['ISBN'].str.len() == 13) & (isbns['ISBN'].str.isdigit())]
isbns = isbns.reset_index()
isbns = isbns.drop('index', axis = 1)
isbns = isbns.iloc[isbns['ISBN'].str.len().sort_values(ascending = False).index]
isbns

               ISBN
0     9781266584633
970   9780894484735
968   9780137501724
967   9780137546428
966   9798385118533
...             ...
479   9780321995629
478   9781599632001
477   9781684424528
476   9781319032937
1443  9780134045207

[1444 rows x 1 columns]

In [7]:
isbns.dtypes

ISBN    object
dtype: object

In [8]:
#Fix known mismatching ISBNs

for i in range(isbns.shape[0]):
    if isbns.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found 1')
        print(i)
        isbns.at[i, 'ISBN'] = '9780191037610'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found 2')
        print(i)
        isbns.at[i, 'ISBN'] = '9781041036487'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found 3')
        print(i)
        isbns.at[i, 'ISBN'] = '9798400648236'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found 4')
        print(i)
        isbns.at[i, 'ISBN'] = '9780367725204' 
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found 5')
        print(i)
        isbns.at[i, 'ISBN'] = '9781119682141' 
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found 6')
        print(i)
        isbns.at[i, 'ISBN'] = '9781351133159'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found 7')
        print(i)
        isbns.at[i, 'ISBN'] = '9781501506024'
        print(isbns.at[i, 'ISBN'])
    if isbns.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found 8')
        print(i)
        isbns.at[i, 'ISBN'] = '9781506352886'
        print(isbns.at[i, 'ISBN'])

Found 6
240
9781351133159
Found 1
427
9780191037610
Found 5
572
9781119682141
Found 8
694
9781506352886
Found 4
734
9780367725204
Found 3
741
9798400648236
Found 7
1295
9781501506024
Found 2
1381
9781041036487

## 5. Save the isbns to an Excel file

In [9]:
#create new itemized set in Alma using this isbn file:
isbns.to_excel(date_str+'_isbns.xlsx', index = False)

# after the set is created, export the results (All Fields) and save the file using format "YYYY-MM-DD_set_output.xlsx"

## 5. Use the isbn file to create an itemized set in alma
## After the set is created, export the results (All Fields) and save using the file name format "YYYY-MM-DD_set_output.xlsx" to the same location that all your other files for this process live in

## 6. The following cell will use the set_output you just made to call on the alma analytics API, looking for any matching ISBNs

In [37]:
#use the alma API and the set results to get all ISBNs for any MMS IDs found in set
#analytics report: Collections folder > "Textbook ISBNs for Overlap Report_TM"

#create list of mms_ids from set output
#mms_ids = pd.read_excel(date_str+"_set_output.xlsx")
mms_ids = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
mms_ids = mms_ids[['MMS ID']]

# Get the list of MMS IDs from the DataFrame
mms_list = mms_ids['MMS ID'].tolist()

# Define the batch size for API call(s)
batch_size = 50

# Create a list to store the batches
batches = []

# Iterate through the MMS ID list and create batches
for i in range(0, len(mms_list), batch_size):
    batch = mms_list[i : i + batch_size]
    batches.append(batch)

#create an empty list into which we will put api call results
df_list = []

#for each batch of mms ids, call analytics api
for batch in batches:
    values_xml = '\n'.join(f'<sawx:expr xsi:type="xsd:string">{value}</sawx:expr>' for value in batch)
    formatted_xml_snippet = xml_snippet.format(values_xml)

    url_encoded_filter_query = urllib.parse.quote(formatted_xml_snippet)

    full_path = base_path + url_encoded_path + r'&filter=' + url_encoded_filter_query

    report_data_df = get_and_concat_report(full_path, pd.DataFrame())
    df_list.append(report_data_df)
    
# concatenate together all the api call results into one big dataframe
combined_df = pd.concat(df_list, ignore_index=True)
combined_df

37
16
38
34
45
40
42
0

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Authentication Note,Portfolio Id,No. of Available Portfolio,Service Authentication Note,Portfolio Public Note
0,https://ebookcentral.proquest.com/lib/utk/deta...,1119003652; 9781119003656; 1119003601; 9781119...,1119003652; 9781119003656; 1119003601; 9781119...,9925362066902311,Qualitative research : a guide to design and i...,ProQuest Ebook Central DDA Discovery,Available,Online access :,53254273170002311,0,NaN,NaN
1,http://ebookcentral.proquest.com/lib/utk/detai...,9781119051169; 1119051169; 9781119049609; 1119...,9781119051169; 1119051169; 9781119049609; 1119...,9925694335502311,"Assessment in Student Affairs, Second Edition.",ProQuest Ebook Central: Academic Complete,Available,NaN,53288614520002311,1,Online Access - Unlimited users,NaN
2,https://ebookcentral.proquest.com/lib/utk/deta...,9781615371457; 1615371451; 9781615370788; 1615...,9781615371457; 1615371451; 9781615370788; 1615...,9925739827102311,Concise Guide to Child and Adolescent Psychiatry.,ProQuest Ebook Central: Academic Complete,Available,NaN,53295666880002311,1,Online Access - Unlimited users,NaN
3,http://search.ebscohost.com/login.aspx?direct=...,0199361193; 9780199361199; 0199361185; 9780199...,0199361193; 9780199361199; 0199361185; 9780199...,9925764257802311,Conflict resolution for the helping profession...,EBSCO Ebooks Individually Purchased,Available,Online Access - Unlimited users,53300190520002311,1,NaN,Online access :
4,https://ebookcentral.proquest.com/lib/utk/deta...,9781501506024; 1501506021; 9781501515156; 1501...,9781501506024; 1501506021; 9781501515156; 1501...,9925796118702311,Demand and Supply Integration : The Key to Wor...,ProQuest Ebook Central: Academic Complete,Available,NaN,53307862990002311,1,Online Access - Unlimited users,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
247,https://link.springer.com/978-3-319-98282-3 Un...,9783319982816; 3319982818; 9783319982823; 3319...,9783319982816; 3319982818; 9783319982823; 3319...,9926845393402311,Time series econometrics learning through repl...,Springer Ebooks Individually Purchased,Available,NaN,53448280980002311,1,NaN,Unlimited Access
248,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,NaN,53449784400002311,1,NaN,Single User
249,https://search.ebscohost.com/login.aspx?direct...,9781684038237; 1684038235; 9781684038220; 1684...,9781684038237; 1684038235; 9781684038220; 1684...,9926843410002311,Trauma-Focused ACT : a Practitioner's Guide to...,EBSCO Ebooks Individually Purchased,Available,NaN,53448072820002311,1,NaN,Unlimited Access
250,https://brill.com/abstract/title/36245 Online ...,9004281339; 9789004281332; 9789004367906; 9004...,9004281339; 9789004281332; 9789004367906; 9004...,9926867450402311,Vulnerability and critical theory /,Brill Ebooks Individually Purchased,Available,Online Access - Unlimited users (DRM-free),53449728710002311,1,NaN,NaN
251,http://link.overdrive.com/?websiteID=120589&ti...,9781642127683; 164212768X; 9781632367709; 1632...,9781642127683; 164212768X; 9781632367709; 1632...,9926858905102311,"Witch hat atelier, volume 1",OverDrive - Advantage,Available,NaN,53449394550002311,1,NaN,Click to access digital title.

In [38]:
combined_df.sort_values(by = 'Title')['Title'].unique()

array(['A Course in Enumeration', 'A Pocket Style Manual',
       'A Practical Guide to Commercial Real Estate Transactions : From Contract to Closing, Third Edition.',
       'A Practice of Anesthesia for Infants and Children.',
       'A Short Course in Reading French /',
       'A companion to paleopathology /',
       'A comprehensive guide to coding and programming in Stata /',
       'A history of the American musical theatre : no business like it /',
       'A mercy /', 'Affrilachia : poems /',
       'After Victory : Institutions, Strategic Restraint, and the Rebuilding of Order after Major Wars /',
       'After hegemony : cooperation and discord in the world political economy /',
       'Always get the name of the dog : a guide to media interviewing /',
       "American Democracy in Peril : Eight Challenges to America's Future /",
       'American military life in the 21st century : social, cultural, and economic issues and trends /',
       'An Introduction to Scientific Computing : Fifteen Computational Projects Solved with MATLAB.',
       'An Unseen Light : Black Struggles for Freedom in Memphis, Tennessee.',
       'An unkindness of ghosts /',
       'Anger : The Conflicted History of an Emotion.',
       'Anger : the conflicted history of an emotion /',
       'Appeals in Modern Rhetoric An Ordinary Language Approach /',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Assessment in Student Affairs, Second Edition.',
       'Assessment in counseling : procedures and practices /',
       'Becoming a data head : how to think, speak, and understand data science, statistics, and machine learning /',
       'Beloved /',
       'Bestiary being an English version of the Bodleian Library, Oxford M.S. Bodley 764 : with all the original miniatures reproduced in facsimile /',
       'Biomechanics of Movement : The Science of Sports, Robotics, and Rehabilitation.',
       'Building the American republic.',
       'Case studies in deaf education : inquiry, application, and resources /',
       'Caste : the origins of our discontents /',
       'Catalog of unabashed gratitude /', 'Ceremony /',
       'Chief sustainability officers at work how CSOs build successful sustainability and ESG strategies /',
       'Computer organization and design : the hardware/software interface : ARM edition /',
       'Concise Guide to Child and Adolescent Psychiatry.',
       'Condensed matter physics /',
       'Conflict Resolution for the Helping Professions : Negotiation, Mediation, Advocacy, Facilitation, and Restorative Justice.',
       'Conflict resolution for the helping professions : negotiation, mediation, advocacy, facilitation, and restorative justice /',
       'Copaganda : how police and the media manipulate our news /',
       "Coté and Lerman's a practice of anesthesia for infants and children /",
       'Counseling children and adolescents : cultivating empathic connection /',
       'Crack rock cocaine, street capitalism, and the decade of greed /',
       'Cracked, not broken surviving and thriving after a suicide attempt /',
       'Crafting The Personal Essay : A Guide for Writing and Publishing Creative Non-Fiction.',
       'Crafting the personal essay : a guide for writing and publishing creative nonfiction /',
       'DeFi and the Future of Finance.',
       'Deaf people and society : psychological, sociological and educational perspectives /',
       'Debating reform conflicting perspectives on how to fix the American political system /',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Development as freedom /',
       'Differential geometry : curves, surfaces, manifolds /',
       'Elegant legal writing /', 'Elementary number theory /',
       'Engineering capstone design /',
       'Enviromedics : the impact of climate change on human health /',
       'Essentials of Assessment Report Writing.',
       'Essentials of Food Science',
       'Euclidean Geometry : A Guided Inquiry Approach /',
       "Evelina : or, The history of a young lady's entrance into the world /",
       'Everything is obvious : once you know the answer /',
       'Evicted poverty and profit in the American city',
       'Facilitating Breakthrough : How to Remove Obstacles, Bridge Differences, and Move Forward Together',
       'Fighting Against the Injustice of the State and Globalization Comparing the African American and Oromo Movements /',
       'Finance for real estate development',
       'Financial Literacy for Managers : Finance and Accounting for Better Decision-Making /',
       'Financial Statements.',
       'Financial and business management for the doctor of nursing practice /',
       'Financial literacy for managers : finance and accounting for better decision-making /',
       'Forensic Anthropology : An Introductory Lab Manual.',
       'Frankenstein', 'Fully nonlinear elliptic equations /',
       'Fun home A family tragicomic.', 'Fundamentals of physics.',
       'Gender and the Musical Canon',
       'Getting real about inequality : intersectionality in real life (IRL) /',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide /',
       'Globalization of education : an introduction /',
       'Government and Politics in Tennessee',
       'Hablar español en Estados Unidos : la sociopolítica del lenguaje /',
       'Halfway home : race, punishment, and the afterlife of mass incarceration /',
       'Handbook for Classical Research.',
       'Handbook for classical research', 'Head off & split poems /',
       'High fidelity', 'How languages are learned /',
       'How to Keep Your Cool : An Ancient Guide to Anger Management /',
       'Human osteology /',
       'Human rights and social justice in a global perspective : an introduction to international social work /',
       'I, robot /', 'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'Information Architecture for the World Wide Web : Designing Large-Scale Web Sites.',
       'Information science : the basics /',
       'International Energy Markets : Understanding Pricing, Policies, and Profits.',
       'International financial statement analysis /',
       'International trade and agriculture',
       'Interpersonal communication : putting theory into practice /',
       'Introduction to Applied Nonlinear Dynamical Systems and Chaos',
       'Introduction to industrial organization. /',
       'Introduction to stochastic processes /',
       'Invasive species : what everyone needs to know /',
       'Just practice : a social justice approach to social work /',
       'Language, truth, and logic /',
       'Leading with questions : how leaders discover powerful answers by knowing how and what to ask /',
       'Let nobody turn us around voices of resistance, reform, and renewal : an African American anthology /',
       'Linear Systems Theory : Second Edition /',
       'Linguistics of American Sign Language, 5th Ed. : An Introduction /',
       'Make it stick : the science of successful learning /',
       'Making race and nation : a comparison of South Africa, the United States, and Brazil /',
       'Management consulting projects : a step-by-step experiential guide /',
       "Managing vulnerability South Africa's struggle for a democratic rhetoric /",
       'Mastering QGIS - Second Edition.',
       'Maximizing the impact of comics in your library : graphic novels, manga, and more /',
       'Me and my daddy listen to Bob Marley : novellas and stories /',
       'Metals and Society An Introduction to Economic Geology /',
       'Milk and filth', 'Mindset : the new psychology of success /',
       'Modular forms a classical and computational introduction /',
       "My grandmother's hands : racialized trauma and the pathway to mending our hearts and bodies /",
       "Nature's Best Hope : A New Approach to Conservation That Starts in Your Yard.",
       'New kid',
       'Next steps : decision cases for social work practice /',
       'Nonlinear Dynamics and Chaos : With Applications to Physics, Biology, Chemistry, and Engineering /',
       'Obit : poems /',
       "Ortner's identification of pathological conditions in human skeletal remains /",
       'Pedagogical grammar /',
       'Pedagogy of the Oppressed : 30th Anniversary Edition.',
       'Performance appraisal and management /',
       'Persuasion in your life /',
       'Planetary Geology : An Introduction.',
       'Pocket guide to nutrition assessment /',
       'Principles of trauma therapy : a guide to symptoms, evaluation, and treatment.',
       'Probability: A Graduate Course',
       'Property of the Rebel Librarian',
       'Public speaking for engineers : communicating effectively with clients, the public, and local government /',
       'Pursuing happiness a Bedford spotlight reader /',
       'Qualitative research : a guide to design and implementation /',
       'Quicksand /',
       'R for political science research : an introduction for absolute beginners /',
       'Race and reunion : the Civil War in American memory /',
       'Racial theories in social science : a systemic racism critique /',
       'Recent developments in southeastern archaeology from colonization to complexity /',
       'Recreation Programming : Designing, Staging, and Managing the Delivery of Leisure Experiences.',
       'Regression analysis and linear models : concepts, applications, and implementation /',
       'Research Methods in Library and Information Science /',
       'Research methods for social work : a problem-based approach /',
       'Riding the Trail of Tears.',
       'Rules of play : game design fundamentals /',
       'Science Notebooks in Student-Centered Classrooms.',
       'Scraping by : wage labor, slavery, and survival in early Baltimore /',
       'Sick enough : a guide to the medical complications of eating disorders and undernutrition /',
       'Silas Marner : the weaver of Raveloe /',
       'Skill acquisition in sport : research, theory and practice /',
       'Social movements : the structure of collective mobilization /',
       'Social theory of international politics /',
       'Social work values and ethics /',
       'Socratic questioning for therapists and counselors : learn how to think and intervene like a cognitive behavior therapist /',
       'Sounding Like a No-No : Queer Sounds and Eccentric Acts in the Post-Soul Era.',
       'Sounding like a no-no : queer sounds and eccentric acts in the post-soul era /',
       'Sounding like a no-no? queer sounds and eccentric acts in the post-soul era /',
       'Statistical Mechanics : Principles and Selected Applications.',
       'Statistical mechanics /',
       'Stochastic Differential Equations An Introduction with Applications /',
       "Stoelting's pharmacology & physiology in anesthetic practice",
       'Storytelling with data : a data visualization guide for business professionals /',
       'Storytelling with you : plan, create, and deliver a stellar presentation /',
       'Strategic planning for public relations',
       'Strategy in 3D : essential tools to diagnose, decide, & deliver /',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time /',
       'Survey Research and Analysis.',
       'Systematic instruction for students with moderate and severe disabilities',
       'Systems engineering : principles and practice /',
       'Systems thinking for social change : a practical guide to solving complex problems, avoiding unintended consequences, and achieving lasting results /',
       'Teaching English as a foreign or second language : a self-development and methodology guide /',
       'Teaching and learning STEM a practical guide /',
       "Teaching strings in today's classroom : a guide for group instruction /",
       'Textbook of drug design and discovery /',
       'The Antinomian controversy, 1636-1638 : a documentary history /',
       'The Basics of Public Budgeting and Financial Management : A Handbook for Academics and Practitioners.',
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The Ethical Executive : Becoming Aware of the Root Causes of Unethical Behavior: 45 Psychological Traps that Every One of Us Falls Prey To /',
       'The Grapes of wrath /',
       'The Ideal Team Player : How to Recognize and Cultivate the Three Essential Virtues.',
       'The Iliad.',
       "The Mediator's Handbook : Revised & Expanded fourth edition.",
       'The Routledge handbook of festivals /',
       'The Student Leadership Challenge  : Student Workbook and Leadership Journal /',
       'The Sun Also Rises : The Hemingway Library Edition.',
       'The Trojans & Their Neighbours.',
       'The art of the pitch persuasion and presentation skills that win business /',
       'The beast within : animals in the Middle Ages /',
       'The bluest eye : a novel /', 'The design of everyday things /',
       'The evaluation and measurement of library services',
       'The great Arizona orphan abduction /',
       'The ideal team player : how to recognize and cultivate the three essential virtues : a leadership fable /',
       'The life of Saint Katherine of Alexandria',
       'The live music business : management and production of concerts and festivals /',
       'The museum of unnatural histories /',
       'The portable feminist reader /',
       'The professor is in : the essential guide to turning your Ph.D. into a job /',
       'The theory and practice of group psychotherapy /',
       'The two fundamental problems of ethics',
       'The woman warrior : memoirs of a girlhood among ghosts /',
       'The world is a high hill : stories about Jamaican women /',
       'Three tales', 'Through the arc of the rain forest /',
       'Time series econometrics learning through replication /',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster /',
       "Trauma-Focused ACT : a Practitioner's Guide to Working with Mind, Body, and Emotion Using Acceptance and Commitment Therapy.",
       'Understanding spirituality and the sacred in social work practice : spirited conversations /',
       'University Physics, Volume 3',
       "Unlocking Multilingual Learners' Potential : Strategies for Making Content Accessible /",
       'Vulnerability and critical theory /',
       "Water 4. 0 : The Past, Present, and Future of the World's Most Vital Resource.",
       "Water 4.0 the past, present, and future of the world's most vital resource /",
       'What really works with exceptional learners. /',
       'Why people die by suicide /',
       'Wicked Flesh : Black Women, Intimacy, and Freedom in the Atlantic World.',
       'Witch hat atelier, volume  1',
       'World religions in seven sentences : a small introduction to a vast topic /',
       'Yaguareté white : poems /', 'Yvain, the Knight of the Lion /',
       'Zami, a new spelling of my name /'], dtype=object)

In [39]:
combined_df['Service Authentication Note']

0                                  NaN
1      Online Access - Unlimited users
2      Online Access - Unlimited users
3                                  NaN
4      Online Access - Unlimited users
                    ...
247                                NaN
248                                NaN
249                                NaN
250                                NaN
251                                NaN
Name: Service Authentication Note, Length: 252, dtype: object

In [40]:
combined_df['Electronic location split'] = combined_df['Electronic location and access'].apply(lambda x: x.split() if isinstance(x, str) else x)

combined_df['Electronic location'] = combined_df['Electronic location split'].apply(lambda x: ''.join(map(str, x[:1])) if isinstance(x, list) else x)

# Extract items excluding the first item from each list
combined_df['Electronic access'] = combined_df['Electronic location split'].apply(lambda x: ' '.join(x[1:]) if isinstance(x, list) else x)

In [41]:
combined_df['Electronic access']

0      Online access : 1 simultaneous user; http://ww...
1                                          Click to View
2                                          Click to View
3                                        Online access :
4                                          Click to View
                             ...
247                    Unlimited Access Unlimited Access
248                              Single User Single User
249                    Unlimited Access Unlimited Access
250           Online Access - Unlimited users (DRM-free)
251                       Click to access digital title.
Name: Electronic access, Length: 252, dtype: object

## 7. save the alma analytics api output as an excel file

In [42]:
#save the big, concatenated dataframe to disk
combined_df.to_excel(date_str+'_analytics_output.xlsx', index = False)

## do some work on the dataframe

In [43]:
# Create a new column 'Concatenated Notes' with deduplication
combined_df['Concatenated Notes'] = combined_df.apply(concatenate_and_deduplicate_notes, axis=1)

#filter to only show rows where the No. of Available Portfolios is not zero
combined_df = combined_df.loc[combined_df['No. of Available Portfolio'] != 0]


# Display the updated DataFrame
combined_df

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Authentication Note,Portfolio Id,No. of Available Portfolio,Service Authentication Note,Portfolio Public Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,https://ebookcentral.proquest.com/lib/utk/deta...,1119003652; 9781119003656; 1119003601; 9781119...,1119003652; 9781119003656; 1119003601; 9781119...,9925362066902311,Qualitative research : a guide to design and i...,ProQuest Ebook Central DDA Discovery,Available,Online access :,53254273170002311,0,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Online access : 1 simultaneous user; http://ww...,https://ebookcentral.proquest.com/lib/utk/deta...
1,http://ebookcentral.proquest.com/lib/utk/detai...,9781119051169; 1119051169; 9781119049609; 1119...,9781119051169; 1119051169; 9781119049609; 1119...,9925694335502311,"Assessment in Student Affairs, Second Edition.",ProQuest Ebook Central: Academic Complete,Available,NaN,53288614520002311,1,Online Access - Unlimited users,NaN,[http://ebookcentral.proquest.com/lib/utk/deta...,http://ebookcentral.proquest.com/lib/utk/detai...,Click to View,Online Access - Unlimited users; http://ebookc...
2,https://ebookcentral.proquest.com/lib/utk/deta...,9781615371457; 1615371451; 9781615370788; 1615...,9781615371457; 1615371451; 9781615370788; 1615...,9925739827102311,Concise Guide to Child and Adolescent Psychiatry.,ProQuest Ebook Central: Academic Complete,Available,NaN,53295666880002311,1,Online Access - Unlimited users,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Online Access - Unlimited users; https://ebook...
3,http://search.ebscohost.com/login.aspx?direct=...,0199361193; 9780199361199; 0199361185; 9780199...,0199361193; 9780199361199; 0199361185; 9780199...,9925764257802311,Conflict resolution for the helping profession...,EBSCO Ebooks Individually Purchased,Available,Online Access - Unlimited users,53300190520002311,1,NaN,Online access :,[http://search.ebscohost.com/login.aspx?direct...,http://search.ebscohost.com/login.aspx?direct=...,Online access :,Online Access - Unlimited users; http://search...
4,https://ebookcentral.proquest.com/lib/utk/deta...,9781501506024; 1501506021; 9781501515156; 1501...,9781501506024; 1501506021; 9781501515156; 1501...,9925796118702311,Demand and Supply Integration : The Key to Wor...,ProQuest Ebook Central: Academic Complete,Available,NaN,53307862990002311,1,Online Access - Unlimited users,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Online Access - Unlimited users; https://ebook...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,https://link.springer.com/978-3-319-98282-3 Un...,9783319982816; 3319982818; 9783319982823; 3319...,9783319982816; 3319982818; 9783319982823; 3319...,9926845393402311,Time series econometrics learning through repl...,Springer Ebooks Individually Purchased,Available,NaN,53448280980002311,1,NaN,Unlimited Access,"[https://link.springer.com/978-3-319-98282-3, ...",https://link.springer.com/978-3-319-98282-3,Unlimited Access Unlimited Access,Unlimited Access; https://link.springer.com/97...
248,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,NaN,53449784400002311,1,NaN,Single User,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,Single User; https://search.ebscohost.com/logi...
249,https://search.ebscohost.com/login.aspx?direct...,9781684038237; 1684038235; 9781684038220; 1684...,9781684038237; 1684038235; 9781684038220; 1684...,9926843410002311,Trauma-Focused ACT : a Practitioner's Guide to...,EBSCO Ebooks Individually Purchased,Available,NaN,53448072820002311,1,NaN,Unlimited Access,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,https://search.ebscohost.com/login.aspx?direct...
250,https://brill.com/abstract/title/36245 Online ...,9004281339; 9789004281332; 9789004367906; 9004...,9004281339; 9789004281332; 9789004367906; 9004...,9926867450402311,Vulnerability and critical theory /,Brill Ebooks Individually Purchased,Available,Online Access - Unlimited users (DRM-free),53449728710002311,1,NaN,NaN,"[https://brill.com/abstract/title/36245, Onlin...",https://brill.com/abstract/title/36245,Online Access - Unlimited users (DRM-free),https://brill.com/abstract/title/36245 Online ...
251,http://link.overdrive.com/?websiteID=120589&ti...,9781642127683; 164212768X; 9781632367709; 1632...,9781642127683; 164212768X; 9781632367709; 1632...,9926858905102311,"Witch hat atelier, volume 1",OverDrive - Advantage,Available,NaN,53449394550002311,1,NaN,Click to access digital title.,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Click to access digital title.; http://link.ov...

## 8. save the analytics_output file as csv

In [44]:
#save the dataframe to disk once again, only this time as a csv
combined_df.to_csv(date_str+'_analytics_output.csv', index = False)

## 9. Combine Data Files for Exporting and the LibGuide

In [45]:
#results = pd.read_excel(date_str+'_set_output.xlsx') #From Alma Directly
results = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
bookstoreList = pd.read_excel('searchresults_'+date_str+'.xlsx') #From VolBooks Directly
textbookISBNs = combined_df #Alma Cleaned-Up Version

In [46]:
#Fix known mismatching ISBNs in bookstoreList

for i in range(bookstoreList.shape[0]):
    if bookstoreList.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found 1')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9780191037610'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found 2')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781041036487'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found 3')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9798400648236'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found 4')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9780367725204' 
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found 5')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781119682141' 
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found 6')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781351133159'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found 7')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781501506024'
        print(bookstoreList.at[i, 'ISBN'])
    if bookstoreList.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found 8')
        print(i)
        bookstoreList.at[i, 'ISBN'] = '9781506352886'
        print(bookstoreList.at[i, 'ISBN'])

Found 6
1108
9781351133159
Found 1
2125
9780191037610
Found 5
2430
9781119682141
Found 5
2431
9781119682141
Found 5
2433
9781119682141
Found 8
2770
9781506352886
Found 4
2840
9780367725204
Found 4
2841
9780367725204
Found 4
2842
9780367725204
Found 4
2843
9780367725204
Found 4
2844
9780367725204
Found 3
2855
9798400648236
Found 3
2856
9798400648236
Found 7
4590
9781501506024
Found 7
4593
9781501506024
Found 2
4881
9781041036487

In [47]:
textbookISBNs = textbookISBNs.astype({'MMS Id': 'int64'})



resultsPlusList = pd.merge(results, textbookISBNs, left_on = 'MMS ID', right_on = 'MMS Id', how = 'inner')

In [48]:
resultsPlusList

,Title_x,Alternate Graphic Representation,Type,Creator / Imprint,Subject,Series,Relation,Modification Date,Edition,Uniform Title,Medium Type,Language,Creation Date,Language of Cataloging,ISBN_x,ISBN (13),ISSN,Cluster ISSN,Record Number,MMS ID,Bibliographic Rank,Local Call Number,Other Classification Number,NLM Call Number,Dewey Decimal Classification Number,LC Call Number,Classification Part,UDC Classification Number,NAL Call Number,Handle Identifier,Peer Reviewed,Open Access,Physical Availability,Digital Availability,Electronic Availability,Collection Name,Collection ID,Orders,Requests,Physical Description Extent,Local Labels,Related Records,Courses,Licenses,Reminders,Notes,Electronic location and access,ISBN (Normalized),ISBN_y,MMS Id,Title_y,Electronic Collection Public Name,Availability,Portfolio Authentication Note,Portfolio Id,No. of Available Portfolio,Service Authentication Note,Portfolio Public Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,The woman warrior : memoirs of a girlhood amon...,NaN,Book {Book - Electronic} text; computer; onlin...,"Kingston, Maxine Hong. (New York : Vintage Int...","Kingston, Maxine Hong--Childhood and youth.;Ki...",NaN,NaN,2025-12-30 10:19:00,Vintage international edition.,NaN,NaN,English,2020-05-13 12:09:00,NaN,9780307759337 (electronic bk.); 0307759334 (el...,9780307759337 (electronic bk.); 9780307759337 ...,NaN,NaN,99984447178; (NhCcYBP)ybp11736978,9925908084602311,106,NaN,HU 4188 and others,E 184 .C5 K55w 1976,979.4/053/092 and others,CT275.K5764 A33 1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource (209 pages.),NaN,0,0,0,0,0,http://search.ebscohost.com/login.aspx?direct=...,0307759334; 9780307759337; 9780679721888; 0679...,0307759334; 9780307759337; 9780679721888; 0679...,9925908084602311,The woman warrior : memoirs of a girlhood amon...,EBSCO Ebooks Individually Purchased,Available,Online Access - 1 user,53331188500002311,1,NaN,NaN,[http://search.ebscohost.com/login.aspx?direct...,http://search.ebscohost.com/login.aspx?direct=...,Online Access - 1 user,Online Access - 1 user; http://search.ebscohos...
1,Riding the Trail of Tears.,NaN,Book {Book - Electronic} text; computer; onlin...,"Hausman, Blake M. (Lincoln : University of Neb...",Tour guides (Persons) -- Fiction.;Cherokee Ind...,Native Storiers: A Series of American Narratives,NaN,2022-05-22 18:20:00,NaN,NaN,NaN,English,2020-04-21 12:03:00,English,9780803235052; 9780803239265,9780803235052; 9780803239265,NaN,NaN,(MiAaPQ)EBC842584; (Au-PeEL)EBL842584; (CaPaEB...,9925903515702311,96,NaN,NaN,NaN,813/.6,PS3608.A8765 -- R53 2011eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,1,0,1 online resource (378 pages),NaN,1,0,0,0,0,https://ebookcentral.proquest.com/lib/utk/deta...,9780803235052; 0803235054; 9780803239265; 0803...,9780803235052; 0803235054; 9780803239265; 0803...,9925903515702311,Riding the Trail of Tears.,ProQuest Ebook Central Ebooks Individually Pur...,Available,Online Access - Unlimited Users,53328205250002311,1,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Online Access - Unlimited Users; https://ebook...
2,Mindset : the new psychology of success / Caro...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dweck, Carol S., (New York : Random House, �20...",Belief and doubt.;Success--Psychological aspec...,NaN,NaN,2025-12-30 10:19:00,1st ed.,NaN,NaN,English,2020-04-04 12:01:00,NaN,9781588365231 (electronic bk.); 1588365239 (el...,9781588365231 (electronic bk.); 9781588365231 ...,NaN,NaN,99984145812; (NhCcYBP)ybp11759037,9925901259602311,97,NaN,NaN,BF 637.S8 D989 2006,153.8,BF773 .D85 2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (x, 276 pages.)",NaN,1,0,0,0,0,http://search.ebscohost.com/login.aspx?direct=...,1588365239; 9781588365231; 9781400062751; 1400...,1588365239; 9781588365231; 9781400062751; 1400...,9925901259602311,Mindset : the new psychology of success /,EBSCO Ebooks Individually Purchased,Available,Online Access - 1 user,53327845480002311,1,NaN,NaN,[http://search.ebscohost.com/login.aspx?direct...,http://search.ebscohost.com/login.aspx?direct=...,Online Access - 1 user,http://search.ebscohost.com/login.aspx?direct=...
3,Nature's Best Hope : A New Approach to Conserv...,NaN,Book {Book - Electronic} text; computer; onlin...,"Tallamy, Douglas W. (North Adams : Timber Pres...",Environmental protection.;Electronic books.,NaN,NaN,2022-05-24 04:38:00,NaN,NaN,NaN,English,2020-02-26 22:01:00,English,9781604699791; 9781604699005,9781604699791; 9781604699005,NaN,NaN,(MiAaPQ)EBC5972411; (Au-PeEL)EBL5972411; (OCoL...,9925885557002311,89,NaN,NaN,NaN,363.7,TD170 .T355 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,1,0,1 online resource (257 pages),NaN,0,0,0,0,0,https://ebookcentral.proquest.com/lib/utk/deta...,9781604699791; 1604699795; 9781604699005; 1604...,9781604699791; 1604699795; 9781604699005; 1604...,9925885557002311,Nature's Best Hope : A New Approach to Conserv...,ProQuest Ebook Central Ebooks Individually Pur...,Available,NaN,53325019480002311,1,NaN,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,https://ebookcentral.proquest.com/lib/utk/deta...
4,"Skill acquisition in sport : research, theory ...",NaN,Book {Book - Electronic} text; computer; onlin...,"Hodges, Nicola J., (Abingdon, Oxon ; New York,...",Sports sciences--Research.;Perceptual-motor le...,NaN,NaN,2022-11-07 04:18:00,Third edition.,NaN,NaN,English,2019-12-26 22:08:00,NaN,9781351189750 (electronic bk.); 1351189751 (el...,9781351189750 (electronic bk.); 9781351189750 ...,NaN,NaN,(NhCcYBP)ybp16168410,9925871824802311,91,NaN,NaN,NaN,796.07,GV558 .S57 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,1,0,"1 online resource (xxiv, 363 pages) :",NaN,1,0,0,0,0,https://www.taylorfrancis.com/books/9781351189...,1351189751; 9781351189750; 9781351189736; 1351...,1351189751; 9781351189750; 9781351189736; 1351...,9925871824802311,"Skill acquisition in sport : research, theory ...",Taylor & Francis Ebooks Individually Purchased,Available,Online Access - Unlimited users (DRM-free),53323272990002311,1,NaN,NaN,[https://www.taylorfrancis.com/books/978135118...,https://www.taylorfrancis.com/books/9781351189750,Online Access - Unlimited users (DRM-free),https://www.taylorfrancis.com/books/9781351189...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,Debating reform [electronic resource] : confli...,NaN,Book {Book - Electronic} text; computer; onlin...,"Ellis, Richard J.; Nelson, Michael (Los Angele...",Political participation--United States.;United...,NaN,NaN,2025-12-13 04:01:00,Fourth edition.,NaN,NaN,English,2025-12-12 14:16:00,NaN,9781544390598; 1544390599; 9781544390451; 9781...,9781544390598; 9781544390598; 9781544390451; 9...,NaN,NaN,(CaONFJC)cis056852840,9926839499602311,93,NaN,NaN,NaN,320.60973,JK274 .D398 2021eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xiv, 386 pages) :",NaN,0,0,0,0,0,https://search.ebscohost.com/login.aspx?direct...,1544390599; 9781544390598; 9781544390451; 1544...,1544390599; 9781544390598; 9781544390451; 1544...,9926839499602311,Debating reform conflicting perspectives on ho...,EBSCO Ebooks Individually Purchased,Available,NaN,53446796630002311,1,NaN,Unlimited Access,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Unlimited Access; https://search.ebscohost.com...
248,The museum of unnatural histories / Annie Wens...,NaN,Book {Book - Electronic} text; computer; onlin...,"Wenstrup, Annie, (Middletown, Connecticut : We...",Gender identity--Poetry.;Race--Poetry.;Culture...,Wesleyan poetry.,NaN,2025-12-30 10:17:00,NaN,NaN,NaN,English,2025-12-11 10:17:00,English,0819501832; 9780819501837; 9780819501875,9780819501837; 9780819501837; 9780819501875,NaN,NaN,(OCoLC)1460025709; (OCoLC)on1460025709,9926839378502311,98,NaN,NaN,NaN,811/.6,PS3623.E574 M87 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Project Muse; Project Mu...,NaN,NaN,1,0,1 online resource (96 pages).,NaN,0,0,0,0,0,https://muse.jhu.edu/book/125818/ Full text av...,9780819501837; 0819501832; 9780819501820; 0819...,9780819501837; 0819501832; 9780819501820; 0819...,9926839378502311,The museum of unnatural histories /,Project Muse Ebooks Individually Purchased,Available,Online Access - Unlimited Users,53446391740002311,1,NaN,NaN,"[https://muse.jhu.edu/book/125818/, Full, text...",https://muse.jhu.edu/book/125818/,Full text available:,Online Access - Unlimited Users; https://muse....
249,Teaching English as a foreign or second langua...,NaN,Book {Book - Electronic} text; computer; onlin...,"Gebhard, Jerry Greer, (Ann Arbor, Michigan : U...",English language--Study and teaching--Foreign ...,NaN,NaN,2025-12-30 10:18:00,Third edition.,NaN,NaN,English,2025-12-12 14:19:00,NaN,9780472036738; 9780472123698 (Proquest Ebook C...,9780472036738; 9780472123698 (Proquest Ebook C...,NaN,NaN,(MiAaPQ)EBC7047443; (OCoLC)1337071197; (CaONFJ...,9926839277802311,88,NaN,NaN,NaN,428.00711,PE1128.A2 .G434 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,1,0,1 online resource (223 pages) :,NaN,0,0,0,0,0,https://ebookcentral.proquest.com/lib/utk/deta...,9780472123698; 0472123696; 9780472036738; 0472...,9780472123698; 0472123696; 9780472036738; 0472...,9926839277802311,Teaching English as a foreign or second langua...,ProQuest Ebook Central Rialto,Available,NaN,53446752960002311,1,NaN,Unlimited Access,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,https://ebookcentral.proquest.com/lib/utk/deta...
250,Recent developments in southeastern archaeolog...,NaN,Book {Book - Electronic} text; computer; onlin...,"Anderson, David G., (Washington, DC : Society ...",Excavations (Archaeology)--Southern States.;In...,SAA contemporary perspectives,NaN,2025-12-13 04:01:00,NaN,NaN,NaN,English,2025-12-12 11:41:00,NaN,9780932839435; 0932839436; 9781646425594 (JSTOR),9780932839435; 9780932839435; 9781646425594 (J...,NaN,NaN,(CaONFJC)cis066443973,9926839178002311,89,NaN,NaN,NaN,975/.01,E78.S65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at JSTOR; JSTOR Ebooks (JST...,NaN,NaN,1,0,1 online resource.,NaN,0,0,0,0,0,https://www.jstor.org/stable/10.2307/jj.385048...,0932839436; 9780932839435; 9781646425594; 1646...,0932839436; 9780932839435; 9781646425594; 1646...,9926839178002311,Recent developments in southeastern archaeolog...,JSTOR Rialto Implementation,Available,NaN,53446823390002311,1,NaN,Unlimited Access,[https://www.jstor.org/stable/10.2307/jj.38504...,https://www.jstor.org/stable/10.2307/jj.3850488,Unlimited Access Unlimited Access,https://www.jstor.org/stable/10.2307/jj.385048...
251,"Crack [electronic resource] : rock cocaine, st...",NaN,Book {Book - Electronic} text; computer; onlin...,"Farber, David, (Cambridge, United Kingdom : Ca...",Crack (Drug)--United States.;Drug addicts--Uni...,NaN,NaN,2025-12-30 10:18:00,NaN,NaN,NaN,English,2025-12-12 12:44:00,NaN,9781108425278; 1108425275; 9781108606394; 9781...,9781108425278; 9781108425278; 9781108606394; 9...,NaN,NaN,(CaONFJC)cis056979768,9926839177902311,84,NaN,NaN,NaN,362.29/8097309048,HV5810 .F37 2019eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Cambridge University Pre...,NaN,NaN,1,0,"1 online resource (x, 214 pages) :",NaN,0,0,0,0,0,http://dx.doi.org/10.1017/9781108349055 Unlimi...,1108425275; 9781108425278; 9781108606394; 1108...,1108425275; 9781108425278; 9781108606394; 1108...,9926839177902311,"Crack rock cocaine, street capitalism, and the...",Cambridge University Press Ebooks Individually...,Available,NaN,53446823350002311,1,NaN,Unlimited Access,"[http://dx.doi.org/10.1017/9781108349055, Unli...",http://dx.doi.org/10.1017/9781108349055,Unlimited Access Unlimited Access,Unlimited Access; http://dx.doi.org/10.1017/97...

In [49]:
#resultsPlusList.to_excel('Results Plus List Example.xlsx')

resultsPlusList.sort_values(by = 'Title_x')['Title_x'].unique()

array(['A Course in Enumeration [electronic resource] / by Martin Aigner.',
       'A Pocket Style Manual [electronic resource].',
       'A Practical Guide to Commercial Real Estate Transactions : From Contract to Closing, Third Edition.',
       'A Practice of Anesthesia for Infants and Children.',
       'A Short Course in Reading French / Celia Brickman ; cover design, Lisa Hamm.',
       'A companion to paleopathology / edited by Anne L. Grauer.',
       'A comprehensive guide to coding and programming in Stata / Rafael Gafoor.',
       'A history of the American musical theatre : no business like it / Nathan Hurwitz.',
       'A mercy / Toni Morrison.',
       'Affrilachia : poems / by Frank X. Walker.',
       'After Victory :  Institutions, Strategic Restraint, and the Rebuilding of Order after Major Wars /  G. John Ikenberry.',
       'After hegemony : cooperation and discord in the world political economy / Robert O. Keohane, with a new preface by the author.',
       'Always get the name of the dog : a guide to media interviewing / Nicole Kraft Ed.D.',
       "American Democracy in Peril : Eight Challenges to America's Future / William E. Hudson.",
       'American military life in the 21st century : social, cultural, and economic issues and trends / Eugenia L. Weiss and Carl Andrew Castro, editors.',
       'An Introduction to Scientific Computing : Fifteen Computational Projects Solved with MATLAB.',
       'An Unseen Light : Black Struggles for Freedom in Memphis, Tennessee.',
       'An unkindness of ghosts / Rivers Solomon.',
       'Anger : The Conflicted History of an Emotion.',
       'Anger : the conflicted history of an emotion / Barbara H. Rosenwein.',
       'Appeals in Modern Rhetoric An Ordinary Language Approach / M. Jimmie Killingsworth.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Assessment in Student Affairs, Second Edition.',
       'Assessment in counseling : procedures and practices / Danica G. Hays.',
       'Becoming a data head : how to think, speak, and understand data science, statistics, and machine learning / Alex J. Gutman, Jordan Goldmeier.',
       'Beloved / a novel by Toni Morrison.',
       'Bestiary [electronic resource] : being an English version of the Bodleian Library, Oxford M.S. Bodley 764 : with all the original miniatures reproduced in facsimile / translated and introduced by Richard Barber.',
       'Biomechanics of Movement : The Science of Sports, Robotics, and Rehabilitation.',
       'Building the American republic. Volume 2, A narrative history from 1877 / Jane Dailey.',
       'Case studies in deaf education : inquiry, application, and resources / Caroline Guardino, Jennifer S. Beal, Joanna E. Cannon, Jenna Voss, and Jessica P. Bergeron.',
       'Caste : the origins of our discontents / Isabel Wilkerson.',
       'Catalog of unabashed gratitude / Ross Gay.',
       'Ceremony / Leslie Marmon Silko ; introduction by Larry McMurtry ; with a new preface by the author.',
       'Chief sustainability officers at work [electronic resource] : how CSOs build successful sustainability and ESG strategies / Chrissa Pagitsas.',
       'Computer organization and design : the hardware/software interface : ARM edition / David A. Patterson, John L. Hennessy.',
       'Concise Guide to Child and Adolescent Psychiatry.',
       'Condensed matter physics / Michael P. Marder.',
       'Conflict Resolution for the Helping Professions : Negotiation, Mediation, Advocacy, Facilitation, and Restorative Justice.',
       'Conflict resolution for the helping professions : negotiation, mediation, advocacy, facilitation, and restorative justice / Allan Edward Barsky.',
       'Copaganda : how police and the media manipulate our news / Alec Karakatsanis.',
       "Coté and Lerman's a practice of anesthesia for infants and children / [edited by] Charles Coté, Jerrold Lerman, Brian J. Anderson.",
       'Counseling children and adolescents : cultivating empathic connection / Rebekah Byrd and Chad Luke.',
       'Crack [electronic resource] : rock cocaine, street capitalism, and the decade of greed / David Farber.',
       'Cracked, not broken [electronic resource] : surviving and thriving after a suicide attempt / Kevin Hines.',
       'Crafting The Personal Essay : A Guide for Writing and Publishing Creative Non-Fiction.',
       'Crafting the personal essay : a guide for writing and publishing creative nonfiction / Dinty W. Moore.',
       'DeFi and the Future of Finance.',
       'Deaf people and society : psychological, sociological and educational perspectives / Irene W. Leigh, Jean F. Andrews, Cara A. Miller, and Ju-Lee A. Wolsey.',
       'Debating reform [electronic resource] : conflicting perspectives on how to fix the American political system / Richard J. Ellis (Willamette University), Michael C. Nelson (Rhodes College), editors.',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Development as freedom / Amartya Sen.',
       'Differential geometry : curves, surfaces, manifolds / Wolfgang Kühnel ; translated by Bruce Hunt.',
       'Elegant legal writing / Ryan McCarl.',
       'Elementary number theory / Underwood Dudley, DePauw University.',
       'Engineering capstone design / Bahram Nassersharif.',
       'Enviromedics : the impact of climate change on human health / Jay Lemery and Paul Auerbach.',
       'Essentials of Assessment Report Writing.',
       'Essentials of Food Science [electronic resource] / by Vickie A. Vaclavik, Elizabeth W. Christian.',
       'Euclidean Geometry : A Guided Inquiry Approach / David M. Clark.',
       "Evelina : or, The history of a young lady's entrance into the world / Frances Burney ; edited by Edward A. Bloom ; with an introduction and notes by Vivien Jones.",
       'Everything is obvious : once you know the answer / Duncan J. Watts.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Facilitating Breakthrough : How to Remove Obstacles, Bridge Differences, and Move Forward Together',
       'Fighting Against the Injustice of the State and Globalization [electronic resource] : Comparing the African American and Oromo Movements / by A. Jalata.',
       'Finance for real estate development [electronic resource] / Charles Long.',
       'Financial Literacy for Managers : Finance and Accounting for Better Decision-Making / Richard A. Lambert.',
       'Financial Statements.',
       'Financial and business management for the doctor of nursing practice / KT Waxman.',
       'Financial literacy for managers : finance and accounting for better decision-making / Richard A. Lambert.',
       'Forensic Anthropology : An Introductory Lab Manual.',
       'Frankenstein [electronic resource] / Mary Shelley.',
       'Fully nonlinear elliptic equations / Luis A. Caffarelli, Xavier Cabré.',
       'Fun home [electronic resource] : A family tragicomic. Alison Bechdel.',
       'Fundamentals of physics. II, Electromagnetism, optics, and quantum mechanics / R. Shankar.',
       'Gender and the Musical Canon [electronic resource].',
       'Getting real about inequality : intersectionality in real life (IRL) / editors,  Cherise A. Harris, Stephanie M. McClure.',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Globalization of education : an introduction / Joel Spring.',
       'Government and Politics in Tennessee [electronic resource].',
       'Hablar español en Estados Unidos : la sociopolítica del lenguaje / Jennifer Leeman y Janet M. Fuller.',
       'Halfway home : race, punishment, and the afterlife of mass incarceration / Reuben Jonathan Miller.',
       'Handbook for Classical Research.',
       'Handbook for classical research [electronic resource] / David M. Schaps.',
       'Head off & split [electronic resource] : poems / Nikky Finney.',
       'High fidelity [electronic resource] / Nick Hornby.',
       'How languages are learned / Patsy M. Lightbown & Nina Spada.',
       'How to Keep Your Cool : An Ancient Guide to Anger Management / Seneca.',
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'Human rights and social justice in a global perspective : an introduction to international social work / Susan C. Mapp.',
       'I, robot / Isaac Asimov.',
       'INTRODUCTION TO AMERICAN DEAF CULTURE [electronic resource].',
       'Information Architecture for the World Wide Web : Designing Large-Scale Web Sites.',
       'Information science : the basics / Judith Pintar and David Hopping.',
       'International Energy Markets : Understanding Pricing, Policies, and Profits.',
       'International financial statement analysis / Thomas R. Robinson, Elaine Henry, Michael A. Broihahn.',
       'International trade and agriculture [electronic resource] / Won W. Koo and P. Lynn Kennedy.',
       'Interpersonal communication : putting theory into practice / Denise Solomon and Jennifer Theiss.',
       'Interpersonal communication : putting theory into practice / Denise Solomon, Jennifer Theiss.',
       'Introduction to Applied Nonlinear Dynamical Systems and Chaos [electronic resource] / by Stephen Wiggins.',
       'Introduction to industrial organization. / Luis M.B. Cabral.',
       'Introduction to stochastic processes / Erhan Cinlar.',
       'Invasive species : what everyone needs to know / Daniel Simberloff.',
       'Just practice : a social justice approach to social work / Janet L. Finn.',
       'Language, truth, and logic / by Alfred Jules Ayer.',
       'Leading with questions : how leaders discover powerful answers by knowing how and what to ask / Michael J. Marquardt and Bob Tiede.',
       'Let nobody turn us around [electronic resource] : voices of resistance, reform, and renewal : an African American anthology / editors, Manning Marable, Leith Mullings.',
       'Linear Systems Theory : Second Edition / João P. Hespanha.',
       'Linguistics of American Sign Language, 5th Ed. :  An Introduction /  Clayton Valli [and others].',
       'Make it stick : the science of successful learning / Peter C. Brown, Henry L. Roediger III, Mark A. McDaniel.',
       'Making race and nation : a comparison of South Africa, the United States, and Brazil / Anthony W. Marx.',
       'Management consulting projects : a step-by-step experiential guide / Ronald Cook, Michael Harris and Dennis Barber III.',
       "Managing vulnerability [electronic resource] : South Africa's struggle for a democratic rhetoric / Richard C. Marback.",
       'Mastering QGIS - Second Edition.',
       'Maximizing the impact of comics in your library : graphic novels, manga, and more / Jack Phoenix.',
       'Me and my daddy listen to Bob Marley : novellas and stories / Ann Pancake.',
       'Metals and Society [electronic resource] : An Introduction to Economic Geology / by Nicholas Arndt, Clément Ganino.',
       'Milk and filth [electronic resource] / Carmen Gimenez Smith.',
       'Mindset : the new psychology of success / Carol S. Dweck.',
       'Modular forms [electronic resource] : a classical and computational introduction / L.J.P. Kilford.',
       "My grandmother's hands : racialized trauma and the pathway to mending our hearts and bodies / Resmaa Menakem.",
       "Nature's Best Hope : A New Approach to Conservation That Starts in Your Yard.",
       'New kid [electronic resource]. Jerry Craft.',
       'Next steps : decision cases for social work practice / Lori D. Franklin, Jonathan R. Kratz, and Karen A. Gray.',
       'Nonlinear Dynamics and Chaos : With Applications to Physics, Biology, Chemistry, and Engineering / Steven H. Strogatz.',
       'Obit : poems / Victoria Chang.',
       "Ortner's identification of pathological conditions in human skeletal remains / edited by Jane E. Buikstra.",
       'Pedagogical grammar / Casey M. Keck, YouJin Kim.',
       'Pedagogy of the Oppressed : 30th Anniversary Edition.',
       'Performance appraisal and management / Kevin R. Murphy, Jeanette N. Cleveland, Madison E. Hanscom.',
       'Persuasion in your life / Shawn T. Wahl, Eric Morris.',
       'Planetary Geology : An Introduction.',
       'Pocket guide to nutrition assessment / Pamela Charney, PhD, RDN, LD, FAND, Ainsley Malone, MS, RDN, LD, CNSC, FAND, FASPEN.',
       'Principles of trauma therapy : a guide to symptoms, evaluation, and treatment.',
       'Probability: A Graduate Course [electronic resource] / by Allan Gut.',
       'Property of the Rebel Librarian [electronic resource] / Allison Varnes.',
       'Public speaking for engineers : communicating effectively with clients, the public, and local government / by Christopher A. "Shoots" Veis, P.E. ; foreword by Mark W. Woodson, P.E., L.S., D. WRE.',
       'Pursuing happiness [electronic resource] : a Bedford spotlight reader / [compiled and edited by] Matthew Parfitt, Boston University, Dawn Skorczewski, Brandeis University.',
       'Qualitative research : a guide to design and implementation / Sharan B. Merriam, Elizabeth J. Tisdell.',
       'Quicksand / Nella Larsen ; [new introduction by T.N.R. Rogers].',
       'R for political science research : an introduction for absolute beginners / Jane L. Sumner.',
       'Race and reunion : the Civil War in American memory / David W. Blight.',
       'Racial theories in social science : a systemic racism critique / Sean Elias and Joe R. Feagin.',
       'Recent developments in southeastern archaeology [electronic resource] : from colonization to complexity / David G. Anderson and Kenneth E. Sassaman.',
       'Recreation Programming : Designing, Staging, and Managing the Delivery of Leisure Experiences.',
       'Regression analysis and linear models : concepts, applications, and implementation / Richard B. Darlington, Andrew F. Hayes.',
       'Research Methods in Library and Information Science / Lynn Silipigni Connaway and Marie L. Radford.',
       'Research methods for social work : a problem-based approach / Antoinette Y. Farmer, G. Lawrence Farmer.',
       'Riding the Trail of Tears.',
       'Rules of play : game design fundamentals / Katie Salen and Eric Zimmerman.',
       'Science Notebooks in Student-Centered Classrooms.',
       'Scraping by : wage labor, slavery, and survival in early Baltimore / Seth Rockman.',
       'Sick enough : a guide to the medical complications of eating disorders and undernutrition / Jennifer L. Gaudiani.',
       'Silas Marner : the weaver of Raveloe / George Eliot ; edited with an introduction and notes by Juliette Atkinson.',
       'Skill acquisition in sport : research, theory and practice / edited by Nicola J. Hodges and A. Mark Williams.',
       'Social movements : the structure of collective mobilization / Paul Almeida.',
       'Social theory of international politics / Alexander Wendt.',
       'Social work values and ethics / Frederic G. Reamer.',
       'Socratic questioning for therapists and counselors : learn how to think and intervene like a cognitive behavior therapist / Scott H. Waltman, R. Trent Codd, III, Lynn M. McFarr, and Bret A. Moore.',
       'Sounding Like a No-No : Queer Sounds and Eccentric Acts in the Post-Soul Era.',
       'Sounding like a no-no : queer sounds and eccentric acts in the post-soul era / Francesca T. Royster.',
       'Sounding like a no-no? [electronic resource] : queer sounds and eccentric acts in the post-soul era / Francesca T. Royster.',
       'Statistical Mechanics : Principles and Selected Applications.',
       'Statistical mechanics / Donald A. McQuarrie.',
       'Stochastic Differential Equations [electronic resource] : An Introduction with Applications / by Bernt Øksendal.',
       "Stoelting's pharmacology & physiology in anesthetic practice [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman",
       'Storytelling with data : a data visualization guide for business professionals / Cole Nussbaumer Knaflic.',
       'Storytelling with you : plan, create, and deliver a stellar presentation / Cole Nussbaumer Knaflic ; illustrations by Catherine Madden.',
       'Strategic planning for public relations [electronic resource] / [edited by] Ronald D. Smith.',
       'Strategy in 3D : essential tools to diagnose, decide, & deliver / Greg Fisher, John E. Wisneski, Rene M. Bakker.',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time / Gerald Feigin.',
       'Survey Research and Analysis.',
       'Systematic instruction for students with moderate and severe disabilities [electronic resource] / Belva C. Collins, Ed.D, Professor Emeritus, University of North Carolina at Charlotte and University of Kentucky.',
       'Systems engineering : principles and practice / Alexander Kossiakoff, Samuel J. Seymour, David A. Flanigan, Steven M. Biemer.',
       'Systems thinking for social change : a practical guide to solving complex problems, avoiding unintended consequences, and achieving lasting results / David Peter Stroh.',
       'Teaching English as a foreign or second language : a self-development and methodology guide / Jerry G. Gebhard.',
       'Teaching and learning STEM [electronic resource] : a practical guide / Richard M. Felder and Rebecca Brent.',
       "Teaching strings in today's classroom : a guide for group instruction / Rebecca B. MacLeod.",
       'Textbook of drug design and discovery / edited by Povl Krogsgaard-Larsen, Kristian Strømgaard, Ulf Madsen.',
       'The Antinomian controversy, 1636-1638 : a documentary history / edited with introduction and notes by David D. Hall.',
       'The Basics of Public Budgeting and Financial Management : A Handbook for Academics and Practitioners.',
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The Ethical Executive : Becoming Aware of the Root Causes of Unethical Behavior: 45 Psychological Traps that Every One of Us Falls Prey To / Paul Hersey, Robert Hoyk.',
       'The Grapes of wrath / John Steinbeck ; introduction and notes by Robert DeMott.',
       'The Ideal Team Player : How to Recognize and Cultivate the Three Essential Virtues.',
       'The Iliad.',
       "The Mediator's Handbook : Revised & Expanded fourth edition.",
       'The Routledge handbook of festivals / edited by Judith Mair.',
       'The Student Leadership Challenge  : Student Workbook and Leadership Journal / James Kouzes; Barry Posner ; with Lisa Hannon and Bathild Junius "June" Covington.',
       'The Sun Also Rises : The Hemingway Library Edition.',
       'The Trojans & Their Neighbours.',
       'The art of the pitch [electronic resource] : persuasion and presentation skills that win business / Peter Coughter.',
       'The beast within : animals in the Middle Ages / Joyce E. Salisbury.',
       'The bluest eye : a novel / Toni Morrison ; [with a foreword by the author].',
       'The design of everyday things / Don Norman.',
       'The evaluation and measurement of library services [electronic resource] / Joseph R. Matthews.',
       'The great Arizona orphan abduction / Linda Gordon.',
       'The ideal team player : how to recognize and cultivate the three essential virtues : a leadership fable / Patrick Lencioni.',
       'The life of Saint Katherine of Alexandria [electronic resource] / by John Capgrave ; translated by Karen A. Winstead.',
       'The live music business : management and production of concerts and festivals / Andy Reynolds.',
       'The museum of unnatural histories / Annie Wenstrup.',
       'The portable feminist reader / edited with an introduction by Roxane Gay.',
       'The professor is in : the essential guide to turning your Ph.D. into a job / Karen Kelsky, Ph.D.',

### Expand the ISBN Normalized Column

In [50]:
resultsPlusList['ISBN (Normalized) List'] = resultsPlusList['ISBN (Normalized)'].apply(lambda x: x.split(";"))

In [51]:
expandedList = resultsPlusList.explode('ISBN (Normalized) List')

expandedList['ISBN (Normalized) List'] = expandedList['ISBN (Normalized) List'].str.strip()

#expandedList.to_excel('Expanded List Example.xlsx')

In [52]:
finalJoin = pd.merge(expandedList, bookstoreList, left_on = 'ISBN (Normalized) List', right_on = 'ISBN', how = 'inner')

#finalJoin

In [53]:
selectiveCols = finalJoin[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN (Normalized) List', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Electronic location', 'Electronic access', 'Electronic Availability']]

selectiveCols = selectiveCols.drop_duplicates()

selectiveCols = selectiveCols.rename(columns = {'Section Code': 'Course Code'})

len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

221

In [54]:
selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique()

array(['(PRINT) FORENSIC ANTHROPOLOGY', '(PRINT) PEDAGOGICAL GRAMMAR',
       '(PRINT) VULNERABILITY AND CRITICAL THEORY',
       'A COMPANION TO PALEOPATHOLOGY',
       'A COMPREHENSIVE GUIDE TO CODING AND PROGRAMMING IN STATA',
       'A COURSE IN ENUMERATION PROBABILITY, A GRADUATE COURSE (FREE DIGITAL ACCESS UTK LIBRARY)',
       'A HISTORY OF THE AMERICAN MUSICAL THEATRE',
       'A POCKET STYLE MANUAL',
       'A PRACTICE OF ANESTHESIA FOR INFANTS AND CHILDREN',
       'A SHORT COURSE IN READING FRENCH',
       'ACADEMY OF NUTRITION AND DIETETICS POCKET GUIDE TO NUTRITION ASSESSMENT',
       'AFFRILACHIA (OLD COVE PRESS)', 'AFTER HEGEMONY',
       'AFTER VICTORY : INSTITUTIONS, STRATEGIC RESTRAINT, AND THE REBUILDING OF ORDER AFTER MAJOR WARS',
       'ALWAYS GET THE NAME OF THE DOG : A GUIDE TO MEDIA INTERVIEWING',
       'AMERICAN DEMOCRACY IN PERIL : EIGHT CHALLENGES TO AMERICAS FUTURE',
       'AMERICAN MILITARY LIFE IN THE 21ST CENTURY : SOCIAL, CULTURAL, AND ECONOMIC ISSUES AND TRENDS [2 VOLUMES]',
       'AN INTRO TO SCIENTIFIC COMPUTING (FREE DIGITAL ACCESS UTK LIBRARY)',
       'AN UNKINDNESS OF GHOSTS',
       'AN UNSEEN LIGHT : BLACK STRUGGLES FOR FREEDOM IN MEMPHIS, TENNESSEE',
       'ANGER : THE CONFLICTED HISTORY OF AN EMOTION',
       'APPEALS IN MODERN RHETORIC',
       'APPEALS IN MODERN RHETORIC : AN ORDINARY LANGUAGE APPROACH',
       'APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS : CONCEPTS AND CASES',
       'ASSESSMENT IN COUNSELING : PROCEDURES AND PRACTICES',
       'ASSESSMENT IN STUDENT AFFAIRS', 'BECOMING A DATA HEAD',
       'BECOMING A DATA HEAD : HOW TO THINK, SPEAK, AND UNDERSTAND DATA SCIENCE, STATISTICS, AND MACHINE LEARNING',
       'BELOVED',
       'BESTIARY : BEING AN ENGLISH VERSION OF THE BODLEIAN LIBRARY, OXFORD, MS BODLEY 764',
       'BIOMECHANICS OF MOVEMENT : THE SCIENCE OF SPORTS, ROBOTICS, AND REHABILITATION',
       'BUILDING THE AMERICAN REPUBLIC, VOLUME 2 : A NARRATIVE HISTORY FROM 1877',
       'CASE STUDIES IN DEAF EDUCATION : INQUIRY, APPLICATION, AND RESOURCES',
       'CASTE : THE ORIGINS OF OUR DISCONTENTS',
       'CATALOG OF UNABASHED GRATITUDE', 'CEREMONY',
       'CHIEF SUSTAINABILITY OFFICERS AT WORK',
       'COMPUTER ORGANIZATION AND DESIGN ARM EDITION : THE HARDWARE SOFTWARE INTERFACE',
       'CONCISE GUIDE TO CHILD AND ADOLESCENT PSYCHIATRY',
       'CONDENSED MATTER PHYSICS',
       'CONFLICT RESOLUTION FOR THE HELPING PROFESSIONSUSTICE',
       'COPAGANDA : HOW POLICE AND THE MEDIA MANIPULATE OUR NEWS',
       'COUNSELING CHILDREN AND ADOLESCENTS',
       'CRACK : ROCK COCAINE, STREET CAPITALISM, AND THE DECADE OF GREED',
       'CRACKED NOT BROKEN',
       'CRAFTING THE PERSONAL ESSAY : A GUIDE FOR WRITING AND PUBLISHING CREATIVE NON-FICTION',
       'DEAF PEOPLE AND SOCIETY : PSYCHOLOGICAL, SOCIOLOGICAL, AND EDUCATIONAL PERSPECTIVES',
       'DEBATING REFORM : CONFLICTING PERSPECTIVES ON HOW TO FIX THE AMERICAN POLITICAL SYSTEM',
       'DEBATING REFORM: CONFLICTING PERSPECTIVES',
       'DEFI AND THE FUTURE OF FINANCE',
       'DEMAND AND SUPPLY INTEGRATION : THE KEY TO WORLD-CLASS DEMAND FORECASTING, SECOND EDITION',
       'DESIGN OF EVERYDAY THINGS W/LIFETIME ACCESS',
       'DEVELOPMENT AS FREEDOM',
       'DIFFERENTIAL GEOMETRY : CURVES - SURFACES - MANIFOLDS',
       'ELEGANT LEGAL WRITING', 'ELEMENTARY NUMBER THEORY',
       'ENGINEERING CAPSTONE DESIGN',
       'ENVIROMEDICS : THE IMPACT OF CLIMATE CHANGE ON HUMAN HEALTH',
       'ESSENTIALS OF ASSESSMENT REPORT WRITING',
       'ESSENTIALS OF FOOD SCIENCE',
       'EUCLIDEAN GEOMETRY : A GUIDED INQUIRY APPROACH',
       'EVALUATION AND MEASUREMENT OF LIBRARY SERVICES', 'EVELINA',
       'EVERYTHING IS OBVIOUS : HOW COMMON SENSE FAILS US', 'EVICTED',
       'FACILITATING BREAKTHROUGH : HOW TO REMOVE OBSTACLES, BRIDGE DIFFERENCES, AND MOVE FORWARD TOGETHER&NBSP;',
       'FIGHTING AGAINST INJUSTICE OF STATE',
       'FINANCE FOR REAL ESTATE DEVELOPMENT',
       'FINANCIAL AND BUSINESS MANAGEMENT FOR THE DOCTOR OF NURSING PRACTICE',
       'FINANCIAL LITERACY FOR MANAGERS : FINANCE AND ACCOUNTING FOR BETTER DECISION-MAKING',
       'FINANCIAL STATEMENTS', 'FRANKENSTEIN',
       'FULLY NONLINEAR ELLIPTIC EQUATIONS',
       'FUN HOME : A FAMILY TRAGICOMIC',
       'FUNDAMENTALS OF PHYSICS II : ELECTROMAGNETISM, OPTICS, AND QUANTUM MECHANICS',
       'GENDER AND THE MUSICAL CANON',
       'GETTING REAL ABOUT INEQUALITY : INTERSECTIONALITY IN REAL LIFE',
       'GLOBAL WRITING FOR PUBLIC RELATIONS : CONNECTING IN ENGLISH WITH STAKEHOLDERS AND PUBLICS WORLDWIDE',
       'GLOBALIZATION OF EDUCATION',
       'GOVERNMENT AND POLITICS IN TENNESSEE',
       'HABLAR ESPANOL EN ESTADOS UNIDOS : LA SOCIOPOLITICA DEL LENGUAJE',
       'HALFWAY HOME : RACE, PUNISHMENT, AND THE AFTERLIFE OF MASS INCARCERATION',
       'HANDBOOK F/CLASSICAL RESEARCH', 'HEAD OFF & SPLIT',
       'HIGH FIDELITY', 'HOW LANGUAGES ARE LEARNED',
       'HOW TO KEEP YOUR COOL : AN ANCIENT GUIDE TO ANGER MANAGEMENT',
       'HUMAN OSTEOLOGY',
       'HUMAN RIGHTS AND SOCIAL JUSTICE IN A GLOBAL PERSPECTIVE',
       'I, ROBOT', 'INFORMATION ARCHITECTURE F/WORLD WI',
       'INFORMATION SCIENCE : THE BASICS',
       'INTERNATIONAL ENERGY MARKETS : UNDERSTANDING PRICING, POLICIES AND PROFITS',
       'INTERNATIONAL FINANCIAL STATEMENT ANALYSIS',
       'INTERNATIONAL TRADE AND AGRICULTURE : THEORIES AND PRACTICES',
       'INTERPERSONAL COMMUNICATION',
       'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'INTRODUCTION TO APPLIED NONLINEAR DYNAMICAL SYSTEMS AND CHAOS',
       'INTRODUCTION TO INDUSTRIAL ORGANIZATION, SECOND EDITION',
       'INTRODUCTION TO STOCHASTIC PROCESSES',
       'INVASIVE SPECIES : WHAT EVERYONE NEEDS TO KNOW?',
       'JUST PRACTICE: A SOCIAL JUSTICE APPROACH TO SOCIAL WORK',
       'LANGUAGE, TRUTH AND LOGIC',
       'LEADING WITH QUESTIONS : HOW LEADERS DISCOVER POWERFUL ANSWERS BY KNOWING HOW AND WHAT TO ASK',
       'LET NOBODY TURN US AROUND', 'LINEAR SYSTEMS THEORY',
       'LINGUISTICS OF ASL: INTRO (W/DVD)',
       'MAKE IT STICK : THE SCIENCE OF SUCCESSFUL LEARNING',
       'MAKING RACE AND NATION', 'MANAGEMENT CONSULTING PROJECTS',
       "MANAGING VULNERABILITY : SOUTH AFRICA'S STRUGGLE FOR A DEMOCRATIC RHETORIC",
       'MASTERING QGIS  SECOND EDITION',
       'MASTERING QGIS - SECOND EDITION',
       'MAXIMIZING THE IMPACT OF COMICS IN YOUR LIBRARY',
       'ME AND MY DADDY LISTEN TO BOB MARLEY : NOVELLAS AND STORIES',
       'MERCY',
       'METALS AND SOCIETY : AN INTRODUCTION TO ECONOMIC GEOLOGY',
       'MILK AND FILTH', 'MINDSET : THE NEW PSYCHOLOGY OF SUCCESS',
       'MODULAR FORMS: A CLASSICAL/COMPUTATIONAL INTRO (FREE DIGITAL ACCESSUTK LIBRARY)',
       "MY GRANDMOTHER'S HANDS : RACIALIZED TRAUMA AND THE PATHWAY TO MENDING OUR HEARTS AND BODIES",
       'NATURES BEST HOPE', 'NEW KID',
       'NEXT STEPS: DECISION CASES F/SOCIAL WORK PRACTICE (FREE DIGITAL ACCESS - UTK LIBRARY)',
       'NONLINEAR DYNAMICS AND CHAOS WITH STUDENT SOLUTIONS MANUAL',
       'OBIT',
       "ORTNER'S IDENTIFICATION OF PATHOLOGICAL CONDITIONS IN HUMAN SKELETAL REMAINS",
       'PEDAGOGY OF THE OPPRESSED 30TH ANNIV ED W/NEW INTRO',
       'PERFORMANCE APPRAISAL & MANAGEMENT', 'PERSUASION IN YOUR LIFE',
       'PLANETARY GEOLOGY : AN INTRODUCTION',
       'PRACTICAL GUIDE TO COMMERCIAL REAL',
       'PRINCIPLES OF TRAUMA THERAPY',
       'PROBABILITY, A GRADUATE COURSE (FREE DIGITAL ACCESS UTK LIBRARY)',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PUBLIC SPEAKING FOR ENGINEERS : COMMUNICATING EFFECTIVELY WITH CLIENTS, THE PUBLIC, AND LOCAL GOVERNMENT',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'QUALITATIVE RESEARCH : A GUIDE TO DESIGN AND IMPLEMENTATION',
       'QUICKSAND',
       'R FOR POLITICAL SCIENCE RESEARCH : AN INTRODUCTION FOR ABSOLUTE BEGINNERS',
       'RACE AND REUNION : THE CIVIL WAR IN AMERICAN MEMORY',
       'RACIAL THEORIES IN SOCIAL SCIENCE',
       'RECENT DEVELOPMENTS IN SOUTHEASTERN ARCHAEOLOGY',
       'RECREATION PROGRAMMING, 8TH ED. DESIGNING, STAGING, AND MANAGING THE DELIVERY OF LEISURE EXPERIENCES',
       'REGRESSION ANALYSIS AND LINEAR MODELS : CONCEPTS, APPLICATIONS, AND IMPLEMENTATION',
       'RESEARCH METHODS FOR SOCIAL WORK : A PROBLEM-BASED APPROACH',
       'RESEARCH METHODS IN LIBRARY AND INFORMATION SCIENCE',
       'RIDING THE TRAIL OF TEARS',
       'RULES OF PLAY : GAME DESIGN FUNDAMENTALS',
       'SCIENCE NOTEBOOKS IN STUDENT-CENTERED CLASSROOMS', 'SCRAPING BY',
       'SICK ENOUGH', 'SILAS MARNER : THE WEAVER OF RAVELOE',
       'SKILL ACQUISITION IN SPORT : THEORY AND PRACTICE',
       'SOCIAL MOVEMENTS : THE STRUCTURE OF COLLECTIVE MOBILIZATION',
       'SOCIAL THEORY OF INTERNATIONAL POLITICS',
       'SOCIAL WORK VALUES AND ETHICS',
       'SOCRATIC QUESTIONING FOR THERAPISTS AND COUNSELORS : LEARN HOW TO THINK AND INTERVENE LIKE A COGNITIVE BEHAVIOR THERAPIST',
       'SOUNDING LIKE A NO-NO : QUEER SOUNDS AND ECCENTRIC ACTS IN THE POST-SOUL ERA',
       'STATISTICAL MECHANICS',
       'STATISTICAL MECHANICS : PRINCIPLES AND SELECTED APPLICATIONS',
       'STOCHASTIC DIFFERENTIAL EQUATIONS : INTRO W/APPLICATIONS (FREE DIGITAL ACCESSUTK LIBRARY)',
       "STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANESTHETIC PRACTICE",
       'STORYTELLING WITH DATA : A DATA VISUALIZATION GUIDE FOR BUSINESS PROFESSIONALS',
       'STORYTELLING WITH YOU : PLAN, CREATE, AND DELIVER A STELLAR PRESENTATION',
       'STRATEGIC PLANNING FOR PUBLIC RELATIONS', 'STRATEGY IN 3D',
       'SUN ALSO RISES', 'SUPPLY CHAIN PLANNING AND ANALYTICS',
       'SURVEY RESEARCH AND ANALYSIS',
       'SYSTEMATIC INSTRUCTION FOR STUDENTS WITH MODERATE AND SEVERE DISABILITIES',
       'SYSTEMS ENGINEERING PRINCIPLES AND PRACTICE',
       'SYSTEMS THINKING FOR SOCIAL CHANGE : A PRACTICAL GUIDE TO SOLVING COMPLEX PROBLEMS, AVOIDING UNINTENDED CONSEQUENCES, AND ACHIEVING LASTING RESULTS',
       'TEACHING AND LEARNING STEM : A PRACTICAL GUIDE',
       'TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUAGE',
       'TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUAGE, THIRD EDITION :',
       "TEACHING STRINGS IN TODAY'S CLASSROOM : A GUIDE FOR GROUP INSTRUCTION",
       'TEXTBOOK OF DRUG DESIGN AND DISCOVERY',
       'THE ANTINOMIAN CONTROVERSY, 16361638 : A DOCUMENTARY HISTORY',
       'THE ART OF THE PITCH : PERSUASION AND PRESENTATION SKILLS THAT WIN BUSINESS',
       'THE BASICS OF PUBLIC BUDGETING AND FINANCIAL MANAGEMENT : A HANDBOOK FOR ACADEMICS AND PRACTITIONERS',
       'THE BEAST WITHIN : ANIMALS IN THE MIDDLE AGES', 'THE BLUEST EYE',
       'THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY VETERINARY SOCIAL WORK',
       'THE ETHICAL EXECUTIVE : BECOMING AWARE OF THE ROOT CAUSES OF UNETHICAL BEHAVIOR: 45 PSYCHOLOGICAL TRAPS THAT EVERY ONE OF US FALLS PREY TO',
       'THE GRAPES OF WRATH', 'THE GREAT ARIZONA ORPHAN ABDUCTION',
       'THE IDEAL TEAM PLAYER : HOW TO RECOGNIZE AND CULTIVATE THE THREE ESSENTIAL VIRTUES',
       'THE ILIAD', 'THE LIFE OF SAINT KATHERINE OF ALEXANDRIA',
       'THE LIVE MUSIC BUSINESS',
       "THE MEDIATOR'S HANDBOOK : REVISED AND EXPANDED FOURTH EDITION",
       'THE MUSEUM OF UNNATURAL HISTORIES',
       'THE PORTABLE FEMINIST READER',
       'THE PROFESSOR IS IN : THE ESSENTIAL GUIDE TO TURNING YOUR PH. D. INTO A JOB',
       'THE ROUTLEDGE HANDBOOK OF FESTIVALS',
       'THE STUDENT LEADERSHIP CHALLENGE : STUDENT WORKBOOK AND LEADERSHIP JOURNAL',
       'THE THEORY AND PRACTICE OF GROUP PSYCHOTHERAPY (REVISED)',
       'THE TROJANS AND THEIR NEIGHBOURS',
       'THE TWO FUNDAMENTAL PROBLEMS OF ETHICS', 'THREE TALES',
       'THROUGH THE ARC OF THE RAIN FOREST',
       'TIME SERIES ECONOMETRICS : LEARNING THROUGH REPLICATION',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER',
       'TRAUMA-FOCUSED ACT',
       'UNDERSTANDING SPIRITUALITY AND THE SACRED IN SOCIAL WORK PRACTICE',
       'UNDERSTANDING SPIRITUALITY AND THE SACRED IN SOCIAL WORK PRACTICE : SPIRITED CONVERSATIONS',
       'UNIVERSITY PHYSICS VOLUME 3 (FREE ACCESS- OPENSTAX)',
       'UNKINDNESS OF GHOSTS',
       'UNLOCKING MULTILINGUAL LEARNERS? POTENTIAL',
       "WATER 4. 0 : THE PAST, PRESENT, AND FUTURE OF THE WORLD'S MOST VITAL RESOURCE",
       'WHAT REALLY WORKS WITH EXCEPTIONAL LEARNERS',
       'WHY PEOPLE DIE BY SUICIDE',
       'WICKED FLESH : BLACK WOMEN, INTIMACY, AND FREEDOM IN THE ATLANTIC WORLD',
       'WITCH HAT ATELIER 1', 'WOMAN WARRIOR', 'WORLD IS A HIGH HILL',
       'WORLD RELIGIONS IN SEVEN SENTENCES : A SMALL INTRODUCTION TO A VAST TOPIC',
       'YAGUARETE WHITE', 'YVAIN : THE KNIGHT OF THE LION',
       'ZAMI: A NEW SPELLING OF MY NAME : A BIOMYTHOGRAPHY'], dtype=object)

In [55]:
# Filter out the titles whose access is not Unlimited

selectiveCols = selectiveCols[(selectiveCols['Electronic access'] != 'Online Access - 1 user') & (selectiveCols['Electronic access'] != 'Single User Single User') & (selectiveCols['Electronic access'] != 'Three User Three User') & (selectiveCols['Electronic access'] != 'Online Access - 3 users') & (selectiveCols['Electronic access'] != 'Online access : 2 simultaneous users; http://www.ebrary.com/corp/legal.jsp Click here for terms of use') & (selectiveCols['Electronic access'] != 'Online access - 1 simultaneous user') & (selectiveCols['Electronic access'] != 'Online Access - 3 simultaneous users.')]

selectiveCols = selectiveCols[(selectiveCols['Short Title'] != 'CEREMONY') & (selectiveCols['Short Title'] != 'CRAFTING THE PERSONAL ESSAY : A GUIDE FOR WRITING AND PUBLISHING CREATIVE NON-FICTION') & (selectiveCols['Short Title'] != 'EVERYTHING IS OBVIOUS : HOW COMMON SENSE FAILS US') & (selectiveCols['Short Title'] != 'FUN HOME : A FAMILY TRAGICOMIC') & (selectiveCols['Short Title'] != 'INFORMATION ARCHITECTURE F/WORLD WI') & (selectiveCols['Short Title'] != 'ME AND MY DADDY LISTEN TO BOB MARLEY : NOVELLAS AND STORIES') & (selectiveCols['Short Title'] != 'PUBLIC LIBRARIES AND THEIR COMMUNITIES') & (selectiveCols['Short Title'] != 'STRATEGIC PLANNING FOR PUBLIC RELATIONS') & (selectiveCols['Short Title'] != 'SUN ALSO RISES') & (selectiveCols['Short Title'] != 'THE PROFESSOR IS IN : THE ESSENTIAL GUIDE TO TURNING YOUR PH. D. INTO A JOB') & (selectiveCols['Short Title'] != "ALL THAT SHE CARRIED : THE JOURNEY OF ASHLEY'S SACK, A BLACK FAMILY KEEPSAKE") & (selectiveCols['Short Title'] != 'INTERPERSONAL COMMUNICATION') & (selectiveCols['Short Title'] != 'LET NOBODY TURN US AROUND') & (selectiveCols['Short Title'] != 'LINEAR SYSTEMS THEORY') & (selectiveCols['Short Title'] != 'MERCY') & (selectiveCols['Short Title'] != 'NATURES BEST HOPE') & (selectiveCols['Short Title'] != 'FACILITATING BREAKTHROUGH : HOW TO REMOVE OBSTACLES, BRIDGE DIFFERENCES, AND MOVE FORWARD TOGETHER&NBSP;')]

selectiveCols = selectiveCols[selectiveCols['MMS ID'] != 9926793973502311]

selectiveCols

,Academic Term,Academic Department Name,Course Code,Instructor Name,ISBN (Normalized) List,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Electronic location,Electronic access,Electronic Availability
2,SPRING 2026,ENGLISH,202620-ENGL.662.001-26255,"Hardwig, William",9780803239265,RIDING THE TRAIL OF TEARS,HAUSMAN,NEBRASKA,10,9925903515702311,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Electronic version at ProQuest; ProQuest Ebook...
7,SPRING 2026,KINESIOLOGY,202620-KNS.637.003-39055,"Porter, Jared",9780815392842,SKILL ACQUISITION IN SPORT : THEORY AND PRACTICE,NaN,ROUTLEDGE,20,9925871824802311,https://www.taylorfrancis.com/books/9781351189750,Online Access - Unlimited users (DRM-free),Electronic version at Taylor & Francis; Taylor...
8,SPRING 2026,CLASSICS,202620-CLAS.565.001-25624,"Van De Moortel, Aleydis",9780199925865,THE ILIAD,"POWELL, BARRY B.","OXFORD UNIVERSITY PRESS, INCORPORATED",2,9925853802202311,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Electronic version at ProQuest; ProQuest Ebook...
9,SPRING 2026,CLASSICS,202620-CLAS.299.001-33029,"Habib, Reema",9780203844373,HANDBOOK F/CLASSICAL RESEARCH,SCHAPS,TAYLOR AND FRANCIS (ROUTLEDGE),15,9925853088402311,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Electronic version at ProQuest; ProQuest Ebook...
12,SPRING 2026,ANTHROLOPOGY,202620-ANTH.472.001-32876,"Williams, Amanda",9780128099018,ORTNER'S IDENTIFICATION OF PATHOLOGICAL CONDIT...,ORTNER,ELSEVIER SCIENCE & TECHNOLOGY,12,9925796568402311,http://search.ebscohost.com/login.aspx?direct=...,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,SPRING 2026,ENGLISH,202620-ENGL.474.001-28310,"Huth, Thorsten",9780472123698,TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUA...,"GEBHARD, JERRY G.",UNIVERSITY OF MICHIGAN PRESS,15,9926839277802311,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...
541,SPRING 2026,ENGLISH,202620-ENGL.474.002-39506,"Huth, Thorsten",9780472123698,TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUA...,"GEBHARD, JERRY G.",UNIVERSITY OF MICHIGAN PRESS,5,9926839277802311,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...
542,SPRING 2026,LINGUISTICS,202620-LING.474.001-28330,"Huth, Thorsten",9780472036738,TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUAGE,GEBHARD,UNIVERSITY OF CHICAGO PRESS,15,9926839277802311,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...
543,SPRING 2026,ANTHROLOPOGY,202620-ANTH.466.001-28339,"Hoover, Hannah",9780932839435,RECENT DEVELOPMENTS IN SOUTHEASTERN ARCHAEOLOGY,ANDERSON,SOCIETY FOR AMER ARCHAEOLOGY,30,9926839178002311,https://www.jstor.org/stable/10.2307/jj.3850488,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...
544,SPRING 2026,HISTORY,202620-HIST.150.001-39666,"Olsson, Carl",9781108606394,"CRACK : ROCK COCAINE, STREET CAPITALISM, AND T...","FARBER, DAVID",CAMBRIDGE UNIVERSITY PRESS,214,9926839177902311,http://dx.doi.org/10.1017/9781108349055,Unlimited Access Unlimited Access,Electronic version at Cambridge University Pre...

In [56]:
len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

184

In [57]:
nonUnlimited = finalJoin[~finalJoin['Short Title'].isin(selectiveCols['Short Title'])].dropna(how = 'all')

nonUnlimited.sort_values(by = 'Short Title')['Short Title'].unique()

array(['A POCKET STYLE MANUAL', 'BELOVED',
       'BESTIARY : BEING AN ENGLISH VERSION OF THE BODLEIAN LIBRARY, OXFORD, MS BODLEY 764',
       'CASTE : THE ORIGINS OF OUR DISCONTENTS', 'CEREMONY',
       'CRAFTING THE PERSONAL ESSAY : A GUIDE FOR WRITING AND PUBLISHING CREATIVE NON-FICTION',
       'DESIGN OF EVERYDAY THINGS W/LIFETIME ACCESS',
       'EVERYTHING IS OBVIOUS : HOW COMMON SENSE FAILS US', 'EVICTED',
       'FACILITATING BREAKTHROUGH : HOW TO REMOVE OBSTACLES, BRIDGE DIFFERENCES, AND MOVE FORWARD TOGETHER&NBSP;',
       'FUN HOME : A FAMILY TRAGICOMIC',
       'HALFWAY HOME : RACE, PUNISHMENT, AND THE AFTERLIFE OF MASS INCARCERATION',
       'HIGH FIDELITY', 'HOW LANGUAGES ARE LEARNED', 'I, ROBOT',
       'INFORMATION ARCHITECTURE F/WORLD WI',
       'INTERPERSONAL COMMUNICATION', 'LET NOBODY TURN US AROUND',
       'LINEAR SYSTEMS THEORY',
       'ME AND MY DADDY LISTEN TO BOB MARLEY : NOVELLAS AND STORIES',
       'MERCY', 'MINDSET : THE NEW PSYCHOLOGY OF SUCCESS',
       'NATURES BEST HOPE', 'PRINCIPLES OF TRAUMA THERAPY',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'RESEARCH METHODS IN LIBRARY AND INFORMATION SCIENCE',
       'STATISTICAL MECHANICS', 'STRATEGIC PLANNING FOR PUBLIC RELATIONS',
       'SUN ALSO RISES', 'THE BLUEST EYE', 'THE GRAPES OF WRATH',
       'THE PORTABLE FEMINIST READER',
       'THE PROFESSOR IS IN : THE ESSENTIAL GUIDE TO TURNING YOUR PH. D. INTO A JOB',
       'THE THEORY AND PRACTICE OF GROUP PSYCHOTHERAPY (REVISED)',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER',
       'WOMAN WARRIOR'], dtype=object)

## Export the Overlap Report

### This is the dataset that gets transferred to the Transforming Bookstore List Python code.

In [58]:
selectiveCols.to_excel(date_str+'_overlap_report.xlsx', index = False)

## Export the Bookstore Results to Send to the Bookstore

In [59]:
warnings.filterwarnings("ignore")

bookstoreExport = selectiveCols

# Fill in the Primo Link based on the MMS ID

for i in range(len(bookstoreExport['MMS ID'])):
    bookstoreExport['Electronic location'].iloc[i] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma' + str(bookstoreExport['MMS ID'].iloc[i])

bookstoreExport = bookstoreExport.rename(columns = {'ISBN (Normalized) List': 'ISBN', 'Electronic access': 'Access_Type', 'Electronic location': 'Permalink', 'Course Code': 'Section Code'})

bookstoreExport = bookstoreExport[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Access_Type', 'Electronic Availability', 'Permalink']]

bookstoreExport

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Electronic Availability,Permalink
2,SPRING 2026,ENGLISH,202620-ENGL.662.001-26255,"Hardwig, William",9780803239265,RIDING THE TRAIL OF TEARS,HAUSMAN,NEBRASKA,10,9925903515702311,Click to View,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
7,SPRING 2026,KINESIOLOGY,202620-KNS.637.003-39055,"Porter, Jared",9780815392842,SKILL ACQUISITION IN SPORT : THEORY AND PRACTICE,NaN,ROUTLEDGE,20,9925871824802311,Online Access - Unlimited users (DRM-free),Electronic version at Taylor & Francis; Taylor...,https://utk.primo.exlibrisgroup.com/permalink/...
8,SPRING 2026,CLASSICS,202620-CLAS.565.001-25624,"Van De Moortel, Aleydis",9780199925865,THE ILIAD,"POWELL, BARRY B.","OXFORD UNIVERSITY PRESS, INCORPORATED",2,9925853802202311,Click to View,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
9,SPRING 2026,CLASSICS,202620-CLAS.299.001-33029,"Habib, Reema",9780203844373,HANDBOOK F/CLASSICAL RESEARCH,SCHAPS,TAYLOR AND FRANCIS (ROUTLEDGE),15,9925853088402311,Click to View,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
12,SPRING 2026,ANTHROLOPOGY,202620-ANTH.472.001-32876,"Williams, Amanda",9780128099018,ORTNER'S IDENTIFICATION OF PATHOLOGICAL CONDIT...,ORTNER,ELSEVIER SCIENCE & TECHNOLOGY,12,9925796568402311,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,SPRING 2026,ENGLISH,202620-ENGL.474.001-28310,"Huth, Thorsten",9780472123698,TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUA...,"GEBHARD, JERRY G.",UNIVERSITY OF MICHIGAN PRESS,15,9926839277802311,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
541,SPRING 2026,ENGLISH,202620-ENGL.474.002-39506,"Huth, Thorsten",9780472123698,TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUA...,"GEBHARD, JERRY G.",UNIVERSITY OF MICHIGAN PRESS,5,9926839277802311,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
542,SPRING 2026,LINGUISTICS,202620-LING.474.001-28330,"Huth, Thorsten",9780472036738,TEACHING ENGLISH AS A FOREIGN OR SECOND LANGUAGE,GEBHARD,UNIVERSITY OF CHICAGO PRESS,15,9926839277802311,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
543,SPRING 2026,ANTHROLOPOGY,202620-ANTH.466.001-28339,"Hoover, Hannah",9780932839435,RECENT DEVELOPMENTS IN SOUTHEASTERN ARCHAEOLOGY,ANDERSON,SOCIETY FOR AMER ARCHAEOLOGY,30,9926839178002311,Unlimited Access Unlimited Access,Electronic version at JSTOR; JSTOR Ebooks (JST...,https://utk.primo.exlibrisgroup.com/permalink/...
544,SPRING 2026,HISTORY,202620-HIST.150.001-39666,"Olsson, Carl",9781108606394,"CRACK : ROCK COCAINE, STREET CAPITALISM, AND T...","FARBER, DAVID",CAMBRIDGE UNIVERSITY PRESS,214,9926839177902311,Unlimited Access Unlimited Access,Electronic version at Cambridge University Pre...,https://utk.primo.exlibrisgroup.com/permalink/...

In [60]:
bookstoreExport.to_excel(date_str+'BookStoreResults_TPQ.xlsx', index = False) #Send this to the Bookstore