## 1. run the next two cells as-is

In [1]:
#import libraries and set some variables

import requests
import pandas as pd
import xml.etree.ElementTree as ET
from pprint import pprint
from urllib.parse import quote
import numpy as np
import urllib.parse
import os
import warnings
from rapidfuzz import process, fuzz
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

#nltk.download('punkt_tab')
#nltk.download('stopwords')

pd.set_option('display.max_columns', None)


#Setting a few Alma Analytics API variables and whatnot
base_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&path=')  

token_path = (r'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?'
             r'limit=1000'
             r'&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5'
             r'&token=')

loc1 = 'shared'
loc2 = 'University of Tennessee, Knoxville'
loc3 = 'Reports'
loc4 = 'Collections'
loc5 = 'Textbook ISBNs for Overlap Report_TM'
if loc5 != '':
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/' + loc5 
else:
    location = '/' + loc1 + '/' + loc2 + '/' + loc3 + '/' + loc4 + '/'

get_path = location 
url_encoded_path = quote(get_path)
report_path = base_path + url_encoded_path

xml_snippet = '''
<sawx:expr xsi:type="sawx:list" op="in"
  xmlns:saw="com.siebel.analytics.web/report/v1.1"
  xmlns:sawx="com.siebel.analytics.web/expression/v1.1" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<sawx:expr xsi:type="sawx:sqlExpression">"Bibliographic Details"."MMS Id"</sawx:expr>
{}
</sawx:expr>
'''

In [2]:
report_path

'https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?limit=1000&apikey=l8xxe4f2dc8ebe644d88a84c2ab98b67e6e5&path=/shared/University%20of%20Tennessee%2C%20Knoxville/Reports/Collections/Textbook%20ISBNs%20for%20Overlap%20Report_TM'

In [3]:
#define some functions

#function to extract data from the analytics report
def extract_data(row_elements, columns):
    data = []
    for row in row_elements:
        row_data = {}
        for col in row.findall('{urn:schemas-microsoft-com:xml-analysis:rowset}*'):
            column_name = col.tag.split('}')[1]
            column_value = col.text
            if column_name in columns:  # Check if the column is in the columns dictionary
                row_data[columns[column_name]] = column_value if column_value is not None else np.nan  # Insert NaN if value is missing
        data.append(row_data)
    return data

#pulling the analytics report and extracting data
def get_report(response):
    # Parse the XML response
    root = ET.fromstring(response.content)
    # Extract the ResumptionToken and IsFinished elements from the response XML
    resumption_token_element = root.find('.//ResumptionToken')
    resumption_token = resumption_token_element.text if resumption_token_element is not None else None
    is_finished_element = root.find('.//IsFinished')
    if is_finished_element is not None:
        is_finished = is_finished_element.text
    else:
        is_finished = None

    namespaces = {
        'xmlns': 'urn:schemas-microsoft-com:xml-analysis:rowset',
        'xsd': 'http://www.w3.org/2001/XMLSchema',
        'saw-sql': 'urn:saw-sql'
    }
    columns = {}

    for i, col in enumerate(root.findall('.//xsd:element[@saw-sql:columnHeading]', namespaces)):
        columns[f'Column{i}'] = col.get('{urn:saw-sql}columnHeading', col.get('name'))
    
    # Extract the data from the XML and store it in a list of dictionaries
    all_data = []
    data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
    all_data.extend(data)
    
    # Iterate through subsequent GET requests until IsFinished is True
    while is_finished == 'false':
        # Make the next GET request with the ResumptionToken
        response = requests.get(token_path + resumption_token)

        # Extract the ResumptionToken and IsFinished elements from the response XML
        root = ET.fromstring(response.content)
        is_finished = root.find('.//IsFinished').text

        # Process the response data
        data = extract_data(root.findall('.//{urn:schemas-microsoft-com:xml-analysis:rowset}Row'), columns)
        all_data.extend(data)

    report_df = pd.DataFrame(all_data)

    # Drop the first column of the dataframe
    if not report_df.empty:
        report_df = report_df.drop(report_df.columns[0], axis=1)

    # Reset the index of the dataframe
    report_df = report_df.reset_index(drop=True)

    return report_df


def get_and_concat_report(report_path, report_data_df):
    response = requests.get(report_path)
    report_df = get_report(response)
    print(len(report_df))
    return pd.concat([report_data_df, report_df], ignore_index=True)

# Define a custom function to concatenate non-NaN values and deduplicate the notes fields which contain information about 
# online access type for each ebook
def concatenate_and_deduplicate_notes(row):
    notes = [str(row['Portfolio Public Note']), str(row['Portfolio Authentication Note']),
             str(row['Service Authentication Note']), str(row['Electronic location and access'])]
    non_nan_notes = set(note for note in notes if note != 'nan')
    return '; '.join(non_nan_notes)

## 2. Set the date

In [4]:
#set the date string for the rest of this notebook
date_str = '2026-06-09'

## 3. Read in the searchresults file from the bookstore
## make sure to point read_excel to the correct file location!

In [5]:
#load most recent file from bookstore
# you will need to have saved the automated bookstore file using format "searchresults_YYYY-MM-DD.xlsx" to your computer
df = pd.read_excel(r'searchresults_'+date_str+'.xlsx')

# Preview the sorted DataFrame
df

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity
0,Summer Mini 2026,ACCOUNTING,202625-ACCT.200.001-70001,"Jordan, Latonya",9781264453948,CONNECT ONLINE ACCESS FOR SURVEY OF ACCOUNTING...,EDMONDS,MCGRAW-HILL HIGHER EDUCATION (US),100
1,Summer Mini 2026,ADVERTISING,202625-ADVT.480.001-70234,"Najera, Christina",9781483315430,CONTROVERSIES IN CONTEMPORARY ADVERTISING,"SHEEHAN, KIM BARTEL AND SHEEHAN, KIM B.","SAGE PUBLICATIONS, INCORPORATED",25
2,Summer Mini 2026,BIOCHEMISTRY CELLULAR MOLECULAR BIOLOGY,202625-BCMB.419.001-70259,"Korotych, Olena",9780470471319,FUNDAMENTAL LABORATORY APPROACHES FOR BIOCHEMI...,"NINFA, ALEXANDER J., BENORE, MARILEE, AND BALL...","WILEY & SONS, INCORPORATED, JOHN",12
3,Summer Mini 2026,BUSINESS ADMINISTRATION,202625-BUAD.200.001-70204,"Grant, Melissa",9781737565307,CAREER AI PLATFORM-QUINNCIA 2 YEAR ACCESS,QUINNCIA,QUINNCIA,50
4,Summer Mini 2026,COMMUNICATION STUDIES,202625-CMST.210.002-70420,"Lively, Traci",9781533943767,CUSTOM COURSE MATERIAL F/CMST 210 W/ACHIEVE,HAAS,MCMILLAN,20
...,...,...,...,...,...,...,...,...,...
890,Summer 2026,THEATRE,202630-THEA.100.392-82104,"Russell, Neno",9798214354422,THE ART OF THEATRE: THEN AND NOW,DOWNS,CENGAGE,30
891,Summer 2026,THEATRE,202630-THEA.100.501-83315,"Russell, Neno",9798214354422,THE ART OF THEATRE: THEN AND NOW,DOWNS,CENGAGE,32
892,Summer 2026,"WOMEN, GENDER AND SEXUALITY",202630-WGS.200.301-87025,"Kendrick, Samantha",9781101992678,THE PORTABLE FEMINIST READER,NaN,PENGUIN PUBLISHING GROUP,20
893,Summer 2026,"WOMEN, GENDER AND SEXUALITY",202630-WGS.200.302-87026,"Kendrick, Samantha",9781101992678,THE PORTABLE FEMINIST READER,NaN,PENGUIN PUBLISHING GROUP,5
894,Summer 2026,"WOMEN, GENDER AND SEXUALITY",202630-WGS.375.301-87054,"Cooper, Sarah",9781324044048,"GENDER : IDEAS, INTERACTIONS, INSTITUTIONS (TH...","WADE, LISA AND FERREE, MYRA MARX","NORTON & COMPANY, INCORPORATED, W. W.",35

## 4. do some work on the bookstore-provided file to generate a list of ISBNs that 
## we will use in a later step

In [6]:
#create list of ISBNs for use in Alma Set creation
#do some pre-processing on the data for cleanup purposes
isbns = df[['ISBN']]
isbns = isbns.dropna()
isbns = isbns.drop_duplicates()
isbns['ISBN'] = isbns['ISBN'].apply(lambda x: x.replace('-',''))
isbns = isbns.astype(str)
isbns = isbns[(isbns['ISBN'].str.len() == 13) & (isbns['ISBN'].str.isdigit())]
isbns = isbns.reset_index()
isbns = isbns.drop('index', axis = 1)
isbns = isbns.iloc[isbns['ISBN'].str.len().sort_values(ascending = False).index]
isbns

              ISBN
0    9781264453948
289  9781071962893
263  9780323846554
262  9780826182142
261  9781948057882
..             ...
126  9798214153506
125  9781778771606
124  9780137319473
123  9781903544877
385  9798214354422

[386 rows x 1 columns]

In [7]:
isbns.dtypes

ISBN    object
dtype: object

## Fix Known Mismatched ISBNs in the cell below.

These titles can be possibly identified with the fuzzy title matching section (Section #7 later in this code), or by checking their Alma holding and VolBooks title information against each other manually.

In [8]:
#Fix known mismatching ISBNs

for i in range(isbns.shape[0]):
    if isbns.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found Silas Marner')
        isbns.at[i, 'ISBN'] = '9780191037610'    
    if isbns.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found Sick Enough')       
        isbns.at[i, 'ISBN'] = '9781041036487'   
    if isbns.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found Evaluation and Measurement of Library Services')     
        isbns.at[i, 'ISBN'] = '9781440855368'     
    if isbns.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found Information Science')     
        isbns.at[i, 'ISBN'] = '9780367725204'      
    if isbns.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found International Financial Statement Analysis')    
        isbns.at[i, 'ISBN'] = '9781119682141'     
    if isbns.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found Counseling Children and Adolescents')  
        isbns.at[i, 'ISBN'] = '9781351133159'   
    if isbns.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found Demand and Supply Integration')  
        isbns.at[i, 'ISBN'] = '9781501506024'  
    if isbns.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found Performance Appraisal and Management')  
        isbns.at[i, 'ISBN'] = '9781506352886'  
    if isbns.at[i, 'ISBN'] == '9781317346005': #On the History of Political Philosophy
        print('Found On the History of Political Philosophy')
        isbns.at[i, 'ISBN'] = '9781317346012'
    if isbns.at[i, 'ISBN'] == '9781000690835': #Child-Centered Play Therapy
        print('Found Child-Centered Play Therapy')
        isbns.at[i, 'ISBN'] = '9781003260431' 
    if isbns.at[i, 'ISBN'] == '9781483315430': #Controversies in Contemporary Advertising
        print('Found Controversies in Contemporary Advertising')
        isbns.at[i, 'ISBN'] = '9781452233130' 
    if isbns.at[i, 'ISBN'] == '9781538139332': #Cooperation and Conflict Between State and Local Government
        print('Found Cooperation and Conflict Between State and Local Government')
        isbns.at[i, 'ISBN'] = '9798216405665' 
    if isbns.at[i, 'ISBN'] == '9781315218489': #Advanced Linear Algebra for Engineers with MATLAB
        print('Found Advanced Linear Algebra for Engineers with MATLAB') 
        isbns.at[i, 'ISBN'] = '9781420095241' 
    if isbns.at[i, 'ISBN'] == '9781351834377': #Advanced Linear Algebra for Engineers with MATLAB, second ISBN
        print('Found Advanced Linear Algebra for Engineers with MATLAB')
        isbns.at[i, 'ISBN'] = '9781420095241'  
    if isbns.at[i, 'ISBN'] == '9780393069754': #Beowulf
        print('Found Beowulf') 
        isbns.at[i, 'ISBN'] = '9781350212718'
    if isbns.at[i, 'ISBN'] == '9781483322100': #Conflict, War, and Peace: An Introduction to Scientific Research
        print('Found Conflict, War, and Peace')
        isbns.at[i, 'ISBN'] = '9781071934111'
    if isbns.at[i, 'ISBN'] == '9780742575622': #Criminologiccal Theory: An Analysis of its Underlying Assumptions
        print('Found Criminological Theory')
        isbns.at[i, 'ISBN'] = '9798216404972'
    if isbns.at[i, 'ISBN'] == '9780191007774': #Global Environments Through the Quarternary: Exploring Environmental Change
        print('Found Global Environments Through the Quarternary')
        isbns.at[i, 'ISBN'] = '9780191810169'
    if isbns.at[i, 'ISBN'] == '9780191606373': #History: A Very Short Introduction
        print('Found History')
        isbns.at[i, 'ISBN'] = '9780191540189'
    if isbns.at[i, 'ISBN'] == '9780124079489': #Introduction to Probability Models
        print('Found Introduction to Probability Models')
        isbns.at[i, 'ISBN'] = '9780125984560'
    if isbns.at[i, 'ISBN'] == '9781948057882': #John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
        print("Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition")
        print('Make sure this is the Unlimited version from ProQuest, not the 1 user from R2 Digital!')
        isbns.at[i, 'ISBN'] = '9781948057899'
    if isbns.at[i, 'ISBN'] == '9780838937952': #Metadata
        print('Found Metadata')
        isbns.at[i, 'ISBN'] = '9780838948637'
    if isbns.at[i, 'ISBN'] == '9780307757890': #Paradise Lost
        print('Found Paradise Lost')
        isbns.at[i, 'ISBN'] = '9781317865735'
    if isbns.at[i, 'ISBN'] == '9781466887787': #14-18: Understanding the Great War
        print('Found 14-18 Understanding the Great War')
        isbns.at[i, 'ISBN'] = '9780809046430'
    if isbns.at[i, 'ISBN'] == '9781400030156': #The Big Sleep
        print('Found The Big Sleep')
        isbns.at[i, 'ISBN'] = '9781479403776'
    if isbns.at[i, 'ISBN'] == '9780191629112': #The Book of Marvels and Travels
        print('Found The Book of Marvels and Travels')
        isbns.at[i, 'ISBN'] = '9780191629105'
    if isbns.at[i, 'ISBN'] == '9780140449617': #The Death of Ivan Ilyich and Other Stories
        print('Found The Death of Ivan Ilyich')
        isbns.at[i, 'ISBN'] = '9780191649042'
    if isbns.at[i, 'ISBN'] == '9781479823550': #Forced Out: Migrant Mothers in Search of Refuge and Hope
        print('Found Forced Out')
        isbns.at[i, 'ISBN'] = '9781479823529'
    if isbns.at[i, 'ISBN'] == '9780198745686': #Imperial Apocalypse: The Great War and the Destruction of the Russian Empire
        print('Found Imperial Apocalypse')
        isbns.at[i, 'ISBN'] = '9781644699522'
    if isbns.at[i, 'ISBN'] == '9780262367509': #Introduction to Algorithms, Fourth Edition
        print('Found Introduction to Algorithms')
        isbns.at[i, 'ISBN'] = '9780262046305'
    if isbns.at[i, 'ISBN'] == '9780813178288': #John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights]
        print('Found John Hervey Wheeler')
        isbns.at[i, 'ISBN'] = '9780813178271'
    if isbns.at[i, 'ISBN'] == '9781452289236': #Mental Health Case Management: A Practical Guide
        print('Found Mental Health Case Management')
        isbns.at[i, 'ISBN'] = '9781452256078'
    if isbns.at[i, 'ISBN'] == '9781101576984': #Merchants of Culture The Publishing Business in the Twenty-First Century
        print('Found Merchants of Culture')
        isbns.at[i, 'ISBN'] = '9780745661421'
    if isbns.at[i, 'ISBN'] == '9781319049966': #Narrative of the Life of Frederick Douglass: An American Slave, Written by Himself
        print('Found Frederick Douglass')
        isbns.at[i, 'ISBN'] = '9780760355466'
    if isbns.at[i, 'ISBN'] == '9780199720149': #The Oxford Handbook of Engineering and Technology in the Classical World
        print('Found Handbook of Engineering and Technology')
        isbns.at[i, 'ISBN'] = '9780195187311'
    if isbns.at[i, 'ISBN'] == '9781350113008': #Performance Drawing
        print('Found Performance Drawing')
        isbns.at[i, 'ISBN'] = '9781350113015'
    if isbns.at[i, 'ISBN'] == '9780191624711': #Persuasion
        print('Found Persuasion')
        isbns.at[i, 'ISBN'] = '9781316848630'
    if isbns.at[i, 'ISBN'] == '9781009314848': #The Gas Mask in Interwar Germany: Visions of Chemical Modernity
        print('Found Gas Mask')
        isbns.at[i, 'ISBN'] = '9781009314862'
    if isbns.at[i, 'ISBN'] == '9780385093309': #Good-Bye to All That
        print('Found Good-Bye to All That')
        isbns.at[i, 'ISBN'] = '9781774649367'
    if isbns.at[i, 'ISBN'] == '9781119837909': #Research Ethics for Scientists
        print('Found Research Ethics for Scientists')
        isbns.at[i, 'ISBN'] = '9781119978862'
    if isbns.at[i, 'ISBN'] == '9780307432568': #The Return of the Soldier
        print('Found The Return of the Soldier')
        isbns.at[i, 'ISBN'] = '9780486846545'
    if isbns.at[i, 'ISBN'] == '9781496203168': #Siberian Exile
        print('Found Siberian Exile')
        isbns.at[i, 'ISBN'] = '9780803299597'
    if isbns.at[i, 'ISBN'] == '9780190879976': #Teaching Music Theory
        print('Found Teaching Music Theory')
        isbns.at[i, 'ISBN'] = '9780197510575'
    if isbns.at[i, 'ISBN'] == '9780197644058': #An Uneasy Peace
        print('Found An Uneasy Peace')
        isbns.at[i, 'ISBN'] = '9780197619407'

Found Controversies in Contemporary Advertising
Found Child-Centered Play Therapy
Found Beowulf
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Make sure this is the Unlimited version from ProQuest, not the 1 user from R2 Digital!
Found On the History of Political Philosophy
Found Demand and Supply Integration

## 5. Save the isbns to an Excel file

In [9]:
#create new itemized set in Alma using this isbn file:
isbns.to_excel(date_str+'_isbns.xlsx', index = False)

# after the set is created, export the results (All Fields) and save the file using format "YYYY-MM-DD_set_output.xlsx"

## Use the isbn file to create an itemized set in alma
## After the set is created, export the results (All Fields) and save using the file name format "YYYY-MM-DD_set_output.xlsx" to the same location that all your other files for this process live in

## 6. The following cell will use the set_output you just made to call on the alma analytics API, looking for any matching ISBNs

In [5]:
#use the alma API and the set results to get all ISBNs for any MMS IDs found in set
#analytics report: Collections folder > "Textbook ISBNs for Overlap Report_TM"

#create list of mms_ids from set output
mms_ids = pd.read_excel(date_str+"_set_output.xlsx")
#mms_ids = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
mms_ids = mms_ids[['MMS ID']]

# Get the list of MMS IDs from the DataFrame
mms_list = mms_ids['MMS ID'].tolist()

# Define the batch size for API call(s)
batch_size = 50

# Create a list to store the batches
batches = []

# Iterate through the MMS ID list and create batches
for i in range(0, len(mms_list), batch_size):
    batch = mms_list[i : i + batch_size]
    batches.append(batch)

#create an empty list into which we will put api call results
df_list = []

#for each batch of mms ids, call analytics api
for batch in batches:
    values_xml = '\n'.join(f'<sawx:expr xsi:type="xsd:string">{value}</sawx:expr>' for value in batch)
    formatted_xml_snippet = xml_snippet.format(values_xml)

    url_encoded_filter_query = urllib.parse.quote(formatted_xml_snippet)

    full_path = base_path + url_encoded_path + r'&filter=' + url_encoded_filter_query

    report_data_df = get_and_concat_report(full_path, pd.DataFrame())
    df_list.append(report_data_df)
    
# concatenate together all the api call results into one big dataframe
combined_df = pd.concat(df_list, ignore_index=True)
combined_df

39
19

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Id,Service Authentication Note,No. of Available Portfolio,Portfolio Public Note,Portfolio Authentication Note
0,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks (EBA),Available,53390423470002311,Online Access: Unlimited Users,0,NaN,NaN
1,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407973790002311,NaN,0,Online Access- Unlimited users (DRM-Free),NaN
2,https://www.taylorfrancis.com/books/9781003524090,1003524095; 9781003524090; 1040524826; 9781040...,1003524095; 9781003524090; 1040524826; 9781040...,9926907593802311,An evidence-based guide to assistive technolog...,Taylor & Francis Ebooks (EBA),Available,53452318750002311,Online Access: Unlimited Users,1,NaN,NaN
3,https://link.springer.com/978-3-031-05740-3 Un...,9783031057403; 3031057406; 9783031057397; 3031...,9783031057403; 3031057406; 9783031057397; 3031...,9926837078602311,Applied Artificial Intelligence in Business : ...,Springer Ebooks Individually Purchased,Available,53446362200002311,NaN,1,Unlimited Access,NaN
4,https://doi.org/10.5040/9781350212732?locatt=l...,1350212717; 9781350212718; 1350212733; 9781350...,1350212717; 9781350212718; 1350212733; 9781350...,9926582988102311,"Beowulf : poem, poet and hero /",Bloomsbury Ebooks Individually Purchased,Available,53422236940002311,NaN,1,NaN,Online Access - Unlimited users (DRM-free)
5,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407996680002311,NaN,1,Online Access- Unlimited users (DRM-Free),NaN
6,https://sk.sagepub.com/book/mono/controversies...,9781452233130; 1452233136; 9780761926351; 0761...,9781452233130; 1452233136; 9780761926351; 0761...,9926908933302311,Controversies in contemporary advertising,SAGE Research Methods Books & Reference,Available,53452449920002311,NaN,1,Unlimited Access,NaN
7,https://www.taylorfrancis.com/books/9780203107...,0415887518; 9780415887519; 0415643465; 9780415...,0415887518; 9780415887519; 0415643465; 9780415...,9926414501702311,Core Competencies in Cognitive-Behavioral Ther...,Taylor & Francis Ebooks EBA Purchased,Available,53407972830002311,NaN,1,Online Access- Unlimited users (DRM-Free),NaN
8,https://www.taylorfrancis.com/books/9781003278290,1000566269; 9781000566260; 1003278299; 9781003...,1000566269; 9781000566260; 1003278299; 9781003...,9926211119402311,Ethics of data and analytics : concepts and ca...,Taylor & Francis Ebooks (EBA),Available,53384931230002311,Online Access: Unlimited Users,1,NaN,NaN
9,https://search.ebscohost.com/login.aspx?direct...,0826182143; 9780826182142; 9780826182135; 0826...,0826182143; 9780826182142; 9780826182135; 0826...,9926521386802311,Evidence-based practice improvement : merging ...,Ebooks moved from ProQuest to EBSCO,Available,53450840880002311,NaN,1,NaN,Online Access - 3 Users
10,NaN,1119819741; 9781119819745; 1119819733; 9781119...,1119819741; 9781119819745; 1119819733; 9781119...,9926910091102311,"Hey whipple, squeeze this : the classic guide ...",O'Reilly Online Learning: Academic/Public Libr...,Available,53452773190002311,NaN,1,NaN,NaN
11,NaN,111828223X; 9781118282236,111828223X; 9781118282236,9926914664702311,How great leaders think : the art of reframing,O'Reilly Online Learning: Academic/Public Libr...,Available,53454187110002311,NaN,1,NaN,NaN
12,https://search.ebscohost.com/login.aspx?direct...,9780080920856; 0080920853; 9780123741349; 0123...,9780080920856; 0080920853; 9780123741349; 0123...,9926677862202311,Human osteology /,EBSCO Ebooks Individually Purchased,Available,53432565050002311,NaN,1,NaN,Online Access - Unlimited users
13,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926852848702311,INTRODUCTION TO AMERICAN DEAF CULTURE,EBSCO Ebooks Individually Purchased,Available,53448439790002311,NaN,1,NaN,Online Access - Unlimited users
14,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926876681102311,INTRODUCTION TO AMERICAN DEAF CULTURE,Ebooks moved from ProQuest to EBSCO,Available,53451023240002311,NaN,1,NaN,NaN
15,https://onlinelibrary.wiley.com/book/10.1002/9...,9781119685135; 1119685133; 9781394347216; 1394...,9781119685135; 1119685133; 9781394347216; 1394...,9926721490202311,Introduction to Crisis and Trauma Counseling.,Wiley Ebooks Individually Purchased,Available,53436129820002311,NaN,1,Unlimited Access,NaN
16,https://muse.jhu.edu/book/77997/ Unlimited Acc...,9781944838881; 1944838880; 1563685078; 9781563...,9781944838881; 1944838880; 1563685078; 9781563...,9926721690202311,"Linguistics of American Sign Language, 5th Ed....",Project Muse Ebooks Individually Purchased,Available,53436149810002311,NaN,1,Unlimited Access,NaN
17,http://link.overdrive.com/?websiteID=120589&ti...,9780062691217; 006269121X; 9780062691194; 0062...,9780062691217; 006269121X; 9780062691194; 0062...,9926858905602311,New kid,OverDrive - Advantage,Available,53449394640002311,NaN,1,Click to access digital title.,NaN
18,https://www.taylorfrancis.com/books/9781315663...,1317346017; 9781317346012; 0205119743; 9780205...,1317346017; 9781317346012; 0205119743; 9780205...,9926414514502311,On the history of political philosophy : great...,Taylor & Francis Ebooks EBA Purchased,Available,53407950100002311,NaN,1,Online Access- Unlimited users (DRM-Free),NaN
19,https://ebookcentral.proquest.com/lib/utk/deta...,9781903544877; 1903544874; 9781780460154; 1780...,9781903544877; 1903544874; 9781780460154; 1780...,9926306865402311,Planetary Geology : An Introduction.,ProQuest Ebook Central: Academic Complete,Available,53393796650002311,NaN,1,Click to View,NaN
20,https://search.ebscohost.com/login.aspx?direct...,1626255989; 9781626255982; 9781626255975; 1626...,1626255989; 9781626255982; 9781626255975; 1626...,9926357087402311,Process-based CBT : the science and core clini...,EBSCO Ebooks Individually Purchased,Available,53400302360002311,NaN,1,NaN,Online Access - Unlimited users
21,https://search.ebscohost.com/login.aspx?direct...,9781524771492; 152477149X,9781524771492; 152477149X,9926255787602311,Property of the Rebel Librarian,EBSCO Ebooks Individually Purchased,Available,53389170510002311,NaN,1,NaN,Online Access - 1 user
22,https://ebookcentral.proquest.com/lib/utk/deta...,1319056326; 9781319056322; 9781319258795; 1319...,1319056326; 9781319056322; 9781319258795; 1319...,9926630187902311,Pursuing happiness a Bedford spotlight reader /,ProQuest Ebook Central Rialto,Available,53427846840002311,NaN,1,Online Access - 3 Users,NaN
23,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,NaN,1,NaN,Online Access - Unlimited users
24,https://search.ebscohost.com/login.aspx?direct...,1590174887; 9781590174883; 9781590175033; 1590...,1590174887; 9781590174883; 9781590175033; 1590...,9926781641702311,"Religio Medici and Hydriotaphia, or Urne-Buria...",EBSCO Ebooks Individually Purchased,Available,53441638660002311,NaN,1,NaN,Online Access - 1 user
25,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,NaN,1,NaN,NaN
26,https://search.ebscohost.com/login.aspx?direct...,9780826163967; 0826163963; 9780826163950; 0826...,9780826163967; 0826163963; 9780826163950; 0826...,9926311284602311,School social work : a skills-based competency...,Ebooks moved from ProQuest to EBSCO,Available,53450018210002311,NaN,1,NaN,NaN
27,https://search.ebscohost.com/login.aspx?direct...,1975126920; 9781975126926; 9781975126919; 1975...,1975126920; 9781975126926; 9781975126919; 1975...,9926738030202311,Stoelting's pharmacology & physiology in anest...,EBSCO Ebooks Individually Purchased,Available,53437481400002311,NaN,1,NaN,Online Access - Unlimited users
28,https://dx.doi.org/10.1093/oso/9780190081478.0...,0197521843; 9780197521847; 9780190081508; 0190...,0197521843; 9780197521847; 9780190081508; 0190...,9926600557802311,"Strategy in 3D : essential tools to diagnose, ...",Oxford Academic Ebooks Individually Purchased,Available,53424712610002311,NaN,1,NaN,Online Access - Unlimited users
29,https://search.ebscohost.com/login.aspx?direct...,9780826148049; 0826148042; 9780826148032; 0826...,9780826148049; 0826148042; 9780826148032; 0826...,9926224985502311,Successful grant writing : strategies for heal...,Ebooks moved from ProQuest to EBSCO,Available,53450032740002311,NaN,1,NaN,Online Access - 3 users
30,NaN,1283634740; 9781283634748; 0071798315; 9780071...,1283634740; 9781283634748; 0071798315; 9780071...,9926913176702311,Supply chain transformation : building and exe...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453702880002311,NaN,1,NaN,NaN
31,https://link.springer.com/978-3-031-10330-8 Un...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926829231602311,The Comprehensive Guide to Interdisciplinary V...,Springer Ebooks Individually Purchased,Available,53433284910002311,NaN,1,Unlimited Access,NaN
32,https://resolver.vitalsource.com/9781770486003,9781770486003; 1770486003; 9781554810826; 1554...,9781770486003; 1770486003; 9781554810826; 1554...,9926966302202311,The Lais of Marie de France : Text and Transla...,Broadview Editions Bookshelf,Available,53462931570002311,NaN,1,NaN,NaN
33,https://search.ebscohost.com/login.aspx?direct...,0593655044; 9780593655047; 1802063285; 9781802...,0593655044; 9780593655047; 1802063285; 9781802...,9926536272302311,The anxious generation : how the great rewirin...,Ebooks moved from ProQuest to EBSCO,Available,53450796290002311,NaN,1,NaN,Online Access - 1 user
34,http://link.overdrive.com/?websiteID=120589&ti...,9780593655047; 0593655044; 9780593655030; 0593...,9780593655047; 0593655044; 9780593655030; 0593...,9926907601302311,The anxious generation How the great rewiring ...,OverDrive - Consortium,Available,53452246900002311,NaN,1,Click to access digital title.,NaN
35,https://search.ebscohost.com/login.aspx?direct...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926301284902311,The comprehensive guide to interdisciplinary v...,Ebooks moved from ProQuest to EBSCO,Available,53450658140002311,NaN,1,NaN,NaN
36,https://search.ebscohost.com/login.aspx?direct...,1101992670; 9781101992678; 9780143110392; 0143...,1101992670; 9781101992678; 9780143110392; 0143...,9926747489202311,The portable feminist reader /,EBSCO Ebooks Individually Purchased,Available,53438150710002311,NaN,1,NaN,Online Access - 1 user
37,https://ebookcentral.proquest.com/lib/utk/deta...,9781422131022; 1422131025; 9781422105764; 1422...,9781422131022; 1422131025; 9781422105764; 1422...,9926689981202311,The practice of adaptive leadership : tools an...,ProQuest Ebook Central Rialto,Available,53433399500002311,NaN,1,Three User,NaN
38,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,NaN,Online Access - 1 user
39,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central DDA Discovery,Available,53342336300002311,NaN,0,Click to View,NaN
40,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53380851750002311,NaN,0,Click to View,NaN
41,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,Ebooks moved from ProQuest to EBSCO,Available,53450960430002311,NaN,1,NaN,Online Access - 1 user
42,https://ebookcentral.proquest.com/lib/utk/deta...,9781501506024; 1501506021; 9781501515156; 1501...,9781501506024; 1501506021; 9781501515156; 1501...,9925796118702311,Demand and Supply Integration : The Key to Wor...,ProQuest Ebook Central: Academic Complete,Available,53307862990002311,NaN,1,NaN,NaN
43,https://search.ebscohost.com/login.aspx?direct...,0553447459; 9780553447453; 9780553447446; 0553...,0553447459; 9780553447453; 9780553447446; 0553...,9925735170102311,Evicted poverty and profit in the American city,EBSCO Ebooks Individually Purchased,Available,53294165900002311,NaN,1,NaN,Online Access - 3 users
44,https://www.taylorfrancis.com/books/9781315774251,1315774259; 9781315774251; 1317683862; 9781317...,1315774259; 9781315774251; 1317683862; 9781317...,9926081510102311,Global writing for public relations : connecti...,Taylor & Francis Ebooks EBA Purchased,Available,53362652360002311,NaN,1,NaN,NaN
45,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,ProQuest Ebook Central: Academic Complete,Available,53377612100002311,NaN,1,NaN,NaN
46,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,ProQuest Ebook Central Rialto,Available,53389361250002311,NaN,1,Single User,NaN
47,https://ebookcentral.proquest.com/lib/utk/deta...,9781621901365; 162190136X; 9781621901006; 1621...,9781621901365; 162190136X; 9781621901006; 1621...,9926164756102311,Guide to the vascular plants of Tennessee /,JSTOR Ebooks Individually Purchased,Available,53436529840002311,NaN,1,Online Access - Unlimited Users,NaN
48,https://search.ebscohost.com/login.aspx?direct...,1538125471; 9781538125472; 1538125463; 9781538...,1538125471; 9781538125472; 1538125463; 9781538...,9926170265102311,Inside out and outside in : psychodynamic clin...,Ebooks moved from ProQuest to EBSCO,Available,53450030560002311,NaN,1,NaN,NaN
49,https://ebookcentral.proquest.com/lib/utk/deta...,9781948057899; 1948057891; 9781948057875; 1948...,9781948057899; 1948057891; 9781948057875; 1948...,9926059281102311,Johns Hopkins Evidence-Based Practice for Nurs...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53356121240002311,NaN,1,NaN,Online Access - Unlimited Users
50,https://www.r2library.com/Resource/Title/19480...,1948057891; 9781948057899; 9781948057875; 1948...,1948057891; 9781948057899; 9781948057875; 1948...,9926058345302311,Johns Hopkins evidence-based practice for nurs...,R2 Digital Library Firm Purchase,Available,53355704560002311,NaN,1,1 user,NaN
51,https://search.ebscohost.com/login.aspx?direct...,9780323755825; 0323755828; 9780323673327; 0323...,9780323755825; 0323755828; 9780323673327; 0323...,9926034431502311,Pediatric acute care : a guide for interprofes...,Ebooks moved from ProQuest to EBSCO,Available,53450032360002311,NaN,1,NaN,NaN
52,https://www.taylorfrancis.com/books/9781315386744,1315386747; 9781315386744; 1315386720; 9781315...,1315386747; 9781315386744; 1315386720; 9781315...,9926068438502311,Professional development : what works /,Taylor & Francis Ebooks EBA Purchased,Available,53358266480002311,NaN,1,NaN,NaN
53,NaN,1071878875; 9781071878873; 150634531X; 9781506...,1071878875; 9781071878873; 150634531X; 9781506...,9926174911902311,Research methods for social work : a problem-b...,SAGE Research Methods Core,Available,53379272510002311,NaN,1,NaN,NaN
54,https://ebookcentral.proquest.com/lib/utk/deta...,9781483322421; 1483322424; 9781483380094; 1483...,9781483322421; 1483322424; 9781483380094; 1483...,9925617965602311,Social welfare policy for a sustainable future...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53270254120002311,NaN,1,NaN,Online Access - Unlimited Users
55,https://ebookcentral.proquest.com/lib/utk/deta...,9781483322421; 1483322424; 9781483380094; 1483...,9781483322421; 1483322424; 9781483380094; 1483...,9925617965602311,Social welfare policy for a sustainable future...,ProQuest Ebook Central Rialto,Available,53462409540002311,NaN,1,Unlimited Access,NaN
56,https://ebookcentral.proquest.com/lib/utk/deta...,9781606492468; 1606492462; 9781606492451; 1606...,9781606492468; 1606492462; 9781606492451; 1606...,9925725944102311,Supply Chain Planning and Analytics : The Righ...,ProQuest Ebook Central: Academic Complete,Available,53292994490002311,NaN,1,NaN,NaN
57,https://search.ebscohost.com/login.aspx?direct...,1606492462; 9781606492468; 9781606492451; 1606...,1606492462; 9781606492468; 9781606492451; 1606...,9924042300102311,Supply chain planning and analytics : the righ...,Ebooks moved from ProQuest to EBSCO,Available,53449627790002311,NaN,1,NaN,NaN

In [7]:
combined_df.to_excel('Alma Textbook List Check Summer 2026.xlsx')

In [12]:
combined_df.sort_values(by = 'Title')['Title'].unique()

array(['An evidence-based guide to assistive technology : meeting the needs of all students with disabilities /',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       'Beowulf : poem, poet and hero /',
       'Child-centered play therapy : a practical guide to therapeutic relationships with children /',
       'Controversies in contemporary advertising',
       'Core Competencies in Cognitive-Behavioral Therapy : Becoming a Highly Effective and Competent Cognitive-Behavioral Therapist /',
       'Deaf culture : exploring deaf communities in the United States /',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Ethics of data and analytics : concepts and cases /',
       'Evicted poverty and profit in the American city',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement /',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide /',
       'Guide to the vascular plants of Tennessee /',
       'Hey whipple, squeeze this : the classic guide to creating great advertising /',
       'How great leaders think : the art of reframing',
       'Human osteology /', 'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'Inside out and outside in : psychodynamic clinical theory and psychopathology in contemporary multicultural contexts /',
       'Introduction to Crisis and Trauma Counseling.',
       'Johns Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition.',
       'Johns Hopkins evidence-based practice for nurses and healthcare professionals : models and guidelines /',
       'Linguistics of American Sign Language, 5th Ed. : An Introduction /',
       'New kid',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke /',
       'Pediatric acute care : a guide for interprofessional practice /',
       'Planetary Geology : An Introduction.',
       'Process-based CBT : the science and core clinical competencies of cognitive behavioral therapy /',
       'Professional development : what works /',
       'Property of the Rebel Librarian',
       'Pursuing happiness a Bedford spotlight reader /',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases /',
       'Religio Medici and Hydriotaphia, or Urne-Buriall /',
       'Research methods for social work : a problem-based approach /',
       'Sales force management : leadership, innovation, technology /',
       'School social work : a skills-based competency approach /',
       'Social welfare policy for a sustainable future : the U.S. in global context /',
       "Stoelting's pharmacology & physiology in anesthetic practice",
       'Strategy in 3D : essential tools to diagnose, decide, & deliver /',
       'Successful grant writing : strategies for health and human service professionals /',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time /',
       'Supply chain transformation : building and executing an integrated supply chain strategy /',
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The Lais of Marie de France : Text and Translation/',
       'The anxious generation : how the great rewiring of childhood is causing an epidemic of mental illness /',
       'The anxious generation How the great rewiring of childhood is causing an epidemic of mental illness.',
       'The comprehensive guide to interdisciplinary veterinary social work /',
       'The portable feminist reader /',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world /',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster /'],
      dtype=object)

## 7. Check for mismatched ISBNs using Fuzzy Matching

Since titles often have several different ISBNs, and we only receive one ISBN from VolBooks, we need to make sure as many of those ISBNs match up as possible. The cell below checks for any of these potential mismatches.

### If a title's ISBN does not align between VolBooks and Alma, go to the ISBN fixing cell in Section #4 and edit the VolBooks holdings to match the Alma holdings.

**NOTE:** This code finds the closest matching title within the VolBooks and Alma lists, and thus it may not always be a direct match. Double-check the code before changing any ISBNs.

In [13]:
## Load the Alma Data

volBooksTitleList = df['Short Title'].unique()
almaUnlimited = pd.read_excel('Textbook ISBN Checking File May 4.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'Textbook ISBN Checking File May 4.xlsx'

In [ ]:
## Alma ISBN Splitting Code
combinedCopy = almaUnlimited

combinedCopy['ISBN (Normalized) List'] = combinedCopy['ISBN (Normalized)'].apply(lambda x: str(x).split(";"))

expandedCopy = combinedCopy.explode('ISBN (Normalized) List')

expandedCopy['ISBN (Normalized) List'] = expandedCopy['ISBN (Normalized) List'].str.strip()

In [ ]:
## Clean and Tokenize the Titles

def TextPreProcess(title):
    title = str(title)
    title = title.lower()
    title = title.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(title)

    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    return tokens

## Load Title Lists
df['Tokenized Title'] = df['Short Title'].apply(TextPreProcess)
expandedCopy['Tokenized Title'] = expandedCopy['Title'].apply(TextPreProcess)

In [ ]:
## Create Stems and Rejoin Titles

stemmer = SnowballStemmer(language = 'english')

def StemTokens(tokens):
    stems = [stemmer.stem(token) for token in tokens]
    return ' '.join(stems)

df['Stemmed Title'] = df['Tokenized Title'].apply(StemTokens)
expandedCopy['Stemmed Title'] = expandedCopy['Tokenized Title'].apply(StemTokens)

In [ ]:
## Initialize Information

volBooksTitleList = df['Stemmed Title'].unique()
almaTitleList = expandedCopy['Stemmed Title'].unique()

almaTitle = pd.Series([])
volBooksTitle = pd.Series([])
almaISBN = pd.Series([])
volBooksISBN = pd.Series([])
almaStem = pd.Series([])
volBooksStem = pd.Series([])

In [ ]:
## Find the Potential Titles with Mismatched ISBNs

for i in range(len(volBooksTitleList)):
    titleName = volBooksTitleList[i]
    bestResult = process.extractOne(titleName, almaTitleList, scorer = fuzz.token_sort_ratio)
    
    selectVolBooksRows = df[df['Stemmed Title'] == titleName]
    volBooksStem = pd.concat([volBooksStem, pd.Series([selectVolBooksRows['Stemmed Title'].iloc[0]])], ignore_index = True)
    volBooksISBN = pd.concat([volBooksISBN, pd.Series([selectVolBooksRows['ISBN'].iloc[0]])], ignore_index = True)
    volBooksTitle = pd.concat([volBooksTitle, pd.Series([selectVolBooksRows['Short Title'].iloc[0]])], ignore_index = True)
    
    selectAlmaRows = expandedCopy[expandedCopy['Stemmed Title'] == bestResult[0]]
    almaStem = pd.concat([almaStem, pd.Series([selectAlmaRows['Stemmed Title'].iloc[0]])], ignore_index = True)
    almaISBN = pd.concat([almaISBN, pd.Series([selectAlmaRows['ISBN (Normalized) List'].iloc[0]])], ignore_index = True)
    almaTitle = pd.concat([almaTitle, pd.Series([selectAlmaRows['Title'].iloc[0]])], ignore_index = True)
    
    #for j in range(expandedCopy.shape[0]):
    #    if expandedCopy['Title'].iloc[j] == bestResult:
    #        almaISBN = pd.concat(volBooksISBN, pd.Series([expandedCopy.at[j, 'ISBN (Normalized) List']]), ignore_index = True)
    #        almaTitle = pd.concat(volBooksTitle, pd.Series([bestResult]), ignore_index = True)
    #for k in range(df.shape[0]):
    #    if expandedCopy['Short Title'].iloc[k] == titleName:
    #        volBooksISBN = pd.concat(almaISBN, pd.Series([df.at[k, 'ISBN']]), ignore_index = True)
    #        volBooksTitle = pd.concat(almaTitle, pd.Series([titleName]), ignore_index = True)

titleComparisonTable = pd.concat([volBooksStem, almaStem, volBooksISBN, almaISBN, volBooksTitle, almaTitle], axis = 1)
    
titleComparisonTable.columns = ['VolBooks Stemmed Title', 'Alma Stemmed Title', 'VolBooks ISBN', 'Alma ISBN', 'VolBooks Raw Title', 'Alma Raw Title']

titleComparisonTable

In [ ]:
titleComparisonTable.to_excel(date_str+'ISBN Matching Table.xlsx', index = False)

## 8. Continue cleaning up the VolBooks report

Return here once all ISBNs have been fixed above.

In [6]:
combined_df['Service Authentication Note']

0     Online Access: Unlimited Users
1                                NaN
2     Online Access: Unlimited Users
3                                NaN
4                                NaN
5                                NaN
6                                NaN
7                                NaN
8     Online Access: Unlimited Users
9                                NaN
10                               NaN
11                               NaN
12                               NaN
13                               NaN
14                               NaN
15                               NaN
16                               NaN
17                               NaN
18                               NaN
19                               NaN
20                               NaN
21                               NaN
22                               NaN
23                               NaN
24                               NaN
25                               NaN
26                               NaN
27                               NaN
28                               NaN
29                               NaN
30                               NaN
31                               NaN
32                               NaN
33                               NaN
34                               NaN
35                               NaN
36                               NaN
37                               NaN
38                               NaN
39                               NaN
40                               NaN
41                               NaN
42                               NaN
43                               NaN
44                               NaN
45                               NaN
46                               NaN
47                               NaN
48                               NaN
49                               NaN
50                               NaN
51                               NaN
52                               NaN
53                               NaN
54                               NaN
55                               NaN
56                               NaN
57                               NaN
Name: Service Authentication Note, dtype: object

In [14]:
combined_df['Electronic location split'] = combined_df['Electronic location and access'].apply(lambda x: x.split() if isinstance(x, str) else x)

combined_df['Electronic location'] = combined_df['Electronic location split'].apply(lambda x: ''.join(map(str, x[:1])) if isinstance(x, list) else x)

# Extract items excluding the first item from each list
combined_df['Electronic access'] = combined_df['Electronic location split'].apply(lambda x: ' '.join(x[1:]) if isinstance(x, list) else x)

In [15]:
combined_df['Electronic access']

0      Online Access- Unlimited users (DRM-Free)
1      Online Access- Unlimited users (DRM-Free)
2
3              Unlimited Access Unlimited Access
4     Online Access - Unlimited users (DRM-free)
5      Online Access- Unlimited users (DRM-Free)
6              Unlimited Access Unlimited Access
7      Online Access- Unlimited users (DRM-Free)
8
9
10                                           NaN
11                                           NaN
12             Unlimited Access Unlimited Access
13             Unlimited Access Unlimited Access
14
15             Unlimited Access Unlimited Access
16             Unlimited Access Unlimited Access
17                Click to access digital title.
18     Online Access- Unlimited users (DRM-Free)
19                                 Click to View
20             Unlimited Access Unlimited Access
21                       Single User Single User
22                       Single User Single User
23               Online Access - Unlimited users
24                       Single User Single User
25                                           NaN
26
27             Unlimited Access Unlimited Access
28               Online Access - Unlimited users
29
30                                           NaN
31             Unlimited Access Unlimited Access
32
33
34                Click to access digital title.
35
36                        Online Access - 1 user
37                         Three User Three User
38                       Single User Single User
39
40
41
42                                 Click to View
43                       Single User Single User
44
45                       Single User Single User
46                       Single User Single User
47                       Single User Single User
48
49                                 Click to View
50                            R2 Digital Library
51
52
53                                           NaN
54             Unlimited Access Unlimited Access
55             Unlimited Access Unlimited Access
56                                 Click to View
57
Name: Electronic access, dtype: object

## 9. save the alma analytics api output as an excel file

In [16]:
#save the big, concatenated dataframe to disk
combined_df.to_excel(date_str+'_analytics_output.xlsx', index = False)

## do some work on the dataframe

In [17]:
# Create a new column 'Concatenated Notes' with deduplication
combined_df['Concatenated Notes'] = combined_df.apply(concatenate_and_deduplicate_notes, axis=1)

#filter to only show rows where the No. of Available Portfolios is not zero
combined_df = combined_df.loc[combined_df['No. of Available Portfolio'] != 0]


# Display the updated DataFrame
combined_df

,Electronic location and access,ISBN (Normalized),ISBN,MMS Id,Title,Electronic Collection Public Name,Availability,Portfolio Id,Service Authentication Note,No. of Available Portfolio,Portfolio Public Note,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks (EBA),Available,53390423470002311,Online Access: Unlimited Users,0,NaN,NaN,[https://www.taylorfrancis.com/books/978100326...,https://www.taylorfrancis.com/books/9781003260431,Online Access- Unlimited users (DRM-Free),Online Access: Unlimited Users; https://www.ta...
1,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407973790002311,NaN,0,Online Access- Unlimited users (DRM-Free),NaN,[https://www.taylorfrancis.com/books/978100326...,https://www.taylorfrancis.com/books/9781003260431,Online Access- Unlimited users (DRM-Free),Online Access- Unlimited users (DRM-Free); htt...
2,https://www.taylorfrancis.com/books/9781003524090,1003524095; 9781003524090; 1040524826; 9781040...,1003524095; 9781003524090; 1040524826; 9781040...,9926907593802311,An evidence-based guide to assistive technolog...,Taylor & Francis Ebooks (EBA),Available,53452318750002311,Online Access: Unlimited Users,1,NaN,NaN,[https://www.taylorfrancis.com/books/978100352...,https://www.taylorfrancis.com/books/9781003524090,,Online Access: Unlimited Users; https://www.ta...
3,https://link.springer.com/978-3-031-05740-3 Un...,9783031057403; 3031057406; 9783031057397; 3031...,9783031057403; 3031057406; 9783031057397; 3031...,9926837078602311,Applied Artificial Intelligence in Business : ...,Springer Ebooks Individually Purchased,Available,53446362200002311,NaN,1,Unlimited Access,NaN,"[https://link.springer.com/978-3-031-05740-3, ...",https://link.springer.com/978-3-031-05740-3,Unlimited Access Unlimited Access,https://link.springer.com/978-3-031-05740-3 Un...
4,https://doi.org/10.5040/9781350212732?locatt=l...,1350212717; 9781350212718; 1350212733; 9781350...,1350212717; 9781350212718; 1350212733; 9781350...,9926582988102311,"Beowulf : poem, poet and hero /",Bloomsbury Ebooks Individually Purchased,Available,53422236940002311,NaN,1,NaN,Online Access - Unlimited users (DRM-free),[https://doi.org/10.5040/9781350212732?locatt=...,https://doi.org/10.5040/9781350212732?locatt=l...,Online Access - Unlimited users (DRM-free),Online Access - Unlimited users (DRM-free); ht...
5,https://www.taylorfrancis.com/books/9781003260...,1003260438; 9781003260431; 9781032196879; 1032...,1003260438; 9781003260431; 9781032196879; 1032...,9926275286002311,Child-centered play therapy : a practical guid...,Taylor & Francis Ebooks EBA Purchased,Available,53407996680002311,NaN,1,Online Access- Unlimited users (DRM-Free),NaN,[https://www.taylorfrancis.com/books/978100326...,https://www.taylorfrancis.com/books/9781003260431,Online Access- Unlimited users (DRM-Free),Online Access- Unlimited users (DRM-Free); htt...
6,https://sk.sagepub.com/book/mono/controversies...,9781452233130; 1452233136; 9780761926351; 0761...,9781452233130; 1452233136; 9780761926351; 0761...,9926908933302311,Controversies in contemporary advertising,SAGE Research Methods Books & Reference,Available,53452449920002311,NaN,1,Unlimited Access,NaN,[https://sk.sagepub.com/book/mono/controversie...,https://sk.sagepub.com/book/mono/controversies...,Unlimited Access Unlimited Access,https://sk.sagepub.com/book/mono/controversies...
7,https://www.taylorfrancis.com/books/9780203107...,0415887518; 9780415887519; 0415643465; 9780415...,0415887518; 9780415887519; 0415643465; 9780415...,9926414501702311,Core Competencies in Cognitive-Behavioral Ther...,Taylor & Francis Ebooks EBA Purchased,Available,53407972830002311,NaN,1,Online Access- Unlimited users (DRM-Free),NaN,[https://www.taylorfrancis.com/books/978020310...,https://www.taylorfrancis.com/books/9780203107447,Online Access- Unlimited users (DRM-Free),Online Access- Unlimited users (DRM-Free); htt...
8,https://www.taylorfrancis.com/books/9781003278290,1000566269; 9781000566260; 1003278299; 9781003...,1000566269; 9781000566260; 1003278299; 9781003...,9926211119402311,Ethics of data and analytics : concepts and ca...,Taylor & Francis Ebooks (EBA),Available,53384931230002311,Online Access: Unlimited Users,1,NaN,NaN,[https://www.taylorfrancis.com/books/978100327...,https://www.taylorfrancis.com/books/9781003278290,,Online Access: Unlimited Users; https://www.ta...
9,https://search.ebscohost.com/login.aspx?direct...,0826182143; 9780826182142; 9780826182135; 0826...,0826182143; 9780826182142; 9780826182135; 0826...,9926521386802311,Evidence-based practice improvement : merging ...,Ebooks moved from ProQuest to EBSCO,Available,53450840880002311,NaN,1,NaN,Online Access - 3 Users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,Online Access - 3 Users; https://search.ebscoh...
10,NaN,1119819741; 9781119819745; 1119819733; 9781119...,1119819741; 9781119819745; 1119819733; 9781119...,9926910091102311,"Hey whipple, squeeze this : the classic guide ...",O'Reilly Online Learning: Academic/Public Libr...,Available,53452773190002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
11,NaN,111828223X; 9781118282236,111828223X; 9781118282236,9926914664702311,How great leaders think : the art of reframing,O'Reilly Online Learning: Academic/Public Libr...,Available,53454187110002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
12,https://search.ebscohost.com/login.aspx?direct...,9780080920856; 0080920853; 9780123741349; 0123...,9780080920856; 0080920853; 9780123741349; 0123...,9926677862202311,Human osteology /,EBSCO Ebooks Individually Purchased,Available,53432565050002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,https://search.ebscohost.com/login.aspx?direct...
13,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926852848702311,INTRODUCTION TO AMERICAN DEAF CULTURE,EBSCO Ebooks Individually Purchased,Available,53448439790002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,https://search.ebscohost.com/login.aspx?direct...
14,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926876681102311,INTRODUCTION TO AMERICAN DEAF CULTURE,Ebooks moved from ProQuest to EBSCO,Available,53451023240002311,NaN,1,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
15,https://onlinelibrary.wiley.com/book/10.1002/9...,9781119685135; 1119685133; 9781394347216; 1394...,9781119685135; 1119685133; 9781394347216; 1394...,9926721490202311,Introduction to Crisis and Trauma Counseling.,Wiley Ebooks Individually Purchased,Available,53436129820002311,NaN,1,Unlimited Access,NaN,[https://onlinelibrary.wiley.com/book/10.1002/...,https://onlinelibrary.wiley.com/book/10.1002/9...,Unlimited Access Unlimited Access,https://onlinelibrary.wiley.com/book/10.1002/9...
16,https://muse.jhu.edu/book/77997/ Unlimited Acc...,9781944838881; 1944838880; 1563685078; 9781563...,9781944838881; 1944838880; 1563685078; 9781563...,9926721690202311,"Linguistics of American Sign Language, 5th Ed....",Project Muse Ebooks Individually Purchased,Available,53436149810002311,NaN,1,Unlimited Access,NaN,"[https://muse.jhu.edu/book/77997/, Unlimited, ...",https://muse.jhu.edu/book/77997/,Unlimited Access Unlimited Access,https://muse.jhu.edu/book/77997/ Unlimited Acc...
17,http://link.overdrive.com/?websiteID=120589&ti...,9780062691217; 006269121X; 9780062691194; 0062...,9780062691217; 006269121X; 9780062691194; 0062...,9926858905602311,New kid,OverDrive - Advantage,Available,53449394640002311,NaN,1,Click to access digital title.,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Click to access digital title.; http://link.ov...
18,https://www.taylorfrancis.com/books/9781315663...,1317346017; 9781317346012; 0205119743; 9780205...,1317346017; 9781317346012; 0205119743; 9780205...,9926414514502311,On the history of political philosophy : great...,Taylor & Francis Ebooks EBA Purchased,Available,53407950100002311,NaN,1,Online Access- Unlimited users (DRM-Free),NaN,[https://www.taylorfrancis.com/books/978131566...,https://www.taylorfrancis.com/books/9781315663401,Online Access- Unlimited users (DRM-Free),https://www.taylorfrancis.com/books/9781315663...
19,https://ebookcentral.proquest.com/lib/utk/deta...,9781903544877; 1903544874; 9781780460154; 1780...,9781903544877; 1903544874; 9781780460154; 1780...,9926306865402311,Planetary Geology : An Introduction.,ProQuest Ebook Central: Academic Complete,Available,53393796650002311,NaN,1,Click to View,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,https://ebookcentral.proquest.com/lib/utk/deta...
20,https://search.ebscohost.com/login.aspx?direct...,1626255989; 9781626255982; 9781626255975; 1626...,1626255989; 9781626255982; 9781626255975; 1626...,9926357087402311,Process-based CBT : the science and core clini...,EBSCO Ebooks Individually Purchased,Available,53400302360002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,https://search.ebscohost.com/login.aspx?direct...
21,https://search.ebscohost.com/login.aspx?direct...,9781524771492; 152477149X,9781524771492; 152477149X,9926255787602311,Property of the Rebel Librarian,EBSCO Ebooks Individually Purchased,Available,53389170510002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
22,https://ebookcentral.proquest.com/lib/utk/deta...,1319056326; 9781319056322; 9781319258795; 1319...,1319056326; 9781319056322; 9781319258795; 1319...,9926630187902311,Pursuing happiness a Bedford spotlight reader /,ProQuest Ebook Central Rialto,Available,53427846840002311,NaN,1,Online Access - 3 Users,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Single User Single User,Online Access - 3 Users; https://ebookcentral....
23,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,https://search.ebscohost.com/login.aspx?direct...
24,https://search.ebscohost.com/login.aspx?direct...,1590174887; 9781590174883; 9781590175033; 1590...,1590174887; 9781590174883; 9781590175033; 1590...,9926781641702311,"Religio Medici and Hydriotaphia, or Urne-Buria...",EBSCO Ebooks Individually Purchased,Available,53441638660002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
25,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
26,https://search.ebscohost.com/login.aspx?direct...,9780826163967; 0826163963; 9780826163950; 0826...,9780826163967; 0826163963; 9780826163950; 0826...,9926311284602311,School social work : a skills-based competency...,Ebooks moved from ProQuest to EBSCO,Available,53450018210002311,NaN,1,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
27,https://search.ebscohost.com/login.aspx?direct...,1975126920; 9781975126926; 9781975126919; 1975...,1975126920; 9781975126926; 9781975126919; 1975...,9926738030202311,Stoelting's pharmacology & physiology in anest...,EBSCO Ebooks Individually Purchased,Available,53437481400002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Online Access - Unlimited users; https://searc...
28,https://dx.doi.org/10.1093/oso/9780190081478.0...,0197521843; 9780197521847; 9780190081508; 0190...,0197521843; 9780197521847; 9780190081508; 0190...,9926600557802311,"Strategy in 3D : essential tools to diagnose, ...",Oxford Academic Ebooks Individually Purchased,Available,53424712610002311,NaN,1,NaN,Online Access - Unlimited users,[https://dx.doi.org/10.1093/oso/9780190081478....,https://dx.doi.org/10.1093/oso/9780190081478.0...,Online Access - Unlimited users,Online Access - Unlimited users; https://dx.do...
29,https://search.ebscohost.com/login.aspx?direct...,9780826148049; 0826148042; 9780826148032; 0826...,9780826148049; 0826148042; 9780826148032; 0826...,9926224985502311,Successful grant writing : strategies for heal...,Ebooks moved from ProQuest to EBSCO,Available,53450032740002311,NaN,1,NaN,Online Access - 3 users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,Online Access - 3 users; https://search.ebscoh...
30,NaN,1283634740; 9781283634748; 0071798315; 9780071...,1283634740; 9781283634748; 0071798315; 9780071...,9926913176702311,Supply chain transformation : building and exe...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453702880002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
31,https://link.springer.com/978-3-031-10330-8 Un...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926829231602311,The Comprehensive Guide to Interdisciplinary V...,Springer Ebooks Individually Purchased,Available,53433284910002311,NaN,1,Unlimited Access,NaN,"[https://link.springer.com/978-3-031-10330-8, ...",https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,https://link.springer.com/978-3-031-10330-8 Un...
32,https://resolver.vitalsource.com/9781770486003,9781770486003; 1770486003; 9781554810826; 1554...,9781770486003; 1770486003; 9781554810826; 1554...,9926966302202311,The Lais of Marie de France : Text and Transla...,Broadview Editions Bookshelf,Available,53462931570002311,NaN,1,NaN,NaN,[https://resolver.vitalsource.com/9781770486003],https://resolver.vitalsource.com/9781770486003,,https://resolver.vitalsource.com/9781770486003
33,https://search.ebscohost.com/login.aspx?direct...,0593655044; 9780593655047; 1802063285; 9781802...,0593655044; 9780593655047; 1802063285; 9781802...,9926536272302311,The anxious generation : how the great rewirin...,Ebooks moved from ProQuest to EBSCO,Available,53450796290002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
34,http://link.overdrive.com/?websiteID=120589&ti...,9780593655047; 0593655044; 9780593655030; 0593...,9780593655047; 0593655044; 9780593655030; 0593...,9926907601302311,The anxious generation How the great rewiring ...,OverDrive - Consortium,Available,53452246900002311,NaN,1,Click to access digital title.,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Click to access digital title.; http://link.ov...
35,https://search.ebscohost.com/login.aspx?direct...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926301284902311,The comprehensive guide to interdisciplinary v...,Ebooks moved from ProQuest to EBSCO,Available,53450658140002311,NaN,1,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
36,https://search.ebscohost.com/login.aspx?direct...,1101992670; 9781101992678; 9780143110392; 0143...,1101992670; 9781101992678; 9780143110392; 0143...,9926747489202311,The portable feminist reader /,EBSCO Ebooks Individually Purchased,Available,53438150710002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - 1 user,https://search.ebscohost.com/login.aspx?direct...
37,https://ebookcentral.proquest.com/lib/utk/deta...,9781422131022; 1422131025; 9781422105764; 1422...,9781422131022; 1422131025; 9781422105764; 1422...,9926689981202311,The practice of adaptive leadership : tools an...,ProQuest Ebook Central Rialto,Available,53433399500002311,NaN,1,Three User,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Three User Three User,Three User; https://ebookcentral.proquest.com/...
38,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
39,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central DDA Discovery,Available,53342336300002311,NaN,0,Click to View,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
40,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53380851750002311,NaN,0,Click to View,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
41,https://search.ebscohost.com/login.aspx?direct...,9781635501803; 1635501806; 9781635501735; 1635...,9781635501803; 1635501806; 9781635501735; 1635...,9925989319102311,Deaf culture : exploring deaf communities in t...,Ebooks moved from ProQuest to EBSCO,Available,53450960430002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...

## 10. save the analytics_output file as csv

In [18]:
#save the dataframe to disk once again, only this time as a csv
combined_df.to_csv(date_str+'_analytics_output.csv', index = False)

## 11. Combine Data Files for Exporting

In [19]:
results = pd.read_excel(date_str+'_set_output.xlsx') #From Alma Directly
#results = pd.read_excel('ProQuest to EBSCO Check 2-4.xlsx')
bookstoreList = pd.read_excel('searchresults_'+date_str+'.xlsx') #From VolBooks Directly
textbookISBNs = combined_df #Alma Cleaned-Up Version

## Make sure that any ISBNs that were fixed before loading into Alma are also fixed here!

In [20]:
#Fix known mismatching ISBNs in bookstoreList

for i in range(bookstoreList.shape[0]):
    if bookstoreList.at[i, 'ISBN'] == '9780191037627': #Silas Marner
        print('Found Silas Marner')
        bookstoreList.at[i, 'ISBN'] = '9780191037610'    
    if bookstoreList.at[i, 'ISBN'] == '9781040675892': #Sick Enough
        print('Found Sick Enough')       
        bookstoreList.at[i, 'ISBN'] = '9781041036487'   
    if bookstoreList.at[i, 'ISBN'] == '9781440855375': #Evaluation and Measurement of Library Services
        print('Found Evaluation and Measurement of Library Services')     
        bookstoreList.at[i, 'ISBN'] = '9781440855368'     
    if bookstoreList.at[i, 'ISBN'] == '9781003155119': #Information Science: The Basics
        print('Found Information Science')     
        bookstoreList.at[i, 'ISBN'] = '9780367725204'      
    if bookstoreList.at[i, 'ISBN'] == '9781119628149': #International Financial Statement Analysis
        print('Found International Financial Statement Analysis')    
        bookstoreList.at[i, 'ISBN'] = '9781119682141'     
    if bookstoreList.at[i, 'ISBN'] == '9781351133135': #Counseling Children and Adolescents
        print('Found Counseling Children and Adolescents')  
        bookstoreList.at[i, 'ISBN'] = '9781351133159'   
    if bookstoreList.at[i, 'ISBN'] == '9781501505935': #Demand and Supply Integration
        print('Found Demand and Supply Integration')  
        bookstoreList.at[i, 'ISBN'] = '9781501506024'  
    if bookstoreList.at[i, 'ISBN'] == '9781506352916': #Performance Appraisal and Management
        print('Found Performance Appraisal and Management')  
        bookstoreList.at[i, 'ISBN'] = '9781506352886'  
    if bookstoreList.at[i, 'ISBN'] == '9781317346005': #On the History of Political Philosophy
        print('Found On the History of Political Philosophy')
        bookstoreList.at[i, 'ISBN'] = '9781317346012'
    if bookstoreList.at[i, 'ISBN'] == '9781000690835': #Child-Centered Play Therapy
        print('Found Child-Centered Play Therapy')
        bookstoreList.at[i, 'ISBN'] = '9781003260431' 
    if bookstoreList.at[i, 'ISBN'] == '9781483315430': #Controversies in Contemporary Advertising
        print('Found Controversies in Contemporary Advertising')
        bookstoreList.at[i, 'ISBN'] = '9781452233130' 
    if bookstoreList.at[i, 'ISBN'] == '9781538139332': #Cooperation and Conflict Between State and Local Government
        print('Found Cooperation and Conflict Between State and Local Government')
        bookstoreList.at[i, 'ISBN'] = '9798216405665' 
    if bookstoreList.at[i, 'ISBN'] == '9781315218489': #Advanced Linear Algebra for Engineers with MATLAB
        print('Found Advanced Linear Algebra for Engineers with MATLAB') 
        bookstoreList.at[i, 'ISBN'] = '9781420095241' 
    if bookstoreList.at[i, 'ISBN'] == '9781351834377': #Advanced Linear Algebra for Engineers with MATLAB, second ISBN
        print('Found Advanced Linear Algebra for Engineers with MATLAB')
        bookstoreList.at[i, 'ISBN'] = '9781420095241'  
    if bookstoreList.at[i, 'ISBN'] == '9780393069754': #Beowulf
        print('Found Beowulf') 
        bookstoreList.at[i, 'ISBN'] = '9781350212718'
    if bookstoreList.at[i, 'ISBN'] == '9781483322100': #Conflict, War, and Peace: An Introduction to Scientific Research
        print('Found Conflict, War, and Peace')
        bookstoreList.at[i, 'ISBN'] = '9781071934111'
    if bookstoreList.at[i, 'ISBN'] == '9780742575622': #Criminologiccal Theory: An Analysis of its Underlying Assumptions
        print('Found Criminological Theory')
        bookstoreList.at[i, 'ISBN'] = '9798216404972'
    if bookstoreList.at[i, 'ISBN'] == '9780191007774': #Global Environments Through the Quarternary: Exploring Environmental Change
        print('Found Global Environments Through the Quarternary')
        bookstoreList.at[i, 'ISBN'] = '9780191810169'
    if bookstoreList.at[i, 'ISBN'] == '9780191606373': #History: A Very Short Introduction
        print('Found History')
        bookstoreList.at[i, 'ISBN'] = '9780191540189'
    if bookstoreList.at[i, 'ISBN'] == '9780124079489': #Introduction to Probability Models
        print('Found Introduction to Probability Models')
        bookstoreList.at[i, 'ISBN'] = '9780125984560'
    if bookstoreList.at[i, 'ISBN'] == '9781948057882': #John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
        print("Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition")
        bookstoreList.at[i, 'ISBN'] = '9781948057899'
    if bookstoreList.at[i, 'ISBN'] == '9780838937952': #Metadata
        print('Found Metadata')
        bookstoreList.at[i, 'ISBN'] = '9780838948637'
    if bookstoreList.at[i, 'ISBN'] == '9780307757890': #Paradise Lost
        print('Found Paradise Lost')
        bookstoreList.at[i, 'ISBN'] = '9781317865735'
    if bookstoreList.at[i, 'ISBN'] == '9781466887787': #14-18: Understanding the Great War
        print('Found 14-18 Understanding the Great War')
        bookstoreList.at[i, 'ISBN'] = '9780809046430'
    if bookstoreList.at[i, 'ISBN'] == '9781400030156': #The Big Sleep
        print('Found The Big Sleep')
        bookstoreList.at[i, 'ISBN'] = '9781479403776'
    if bookstoreList.at[i, 'ISBN'] == '9780191629112': #The Book of Marvels and Travels
        print('Found The Book of Marvels and Travels')
        bookstoreList.at[i, 'ISBN'] = '9780191629105'
    if bookstoreList.at[i, 'ISBN'] == '9780140449617': #The Death of Ivan Ilyich and Other Stories
        print('Found The Death of Ivan Ilyich')
        bookstoreList.at[i, 'ISBN'] = '9780191649042'
    if bookstoreList.at[i, 'ISBN'] == '9781479823550': #Forced Out: Migrant Mothers in Search of Refuge and Hope
        print('Found Forced Out')
        bookstoreList.at[i, 'ISBN'] = '9781479823529'
    if bookstoreList.at[i, 'ISBN'] == '9780198745686': #Imperial Apocalypse: The Great War and the Destruction of the Russian Empire
        print('Found Imperial Apocalypse')
        bookstoreList.at[i, 'ISBN'] = '9781644699522'
    if bookstoreList.at[i, 'ISBN'] == '9780262367509': #Introduction to Algorithms, Fourth Edition
        print('Found Introduction to Algorithms')
        bookstoreList.at[i, 'ISBN'] = '9780262046305'
    if bookstoreList.at[i, 'ISBN'] == '9780813178288': #John Hervey Wheeler, Black Banking, and the Economic Struggle for Civil Rights]
        print('Found John Hervey Wheeler')
        bookstoreList.at[i, 'ISBN'] = '9780813178271'
    if bookstoreList.at[i, 'ISBN'] == '9781452289236': #Mental Health Case Management: A Practical Guide
        print('Found Mental Health Case Management')
        bookstoreList.at[i, 'ISBN'] = '9781452256078'
    if bookstoreList.at[i, 'ISBN'] == '9781101576984': #Merchants of Culture The Publishing Business in the Twenty-First Century
        print('Found Merchants of Culture')
        bookstoreList.at[i, 'ISBN'] = '9780745661421'
    if bookstoreList.at[i, 'ISBN'] == '9781319049966': #Narrative of the Life of Frederick Douglass: An American Slave, Written by Himself
        print('Found Frederick Douglass')
        bookstoreList.at[i, 'ISBN'] = '9780760355466'
    if bookstoreList.at[i, 'ISBN'] == '9780199720149': #The Oxford Handbook of Engineering and Technology in the Classical World
        print('Found Handbook of Engineering and Technology')
        bookstoreList.at[i, 'ISBN'] = '9780195187311'
    if bookstoreList.at[i, 'ISBN'] == '9781350113008': #Performance Drawing
        print('Found Performance Drawing')
        bookstoreList.at[i, 'ISBN'] = '9781350113015'
    if bookstoreList.at[i, 'ISBN'] == '9780191624711': #Persuasion
        print('Found Persuasion')
        bookstoreList.at[i, 'ISBN'] = '9781316848630'
    if bookstoreList.at[i, 'ISBN'] == '9781009314848': #The Gas Mask in Interwar Germany: Visions of Chemical Modernity
        print('Found Gas Mask')
        bookstoreList.at[i, 'ISBN'] = '9781009314862'
    if bookstoreList.at[i, 'ISBN'] == '9780385093309': #Good-Bye to All That
        print('Found Good-Bye to All That')
        bookstoreList.at[i, 'ISBN'] = '9781774649367'
    if bookstoreList.at[i, 'ISBN'] == '9781119837909': #Research Ethics for Scientists
        print('Found Research Ethics for Scientists')
        bookstoreList.at[i, 'ISBN'] = '9781119978862'
    if bookstoreList.at[i, 'ISBN'] == '9780307432568': #The Return of the Soldier
        print('Found The Return of the Soldier')
        bookstoreList.at[i, 'ISBN'] = '9780486846545'
    if bookstoreList.at[i, 'ISBN'] == '9781496203168': #Siberian Exile
        print('Found Siberian Exile')
        bookstoreList.at[i, 'ISBN'] = '9780803299597'
    if bookstoreList.at[i, 'ISBN'] == '9780190879976': #Teaching Music Theory
        print('Found Teaching Music Theory')
        bookstoreList.at[i, 'ISBN'] = '9780197510575'
    if bookstoreList.at[i, 'ISBN'] == '9780197644058': #An Uneasy Peace
        print('Found An Uneasy Peace')
        bookstoreList.at[i, 'ISBN'] = '9780197619407'

Found Controversies in Contemporary Advertising
Found Child-Centered Play Therapy
Found Beowulf
Found Beowulf
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found John's Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition
Found On the History of Political Philosophy
Found On the History of Political Philosophy
Found Demand and Supply Integration

In [21]:
#pd.set_option('display.max_rows', None)
results.sort_values(by = 'Title')['Title'].unique()

array(['An evidence-based guide to assistive technology : meeting the needs of all students with disabilities / edited by Alice L. Rhodes and Victoria Slocum.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       "Beowulf : poem, poet and hero / Heather O'Donoghue.",
       'Child-centered play therapy : a practical guide to therapeutic relationships with children / Nancy H. Cochran, William J. Nordling and Jeff L. Cochran.',
       'Child-centered play therapy : a practical guide to therapeutic relationships with children / Nancy H. Cochran, William J. Nordling, Jeff L. Cochran.',
       'Controversies in contemporary advertising [electronic resource] / Kim Bartel Sheehan.',
       'Core Competencies in Cognitive-Behavioral Therapy : Becoming a Highly Effective and Competent Cognitive-Behavioral Therapist / Cory F. Newman.',
       'Deaf culture : exploring deaf communities in the United States / Irene W. Leigh, PhD, Jean F. Andrews, PhD, Raychelle L. Harris, PhD, Topher González Ávila, MA.',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Diagnostic and statistical manual of mental disorders : DSM-5-TR / American Psychiatric Association.',
       'Ethical issues in professional life / Joan C. Callahan, [editor].',
       'Ethics of data and analytics : concepts and cases / Kirsten Martin.',
       'Evicted : poverty and profit in the American city / Matthew Desmond.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement / Rona F. Levin, Bonnie Lauder, editors.',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Gordis epidemiology / David D. Celentano, Moyses Szklo.',
       'Guide to the vascular plants of Tennessee / compiled and edited by members of the Tennessee Flora Committee.',
       'Hey whipple, squeeze this : the classic guide to creating great advertising / Luke Sullivan.',
       'How great leaders think : the art of reframing',
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'INTRODUCTION TO AMERICAN DEAF CULTURE [electronic resource].',
       'Inside out and outside in : psychodynamic clinical theory and psychopathology in contemporary multicultural contexts / edited by Joan Berzoff, Laura Melano Flanagan, and Patricia Hertz.',
       'Introduction to American deaf culture / Thomas K. Holcomb.',
       'Introduction to Crisis and Trauma Counseling.',
       'Introduction to kinesiology : studying physical activity / Duane V. Knudson, Timothy A. Brusseau, editors.',
       'Introductory textbook of psychiatry / Donald W. Black, Nancy C. Andreasen.',
       'Johns Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition.',
       'Johns Hopkins evidence-based practice for nurses and healthcare professionals : models and guidelines / [edited by] Deborah Dang, PhD, RN, NEA-BC, Sandra Dearholt, DNP, RN, NEA-BC, Kim Bissett, PhD, MBA, RN, Judy Ascenzi, DNP, RN, CCRN-K, Madeleine Whalen, MSN/MPH, RN, CEN.',
       'Linguistics of American Sign Language, 5th Ed. :  An Introduction /  Clayton Valli [and others].',
       "Miller's basics of anesthesia / Manuel C. Pardo, Jr., MD.",
       'Multicultural psychology : understanding our diverse communities / Jeffery Scott Mio, Lori A. Barker, Melanie M. Domenech Rodríguez, John Gonzalez.',
       'New kid / Jerry Craft ; with color by Jim Callahan.',
       'New kid [electronic resource]. Jerry Craft.',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke / W. Julian Korab-Karpowicz.',
       'Pediatric acute care : a guide for interprofessional practice / edited by Beth Nachtsheim Bolick, Karin Reuter-Rice, Maureen A. Madden, Paul N. Severin.',
       'Physical activity epidemiology / Rod K. Dishman, Gregory W. Heath, Michael D. Schmidt,  I-Min Lee.',
       'Planetary Geology : An Introduction.',
       'Process-based CBT : the science and core clinical competencies of cognitive behavioral therapy / edited by Steven C. Hayes, and Stefan G. Hofmann.',
       'Professional development : what works / Sally J. Zepeda.',
       'Property of the Rebel Librarian [electronic resource] / Allison Varnes.',
       'Property of the rebel librarian / Allison Varnes.',
       'Publication manual of the American Psychological Association : the official guide to APA style.',
       'Pursuing happiness [electronic resource] : a Bedford spotlight reader / [compiled and edited by] Matthew Parfitt, Boston University, Dawn Skorczewski, Brandeis University.',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases / author: Committee on Infectious Diseases, American Academy of Pediatrics; David W. Kimberlin, MD, FAAP, editor; Ritu Banerjee, MD, PhD, FAAP, Elizabeth D. Barnett, MD, FAAP, Ruth Lynfield, MD, FAAP, Mark H. Sawyer, MD, FAAP, associate editor.',
       'Religio Medici and Hydriotaphia, or Urne-Buriall / Sir Thomas Browne ; edited and with an introduction by Stephen Greenblatt and Ramie Targoff.',
       'Research methods for social work : a problem-based approach / Antoinette Y. Farmer, G. Lawrence Farmer.',
       'Sales force management : leadership, innovation, technology / Mark W. Johnston, Greg W. Marshall, and Jessica L. Ogilvie.',
       'School social work : a skills-based competency approach / JoDee Keller, PhD, LICSW Department of Social Work, Professor of Social Work Pacific Lutheran University.',
       'Social welfare policy for a sustainable future : the U.S. in global context / Katherine S. van Wormer, Rosemary J. Link.',
       "Stoelting's pharmacology & physiology in anesthetic practice / [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman.",
       "Stoelting's pharmacology & physiology in anesthetic practice [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman",
       'Strategy in 3D : essential tools to diagnose, decide, & deliver / Greg Fisher, John E. Wisneski, Rene M. Bakker.',
       'Successful grant writing : strategies for health and human service professionals / Laura N. Gitlin, Ann Kolanowski, Kevin J. Lyons.',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time / Gerald Feigin.',
       'Supply chain transformation : building and executing an integrated supply chain strategy / J. Paul Dittmann.',
       "Thanks for the feedback : the science and art of receiving feedback well (even when it is off base, unfair, poorly delivered, and frankly, you're not in the mood) / Douglas Stone & Sheila Heen.",
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The Lais of Marie de France : Text and Translation/',
       'The anxious generation : how the great rewiring of childhood is causing an epidemic of mental illness / Jonathan Haidt.',
       'The anxious generation [electronic resource] : How the great rewiring of childhood is causing an epidemic of mental illness. Jonathan Haidt.',
       'The comprehensive guide to interdisciplinary veterinary social work / Sana Loue, Pamela Linden, editors.',
       'The goal : a process of ongoing improvement / by Eliyahu M. Goldratt and Jeff Cox.',
       'The holocene : an environmental history / Professor Neil Roberts, School of Geography, Earth and Environmental Sciences, Plymouth University, UK.',
       'The portable feminist reader / edited with an introduction by Roxane Gay.',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world / Ronald Heifetz, Alexander Grashow, Marty Linsky.',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster / [edited by] Lisa López Levers, PhD, LPCC-S, LPC, CRC, NCC.'],
      dtype=object)

In [22]:
textbookISBNs = textbookISBNs.astype({'MMS Id': 'int64'})



resultsPlusList = pd.merge(results, textbookISBNs, left_on = 'MMS ID', right_on = 'MMS Id', how = 'inner')

In [23]:
resultsPlusList

,Title_x,Alternate Graphic Representation,Type,Creator / Imprint,Subject,Series,Relation,Modification Date,Edition,Uniform Title,Medium Type,Language,Creation Date,Language of Cataloging,ISBN_x,ISBN (13),ISSN,Cluster ISSN,Record Number,MMS ID,Bibliographic Rank,Local Call Number,Other Classification Number,NLM Call Number,Dewey Decimal Classification Number,LC Call Number,Classification Part,UDC Classification Number,NAL Call Number,Handle Identifier,Peer Reviewed,Open Access,Physical Availability,Digital Availability,Electronic Availability,Collection Name,Collection ID,Orders,Requests,Physical Description Extent,Local Labels,Related Records,Courses,Licenses,Reminders,Notes,Short Title,Electronic location and access,ISBN (Normalized),ISBN_y,MMS Id,Title_y,Electronic Collection Public Name,Availability,Portfolio Id,Service Authentication Note,No. of Available Portfolio,Portfolio Public Note,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes
0,The Lais of Marie de France : Text and Transla...,NaN,Book {Book - Physical} text; computer; online ...,"Waters, Claire M. (Orchard Park : Broadview Pr...",NaN,NaN,NaN,2026-05-27 09:15:00,NaN,NaN,NaN,unknown,2026-05-27 09:15:00,English,9781770486003,9781770486003,NaN,NaN,(VST)9781770486003,9926966302202311,72,NaN,NaN,NaN,841/.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at VitalSource Bookshelf; B...,NaN,NaN,0,0,1 online resource,NaN,1,0,0,0,0,The Lais of Marie de France :,https://resolver.vitalsource.com/9781770486003,9781770486003; 1770486003; 9781554810826; 1554...,9781770486003; 1770486003; 9781554810826; 1554...,9926966302202311,The Lais of Marie de France : Text and Transla...,Broadview Editions Bookshelf,Available,53462931570002311,NaN,1,NaN,NaN,[https://resolver.vitalsource.com/9781770486003],https://resolver.vitalsource.com/9781770486003,,https://resolver.vitalsource.com/9781770486003
1,Red book : 2024-2027 report of the Committee o...,NaN,Book {Book - Electronic} text; computer; onlin...,American Academy of Pediatrics. Committee on I...,Communicable diseases in children--Periodicals...,STAT!Ref electronic medical library. Red Book:...,NaN,2026-04-03 04:22:00,33rd edition.,NaN,NaN,English,2026-04-02 10:08:00,NaN,9781610027359; 1610027353; 9781610027342,9781610027359; 9781610027359; 9781610027342,NaN,NaN,90103981814; (NhCcYBP)ybp306401256,9926931276402311,111,NaN,NaN,WC 100,618.929,RJ240 .A44 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (L, 1261 pages) :",NaN,1,0,0,0,0,Red book :,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,https://search.ebscohost.com/login.aspx?direct...
2,"Sales force management : leadership, innovatio...",NaN,Book {Book - Electronic} text; computer; onlin...,"Johnston, Mark W., (New York, NY : Routledge, ...",Sales management.,NaN,NaN,2026-03-27 13:24:00,Fourteenth edition.,NaN,NaN,English,2025-06-10 08:16:00,English,1-04-030131-2,9781040301319,NaN,NaN,(CKB)39206405800041; (CaSebORM)9781040301319; ...,9926916167202311,90,NaN,NaN,NaN,658.8/1,HF5438.4 .C48 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,"1 online resource (xxx, 470 pages) :",NaN,0,0,0,0,0,Sales force management :,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
3,How great leaders think : the art of reframing,NaN,Book {Book - Electronic} text; computer; onlin...,"Bolman, Lee G., (San Francisco CA Jossey Bass ...",Leadership.;Organizational change.;Management;...,NaN,NaN,2026-05-28 01:33:00,1st edition,NaN,NaN,English,2015-03-15 08:35:00,NaN,9781118282236; 111828223X,9781118282236; 9781118282236,NaN,NaN,(CKB)3710000000372697; (SSID)ssj0001261991; (P...,9926914664702311,92,NaN,NaN,NaN,658.4/092,HD57.7.B6393 2014 and others,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (240 pages),NaN,0,0,0,0,0,How great leaders think : the art of reframing,NaN,111828223X; 9781118282236,111828223X; 9781118282236,9926914664702311,How great leaders think : the art of reframing,O'Reilly Online Learning: Academic/Public Libr...,Available,53454187110002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
4,Supply chain transformation : building and exe...,NaN,Book {Book - Electronic} text; computer; onlin...,"Dittmann, J. Paul, (New York : McGraw-Hill, 20...",Business logistics.;Strategic planning.,NaN,NaN,2026-03-27 13:18:00,1st edition,NaN,NaN,English,2013-01-20 01:44:00,English,9781283634748; 1283634740; 9780071798310; 0071...,9781283634748; 9781283634748; 9780071798310; 9...,NaN,NaN,(CKB)2550000000707210; (SSID)ssj0000760008; (P...,9926913176702311,100,NaN,NaN,NaN,658.7,HD38.5 .D588 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (1 v.) :,NaN,1,0,0,0,0,Supply chain transformation :,NaN,1283634740; 9781283634748; 0071798315; 9780071...,1283634740; 9781283634748; 0071798315; 9780071...,9926913176702311,Supply chain transformation : building and exe...,O'Reilly Online Learning: Academic/Public Libr...,Available,53453702880002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
5,"Hey whipple, squeeze this : the classic guide ...",NaN,Book {Book - Electronic} text; computer; onlin...,"Sullivan, Luke, (Hoboken, New Jersey : John Wi...",Advertising copy.,NaN,NaN,2026-05-18 09:38:00,Sixth edition,NaN,NaN,English,2022-03-02 03:11:00,English,1-119-81974-1; 1-119-81973-3; 1-119-81969-5,9781119819745; 9781119819738; 9781119819691,NaN,NaN,(MiAaPQ)EBC6896741; (Au-PeEL)EBL6896741; (CKB)...,9926910091102311,92,NaN,674 and others,NaN,659.132,HF5825 .S855 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,1 online resource (413 pages),NaN,0,0,0,0,0,"Hey whipple, squeeze this :",NaN,1119819741; 9781119819745; 1119819733; 9781119...,1119819741; 9781119819745; 1119819733; 9781119...,9926910091102311,"Hey whipple, squeeze this : the classic guide ...",O'Reilly Online Learning: Academic/Public Libr...,Available,53452773190002311,NaN,1,NaN,NaN,NaN,NaN,NaN,
6,Controversies in contemporary advertising [ele...,NaN,Book {Book - Electronic} text; computer; onlin...,"Sheehan, Kim Bartel, (Thousand oaks, [Calif.] ...",Advertising.,NaN,NaN,2026-04-10 04:10:00,NaN,NaN,NaN,English,2026-04-06 15:59:00,NaN,9781452233130 (Sage); 9780761926351,9781452233130 (Sage); 9780761926351,NaN,NaN,(CaONFJC)cis023286175,9926908933302311,78,NaN,NaN,NaN,659.1,HF5823 .S4854 2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at SAGE; SAGE Research Meth...,NaN,NaN,1,0,"1 online resource (ix, 333 p.)",NaN,0,0,0,0,0,Controversies in contemporary advertising,https://sk.sagepub.com/book/mono/controversies...,9781452233130; 1452233136; 9780761926351; 0761...,9781452233130; 1452233136; 9780761926351; 0761...,9926908933302311,Controversies in contemporary advertising,SAGE Research Methods Books & Reference,Available,53452449920002311,NaN,1,Unlimited Access,NaN,[https://sk.sagepub.com/book/mono/controversie...,https://sk.sagepub.com/book/mono/controversies...,Unlimited Access Unlimited Access,https://sk.sagepub.com/book/mono/controversies...
7,The anxious generation [electronic resource] :...,NaN,Book {Book - Electronic} text; computer; onlin...,"Haidt, Jonathan. (2024.)",Nonfiction.;Family & Relationships.;Psychology...,NaN,NaN,2026-03-20 04:08:00,NaN,NaN,NaN,English,2026-03-19 12:45:00,NaN,9780593655047 (electronic bk); 9780593655030,9780593655047 (electronic bk); 9780593655030,NaN,NaN,NaN,9926907601302311,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at OverDrive (OverDrive - C...,NaN,NaN,0,0,1 online resource,NaN,1,0,1,0,0,The anxious generation,http://link.overdrive.com/?websiteID=120589&ti...,9780593655047; 0593655044; 9780593655030; 0593...,9780593655047; 0593655044; 9780593655030; 0593...,9926907601302311,The anxious generation How the great rewiring ...,OverDrive - Consortium,Available,53452246900002311,NaN,1,Click to access digital title.,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Click to access digital title.; http://link.ov...
8,An evidence-based guide to assistive technolog...,NaN,Book {Book - Electronic} text; computer; onlin...,"Rhodes, Alice L., (New York, NY : Routledge, 2...",Students with disabilities--Services for.;Stud...,Evidence-based instruction in special education,NaN,2026-03-24 04:13:00,NaN,NaN,NaN,English,2026-03-23 16:04:00,English,9781003524090; 1003524095; 9781040524824; 1040...,9781003524090; 9781003524090; 9781040524824; 9...,NaN,NaN,(NhCcYBP)880e3b0db083431896f223e324a7708697810...,9926907593802311,98,NaN,NaN,NaN,371.9045,LC4015 .E87 2026eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Taylor & Francis; Taylor...,NaN,NaN,0,0,1 online resource (200 pages) :,NaN,0,0,0,0,0,An evidence-based guide to assistive technology :,https://www.taylorfrancis.com/books/9781003524090,1003524095; 9781003524090; 1040524826; 9781040...,1003524095; 9781003524090; 1040524826; 9781040...,9926907593802311,An evidence-based guide to assistive technolog...,Taylor & Francis Ebooks (EBA),Available,53452318750002311,Online Access: Unlimited Users,1,NaN,NaN,[https://www.taylorfrancis.com/books/978100352...,https://www.taylorfrancis.com/books/9781003524090,,Online Access: Unlimited Users; https://www.ta...
9,INTRODUCTION TO AMERICAN DEAF CULTURE [electro...,NaN,Book {Book - Electronic},THOMAS K. HOLCOMB. (OXFORD : OXFORD UNIV PRESS...,Deaf culture--United States.;Electronic books.,NaN,NaN,2026-02-17 04:03:00,NaN,NaN,NaN,English,2026-02-16 15:58:00,English,0190240857; 9780190240851,9780190240851; 9780190240851,NaN,NaN,(OCoLC)on1500519961; (OCoLC)1500519961,9926876681102311,78,NaN,NaN,NaN,NaN,HV2380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,0,0,1 online resource,NaN,0,0,0,0,0,INTRODUCTION TO AMERICAN DEAF CULTURE,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926876681102311,INTRODUCTION TO AMERICAN DEAF CULTURE,Ebooks moved from ProQuest to EBSCO,Available,53451023240002311,NaN,1,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...
10,Trauma counseling : theories and interventions...,NaN,Book {Book - Electronic} text; computer; onlin...,"López Levers, Lisa (New York, NY : Springer Pu...",Psychic trauma--Treatment.;Wounds and injuries...,NaN,NaN,2026-04-15 08:28:00,Second edition.,NaN,NaN,English,2026-02-02 11:07:00,English,9780826150851; 0826150853; 9780826150851 (EBSC...,9780826150851; 9780826150851; 9780826150851 (E...,NaN,NaN,(OCoLC)1298514014; (OCoLC)cis063794753,9926868740402311,101,NaN,NaN,NaN,362.1/04256,RC552.P67 L475 2023eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (xxvi, 550 pages) :",NaN,0,0,0,0,0,Trauma counseling :,https://search.ebscohost.com/login.aspx?direct...,9780826150851; 0826150853; 9780826150844; 0826...,9780826150851; 0826150853; 9780826150844; 0826...,9926868740402311,Trauma counseling : theories and interventions...,EBSCO Ebooks Individually Purchased,Available,53449784400002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
11,New kid [electronic resource]. Jerry Craft.,NaN,Book {Book - Electronic} text; computer; onlin...,"Craft, Jerry. (2019.)",Juvenile Fiction.;African American Fiction.;Co...,NaN,NaN,2026-01-27 04:11:00,NaN,NaN,NaN,English,2026-01-26 15:25:00,NaN,9780062691217 (electronic bk); 9780062691194,9780062691217 (electronic bk); 9780062691194,NaN,NaN,NaN,9926858905602311,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at OverDrive (OverDrive - A...,NaN,NaN,0,0,1 online resource,NaN,1,0,1,0,0,New kid,http://link.overdrive.com/?websiteID=120589&ti...,9780062691217; 006269121X; 9780062691194; 0062...,9780062691217; 006269121X; 9780062691194; 0062...,9926858905602311,New kid,OverDrive - Advantage,Available,53449394640002311,NaN,1,Click to access digital title.,NaN,[http://link.overdrive.com/?websiteID=120589&t...,http://link.overdrive.com/?websiteID=120589&ti...,Click to access digital title.,Click to access digital title.; http://link.ov...
12,INTRODUCTION TO AMERICAN DEAF CULTURE [electro...,NaN,Book {Book - Electronic} text; unmediated; volume,THOMAS K. HOLCOMB. (OXFORD : OXFORD UNIV PRESS...,Deaf culture--United States.;Culture sourde--É...,NaN,NaN,2026-04-15 08:28:00,NaN,NaN,NaN,English,2026-01-05 16:35:00,English,0190240857; 9780190240851; 9780190240851 (EBSCO),9780190240851; 9780190240851; 9780190240851 (E...,NaN,NaN,(OCoLC)1500519961; (OCoLC)cis070811966,9926852848702311,84,NaN,NaN,NaN,305.9/0820973,HV2380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,0,0,0,0,0,INTRODUCTION TO AMERICAN DEAF CULTURE,https://search.ebscohost.com/login.aspx?direct...,9780190240851; 0190240857,9780190240851; 0190240857,9926852848702311,INTRODUCTION TO AMERICAN DEAF CULTURE,EBSCO Ebooks Individually Purchased,Available,53448439790002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,https://search.ebscohost.com/login.aspx?direct...
13,Applied Artificial Intelligence in Business : ...,NaN,Book {Book - Electronic} text; computer; onlin...,"Chan, Leong. (Cham : Springer International Pu...",Artificial intelligence-Industrial application...,Applied Innovation and Technology Management S...,NaN,2026-04-15 08:28:00,NaN,NaN,NaN,English,2025-12-03 09:32:00,NaN,9783031057397; 9783031057403 (Springer e-books...,9783031057397; 9783031057403 (Springer e-books...,NaN,NaN,(CaONFJC)cis064550969,9926837078602311,87,NaN,NaN,NaN,658.0563,HD30.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Springer Nature; Springe...,NaN,NaN,1,0,1 online resource (370 pages),NaN,0,0,0,0,0,Applied Artificial Intelligence in Business :,https://link.springer.com/978-3-031-05740-3 Un...,9783031057403; 3031057406; 9783031057397; 3031...,9783031057403; 3031057406; 9783031057397; 3031...,9926837078602311,Applied Artificial Intelligence in Business : ...,Springer Ebooks Individually Purchased,Available,53446362200002311,NaN,1,Unlimited Access,NaN,"[https://link.springer.com/978-3-031-05740-3, ...",https://link.springer.com/978-3-031-05740-3,Unlimited Access Unlimited Access,https://link.springer.com/978-3-031-05740-3 Un...
14,The Comprehensive Guide to Interdisciplinary V...,NaN,Book {Book - Electronic} text; computer; onlin...,"Loue, Sana. (Cham : Springer International Pub...",Animal welfare.,NaN,NaN,2025-12-30 10:17:00,1st ed.,NaN,NaN,English,2025-12-06 14:56:00,NaN,9783031103292; 9783031103308 (Springer e-books...,9783031103292; 9783031103308 (Springer e-books...,NaN,NaN,(CaONFJC)cis064862564,9926829231602311,86,NaN,NaN,NaN,NaN,RC455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at Springer Nature; Springe...,NaN,NaN,0,0,1 online resource (370 pages),NaN,2,0,0,0,0,The Comprehensive Guide to Interdisciplinary V...,https://link.springer.com/978-3-031-10330-8 Un...,9783031103308; 3031103300; 9783031103292; 3031...,9783031103308; 3031103300; 9783031103292; 3031...,9926829231602311,The Comprehensive Guide to Interdisciplinary V...,Springer Ebooks Individually Purchased,Available,53433284910002311,NaN,1,Unlimited Access,NaN,"[https://link.springer.com/978-3-031-10330-8, ...",https://link.springer.com/978-3-031-10330-8,Unlimited Access Unlimited Access,https://link.springer.com/978-3-031-10330-8 Un...
15,"Religio Medici and Hydriotaphia, or Urne-Buria...",NaN,Book {Book - Electronic} text; computer; onlin...,"Browne, Thomas, (New York, NY : The New York R...",1500-1700;English prose literature--Early mode...,New York Review Books classics,NaN,2026-04-15 08:28:00,NaN,NaN,NaN,English,2025-08-15 13:02:00,English,9781590175033; 1590175034; 9781590175033 (EBSC...,9781590175033; 9781590175033; 9781590175033 (E...,NaN,NaN,(OCoLC)869384333; (OCoLC)cis023169076,9926781641702311,114,NaN,NaN,2015 J-990 and others,828/.409,PR3327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,0,0,0,0,0,"Religio Medici and Hydriotaphia, or Urne-Buria...",https://search.ebscohost.com/login.aspx?direct...,1590174887; 9781590174883; 9781590175033; 1590...,1590174887; 9781590174883; 9781590175033; 1590...,9926781641702311,"Religio Medici and Hydriotaphia, or Urne-Buria...",EBSCO Ebooks Individually Purchased,Available,53441638660002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Single User Single User,https://search.ebscohost.com/login.aspx?direct...
16,The portable feminist reader / edited with an ...,NaN,Book {Book - Electronic} text; computer; onlin...,"Gay, Roxane, (New York : Penguin Books, [2025])",Feminism.;Electronic books.,Penguin classics,NaN,2025-12-30 10:17:00,NaN,NaN,NaN,English,2025-06-10 15:02:00,NaN,9781101992678; 1101992670; 9780143110392,9781101992678; 9781101992678; 9780143110392,NaN,NaN,90101993167; (DLC)ybp308895455,9926747489202311,88,NaN,NaN,NaN,305.42,HQ1150 .P67 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,0,0,0,0,0,The portable feminist reader /,https://search.ebscohost.com/login.aspx?direct...,1101992670; 9781101992678; 9780143110392; 0143...,1101992670; 9781101992678; 9780143110392; 0143...,9926747489202311,The portable feminist reader /,EBSCO Ebooks Individually Purchased,Available,53438150710002311,NaN,1,NaN,Online Access - 1 user,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - 1 user,https://search.ebscohost.com/login.aspx?direct...
17,Stoelting's pharmacology & physiology in anest...,NaN,Book {Book - Electronic} text; computer; onlin...,"Flood, Pamela; Rathmell, James P.; Urman, Rich...","Anesthesiology--Handbooks, manuals, etc.;Anest...",NaN,NaN,2026-04-15 08:28:00,Sixth edition,Stoelting's pharmacology and physiology in ane...,NaN,English,2025-05-30 09:32:00,English,9781975126926; 1975126920; 9781975126919; 1975...,9781975126926; 9781975126926; 9781975126919; 9...,NaN,NaN,(OCoLC)1249630319; (OCoLC)cis062117750,9926738030202311,106,NaN,NaN,QV 81,615.7/81,RD82.2 .S76 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,1 online resource,NaN,1,0,0,0,0,Stoelting's pharmacology & physiology in anest...,https://search.ebscohost.com/login.aspx?direct...,1975126920; 9781975126926; 9781975126919; 1975...,1975126920; 9781975126926; 9781975126919; 1975...,9926738030202311,Stoelting's pharmacology & physiology in anest...,EBSCO Ebooks Individually Purchased,Available,53437481400002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Unlimited Access Unlimited Access,Online Access - Unlimited users; https://searc...

In [24]:
#resultsPlusList.to_excel('Results Plus List Example.xlsx')

resultsPlusList.sort_values(by = 'Title_x')['Title_x'].unique()

array(['An evidence-based guide to assistive technology : meeting the needs of all students with disabilities / edited by Alice L. Rhodes and Victoria Slocum.',
       'Applied Artificial Intelligence in Business : Concepts and Cases.',
       "Beowulf : poem, poet and hero / Heather O'Donoghue.",
       'Child-centered play therapy : a practical guide to therapeutic relationships with children / Nancy H. Cochran, William J. Nordling, Jeff L. Cochran.',
       'Controversies in contemporary advertising [electronic resource] / Kim Bartel Sheehan.',
       'Core Competencies in Cognitive-Behavioral Therapy : Becoming a Highly Effective and Competent Cognitive-Behavioral Therapist / Cory F. Newman.',
       'Deaf culture : exploring deaf communities in the United States / Irene W. Leigh, PhD, Jean F. Andrews, PhD, Raychelle L. Harris, PhD, Topher González Ávila, MA.',
       'Demand and Supply Integration : The Key to World-Class Demand Forecasting, Second Edition.',
       'Ethics of data and analytics : concepts and cases / Kirsten Martin.',
       'Evicted poverty and profit in the American city Matthew Desmond.',
       'Evidence-based practice improvement : merging evidence-based practice and quality improvement / Rona F. Levin, Bonnie Lauder, editors.',
       'Global writing for public relations : connecting in English with stakeholders and publics worldwide / Arhlene A. Flowers.',
       'Guide to the vascular plants of Tennessee / compiled and edited by members of the Tennessee Flora Committee.',
       'Hey whipple, squeeze this : the classic guide to creating great advertising / Luke Sullivan.',
       'How great leaders think : the art of reframing',
       'Human osteology / Tim D. White, Michael T. Black, Pieter A. Folkens.',
       'INTRODUCTION TO AMERICAN DEAF CULTURE [electronic resource].',
       'Inside out and outside in : psychodynamic clinical theory and psychopathology in contemporary multicultural contexts / edited by Joan Berzoff, Laura Melano Flanagan, and Patricia Hertz.',
       'Introduction to Crisis and Trauma Counseling.',
       'Johns Hopkins Evidence-Based Practice for Nurses and Healthcare Professionals, Fourth Edition.',
       'Johns Hopkins evidence-based practice for nurses and healthcare professionals : models and guidelines / [edited by] Deborah Dang, PhD, RN, NEA-BC, Sandra Dearholt, DNP, RN, NEA-BC, Kim Bissett, PhD, MBA, RN, Judy Ascenzi, DNP, RN, CCRN-K, Madeleine Whalen, MSN/MPH, RN, CEN.',
       'Linguistics of American Sign Language, 5th Ed. :  An Introduction /  Clayton Valli [and others].',
       'New kid [electronic resource]. Jerry Craft.',
       'On the history of political philosophy : great political thinkers from Thucydides to Locke / W. Julian Korab-Karpowicz.',
       'Pediatric acute care : a guide for interprofessional practice / edited by Beth Nachtsheim Bolick, Karin Reuter-Rice, Maureen A. Madden, Paul N. Severin.',
       'Planetary Geology : An Introduction.',
       'Process-based CBT : the science and core clinical competencies of cognitive behavioral therapy / edited by Steven C. Hayes, and Stefan G. Hofmann.',
       'Professional development : what works / Sally J. Zepeda.',
       'Property of the Rebel Librarian [electronic resource] / Allison Varnes.',
       'Pursuing happiness [electronic resource] : a Bedford spotlight reader / [compiled and edited by] Matthew Parfitt, Boston University, Dawn Skorczewski, Brandeis University.',
       'Red book : 2024-2027 report of the Committee on Infectious Diseases / author: Committee on Infectious Diseases, American Academy of Pediatrics; David W. Kimberlin, MD, FAAP, editor; Ritu Banerjee, MD, PhD, FAAP, Elizabeth D. Barnett, MD, FAAP, Ruth Lynfield, MD, FAAP, Mark H. Sawyer, MD, FAAP, associate editor.',
       'Religio Medici and Hydriotaphia, or Urne-Buriall / Sir Thomas Browne ; edited and with an introduction by Stephen Greenblatt and Ramie Targoff.',
       'Research methods for social work : a problem-based approach / Antoinette Y. Farmer, G. Lawrence Farmer.',
       'Sales force management : leadership, innovation, technology / Mark W. Johnston, Greg W. Marshall, and Jessica L. Ogilvie.',
       'School social work : a skills-based competency approach / JoDee Keller, PhD, LICSW Department of Social Work, Professor of Social Work Pacific Lutheran University.',
       'Social welfare policy for a sustainable future : the U.S. in global context / Katherine S. van Wormer, Rosemary J. Link.',
       "Stoelting's pharmacology & physiology in anesthetic practice [edited by] Pamela Flood, James P. Rathmell, Richard D. Urman",
       'Strategy in 3D : essential tools to diagnose, decide, & deliver / Greg Fisher, John E. Wisneski, Rene M. Bakker.',
       'Successful grant writing : strategies for health and human service professionals / Laura N. Gitlin, Ann Kolanowski, Kevin J. Lyons.',
       'Supply Chain Planning and Analytics : The Right Product in the Right Place at the Right Time   The Right Product in the Right Place at the Right Time.',
       'Supply chain planning and analytics : the right product in the right place at the right time / Gerald Feigin.',
       'Supply chain transformation : building and executing an integrated supply chain strategy / J. Paul Dittmann.',
       'The Comprehensive Guide to Interdisciplinary Veterinary Social Work.',
       'The Lais of Marie de France : Text and Translation/',
       'The anxious generation : how the great rewiring of childhood is causing an epidemic of mental illness / Jonathan Haidt.',
       'The anxious generation [electronic resource] : How the great rewiring of childhood is causing an epidemic of mental illness. Jonathan Haidt.',
       'The comprehensive guide to interdisciplinary veterinary social work / Sana Loue, Pamela Linden, editors.',
       'The portable feminist reader / edited with an introduction by Roxane Gay.',
       'The practice of adaptive leadership : tools and tactics for changing your organization and the world / Ronald Heifetz, Alexander Grashow, Marty Linsky.',
       'Trauma counseling : theories and interventions for managing trauma, stress, crisis, and disaster / [edited by] Lisa López Levers, PhD, LPCC-S, LPC, CRC, NCC.'],
      dtype=object)

### Expand the ISBN Normalized Column

In [25]:
resultsPlusList['ISBN (Normalized) List'] = resultsPlusList['ISBN (Normalized)'].apply(lambda x: x.split(";"))

In [26]:
expandedList = resultsPlusList.explode('ISBN (Normalized) List')

expandedList['ISBN (Normalized) List'] = expandedList['ISBN (Normalized) List'].str.strip()

#expandedList.to_excel('Expanded List Example.xlsx')

In [27]:
finalJoin = pd.merge(expandedList, bookstoreList, left_on = 'ISBN (Normalized) List', right_on = 'ISBN', how = 'inner')

finalJoin = finalJoin.rename(columns = {'Short Title_y': 'Short Title'})

finalJoin

,Title_x,Alternate Graphic Representation,Type,Creator / Imprint,Subject,Series,Relation,Modification Date,Edition,Uniform Title,Medium Type,Language,Creation Date,Language of Cataloging,ISBN_x,ISBN (13),ISSN,Cluster ISSN,Record Number,MMS ID,Bibliographic Rank,Local Call Number,Other Classification Number,NLM Call Number,Dewey Decimal Classification Number,LC Call Number,Classification Part,UDC Classification Number,NAL Call Number,Handle Identifier,Peer Reviewed,Open Access,Physical Availability,Digital Availability,Electronic Availability,Collection Name,Collection ID,Orders,Requests,Physical Description Extent,Local Labels,Related Records,Courses,Licenses,Reminders,Notes,Short Title_x,Electronic location and access,ISBN (Normalized),ISBN_y,MMS Id,Title_y,Electronic Collection Public Name,Availability,Portfolio Id,Service Authentication Note,No. of Available Portfolio,Portfolio Public Note,Portfolio Authentication Note,Electronic location split,Electronic location,Electronic access,Concatenated Notes,ISBN (Normalized) List,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity
0,The Lais of Marie de France : Text and Transla...,NaN,Book {Book - Physical} text; computer; online ...,"Waters, Claire M. (Orchard Park : Broadview Pr...",NaN,NaN,NaN,2026-05-27 09:15:00,NaN,NaN,NaN,unknown,2026-05-27 09:15:00,English,9781770486003,9781770486003,NaN,NaN,(VST)9781770486003,9926966302202311,72,NaN,NaN,NaN,841/.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at VitalSource Bookshelf; B...,NaN,NaN,0,0,1 online resource,NaN,1,0,0,0,0,The Lais of Marie de France :,https://resolver.vitalsource.com/9781770486003,9781770486003; 1770486003; 9781554810826; 1554...,9781770486003; 1770486003; 9781554810826; 1554...,9926966302202311,The Lais of Marie de France : Text and Transla...,Broadview Editions Bookshelf,Available,53462931570002311,NaN,1,NaN,NaN,[https://resolver.vitalsource.com/9781770486003],https://resolver.vitalsource.com/9781770486003,,https://resolver.vitalsource.com/9781770486003,9781770486003,Summer 2026,ENGLISH,202630-ENGL.301.301-88080,"Perry, Ryan",9781770486003,THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLA...,NaN,BROADVIEW PRESS,15
1,The Lais of Marie de France : Text and Transla...,NaN,Book {Book - Physical} text; computer; online ...,"Waters, Claire M. (Orchard Park : Broadview Pr...",NaN,NaN,NaN,2026-05-27 09:15:00,NaN,NaN,NaN,unknown,2026-05-27 09:15:00,English,9781770486003,9781770486003,NaN,NaN,(VST)9781770486003,9926966302202311,72,NaN,NaN,NaN,841/.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at VitalSource Bookshelf; B...,NaN,NaN,0,0,1 online resource,NaN,1,0,0,0,0,The Lais of Marie de France :,https://resolver.vitalsource.com/9781770486003,9781770486003; 1770486003; 9781554810826; 1554...,9781770486003; 1770486003; 9781554810826; 1554...,9926966302202311,The Lais of Marie de France : Text and Transla...,Broadview Editions Bookshelf,Available,53462931570002311,NaN,1,NaN,NaN,[https://resolver.vitalsource.com/9781770486003],https://resolver.vitalsource.com/9781770486003,,https://resolver.vitalsource.com/9781770486003,9781770486003,Summer 2026,ENGLISH,202630-ENGL.301.302-88081,"Perry, Ryan",9781770486003,THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLA...,NaN,BROADVIEW PRESS,10
2,Red book : 2024-2027 report of the Committee o...,NaN,Book {Book - Electronic} text; computer; onlin...,American Academy of Pediatrics. Committee on I...,Communicable diseases in children--Periodicals...,STAT!Ref electronic medical library. Red Book:...,NaN,2026-04-03 04:22:00,33rd edition.,NaN,NaN,English,2026-04-02 10:08:00,NaN,9781610027359; 1610027353; 9781610027342,9781610027359; 9781610027359; 9781610027342,NaN,NaN,90103981814; (NhCcYBP)ybp306401256,9926931276402311,111,NaN,NaN,WC 100,618.929,RJ240 .A44 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (L, 1261 pages) :",NaN,1,0,0,0,0,Red book :,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,https://search.ebscohost.com/login.aspx?direct...,9781610027359,Summer 2026,NURSING,202630-NURS.670.001-85245,"Malone, Marian",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,9
3,Red book : 2024-2027 report of the Committee o...,NaN,Book {Book - Electronic} text; computer; onlin...,American Academy of Pediatrics. Committee on I...,Communicable diseases in children--Periodicals...,STAT!Ref electronic medical library. Red Book:...,NaN,2026-04-03 04:22:00,33rd edition.,NaN,NaN,English,2026-04-02 10:08:00,NaN,9781610027359; 1610027353; 9781610027342,9781610027359; 9781610027359; 9781610027342,NaN,NaN,90103981814; (NhCcYBP)ybp306401256,9926931276402311,111,NaN,NaN,WC 100,618.929,RJ240 .A44 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at EBSCOhost; EBSCO Ebooks ...,NaN,NaN,1,0,"1 online resource (L, 1261 pages) :",NaN,1,0,0,0,0,Red book :,https://search.ebscohost.com/login.aspx?direct...,1610027353; 9781610027359; 9781610027342; 1610...,1610027353; 9781610027359; 9781610027342; 1610...,9926931276402311,Red book : 2024-2027 report of the Committee o...,EBSCO Ebooks Individually Purchased,Available,53454770480002311,NaN,1,NaN,Online Access - Unlimited users,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,https://search.ebscohost.com/login.aspx?direct...,9781610027359,Summer 2026,NURSING,202630-NURS.670.002-87778,"Neal, Allyson",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,5
4,"Sales force management : leadership, innovatio...",NaN,Book {Book - Electronic} text; computer; onlin...,"Johnston, Mark W., (New York, NY : Routledge, ...",Sales management.,NaN,NaN,2026-03-27 13:24:00,Fourteenth edition.,NaN,NaN,English,2025-06-10 08:16:00,English,1-04-030131-2,9781040301319,NaN,NaN,(CKB)39206405800041; (CaSebORM)9781040301319; ...,9926916167202311,90,NaN,NaN,NaN,658.8/1,HF5438.4 .C48 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...,NaN,NaN,0,0,"1 online resource (xxx, 470 pages) :",NaN,0,0,0,0,0,Sales force management :,NaN,1040301312; 9781040301319,1040301312; 9781040301319,9926916167202311,"Sales force management : leadership, innovatio...",O'Reilly Online Learning: Academic/Public Libr...,Available,53454615920002311,NaN,1,NaN,NaN,NaN,NaN,NaN,,9781040301319,Summer 2026,MARKETING,202630-MARK.471.301-88179,"Presley Bone, Blair",9781040301319,"SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATIO...","JOHNSTON, MARK W., MARSHALL, GREG W., AND OGIL...","ROUTLEDGE, CHAPMAN & HALL, INCORPORATED",35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,Social welfare policy for a sustainable future...,NaN,Book {Book - Electronic} text; computer; onlin...,"Van Wormer, Katherine S., (Los Angeles, [Calif...",Electronic books.;Social service--United State...,NaN,NaN,2026-05-13 04:13:00,1st ed.,NaN,NaN,English,2017-01-04 12:01:00,NaN,9781452240312; 9781483322421 (e-book); 9781483...,9781452240312; 9781483322421 (e-book); 9781483...,NaN,NaN,(MiAaPQ)EBC4733087; (OCoLC)962451445; (CaONFJC...,9925617965602311,97,NaN,NaN,NaN,361.610973,HV95 .V36 2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,2,0,1 online resource (449 pages) :,NaN,0,0,0,0,0,Social welfare policy for a sustainable future :,https://ebookcentral.proquest.com/lib/utk/deta...,9781483322421; 1483322424; 9781483380094; 1483...,9781483322421; 1483322424; 9781483380094; 1483...,9925617965602311,Social welfare policy for a sustainable future...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53270254120002311,NaN,1,NaN,Online Access - Unlimited Users,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,https://ebookcentral.proquest.com/lib/utk/deta...,9781483380094,Summer 2026,SOCIAL WORK,202630-SOWK.250.001-84600,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15
144,Social welfare policy for a sustainable future...,NaN,Book {Book - Electronic} text; computer; onlin...,"Van Wormer, Katherine S., (Los Angeles, [Calif...",Electronic books.;Social service--United State...,NaN,NaN,2026-05-13 04:13:00,1st ed.,NaN,NaN,English,2017-01-04 12:01:00,NaN,9781452240312; 9781483322421 (e-book); 9781483...,9781452240312; 9781483322421 (e-book); 9781483...,NaN,NaN,(MiAaPQ)EBC4733087; (OCoLC)962451445; (CaONFJC...,9925617965602311,97,NaN,NaN,NaN,361.610973,HV95 .V36 2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,2,0,1 online resource (449 pages) :,NaN,0,0,0,0,0,Social welfare policy for a sustainable future :,https://ebookcentral.proquest.com/lib/utk/deta...,9781483322421; 1483322424; 9781483380094; 1483...,9781483322421; 1483322424; 9781483380094; 1483...,9925617965602311,Social welfare policy for a sustainable future...,ProQuest Ebook Central Ebooks Individually Pur...,Available,53270254120002311,NaN,1,NaN,Online Access - Unlimited Users,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,https://ebookcentral.proquest.com/lib/utk/deta...,9781483380094,Summer 2026,SOCIAL WORK,202630-SOWK.250.002-84791,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15
145,Social welfare policy for a sustainable future...,NaN,Book {Book - Electronic} text; computer; onlin...,"Van Wormer, Katherine S., (Los Angeles, [Calif...",Electronic books.;Social service--United State...,NaN,NaN,2026-05-13 04:13:00,1st ed.,NaN,NaN,English,2017-01-04 12:01:00,NaN,9781452240312; 9781483322421 (e-book); 9781483...,9781452240312; 9781483322421 (e-book); 9781483...,NaN,NaN,(MiAaPQ)EBC4733087; (OCoLC)962451445; (CaONFJC...,9925617965602311,97,NaN,NaN,NaN,361.610973,HV95 .V36 2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,2,0,1 online resource (449 pages) :,NaN,0,0,0,0,0,Social welfare policy for a sustainable future :,https://ebookcentral.proquest.com/lib/utk/deta...,9781483322421; 1483322424; 9781483380094; 1483...,9781483322421; 1483322424; 9781483380094; 1483...,9925617965602311,Social welfare policy for a sustainable future...,ProQuest Ebook Central Rialto,Available,53462409540002311,NaN,1,Unlimited Access,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,https://ebookcentral.proquest.com/lib/utk/deta...,9781483380094,Summer 2026,SOCIAL WORK,202630-SOWK.250.001-84600,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15
146,Social welfare policy for a sustainable future...,NaN,Book {Book - Electronic} text; computer; onlin...,"Van Wormer, Katherine S., (Los Angeles, [Calif...",Electronic books.;Social service--United State...,NaN,NaN,2026-05-13 04:13:00,1st ed.,NaN,NaN,English,2017-01-04 12:01:00,NaN,9781452240312; 9781483322421 (e-book); 9781483...,9781452240312; 9781483322421 (e-book); 9781483...,NaN,NaN,(MiAaPQ)EBC4733087; (OCoLC)962451445; (CaONFJC...,9925617965602311,97,NaN,NaN,NaN,361.610973,HV95 .V36 2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,2,0,1 online resource (449 pages) :,NaN,0,0,0,0,0,Social welfare policy for a sustainable future :,https://ebookcentral.proquest.com/lib/utk/deta...,9781483322421; 1483322424; 9781483380094; 1483...,9781483322421; 1483322424; 9781483380094; 1483...,9925617965602311,Social welfare policy for a sustainable future...,ProQuest Ebook Central Rialto,Available,53462409540002311,NaN,1,Unlimited Access,NaN,[https://ebookcentral.proquest.com/lib/utk/det...,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,https://ebookcentral.proquest.com/lib/utk/deta...,9781483380094,Summer 2026,SOCIAL WORK,202630-SOWK.250.002-84791,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15
147,Supply chain planning and analytics : the righ...,NaN,Book {Book - Electronic} text; computer; onlin...,"Feigin, Gerald. (New York, NY : Business Exper...",Business logistics.;Just-in-time systems.;Phys...,Supply and operations management collection ; ...,NaN,2026-01-29 04:11:00,1st ed.,NaN,NaN,English,2014-12-07 13:26:00,English,9781606492468; 1606492462; 9781606492451,9781606492468; 9781606492468; 9781606492451,NaN,NaN,(OCoLC)ocn758980820; (OCoLC)758980820; (OCoLC)...,9924042300102311,113,NaN,NaN,NaN,NaN,HD38.5 .F457 2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electronic version at ProQuest; ProQuest Ebook...,NaN,NaN,1,0,"1 online resource (xi, 159 pages) :",NaN,1,0,0,0,0,Supply chain planning and analytics :,https://search.ebscohost.com/login.aspx?direct...,1606492462; 9781606492468; 9781606492451; 1606...,1606492462; 9781606492468; 9781606492451; 1606...,9924042300102311,Supply chain planning and analytics : the righ...,Ebooks moved from ProQuest to EBSCO,Available,53449627790002311,NaN,1,NaN,NaN,[https://search.ebscohost.com/login.aspx?direc...,https://search.ebscohost.com/login.aspx?direct...,,https://search.ebscohost.com/login.aspx?direct...,9781606492468,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.547.002-85249,"Pellathy, Daniel",9781606492468,THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION...,"FEIGIN, GERALD",BUSINESS EXPERT PRESS,30

In [28]:
selectiveCols = finalJoin[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN (Normalized) List', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Electronic location', 'Electronic access', 'Electronic Availability']]

selectiveCols = selectiveCols.drop_duplicates()

selectiveCols = selectiveCols.rename(columns = {'Section Code': 'Course Code'})

len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

49

In [29]:
selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique()

array(['AN EVIDENCE-BASED GUIDE TO ASSISTIVE TECHNOLOGY : MEETING THE NEEDS OF ALL STUDENTS WITH DISABILITIES',
       'APPLIED ARTIFICIAL INTELLIGENCE IN BUSINESS',
       'BEOWULF A NEW VERSE TRANSLATION BILINGUAL EDITION',
       'CHILD-CENTERED PLAY THERAPY',
       'CONTROVERSIES IN CONTEMPORARY ADVERTISING',
       'CORE COMPETENCIES IN COGNITIVE-BEHAVIORAL THERAPY',
       'DEAF CULTURE : EXPLORING DEAF COMMUNITIES IN THE UNITED STATES',
       'DEMAND AND SUPPLY INTEGRATION : THE KEY TO WORLD-CLASS DEMAND FORECASTING, SECOND EDITION',
       'ETHICS OF DATA AND ANALYTICS',
       'ETHICS OF DATA AND ANALYTICS : CONCEPTS AND CASES', 'EVICTED',
       'EVIDENCE-BASED PRACTICE IMPROVEMENT : MERGING EVIDENCE-BASED PRACTICE AND QUALITY IMPROVEMENT',
       'GLOBAL WRITING FOR PUBLIC RELATIONS',
       'GUIDE TO THE VASCULAR PLANTS OF TENNESSEE',
       'HEY WHIPPLE, SQUEEZE THIS',
       'HOW GREAT LEADERS THINK : THE ART OF REFRAMING',
       'HUMAN OSTEOLOGY', 'INSIDE OUT AND OUTSIDE IN',
       'INTRODUCTION TO AMERICAN DEAF CULTURE',
       'INTRODUCTION TO CRISIS AND TRAUMA COUNSELING',
       'JOHNS HOPKINS EVIDENCE-BASED PRACTICE FOR NURSES AND HEALTHCARE PROFESSIONALS, FOURTH EDITION',
       'LINGUISTICS OF ASL: INTRO (W/DVD)', 'NEW KID',
       'ON THE HISTORY OF POLITICAL PHILOSOPHY : GREAT POLITICAL THINKERS FROM THUCYDIDES TO LOCKE',
       'PEDIATRIC ACUTE CARE : A GUIDE TO INTERPROFESSIONAL PRACTICE',
       'PLANETARY GEOLOGY : AN INTRODUCTION', 'PROCESSED BASED CBT',
       'PROFESSIONAL DEVELOPMENT : WHAT WORKS',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'RED BOOK 2024 : REPORT OF THE COMMITTEE ON INFECTIOUS DISEASES',
       'RELIGIO MEDICI AND URNE-BURIALL',
       'RESEARCH METHODS FOR SOCIAL WORK : A PROBLEM-BASED APPROACH',
       'SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATION, TECHNOLOGY',
       'SCHOOL SOCIAL WORK',
       'SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE',
       "STOELTING'S PHARMACOLOGY AND PHYSIOLOGY IN ANESTHETIC PRACTICE",
       'STRATEGY IN 3D',
       'STRATEGY IN 3D : ESSENTIAL TOOLS TO DIAGNOSE, DECIDE, AND DELIVER',
       'SUCCESSFUL GRANT WRITING : STRATEGIES FOR HEALTH AND HUMAN SERVICE PROFESSIONALS',
       'SUPPLY CHAIN TRANSFORMATION: BUILDING AND EXECUTING AN INTEGRATED SUPPLY CHAIN STRATEGY',
       'THE ANXIOUS GENERATION',
       'THE ANXIOUS GENERATION : HOW THE GREAT REWIRING OF CHILDHOOD IS CAUSING AN EPIDEMIC OF MENTAL ILLNESS',
       'THE COMPREHENSIVE GUIDE TO INTERDISCIPLINARY VETERINARY SOCIAL WORK',
       'THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLATION',
       'THE PORTABLE FEMINIST READER',
       'THE PRACTICE OF ADAPTIVE LEADERSHIP',
       'THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION: SUPPLY CHAIN PLANNING AND ANALYTICS : THE RIGHT PRODUCT IN THE RIGHT PLACE AT THE RIGHT TIME',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER'],
      dtype=object)

In [30]:
# Filter out the titles whose access is not Unlimited

salvagedCols = selectiveCols[(selectiveCols['Short Title'] == 'GUIDE TO THE VASCULAR PLANTS OF TENNESSEE')] #Use this to save titles from the delete codes that come later in this cell!

selectiveCols = selectiveCols[(selectiveCols['Electronic access'] != 'Online Access - 1 user') & (selectiveCols['Electronic access'] != 'Single User Single User') & (selectiveCols['Electronic access'] != 'Three User Three User') & (selectiveCols['Electronic access'] != 'Online Access - 3 users') & (selectiveCols['Electronic access'] != 'Online access : 2 simultaneous users; http://www.ebrary.com/corp/legal.jsp Click here for terms of use') & (selectiveCols['Electronic access'] != 'Online access - 1 simultaneous user') & (selectiveCols['Electronic access'] != 'Online Access - 3 simultaneous users.')]

selectiveCols = selectiveCols[(selectiveCols['Short Title'] != 'BEOWULF A NEW VERSE TRANSLATION BILINGUAL EDITION') & (selectiveCols['Short Title'] != 'CEREMONY') & (selectiveCols['Short Title'] != 'CRAFTING THE PERSONAL ESSAY : A GUIDE FOR WRITING AND PUBLISHING CREATIVE NON-FICTION') & (selectiveCols['Short Title'] != 'EVERYTHING IS OBVIOUS : HOW COMMON SENSE FAILS US') & (selectiveCols['Short Title'] != 'FUN HOME : A FAMILY TRAGICOMIC') & (selectiveCols['Short Title'] != 'INFORMATION ARCHITECTURE F/WORLD WI') & (selectiveCols['Short Title'] != 'ME AND MY DADDY LISTEN TO BOB MARLEY : NOVELLAS AND STORIES') & (selectiveCols['Short Title'] != 'PUBLIC LIBRARIES AND THEIR COMMUNITIES') & (selectiveCols['Short Title'] != 'STRATEGIC PLANNING FOR PUBLIC RELATIONS') & (selectiveCols['Short Title'] != 'SUN ALSO RISES') & (selectiveCols['Short Title'] != 'THE PROFESSOR IS IN : THE ESSENTIAL GUIDE TO TURNING YOUR PH. D. INTO A JOB') & (selectiveCols['Short Title'] != "ALL THAT SHE CARRIED : THE JOURNEY OF ASHLEY'S SACK, A BLACK FAMILY KEEPSAKE") & (selectiveCols['Short Title'] != 'INTERPERSONAL COMMUNICATION') & (selectiveCols['Short Title'] != 'LET NOBODY TURN US AROUND') & (selectiveCols['Short Title'] != 'LINEAR SYSTEMS THEORY') & (selectiveCols['Short Title'] != 'MERCY') & (selectiveCols['Short Title'] != 'NATURES BEST HOPE') & (selectiveCols['Short Title'] != 'FACILITATING BREAKTHROUGH : HOW TO REMOVE OBSTACLES, BRIDGE DIFFERENCES, AND MOVE FORWARD TOGETHER&NBSP;')]

selectiveCols = selectiveCols[selectiveCols['MMS ID'] != 9926793973502311]

selectiveCols = pd.concat([selectiveCols, salvagedCols])

selectiveCols

,Academic Term,Academic Department Name,Course Code,Instructor Name,ISBN (Normalized) List,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Electronic location,Electronic access,Electronic Availability
0,Summer 2026,ENGLISH,202630-ENGL.301.301-88080,"Perry, Ryan",9781770486003,THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLA...,NaN,BROADVIEW PRESS,15,9926966302202311,https://resolver.vitalsource.com/9781770486003,,Electronic version at VitalSource Bookshelf; B...
1,Summer 2026,ENGLISH,202630-ENGL.301.302-88081,"Perry, Ryan",9781770486003,THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLA...,NaN,BROADVIEW PRESS,10,9926966302202311,https://resolver.vitalsource.com/9781770486003,,Electronic version at VitalSource Bookshelf; B...
2,Summer 2026,NURSING,202630-NURS.670.001-85245,"Malone, Marian",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,9,9926931276402311,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...
3,Summer 2026,NURSING,202630-NURS.670.002-87778,"Neal, Allyson",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,5,9926931276402311,https://search.ebscohost.com/login.aspx?direct...,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...
4,Summer 2026,MARKETING,202630-MARK.471.301-88179,"Presley Bone, Blair",9781040301319,"SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATIO...","JOHNSTON, MARK W., MARSHALL, GREG W., AND OGIL...","ROUTLEDGE, CHAPMAN & HALL, INCORPORATED",35,9926916167202311,NaN,NaN,Electronic version at ProQuest; O'Reilly for H...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.547.002-85249,"Pellathy, Daniel",9781606492468,THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION...,"FEIGIN, GERALD",BUSINESS EXPERT PRESS,30,9925725944102311,https://ebookcentral.proquest.com/lib/utk/deta...,Click to View,Electronic version at ProQuest; ProQuest Ebook...
143,Summer 2026,SOCIAL WORK,202630-SOWK.250.001-84600,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15,9925617965602311,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...
144,Summer 2026,SOCIAL WORK,202630-SOWK.250.002-84791,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15,9925617965602311,https://ebookcentral.proquest.com/lib/utk/deta...,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...
147,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.547.002-85249,"Pellathy, Daniel",9781606492468,THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION...,"FEIGIN, GERALD",BUSINESS EXPERT PRESS,30,9924042300102311,https://search.ebscohost.com/login.aspx?direct...,,Electronic version at ProQuest; ProQuest Ebook...
103,Summer 2026,ECOLOGY AND EVOLUTIONARY BIOLOGY,202630-EEB.330.303-87140,"Benoit, Amanda",9781621901365,GUIDE TO THE VASCULAR PLANTS OF TENNESSEE,"CHESTER, EDWARD W., ESTES, DWAYNE, SHAW, JOEY ...",UNIVERSITY OF TENNESSEE PRESS,11,9926164756102311,https://ebookcentral.proquest.com/lib/utk/deta...,Single User Single User,Electronic version at ProQuest; ProQuest Ebook...

In [31]:
len(selectiveCols.sort_values(by = 'Short Title')['Short Title'].unique())

41

In [32]:
nonUnlimited = finalJoin[~finalJoin['Short Title'].isin(selectiveCols['Short Title'])].dropna(how = 'all')

nonUnlimited.sort_values(by = 'Short Title')['Short Title'].unique()

array(['BEOWULF A NEW VERSE TRANSLATION BILINGUAL EDITION', 'EVICTED',
       'PROPERTY OF THE REBEL LIBRARIAN',
       'PURSUING HAPPINESS : A BEDFORD SPOTLIGHT READER',
       'RELIGIO MEDICI AND URNE-BURIALL', 'THE PORTABLE FEMINIST READER',
       'THE PRACTICE OF ADAPTIVE LEADERSHIP',
       'TRAUMA COUNSELING : THEORIES AND INTERVENTIONS FOR MANAGING TRAUMA, STRESS, CRISIS, AND DISASTER'],
      dtype=object)

## Export the Overlap Report

### This is the dataset that gets transferred to the Transforming Bookstore List Python code.

In [33]:
selectiveCols.to_excel(date_str+'_overlap_report.xlsx', index = False)

## Export the Bookstore Results to Send to the Bookstore

In [34]:
warnings.filterwarnings("ignore")

bookstoreExport = selectiveCols

# Fill in the Primo Link based on the MMS ID

for i in range(len(bookstoreExport['MMS ID'])):
    bookstoreExport['Electronic location'].iloc[i] = 'https://utk.primo.exlibrisgroup.com/permalink/01UTN_KNOXVILLE/bcmt7h/alma' + str(bookstoreExport['MMS ID'].iloc[i])

bookstoreExport = bookstoreExport.rename(columns = {'ISBN (Normalized) List': 'ISBN', 'Electronic access': 'Access_Type', 'Electronic location': 'Permalink', 'Course Code': 'Section Code'})

bookstoreExport = bookstoreExport[['Academic Term', 'Academic Department Name', 'Section Code', 'Instructor Name', 'ISBN', 'Short Title', 'Book Author', 'Book Publisher', 'Enrollment Capacity', 'MMS ID', 'Access_Type', 'Electronic Availability', 'Permalink']]

bookstoreExport

,Academic Term,Academic Department Name,Section Code,Instructor Name,ISBN,Short Title,Book Author,Book Publisher,Enrollment Capacity,MMS ID,Access_Type,Electronic Availability,Permalink
0,Summer 2026,ENGLISH,202630-ENGL.301.301-88080,"Perry, Ryan",9781770486003,THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLA...,NaN,BROADVIEW PRESS,15,9926966302202311,,Electronic version at VitalSource Bookshelf; B...,https://utk.primo.exlibrisgroup.com/permalink/...
1,Summer 2026,ENGLISH,202630-ENGL.301.302-88081,"Perry, Ryan",9781770486003,THE LAIS OF MARIE DE FRANCE : TEXT AND TRANSLA...,NaN,BROADVIEW PRESS,10,9926966302202311,,Electronic version at VitalSource Bookshelf; B...,https://utk.primo.exlibrisgroup.com/permalink/...
2,Summer 2026,NURSING,202630-NURS.670.001-85245,"Malone, Marian",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,9,9926931276402311,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
3,Summer 2026,NURSING,202630-NURS.670.002-87778,"Neal, Allyson",9781610027359,RED BOOK 2024 : REPORT OF THE COMMITTEE ON INF...,NaN,AMERICAN ACADEMY OF PEDIATRICS,5,9926931276402311,Online Access - Unlimited users,Electronic version at EBSCOhost; EBSCO Ebooks ...,https://utk.primo.exlibrisgroup.com/permalink/...
4,Summer 2026,MARKETING,202630-MARK.471.301-88179,"Presley Bone, Blair",9781040301319,"SALES FORCE MANAGEMENT : LEADERSHIP, INNOVATIO...","JOHNSTON, MARK W., MARSHALL, GREG W., AND OGIL...","ROUTLEDGE, CHAPMAN & HALL, INCORPORATED",35,9926916167202311,NaN,Electronic version at ProQuest; O'Reilly for H...,https://utk.primo.exlibrisgroup.com/permalink/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.547.002-85249,"Pellathy, Daniel",9781606492468,THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION...,"FEIGIN, GERALD",BUSINESS EXPERT PRESS,30,9925725944102311,Click to View,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
143,Summer 2026,SOCIAL WORK,202630-SOWK.250.001-84600,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15,9925617965602311,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
144,Summer 2026,SOCIAL WORK,202630-SOWK.250.002-84791,"Mccormack, Sarah",9781483380094,SOCIAL WELFARE POLICY F/A SUSTAINABLE FUTURE,VAN WORMER,SAGE,15,9925617965602311,Unlimited Access Unlimited Access,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
147,Summer 2026,SUPPLY CHAIN MANAGMENET,202630-SCM.547.002-85249,"Pellathy, Daniel",9781606492468,THE SUPPLY AND OPERATIONS MANGEMENT COLLECTION...,"FEIGIN, GERALD",BUSINESS EXPERT PRESS,30,9924042300102311,,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...
103,Summer 2026,ECOLOGY AND EVOLUTIONARY BIOLOGY,202630-EEB.330.303-87140,"Benoit, Amanda",9781621901365,GUIDE TO THE VASCULAR PLANTS OF TENNESSEE,"CHESTER, EDWARD W., ESTES, DWAYNE, SHAW, JOEY ...",UNIVERSITY OF TENNESSEE PRESS,11,9926164756102311,Single User Single User,Electronic version at ProQuest; ProQuest Ebook...,https://utk.primo.exlibrisgroup.com/permalink/...

In [35]:
bookstoreExport.to_excel(date_str+'BookStoreResults_TPQ.xlsx', index = False) #Send this to the Bookstore